
AddonProfilerDB = {
["enabled"] = true,
["closeOnEsc"] = "always",
["historySelectionTimeRange"] = 30,
["minimap"] = {
["minimapPos"] = 303.8588865091472,
["hide"] = false,
},
["shownColumns"] = {
["peakTimeMs"] = true,
["overCount-10"] = true,
["overCount-1000"] = true,
["totalMs"] = true,
["applicationTotalPercent"] = true,
["encounterAvgMs"] = true,
["recentMs"] = false,
["overCount-100"] = true,
["overallEncounterAvgPercent"] = false,
["overCount-1"] = true,
["overallPeakTimePercent"] = false,
["overallTotalPercent"] = true,
["overallRecentPercent"] = false,
["spikeSumMs"] = true,
["overCount-5"] = true,
["overCount-50"] = true,
["addonTitle"] = true,
["overCount-500"] = true,
["averageMs"] = true,
},
["sortColumn"] = "overallTotalPercent",
["historySelectionType"] = "timeRange",
["mode"] = "performance",
["sortOrder"] = -1,
["pinnedAddons"] = {
},
}
