
BugGrabberDB = {
	["lastSanitation"] = 3,
	["session"] = 4769,
	["errors"] = {
		{
			["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'AdiBags' tried to call the protected function 'OnOpen()'.",
			["time"] = "2024/02/09 19:48:45",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:557\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:557\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:551\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:566\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:511\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:485: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:485>\n[string \"=[C]\"]: in function `OnOpen'\n[string \"@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua\"]:586: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:575>\n[string \"=[C]\"]: in function `Show'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2968: in function `SetUIPanel'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2811: in function `ShowUIPanel'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2676: in function <Interface/FrameXML/UIParent.lua:2672>\n[string \"=[C]\"]: in function `SetAttribute'\n[string \"@Interface/FrameXML/UIParent.lua\"]:3278: in function <Interface/FrameXML/UIParent.lua:3257>\n[string \"=[C]\"]: in function `ShowUIPanel'\n[string \"@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua\"]:2390: in function `EncounterJournal_OpenJournal'\n[string \"@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_MonthlyActivities.lua\"]:1557: in function `MonthlyActivitiesFrame_OpenFrameToActivity'\n[string \"@Interface/FrameXML/AlertFrameSystems.lua\"]:1359: in function <Interface/FrameXML/AlertFrameSystems.lua:1345>",
			["session"] = 4767,
			["counter"] = 1,
		}, -- [1]
		{
			["message"] = "...adeSkillMaster/Core/UI/Elements/ApplicationFrame.lua:381: attempt to index a nil value",
			["time"] = "2024/02/09 20:10:35",
			["locals"] = "self = <table> {\n}\ndialogFrame = <table> {\n}\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index a nil value\"\n",
			["stack"] = "[string \"@Interface/AddOns/TradeSkillMaster/Core/UI/Elements/ApplicationFrame.lua\"]:381: in function <...adeSkillMaster/Core/UI/Elements/ApplicationFrame.lua:376>\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:332: in function `HideDialog'\n[string \"@Interface/AddOns/TradeSkillMaster/Core/UI/AuctionUI/Auctioning.lua\"]:1448: in function <...ns/TradeSkillMaster/Core/UI/AuctionUI/Auctioning.lua:1447>\n[string \"=(tail call)\"]: ?\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:332: in function <...radeSkillMaster/External/LibTSMClass/LibTSMClass.lua:319>\n[string \"=(tail call)\"]: ?\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:332: in function `_ProcessEvent'\n[string \"@Interface/AddOns/TradeSkillMaster/LibTSM/Util/FSMClasses/Machine.lua\"]:127: in function <.../TradeSkillMaster/LibTSM/Util/FSMClasses/Machine.lua:105>\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:332: in function `ProcessEvent'\n[string \"@Interface/AddOns/TradeSkillMaster/Core/UI/AuctionUI/Auctioning.lua\"]:731: in function `_onClickHandler'\n[string \"@Interface/AddOns/TradeSkillMaster/Core/UI/Components/Controls/ActionButton.lua\"]:333: in function <...lMaster/Core/UI/Components/Controls/ActionButton.lua:320>\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:332: in function <...radeSkillMaster/External/LibTSMClass/LibTSMClass.lua:319>\n[string \"@Interface/AddOns/TradeSkillMaster/External/LibTSMClass-2/LibTSMClass.lua\"]:502: in function `?'\n[string \"@Interface/AddOns/TradeSkillMaster/LibTSM/Util/ScriptWrapper.lua\"]:86: in function `ScriptHandlerCommon'\n[string \"@Interface/AddOns/TradeSkillMaster/LibTSM/Util/ScriptWrapper.lua\"]:37: in function <...ddOns/TradeSkillMaster/LibTSM/Util/ScriptWrapper.lua:36>",
			["session"] = 4767,
			["counter"] = 1,
		}, -- [2]
		{
			["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn 'ElvUI' tried to call the protected function 'OnOpen()'.",
			["time"] = "2024/02/09 21:13:57",
			["locals"] = "_ = Frame {\n RegisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n 0 = <userdata>\n UnregisterEvent = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n SetScript = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:491\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\nevents = <table> {\n ADDON_ACTION_BLOCKED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:557\n ADDON_ACTION_FORBIDDEN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:557\n PLAYER_LOGIN = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:551\n LUA_WARNING = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:566\n ADDON_LOADED = <function> defined @Interface/AddOns/!BugGrabber/BugGrabber.lua:511\n}\n",
			["stack"] = "[string \"@Interface/AddOns/!BugGrabber/BugGrabber.lua\"]:485: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:485>\n[string \"=[C]\"]: in function `OnOpen'\n[string \"@Interface/AddOns/Blizzard_EncounterJournal/Blizzard_EncounterJournal.lua\"]:586: in function <...zzard_EncounterJournal/Blizzard_EncounterJournal.lua:575>\n[string \"=[C]\"]: in function `Show'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2968: in function `SetUIPanel'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2811: in function `ShowUIPanel'\n[string \"@Interface/FrameXML/UIParent.lua\"]:2676: in function <Interface/FrameXML/UIParent.lua:2672>\n[string \"=[C]\"]: in function `SetAttribute'\n[string \"@Interface/FrameXML/UIParent.lua\"]:3278: in function <Interface/FrameXML/UIParent.lua:3257>\n[string \"=[C]\"]: in function `ShowUIPanel'\n[string \"@Interface/FrameXML/UIParent.lua\"]:3239: in function `ToggleFrame'\n[string \"@Interface/FrameXML/UIParent.lua\"]:1177: in function `ToggleEncounterJournal'\n[string \"TOGGLEENCOUNTERJOURNAL\"]:1: in function <[string \"TOGGLEENCOUNTERJOURNAL\"]:1>",
			["session"] = 4769,
			["counter"] = 1,
		}, -- [3]
	},
}
