
BugGrabberDB = {
["session"] = 12794,
["lastSanitation"] = 3,
["errors"] = {
{
["message"] = "Interface/AddOns/Plater/Plater.lua:5801: attempt to index field '?' (a nil value)",
["time"] = "2026/02/01 15:37:49",
["locals"] = "self = NamePlate10PlaterUnitFrameCastBar {\n isNamePlate = true\n startEventTime = 794397578.235300\n barBorderTextureForMask = Texture {\n }\n SpellNameRenamed = <no value>\n BorderShield = Texture {\n }\n extraBackground = Texture {\n }\n minValue = <no value>\n HookList = <table> {\n }\n unit = \"nameplate10\"\n notInterruptible = <no value>\n Colors = <table> {\n }\n unitFrame = NamePlate10PlaterUnitFrame {\n }\n SpellName = <no value>\n IsCastBar = true\n fadeInAnimation = AnimationGroup {\n }\n spellTexture = <no value>\n casting = true\n castBarID = 6\n spellName = <no value>\n maxValue = <no value>\n barTexture = Texture {\n }\n fadeOutAnimation = AnimationGroup {\n }\n flashAnimation = AnimationGroup {\n }\n Icon = Texture {\n }\n lazyUpdateCooldown = 0.100000\n ReUpdateNextTick = true\n IsInterrupted = false\n SpellEndTime = 794397578.265600\n percentText = FontString {\n }\n SpellStartTime = <no value>\n SpellTexture = <no value>\n SpellID = <no value>\n PlateFrame = NamePlate10 {\n }\n isImportant = <no value>\n FrameOverlay = NamePlate10PlaterUnitFrameCastBarOverlayFrame {\n }\n Settings = <table> {\n }\n value = 794397578.240800\n spellEndTime = <no value>\n spellStartTime = <no value>\n castID = <no value>\n Spark = Texture {\n }\n FadeAnimation = AnimationGroup {\n }\n spellID = <no value>\n displayedUnit = \"nameplate10\"\n CastBarEvents = <table> {\n }\n customborder = Frame {\n }\n castColorTexture = NamePlate10PlaterUnitFrameCastBarCastColor {\n }\n TargetName = FontString {\n }\n FrameDownlayer = NamePlate10PlaterUnitFrameCastBarDownlayerFrame {\n }\n flashTexture = Texture {\n }\n Text = FontString {\n }\n barTextureMask = MaskTexture {\n }\n WidgetType = \"castBar\"\n ThrottleUpdate = -1\n background = Texture {\n }\n}\nevent = \"UNIT_SPELLCAST_START\"\nunit = \"nameplate10\"\nunitFrame = NamePlate10PlaterUnitFrame {\n UnitFrameEvents = <table> {\n }\n isNamePlate = true\n HasHideHookRegistered = true\n class = \"MAGE\"\n castBar = NamePlate10PlaterUnitFrameCastBar {\n }\n IsUIParent = true\n TargetNeonDown = Texture {\n }\n powerBar = NamePlate10PlaterUnitFramePowerBar {\n }\n TargetTextures4Sides = <table> {\n }\n targetOverlay = Texture {\n }\n isSoftFriend = false\n PlaterRaidTargetFrame = Frame {\n }\n baseFrameLevel = 91\n name = \"Trueborn Rainmaker\"\n ActorNameSpecial = FontString {\n }\n guid = \"Creature-0-4220-2570-16782-184404-0000FFC77A\"\n aggroGlowUpper = Texture {\n }\n AuraCache = <table> {\n }\n namePlateNpcId = 184404\n unit = \"nameplate10\"\n displayedUnit = \"nameplate10\"\n nameplateScaleAdjust = 1\n WidgetType = \"unitFrame\"\n IsNeutralOrHostile = true\n UnitAuraEventHandlerFrame = Frame {\n }\n PlaterOnScreen = true\n blizzardPlateFrameID = \"table: 00000000CD485170\"\n namePlateUnitGUID = \"Creature-0-4220-2570-16782-184404-0000FFC77A\"\n IsUnitNameplate = true\n ExtraIconFrame = NamePlate10PlaterUnitFrameExtraIconRow {\n }\n RefreshID = 0\n isLooseTarget = true\n isSoftInteractObject = false\n targetOverlayTexture = Texture {\n }\n isSoftInteract = false\n namePlateUnitToken = \"nameplate10\"\n HasHooksRegistered = true\n IsUnitEvent = <table> {\n }\n softInteractIcon = NamePlate10PlaterUnitFramesoftInteractIconFrameIcon {\n }\n softInteractIconFrame = NamePlate10PlaterUnitFramesoftInteractIconFrame {\n }\n PlateFrame = NamePlate10 {\n }\n FocusIndicator = Texture {\n }\n HighlightFrame = NamePlate10PlaterUnitFrameHealthBarHighlightOverlay {\n }\n Settings = <table> {\n }\n Top3DFrame = NamePlate103DFrame {\n }\n castBar2 = NamePlate10PlaterUnitFrameCastBar2 {\n }\n ExtraAuraCache = <table> {\n }\n healthBar = NamePlate10PlaterUnitFrameHealthBar {\n }\n BossModIconFrame = NamePlate10PlaterUnitFrameHealthBarBossModIconRow {\n }\n isObject = false\n TargetNeonUp = Texture {\n }\n TargetTextures2Sides = <table> {\n }\n BodyFlashFrame = Frame {\n }\n CustomIndicators = <table> {\n }\n FadeAnimation = AnimationGroup {\n }\n ActorTitleSpecial = FontString {\n }\n GhostAuraCache = <table> {\n }\n border = NamePlate10PlaterUnitFrameBorder {\n }\n unitName = FontString {\n }\n Plater = true\n isSoftEnemy = false\n aggroGlowLower = Texture {\n }\n BuffFrame = NamePlate10PlaterUnitFrameBuffFrame1 {\n }\n overlayFrame = NamePlate10PlaterUnitFrameOverlayFrame {\n }\n BuffFrame2 = NamePlate10P",
["stack"] = "[Interface/AddOns/Plater/Plater.lua]:5801: in function <Interface/AddOns/Plater/Plater.lua:5647>\n[C]: in function 'OnEvent'\n[Interface/AddOns/Details/Libs/DF/unitframe_midnight.lua]:1445: in function <...erface/AddOns/Details/Libs/DF/unitframe_midnight.lua:1438>\n[C]: in function 'OnEvent'\n[Interface/AddOns/Details/Libs/DF/unitframe_midnight.lua]:1333: in function 'SetUnit'\n[Interface/AddOns/Details/Libs/DF/unitframe_midnight.lua]:2421: in function 'SetUnit'\n[Interface/AddOns/Plater/Plater.lua]:3844: in function 'func'\n[Interface/AddOns/Plater/Plater.lua]:4407: in function <Interface/AddOns/Plater/Plater.lua:4403>",
["session"] = 12769,
["counter"] = 2,
},
{
["message"] = "attempt to call a secret value",
["time"] = "2026/02/01 15:38:40",
["locals"] = "funcTbl = <no value>\ncanTerminate = false\n(for state) = <no value>\n(for control) = <no value>\ni = <no value>\nfunc = <no value>\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:67: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:62>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:87: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:83>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:123: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:113>\n[C]: in function 'SetAttribute'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:172: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:165>\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:334: in function 'ProcessLineData'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:315: in function 'ProcessLines'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:292: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:245>\n[C]: in function 'securecallfunction'\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:242: in function <...lizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua:241>\n[tail call]: ?\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLGame/Tooltip/TooltipDataHandler.lua]:517: in function 'SetUnitBuffByAuraInstanceID'\n[*TargetFrame.xml:134_OnEnter]:2: in function <[string \"*TargetFrame.xml:134_OnEnter\"]:1>",
["session"] = 12769,
["counter"] = 47,
},
{
["message"] = "...ce/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua:859: attempt to perform boolean test on field 'allowAvailableAlert' (a secret value)",
["time"] = "2026/02/02 17:47:23",
["locals"] = "self = Frame {\n includeAsLayoutChildWhenHidden = true\n cooldownChargesCount = 0\n _cmcSwipeColorHooked = true\n hideWhenInactive = true\n cooldownIsActive = false\n isActive = false\n OutOfRange = Texture {\n }\n Cooldown = Cooldown {\n }\n cooldownModRate = 1\n isEditing = true\n ChargeCount = Frame {\n }\n wasSetFromAura = false\n spellOutOfRange = false\n rangeCheckSpellID = 1276467\n needsRangeCheck = true\n alertsByEvent = <table> {\n }\n cooldownInfo = <table> {\n }\n cooldownPlayFlash = false\n cooldownDesaturated = false\n cooldownPaused = false\n cooldownUseAuraDisplayTime = false\n cooldownShowSwipe = true\n allowAvailableAlert = <no value>\n cooldownDuration = 0\n cooldownEnabled = true\n cooldownStartTime = 0\n cooldownSwipeColor = <table> {\n }\n isOnActualCooldown = false\n cooldownChargesShown = false\n previousCooldownChargesCount = 0\n wasSetFromEditMode = false\n wasSetFromCooldown = true\n wasSetFromCharges = false\n viewerFrame = EssentialCooldownViewer {\n }\n layoutIndex = 7\n CooldownFlash = Frame {\n }\n Icon = Texture {\n }\n cooldownFont = \"GameFontHighlightHugeOutline\"\n cooldownShowDrawEdge = false\n cooldownID = 3045\n allowOnCooldownAlert = false\n}\ntimeNow = 888570.270000\nspellID = 1276467\nspellCooldownInfo = <table> {\n modRate = 1\n isEnabled = true\n startTime = 0\n duration = 0\n}\nendTime = 0\n(*temporary) = <no value>\n(*temporary) = Frame {\n includeAsLayoutChildWhenHidden = true\n cooldownChargesCount = 0\n _cmcSwipeColorHooked = true\n hideWhenInactive = true\n cooldownIsActive = false\n isActive = false\n OutOfRange = Texture {\n }\n Cooldown = Cooldown {\n }\n cooldownModRate = 1\n isEditing = true\n ChargeCount = Frame {\n }\n wasSetFromAura = false\n spellOutOfRange = false\n rangeCheckSpellID = 1276467\n needsRangeCheck = true\n alertsByEvent = <table> {\n }\n cooldownInfo = <table> {\n }\n cooldownPlayFlash = false\n cooldownDesaturated = false\n cooldownPaused = false\n cooldownUseAuraDisplayTime = false\n cooldownShowSwipe = true\n allowAvailableAlert = <no value>\n cooldownDuration = 0\n cooldownEnabled = true\n cooldownStartTime = 0\n cooldownSwipeColor = <table> {\n }\n isOnActualCooldown = false\n cooldownChargesShown = false\n previousCooldownChargesCount = 0\n wasSetFromEditMode = false\n wasSetFromCooldown = true\n wasSetFromCharges = false\n viewerFrame = EssentialCooldownViewer {\n }\n layoutIndex = 7\n CooldownFlash = Frame {\n }\n Icon = Texture {\n }\n cooldownFont = \"GameFontHighlightHugeOutline\"\n cooldownShowDrawEdge = false\n cooldownID = 3045\n allowOnCooldownAlert = false\n}\n(*temporary) = 1276467\n(*temporary) = <table> {\n modRate = 1\n isEnabled = true\n startTime = 0\n duration = 0\n}\n(*temporary) = true\n(*temporary) = false\n(*temporary) = 0\n(*temporary) = 0.750000\n(*temporary) = \"attempt to perform boolean test on field 'allowAvailableAlert' (a secret value)\"\nMIN_GLOBAL_RECOVERY_TIME = 0.750000\n",
["stack"] = "[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:859: in function 'CheckCacheCooldownValuesFromSpellCooldown'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:900: in function 'CacheCooldownValues'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:965: in function 'RefreshSpellCooldownInfo'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1069: in function 'RefreshData'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1576: in function 'RefreshActiveFramesForTargetChange'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1563: in function 'OnUnitAura'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1513: in function 'OnEvent'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1842: in function 'OnEvent'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1891: in function <...ce/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua:1890>",
["session"] = 12772,
["counter"] = 2,
},
{
["message"] = "...ce/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua:859: attempt to perform boolean test on field 'allowAvailableAlert' (a secret value)\n|cffffd200Stack:|r\n[C]: in function 'secureexecuterange'\n[Interface/AddOns/Blizzard_EditMode/Shared/EditModeManager.lua]:97: in function 'HideSystemSelections'\n[Interface/AddOns/Blizzard_EditMode/Shared/EditModeManager.lua]:104: in function 'ExitEditMode'\n[Interface/AddOns/Blizzard_EditMode/Shared/EditModeManager.lua]:126: in function <.../AddOns/Blizzard_EditMode/Shared/EditModeManager.lua:124>\n[C]: ?\n[C]: ?\n[C]: ?\n[C]: in function 'Hide'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:445: in function 'SetUIPanel'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:476: in function 'MoveUIPanel'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:530: in function 'HideUIPanelImplementation'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:489: in function 'HideUIPanel'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:137: in function <...UIParentPanelManager/Shared/UIParentPanelManager.lua:128>\n[C]: in function 'SetAttribute'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Shared/UIParentPanelManager.lua]:870: in function <...UIParentPanelManager/Shared/UIParentPanelManager.lua:853>\n[C]: in function 'HideUIPanel'\n[Interface/AddOns/Blizzard_EditMode/Shared/EditModeManager.lua]:42: in function 'onCloseCallback'\n[Interface/AddOns/Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua]:143: in function <...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:138>\n[C]: in function 'Click'\n[Interface/AddOns/Blizzard_UIParent/Mainline/UIParent.lua]:2335: in function 'ToggleGameMenu'\n[TOGGLEGAMEMENU]:1: in function <[string \"TOGGLEGAMEMENU\"]:1>\n",
["time"] = "2026/02/02 17:47:36",
["session"] = 12772,
["counter"] = 1,
},
{
["message"] = "...ce/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua:459: attempt to perform boolean test on field 'allowAvailableAlert' (a secret value)",
["time"] = "2026/02/02 17:47:23",
["locals"] = "self = Frame {\n includeAsLayoutChildWhenHidden = true\n cooldownChargesCount = 0\n _cmcSwipeColorHooked = true\n hideWhenInactive = true\n cooldownIsActive = false\n isActive = false\n OutOfRange = Texture {\n }\n Cooldown = Cooldown {\n }\n cooldownModRate = 1\n isEditing = true\n ChargeCount = Frame {\n }\n wasSetFromAura = false\n spellOutOfRange = false\n rangeCheckSpellID = 29893\n needsRangeCheck = true\n alertsByEvent = <table> {\n }\n cooldownInfo = <table> {\n }\n cooldownPlayFlash = false\n cooldownDesaturated = false\n cooldownPaused = false\n cooldownUseAuraDisplayTime = false\n cooldownShowSwipe = true\n allowAvailableAlert = <no value>\n cooldownDuration = 0\n cooldownEnabled = true\n cooldownStartTime = 0\n cooldownSwipeColor = <table> {\n }\n isOnActualCooldown = false\n cooldownChargesShown = false\n previousCooldownChargesCount = 0\n wasSetFromEditMode = false\n wasSetFromCooldown = true\n wasSetFromCharges = false\n viewerFrame = UtilityCooldownViewer {\n }\n layoutIndex = 7\n CooldownFlash = Frame {\n }\n Icon = Texture {\n }\n cooldownFont = \"GameFontHighlightOutline\"\n cooldownShowDrawEdge = false\n cooldownID = 2350\n allowOnCooldownAlert = false\n}\ntimeNow = 888570.270000\n(*temporary) = <no value>\n(*temporary) = \"attempt to perform boolean test on field 'allowAvailableAlert' (a secret value)\"\n",
["stack"] = "[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:459: in function 'ShouldTriggerAvailableAlert'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:95: in function 'OnUpdate'\n[Interface/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua]:1529: in function <...ce/AddOns/Blizzard_CooldownViewer/CooldownViewer.lua:1526>",
["session"] = 12772,
["counter"] = 180,
},
{
["message"] = "[string \"return issecurevariable(FriendsListFrame.Sc...\"]:1: Usage: issecurevariable([table,] \"variable\")",
["time"] = "2026/02/16 03:35:46",
["locals"] = "msg = \"issecurevariable(FriendsListFrame.ScrollBox:GetDataProvider())\"\neditBox = nil\nerr = nil\n(*temporary) = <table> {\n}\nFORMATS = <table> {\n tableReference = \"%s|cffffcc00%s|r%s\"\n opaqueTypeVal = \"%s|cff88ff88<%s>|r%s\"\n simpleValueSecret = \"%s|cff88ff88<secret>|r %s%s\"\n bracketTableKey = \"[%s]\"\n opaqueTypeKey = \"<%s>\"\n opaqueTypeValSecret = \"%s|cff88ff88<secret %s>|r%s\"\n simpleValue = \"%s%s%s\"\n tableEntriesSkipped = \"%s|cffff0000<skipped %s>|r\"\n opaqueTypeValName = \"%s|cff88ff88<%s %s>|r%s\"\n tableTooDeep = \"%s|cffff0000<table (too deep)>|r%s\"\n tableKeyAssignPrefix = \"|cff88ccff%s%s|r=\"\n opaqueTypeKeyName = \"<%s %s>\"\n opaqueTypeKeySecret = \"<secret %s>\"\n}\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXML/Dump.lua]:467: in function 'DevTools_DumpCommand'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/SlashCommands.lua]:1361: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:206>\n[C]: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:283>\n[C]: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>",
["session"] = 12779,
["counter"] = 1,
},
{
["message"] = "[string \"return CheckProtectedFunctionsAllowed()\"]:1: attempt to call global 'CheckProtectedFunctionsAllowed' (a nil value)",
["time"] = "2026/02/16 04:19:47",
["locals"] = "msg = \"CheckProtectedFunctionsAllowed()\"\neditBox = nil\nerr = nil\n(*temporary) = <table> {\n}\nFORMATS = <table> {\n tableReference = \"%s|cffffcc00%s|r%s\"\n opaqueTypeVal = \"%s|cff88ff88<%s>|r%s\"\n simpleValueSecret = \"%s|cff88ff88<secret>|r %s%s\"\n bracketTableKey = \"[%s]\"\n opaqueTypeKey = \"<%s>\"\n opaqueTypeValSecret = \"%s|cff88ff88<secret %s>|r%s\"\n simpleValue = \"%s%s%s\"\n tableEntriesSkipped = \"%s|cffff0000<skipped %s>|r\"\n opaqueTypeValName = \"%s|cff88ff88<%s %s>|r%s\"\n tableTooDeep = \"%s|cffff0000<table (too deep)>|r%s\"\n tableKeyAssignPrefix = \"|cff88ccff%s%s|r=\"\n opaqueTypeKeyName = \"<%s %s>\"\n opaqueTypeKeySecret = \"<secret %s>\"\n}\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXML/Dump.lua]:467: in function 'DevTools_DumpCommand'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/SlashCommands.lua]:1361: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:206>\n[C]: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:283>\n[C]: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>",
["session"] = 12787,
["counter"] = 1,
},
{
["message"] = "...izzard_SharedXML/Mainline/SharedUIPanelTemplates.lua:524: attempt to index field 'Left' (a nil value)",
["time"] = "2026/02/16 05:13:49",
["locals"] = "tab = FriendsFrame {\n FriendsTabHeader = FriendsTabHeader {\n }\n TitleContainer = Frame {\n }\n Tabs = <table> {\n }\n IgnoreListWindow = Frame {\n }\n layoutType = \"PortraitFrameTemplate\"\n PortraitContainer = Frame {\n }\n Bg = FriendsFrameBg {\n }\n NineSlice = Frame {\n }\n TopTileStreaks = Texture {\n }\n selectedFriend = 1\n CloseButton = FriendsFrameCloseButton {\n }\n numTabs = 4\n Inset = FriendsFrameInset {\n }\n selectedTab = 1\n}\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index field 'Left' (a nil value)\"\n",
["stack"] = "[Interface/AddOns/Blizzard_SharedXML/Mainline/SharedUIPanelTemplates.lua]:524: in function 'PanelTemplates_SelectTab'\n[PanelTemplates_SelectTab(FriendsFrame, 1)]:1: in main chunk\n[C]: in function 'RunScript'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/SlashCommands.lua]:1172: in function '?'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:259: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:206>\n[C]: in function 'ParseText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:284: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:283>\n[C]: in function 'SendText'\n[Interface/AddOns/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua]:407: in function <...s/Blizzard_ChatFrameBase/Shared/ChatFrameEditBox.lua:403>",
["session"] = 12789,
["counter"] = 1,
},
{
["message"] = "[ADDON_ACTION_FORBIDDEN] AddOn '*** ForceTaint_Strong ***' tried to call the protected function 'VisitHouse()'.",
["time"] = "2026/02/16 03:41:43",
["locals"] = "self = <table> {\n}\nevent = \"ADDON_ACTION_FORBIDDEN\"\naddonName = \"*** ForceTaint_Strong ***\"\naddonFunc = \"VisitHouse()\"\nname = \"*** ForceTaint_Strong ***\"\nbadAddons = <table> {\n *** ForceTaint_Strong *** = true\n}\nL = <table> {\n ADDON_CALL_PROTECTED_MATCH = \"^%[(.*)%] (AddOn '.*' tried to call the protected function '.*'.)$\"\n NO_DISPLAY_2 = \"|cffffff00The standard display is called BugSack, and can probably be found on the same site where you found !BugGrabber.|r\"\n ERROR_DETECTED = \"%s |cffffff00captured, click the link for more information.|r\"\n USAGE = \"|cffffff00Usage: /buggrabber <1-%d>.|r\"\n BUGGRABBER_STOPPED = \"|cffffff00There are too many errors in your UI. As a result, your game experience may be degraded. Disable or update the failing addons if you don't want to see this message again.|r\"\n STOP_NAG = \"|cffffff00!BugGrabber will not nag about missing a display addon again until next patch.|r\"\n ADDON_DISABLED = \"|cffffff00!BugGrabber and %s cannot coexist; %s has been forcefully disabled. If you want to, you may log out, disable !BugGrabber, and enable %s.|r\"\n NO_DISPLAY_STOP = \"|cffffff00If you don't want to be reminded about this again, run /stopnag.|r\"\n NO_DISPLAY_1 = \"|cffffff00You seem to be running !BugGrabber with no display addon to go along with it. Although a slash command is provided for accessing error reports, a display can help you manage these errors in a more convenient way.|r\"\n ERROR_UNABLE = \"|cffffff00!BugGrabber is unable to retrieve errors from other players by itself. Please install BugSack or a similar display addon that might give you this functionality.|r\"\n ADDON_CALL_PROTECTED = \"[%s] AddOn '%s' tried to call the protected function '%s'.\"\n}\n",
["stack"] = "[Interface/AddOns/!BugGrabber/BugGrabber.lua]:583: in function '?'\n[Interface/AddOns/!BugGrabber/BugGrabber.lua]:507: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:507>\n[C]: in function 'VisitHouse'\n[Interface/AddOns/Blizzard_HouseList/Blizzard_HouseList.lua]:135: in function <...ace/AddOns/Blizzard_HouseList/Blizzard_HouseList.lua:133>\n[tail call]: ?",
["session"] = 12792,
["counter"] = 3,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/loadLibs.xml:18 Error loading Interface/AddOns/CooldownManagerCentered/libs/LibButtonGlow-1.0/LibButtonGlow-1.0.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/loadLibs.xml:19 Error loading Interface/AddOns/CooldownManagerCentered/libs/LibActionButton-1.0/LibActionButton-1.0.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:27 Error loading Interface/AddOns/CooldownManagerCentered/core/scaling.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:28 Error loading Interface/AddOns/CooldownManagerCentered/core/spellIdOverrides.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:29 Error loading Interface/AddOns/CooldownManagerCentered/core/uiCore.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:36 Error loading Interface/AddOns/CooldownManagerCentered/modules/Tracker/TrackerDB.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:37 Error loading Interface/AddOns/CooldownManagerCentered/modules/Tracker/TrackerItemsData.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:38 Error loading Interface/AddOns/CooldownManagerCentered/modules/Tracker/TrackerItemVisuals.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:39 Error loading Interface/AddOns/CooldownManagerCentered/modules/Tracker/TrackerItemViewer.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
{
["message"] = "Interface/AddOns/CooldownManagerCentered/CooldownManagerCentered.toc:45 Error loading Interface/AddOns/CooldownManagerCentered/modules/glowStyle.lua",
["time"] = "2026/02/23 12:15:29",
["session"] = 12794,
["counter"] = 1,
},
},
}
