
AddOnSkinsDB = {
["profileKeys"] = {
["Calestin - Sargeras"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Naturerivers - Korgath"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Saellindris - Kel'Thuzad"] = "Default",
["Lotic - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Ochrian - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Inundito - Kel'Thuzad"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptystreams - Argent Dawn"] = "Default",
["Emptyrivers - Sargeras"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Mothugeon - Argent Dawn"] = "Default",
["Asperos - Kel'Thuzad"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Evilrivers - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Wildeadoriah - The Scryers"] = "Default",
["Zimuures - Argent Dawn"] = "Default",
["Emptyrivers - Arthas"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Alandere - Argent Dawn"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["MinimalArchaeology"] = false,
["Auctionator"] = false,
["EmbedBackdropTransparent"] = false,
["Immersion"] = false,
["Altoholic"] = false,
["ColorPickerPlus"] = false,
["EmbedOoCDelay"] = 30,
["EmbedBackdrop"] = false,
["EmbedBelowTop"] = true,
},
},
}
AddOnSkinsDS = {
[4.73] = {
["MinimalArchaeology"] = true,
},
}
