
AdiBagsDB = {
	["char"] = {
		["Serenerivers - Korgath"] = {
			["collapsedSections"] = {
				["Miscellaneous#Junk"] = true,
			},
		},
	},
	["namespaces"] = {
		["ItemLevel"] = {
		},
		["FilterOverride"] = {
			["profiles"] = {
				["Default"] = {
					["version"] = 3,
					["overrides"] = {
						[37431] = "Miscellaneous#Pet stuff",
						[201921] = "Consumable#Renown",
						[116419] = "Miscellaneous#Pet stuff",
						[86582] = "Item Enhancement!#Utility",
						[128373] = "Miscellaneous#garrison shit",
						[109585] = "Item Enhancement!#Archaeology",
						[127881] = "Miscellaneous#garrison shit",
						[201922] = "Consumable#Renown",
						[127770] = "Junk#Junk",
						[49040] = "Item Enhancement!#Utility",
						[93147] = "Miscellaneous#Pet stuff",
						[114745] = "Miscellaneous#garrison shit",
						[48933] = "Item Enhancement!#Utility",
						[200939] = "Junk#Discenchant",
						[116420] = "Miscellaneous#Pet stuff",
						[92679] = "Miscellaneous#Pet stuff",
						[79868] = "Item Enhancement!#Archaeology",
						[127755] = "Miscellaneous#Pet stuff",
						[79249] = "Junk#Junk",
						[200289] = "Consumable#Renown",
						[200940] = "Junk#Discenchant",
						[191304] = "Consumable#Renown",
						[65360] = "Item Enhancement!#Utility",
						[200288] = "Consumable#Renown",
						[117397] = "Junk#Junk",
						[93148] = "Miscellaneous#Pet stuff",
						[201923] = "Consumable#Renown",
						[71153] = "Miscellaneous#Pet stuff",
						[200941] = "Junk#Discenchant",
						[116421] = "Miscellaneous#Pet stuff",
						[116429] = "Miscellaneous#Pet stuff",
						[114943] = "Item Enhancement!#Utility",
						[37460] = "Miscellaneous#Pet stuff",
						[30544] = "Item Enhancement!#Utility",
						[93146] = "Miscellaneous#Pet stuff",
						[114807] = "Miscellaneous#garrison shit",
						[200942] = "Junk#Discenchant",
						[200450] = "Consumable#Renown",
						[127669] = "Junk#Junk",
						[116374] = "Miscellaneous#Pet stuff",
						[92678] = "Miscellaneous#Pet stuff",
						[93149] = "Miscellaneous#Pet stuff",
						[92681] = "Miscellaneous#Pet stuff",
						[200071] = "Consumable#Renown",
						[92665] = "Miscellaneous#Pet stuff",
						[116422] = "Miscellaneous#Pet stuff",
						[89125] = "Miscellaneous#Pet stuff",
						[128503] = "Miscellaneous#garrison shit",
						[92677] = "Miscellaneous#Pet stuff",
						[202039] = "Consumable#Renown",
						[116418] = "Miscellaneous#Pet stuff",
						[127662] = "Miscellaneous#garrison shit",
						[116415] = "Miscellaneous#Pet stuff",
						[200452] = "Consumable#Renown",
						[118907] = "Item Enhancement!#Utility",
						[40727] = "Item Enhancement!#Utility",
						[104329] = "Item Enhancement!#Utility",
						[200945] = "Junk#Discenchant",
						[122601] = "Item Enhancement!#Utility",
						[60854] = "Item Enhancement!#Utility",
						[192055] = "Consumable#Renown",
						[200453] = "Consumable#Renown",
						[92682] = "Miscellaneous#Pet stuff",
						[87216] = "Item Enhancement!#Utility",
						[163036] = "Miscellaneous#Pet stuff",
						[101529] = "Miscellaneous#Pet stuff",
						[87214] = "Item Enhancement!#Utility",
						[127768] = "Miscellaneous#Pet stuff",
						[127655] = "Junk#Junk",
						[200454] = "Consumable#Renown",
						[98715] = "Miscellaneous#Pet stuff",
						[40768] = "Item Enhancement!#Utility",
						[120321] = "Miscellaneous#Pet stuff",
						[111820] = "Item Enhancement!#Utility",
						[98112] = "Miscellaneous#Pet stuff",
						[89906] = "Miscellaneous#Pet stuff",
						[200947] = "Junk#Discenchant",
						[200455] = "Consumable#Renown",
						[92683] = "Miscellaneous#Pet stuff",
						[108439] = "Item Enhancement!#Archaeology",
						[122272] = "Miscellaneous#garrison shit",
						[122298] = "Miscellaneous#garrison shit",
						[116416] = "Miscellaneous#Pet stuff",
						[92676] = "Miscellaneous#Pet stuff",
						[193201] = "Consumable#Renown",
						[85500] = "Item Enhancement!#Utility",
						[86143] = "Miscellaneous#Pet stuff",
						[116424] = "Miscellaneous#Pet stuff",
						[122457] = "Miscellaneous#Pet stuff",
						[111821] = "Item Enhancement!#Utility",
						[129929] = "Item Enhancement!#Utility",
						[94207] = "Miscellaneous#Pet stuff",
						[116417] = "Miscellaneous#Pet stuff",
						[87215] = "Item Enhancement!#Utility",
						[44820] = "Miscellaneous#Pet stuff",
						[43352] = "Miscellaneous#Pet stuff",
						[18986] = "Item Enhancement!#Utility",
						[114806] = "Miscellaneous#garrison shit",
						[127895] = "Miscellaneous#garrison shit",
						[127663] = "Miscellaneous#garrison shit",
						[92680] = "Miscellaneous#Pet stuff",
						[116423] = "Miscellaneous#Pet stuff",
						[200093] = "Consumable#Renown",
						[103678] = "Item Enhancement!#Utility",
						[128353] = "Item Enhancement!#Utility",
						[191251] = "Consumable#Renown",
						[110560] = "Miscellaneous#garrison shit",
						[125787] = "Miscellaneous#garrison shit",
						[200443] = "Consumable#Renown",
						[119093] = "Item Enhancement!#Utility",
						[127884] = "Miscellaneous#garrison shit",
						[109584] = "Item Enhancement!#Archaeology",
						[127880] = "Miscellaneous#garrison shit",
						[43626] = "Miscellaneous#Pet stuff",
						[200285] = "Consumable#Renown",
						[40586] = "Item Enhancement!#Utility",
						[199906] = "Consumable#Renown",
						[201924] = "Consumable#Renown",
						[200447] = "Consumable#Renown",
					},
				},
			},
		},
		["ItemCategory"] = {
			["profiles"] = {
				["Default"] = {
					["splitBySubclass"] = {
						["Recipe"] = true,
						["Tradeskill"] = true,
						["Gem"] = true,
						["Consumable"] = true,
						["Item Enhancement!"] = true,
						["Glyph"] = true,
						["Trade Goods"] = false,
						["Miscellaneous"] = true,
					},
					["splitExpansion"] = true,
				},
			},
		},
		["NewItem"] = {
			["profiles"] = {
				["Default"] = {
					["highlight"] = "blizzard",
				},
			},
		},
		["AdiBags_TooltipInfo"] = {
		},
		["Equipment"] = {
		},
		["CurrencyFrame"] = {
			["profiles"] = {
				["Default"] = {
					["shown"] = {
						["Ancient Mana"] = true,
						["Ironpaw Token"] = false,
						["Bloody Coin"] = false,
						["Nethershard"] = false,
						["Valor"] = true,
						["Wakening Essence"] = false,
						["Lesser Charm of Good Fortune"] = false,
						["Flightstones"] = true,
						["Order Resources"] = false,
						["Veiled Argunite"] = false,
						["Warforged Seal"] = false,
						["Garrison Resources"] = false,
						["Seal of Tempered Fate"] = false,
						["Elemental Overflow"] = true,
						["Mote of Darkness"] = false,
						["Seal of Inevitable Fate"] = false,
						["Elder Charm of Good Fortune"] = false,
						["Timewarped Badge"] = true,
						["Epicurean's Award"] = false,
						["Honor Points"] = false,
						["Conquest Points"] = false,
						["Timeless Coin"] = false,
						["Essence of Corrupted Deathwing"] = false,
						["Apexis Crystal"] = false,
						["Darkmoon Prize Ticket"] = true,
						["Dragon Isles Supplies"] = true,
						["Oil"] = false,
						["Seal of Broken Fate"] = false,
						["Champion's Seal"] = false,
						["Curious Coin"] = true,
					},
					["hideZeroes"] = true,
					["width"] = 10,
				},
			},
		},
		["DataSource"] = {
		},
		["ItemSets"] = {
		},
		["Junk"] = {
			["profiles"] = {
				["Default"] = {
					["include"] = {
						[127669] = true,
						[86583] = true,
						[127655] = true,
						[115506] = true,
						[110505] = true,
						[79249] = true,
						[127770] = true,
						[117397] = true,
					},
				},
			},
		},
		["MoneyFrame"] = {
		},
	},
	["profileKeys"] = {
		["Sverdrup - Argent Dawn"] = "Default",
		["Canerena - Arthas"] = "Default",
		["Beefyrivers - Thrall"] = "Default",
		["Yandanderex - Moon Guard"] = "Default",
		["Serenerivers - Arthas"] = "Default",
		["Sacredrivers - Korgath"] = "Default",
		["Dammedrivers - Exodar"] = "Default",
		["Wildrivers - Korgath"] = "Default",
		["Crazyrivers - Bleeding Hollow"] = "Default",
		["Wildrivers - Bleeding Hollow"] = "Default",
		["Deadrivers - Korgath"] = "Default",
		["Crazyrivers - Sargeras"] = "Default",
		["Testrivers - Arthas"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Shachein - Arthas"] = "Default",
		["Notariver - Arthas"] = "Default",
		["Tinyrivers - Arthas"] = "Default",
		["Sneakyrivers - Korgath"] = "Default",
		["Angryrivers - Korgath"] = "Default",
		["Toofattohide - Kel'Thuzad"] = "Default",
		["Serenerivers - Korgath"] = "Default",
		["Kdajshtlaiuw - Bleeding Hollow"] = "Default",
		["Smaz - Mug'thol"] = "Default",
		["Testes - Arthas"] = "Default",
		["Daedrasminia - Arthas"] = "Default",
		["Riversticks - Bleeding Hollow"] = "Default",
		["Emptyrivers - Argent Dawn"] = "Default",
		["Skankyrivers - Arthas"] = "Default",
		["Estuary - Argent Dawn"] = "Default",
		["Boringrivers - Korgath"] = "Default",
		["Rapidrivers - Arthas"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Ailisuul - Arthas"] = "Default",
		["Mindrivers - Korgath"] = "Default",
		["Ochrian - Argent Dawn"] = "Default",
		["Serenerivers - Bleeding Hollow"] = "Default",
		["Blindrivers - Sargeras"] = "Default",
		["Tinyrivers - Kel'Thuzad"] = "Default",
		["Testrivers - Bleeding Hollow"] = "Default",
		["Sassyrivers - Arthas"] = "Default",
		["Headcut - Argent Dawn"] = "Default",
		["Serenerivers - Kel'Thuzad"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
		["Brightrivers - Korgath"] = "Default",
		["Evilrivers - Sargeras"] = "Default",
		["Littlerivers - Kel'Thuzad"] = "Default",
		["Confluence - Argent Dawn"] = "Default",
		["Hiddenrivers - Korgath"] = "Default",
		["Savattellir - Arthas"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Mahntaiaga - Arthas"] = "Default",
		["Emptyrivers - Korgath"] = "Default",
		["Hulyon - Kel'Thuzad"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Holyrivers - Sargeras"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Feralrivers - Sargeras"] = "Default",
		["Edgyrivers - Kel'Thuzad"] = "Default",
		["Beefyrivers - Bleeding Hollow"] = "Default",
		["Emptyrivers - Arthas"] = "Default",
		["Blindrivers - Korgath"] = "Default",
		["Serenerivers - Sargeras"] = "Default",
		["Crazyrivers - Arthas"] = "Default",
		["Luckyrivers - Korgath"] = "Default",
		["Mecharivers - Sargeras"] = "Default",
		["Eysta - Sargeras"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Emptyrivers - Bleeding Hollow"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Boringrivers - Bleeding Hollow"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Riparium - Argent Dawn"] = "Default",
		["Evilrivers - Korgath"] = "Default",
		["Magicrivers - Korgath"] = "Default",
		["Garumn - Arthas"] = "Default",
		["Tinyrivers - Sargeras"] = "Default",
		["Alluvium - Argent Dawn"] = "Default",
		["Flumina - Argent Dawn"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["virtualStacks"] = {
				["incomplete"] = true,
			},
			["columnWidth"] = {
				["Backpack"] = 8,
			},
			["maxHeight"] = 0.5,
			["positions"] = {
				["Backpack"] = {
					["xOffset"] = -221.3548814606475,
					["yOffset"] = 133.6952900781525,
				},
				["Bank"] = {
					["xOffset"] = 58.78611537793449,
					["yOffset"] = -298.5882693506101,
				},
			},
			["scale"] = 0.8,
			["autoDeposit"] = true,
			["theme"] = {
				["backpack"] = {
					["color"] = {
						nil, -- [1]
						nil, -- [2]
						nil, -- [3]
						0.548191010951996, -- [4]
					},
				},
				["themes"] = {
					["legacy theme"] = {
						["reagentBank"] = {
							["bagFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 1,
								["g"] = 1,
								["size"] = 16,
							},
							["sectionFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 0,
								["g"] = 0.8196079134941101,
								["size"] = 13,
							},
							["border"] = "None",
							["insets"] = 0,
						},
						["backpack"] = {
							["sectionFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 0,
								["g"] = 0.8196079134941101,
								["size"] = 13,
							},
							["color"] = {
								[4] = 0.548191010951996,
							},
							["bagFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 1,
								["g"] = 1,
								["size"] = 16,
							},
							["border"] = "None",
							["insets"] = 0,
						},
						["bank"] = {
							["bagFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 1,
								["g"] = 1,
								["size"] = 16,
							},
							["sectionFont"] = {
								["name"] = "PT Sans Narrow",
								["r"] = 1,
								["b"] = 0,
								["g"] = 0.8196079134941101,
								["size"] = 13,
							},
							["border"] = "None",
							["insets"] = 0,
						},
					},
				},
			},
			["experiments"] = {
				["Bag Lag Fix"] = {
					["Enabled"] = false,
					["Name"] = "Bag Lag Fix",
					["Description"] = "This experiment will fix the lag when opening bags via per-item change draws instead of full redraws.",
					["Percent"] = 1,
				},
			},
		},
	},
}
