
AdiBagsDB = {
	["char"] = {
		["Serenerivers - Korgath"] = {
			["collapsedSections"] = {
				["Miscellaneous#Junk"] = true,
			},
		},
	},
	["namespaces"] = {
		["ItemLevel"] = {
		},
		["FilterOverride"] = {
			["profiles"] = {
				["Default"] = {
					["version"] = 3,
					["overrides"] = {
						[37431] = "Miscellaneous#Pet stuff",
						[116419] = "Miscellaneous#Pet stuff",
						[86582] = "Item Enhancement!#Utility",
						[128373] = "Miscellaneous#garrison shit",
						[109585] = "Item Enhancement!#Archaeology",
						[127881] = "Miscellaneous#garrison shit",
						[127770] = "Junk#Junk",
						[49040] = "Item Enhancement!#Utility",
						[93147] = "Miscellaneous#Pet stuff",
						[114745] = "Miscellaneous#garrison shit",
						[48933] = "Item Enhancement!#Utility",
						[116420] = "Miscellaneous#Pet stuff",
						[92679] = "Miscellaneous#Pet stuff",
						[79868] = "Item Enhancement!#Archaeology",
						[127755] = "Miscellaneous#Pet stuff",
						[79249] = "Junk#Junk",
						[65360] = "Item Enhancement!#Utility",
						[117397] = "Junk#Junk",
						[93148] = "Miscellaneous#Pet stuff",
						[116421] = "Miscellaneous#Pet stuff",
						[116429] = "Miscellaneous#Pet stuff",
						[37460] = "Miscellaneous#Pet stuff",
						[30544] = "Item Enhancement!#Utility",
						[127669] = "Junk#Junk",
						[116374] = "Miscellaneous#Pet stuff",
						[93149] = "Miscellaneous#Pet stuff",
						[92665] = "Miscellaneous#Pet stuff",
						[116422] = "Miscellaneous#Pet stuff",
						[89125] = "Miscellaneous#Pet stuff",
						[128503] = "Miscellaneous#garrison shit",
						[127884] = "Miscellaneous#garrison shit",
						[127662] = "Miscellaneous#garrison shit",
						[118907] = "Item Enhancement!#Utility",
						[40727] = "Item Enhancement!#Utility",
						[116415] = "Miscellaneous#Pet stuff",
						[116423] = "Miscellaneous#Pet stuff",
						[122273] = "Consumable#Consumable",
						[163036] = "Miscellaneous#Pet stuff",
						[92681] = "Miscellaneous#Pet stuff",
						[127655] = "Junk#Junk",
						[127663] = "Miscellaneous#garrison shit",
						[98715] = "Miscellaneous#Pet stuff",
						[92682] = "Miscellaneous#Pet stuff",
						[120321] = "Miscellaneous#Pet stuff",
						[111820] = "Item Enhancement!#Utility",
						[98112] = "Miscellaneous#Pet stuff",
						[92683] = "Miscellaneous#Pet stuff",
						[116416] = "Miscellaneous#Pet stuff",
						[87214] = "Item Enhancement!#Utility",
						[94207] = "Miscellaneous#Pet stuff",
						[108439] = "Item Enhancement!#Archaeology",
						[92680] = "Miscellaneous#Pet stuff",
						[122298] = "Miscellaneous#garrison shit",
						[125787] = "Miscellaneous#garrison shit",
						[43626] = "Miscellaneous#Pet stuff",
						[122457] = "Miscellaneous#Pet stuff",
						[85500] = "Item Enhancement!#Utility",
						[86143] = "Miscellaneous#Pet stuff",
						[112059] = "Item Enhancement!#Utility",
						[101529] = "Miscellaneous#Pet stuff",
						[111821] = "Item Enhancement!#Utility",
						[129929] = "Item Enhancement!#Utility",
						[119093] = "Item Enhancement!#Utility",
						[116417] = "Miscellaneous#Pet stuff",
						[87215] = "Item Enhancement!#Utility",
						[44820] = "Miscellaneous#Pet stuff",
						[43352] = "Miscellaneous#Pet stuff",
						[89906] = "Miscellaneous#Pet stuff",
						[114806] = "Miscellaneous#garrison shit",
						[127895] = "Miscellaneous#garrison shit",
						[116424] = "Miscellaneous#Pet stuff",
						[92676] = "Miscellaneous#Pet stuff",
						[103678] = "Item Enhancement!#Utility",
						[60854] = "Item Enhancement!#Utility",
						[122601] = "Item Enhancement!#Utility",
						[122272] = "Miscellaneous#garrison shit",
						[104329] = "Item Enhancement!#Utility",
						[110560] = "Miscellaneous#garrison shit",
						[40768] = "Item Enhancement!#Utility",
						[116418] = "Miscellaneous#Pet stuff",
						[87216] = "Item Enhancement!#Utility",
						[18986] = "Item Enhancement!#Utility",
						[109584] = "Item Enhancement!#Archaeology",
						[127880] = "Miscellaneous#garrison shit",
						[114807] = "Miscellaneous#garrison shit",
						[93146] = "Miscellaneous#Pet stuff",
						[40586] = "Item Enhancement!#Utility",
						[128353] = "Item Enhancement!#Utility",
						[114943] = "Item Enhancement!#Utility",
						[71153] = "Miscellaneous#Pet stuff",
					},
				},
			},
		},
		["ItemCategory"] = {
			["profiles"] = {
				["Default"] = {
					["splitBySubclass"] = {
						["Recipe"] = true,
						["Consumable"] = true,
						["Item Enhancement!"] = true,
						["Tradeskill"] = true,
						["Trade Goods"] = false,
						["Gem"] = true,
						["Glyph"] = true,
						["Miscellaneous"] = true,
					},
				},
			},
		},
		["NewItem"] = {
			["profiles"] = {
				["Default"] = {
					["highlight"] = "blizzard",
				},
			},
		},
		["AdiBags_TooltipInfo"] = {
		},
		["MoneyFrame"] = {
		},
		["CurrencyFrame"] = {
			["profiles"] = {
				["Default"] = {
					["shown"] = {
						["Ancient Mana"] = false,
						["Ironpaw Token"] = false,
						["Bloody Coin"] = false,
						["Valor"] = false,
						["Lesser Charm of Good Fortune"] = false,
						["Curious Coin"] = false,
						["Order Resources"] = false,
						["Veiled Argunite"] = false,
						["Warforged Seal"] = false,
						["Mote of Darkness"] = false,
						["Timewarped Badge"] = false,
						["Seal of Tempered Fate"] = false,
						["Seal of Inevitable Fate"] = false,
						["Oil"] = false,
						["Epicurean's Award"] = false,
						["Honor Points"] = false,
						["Garrison Resources"] = false,
						["Timeless Coin"] = false,
						["Essence of Corrupted Deathwing"] = false,
						["Apexis Crystal"] = false,
						["Darkmoon Prize Ticket"] = false,
						["Wakening Essence"] = false,
						["Conquest Points"] = false,
						["Elder Charm of Good Fortune"] = false,
						["Champion's Seal"] = false,
						["Seal of Broken Fate"] = false,
					},
				},
			},
		},
		["DataSource"] = {
		},
		["ItemSets"] = {
		},
		["Junk"] = {
			["profiles"] = {
				["Default"] = {
					["include"] = {
						[127669] = true,
						[86583] = true,
						[117397] = true,
						[127770] = true,
						[110505] = true,
						[79249] = true,
						[115506] = true,
						[127655] = true,
					},
				},
			},
		},
		["Equipment"] = {
		},
	},
	["profileKeys"] = {
		["Canerena - Arthas"] = "Default",
		["Beefyrivers - Thrall"] = "Default",
		["Yandanderex - Moon Guard"] = "Default",
		["Serenerivers - Arthas"] = "Default",
		["Sacredrivers - Korgath"] = "Default",
		["Dammedrivers - Exodar"] = "Default",
		["Wildrivers - Korgath"] = "Default",
		["Crazyrivers - Bleeding Hollow"] = "Default",
		["Wildrivers - Bleeding Hollow"] = "Default",
		["Deadrivers - Korgath"] = "Default",
		["Crazyrivers - Sargeras"] = "Default",
		["Testrivers - Arthas"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Shachein - Arthas"] = "Default",
		["Notariver - Arthas"] = "Default",
		["Tinyrivers - Arthas"] = "Default",
		["Sneakyrivers - Korgath"] = "Default",
		["Angryrivers - Korgath"] = "Default",
		["Toofattohide - Kel'Thuzad"] = "Default",
		["Serenerivers - Korgath"] = "Default",
		["Kdajshtlaiuw - Bleeding Hollow"] = "Default",
		["Smaz - Mug'thol"] = "Default",
		["Testes - Arthas"] = "Default",
		["Daedrasminia - Arthas"] = "Default",
		["Riversticks - Bleeding Hollow"] = "Default",
		["Skankyrivers - Arthas"] = "Default",
		["Boringrivers - Korgath"] = "Default",
		["Rapidrivers - Arthas"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Ailisuul - Arthas"] = "Default",
		["Mindrivers - Korgath"] = "Default",
		["Serenerivers - Bleeding Hollow"] = "Default",
		["Blindrivers - Sargeras"] = "Default",
		["Tinyrivers - Kel'Thuzad"] = "Default",
		["Testrivers - Bleeding Hollow"] = "Default",
		["Sassyrivers - Arthas"] = "Default",
		["Serenerivers - Kel'Thuzad"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
		["Brightrivers - Korgath"] = "Default",
		["Evilrivers - Sargeras"] = "Default",
		["Littlerivers - Kel'Thuzad"] = "Default",
		["Hiddenrivers - Korgath"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Feralrivers - Sargeras"] = "Default",
		["Evilrivers - Korgath"] = "Default",
		["Hulyon - Kel'Thuzad"] = "Default",
		["Holyrivers - Sargeras"] = "Default",
		["Edgyrivers - Kel'Thuzad"] = "Default",
		["Serenerivers - Sargeras"] = "Default",
		["Luckyrivers - Korgath"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Mecharivers - Sargeras"] = "Default",
		["Eysta - Sargeras"] = "Default",
		["Crazyrivers - Arthas"] = "Default",
		["Emptyrivers - Bleeding Hollow"] = "Default",
		["Blindrivers - Korgath"] = "Default",
		["Boringrivers - Bleeding Hollow"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Emptyrivers - Arthas"] = "Default",
		["Beefyrivers - Bleeding Hollow"] = "Default",
		["Magicrivers - Korgath"] = "Default",
		["Savattellir - Arthas"] = "Default",
		["Tinyrivers - Sargeras"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Emptyrivers - Korgath"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["virtualStacks"] = {
				["stackable"] = true,
				["incomplete"] = true,
			},
			["skin"] = {
				["BackpackColor"] = {
					nil, -- [1]
					nil, -- [2]
					nil, -- [3]
					0.548191010951996, -- [4]
				},
				["border"] = "None",
				["insets"] = 0,
			},
			["positions"] = {
				["Bank"] = {
					["xOffset"] = 168.500112374129,
					["point"] = "BOTTOMLEFT",
					["yOffset"] = 361.369805189517,
				},
				["Backpack"] = {
					["xOffset"] = -331.248706794511,
					["point"] = "TOPRIGHT",
					["yOffset"] = -156.446543855171,
				},
			},
			["compactLayout"] = true,
			["rightClickConfig"] = false,
			["autoDeposit"] = true,
			["positionMode"] = "manual",
			["columnWidth"] = {
				["Backpack"] = 5,
			},
		},
	},
}
