
AdvancedInterfaceOptionsSaved = {
	["CustomVars"] = {
	},
	["DBVersion"] = 3,
	["ModifiedCVars"] = {
		["test_cameradynamicpitchbasefovpad"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["camerapitchmovespeed"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["sound_ambiencevolume"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["nameplateverticalscale"] = "Interface\\FrameXML\\InterfaceOptionsPanels.lua:1322",
		["test_cameratargetfocusenemyenable"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["test_cameraheadmovementfirstpersondamprate"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["mapanimminalpha"] = "Interface\\AddOns\\ElvUI\\Modules\\maps\\worldmap.lua:212",
		["test_cameraheadmovementmovingstrength"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["nameplateshowdebuffsonfriendly"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:160",
		["mousespeed"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["test_cameraheadmovementmovingdamprate"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["nameplatemaxdistance"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:1012",
		["test_cameraheadmovementstandingstrength"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["nameplateotherbottominset"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:993",
		["nameplateshowself"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:1000",
		["camerazoomspeed"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["mapfade"] = "Interface\\AddOns\\ElvUI\\Modules\\maps\\worldmap.lua:212",
		["chatstyle"] = "Interface\\FrameXML\\InterfaceOptionsPanels.lua:906",
		["nameplatemotion"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:985",
		["nameplatehorizontalscale"] = "Interface\\FrameXML\\InterfaceOptionsPanels.lua:1321",
		["cameradistancemaxzoomfactor"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["lastselectedclubid"] = "...ace\\AddOns\\Blizzard_Communities\\CommunitiesFrame.lua:593",
		["nameplatepersonalhidedelayseconds"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:1025",
		["activecufprofile"] = "...rd_CUFProfiles\\Blizzard_CompactUnitFrameProfiles.lua:262",
		["sound_mastervolume"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["test_cameradynamicpitch"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["nameplateothertopinset"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:992",
		["nameplateshowall"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:986",
		["test_cameratargetfocusinteractenable"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["test_cameraovershoulder"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["autoclearafk"] = "Interface\\AddOns\\ElvUI\\Modules\\misc\\afk.lua:339",
		["advjournallastopened"] = "Interface\\FrameXML\\MainMenuBarMicroButtons.lua:820",
		["spellactivationoverlayopacity"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["colorblindweaknessfactor"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["sound_dialogvolume"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["unitnameown"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["camerayawsmoothspeed"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["test_cameraheadmovementstandingdamprate"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["test_cameradynamicpitchbasefovpadflying"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["test_cameradynamicpitchbasefovpaddownscale"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["test_cameraheadmovementdeadzone"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["lockactionbars"] = "...rface\\AddOns\\ElvUI\\Modules\\actionbars\\actionbars.lua:1296",
		["test_cameraheadmovementstrength"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["sound_musicvolume"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:204",
		["test_cameraheadmovementrangescale"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["camerayawmovespeed"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["nameplateresourceontarget"] = "...rface\\AddOns\\ElvUI\\Modules\\nameplates\\nameplates.lua:1018",
		["petjournaltab"] = "...AddOns\\Blizzard_Collections\\Blizzard_Collections.lua:6",
		["minicommunitiesframe"] = "Interface\\SharedXML\\SharedUIPanelTemplates.lua:853",
		["test_cameradynamicpitchsmartpivotcutoffdist"] = "Interface\\AddOns\\DynamicCam\\Core.lua:105",
		["displayspellactivationoverlays"] = "Interface\\FrameXML\\OptionsPanelTemplates.lua:468",
		["camerawatercollision"] = "Interface\\AddOns\\WeakAuras\\RegionTypes\\Icon.lua:458",
	},
	["CharVars"] = {
	},
	["AccountVars"] = {
	},
	["EnforceSettings"] = false,
}
