
AltoholicDB = {
["profileKeys"] = {
["Calestin - Sargeras"] = "Calestin - Sargeras",
["Stream - Argent Dawn"] = "Stream - Argent Dawn",
["Naturerivers - Korgath"] = "Naturerivers - Korgath",
["Lotic - Argent Dawn"] = "Lotic - Argent Dawn",
["Mangrove - Argent Dawn"] = "Mangrove - Argent Dawn",
["Flumina - Argent Dawn"] = "Flumina - Argent Dawn",
["Emptyrivers - Sargeras"] = "Emptyrivers - Sargeras",
["Alluvium - Argent Dawn"] = "Alluvium - Argent Dawn",
["Esker - Kel'Thuzad"] = "Esker - Kel'Thuzad",
["Asperos - Kel'Thuzad"] = "Asperos - Kel'Thuzad",
["Headcut - Argent Dawn"] = "Headcut - Argent Dawn",
["Confluence - Argent Dawn"] = "Confluence - Argent Dawn",
["Ochrian - Argent Dawn"] = "Ochrian - Argent Dawn",
["Riparium - Argent Dawn"] = "Riparium - Argent Dawn",
["Wildeadoriah - The Scryers"] = "Wildeadoriah - The Scryers",
["Benthos - Argent Dawn"] = "Benthos - Argent Dawn",
["Emptyrivers - Argent Dawn"] = "Emptyrivers - Argent Dawn",
["Karst - Argent Dawn"] = "Karst - Argent Dawn",
["Cataracts - Argent Dawn"] = "Cataracts - Argent Dawn",
["Sverdrup - Argent Dawn"] = "Sverdrup - Argent Dawn",
["Estuary - Argent Dawn"] = "Estuary - Argent Dawn",
},
["global"] = {
["options"] = {
["Tabs.Grids.Default.Argent Dawn.Column5"] = "Default.Argent Dawn.Estuary",
["Tabs.Achievements.Default.Argent Dawn.Column10"] = "Default.Argent Dawn.Estuary",
["UI.Tabs.Grids.Sets.PVP.Warfront"] = true,
["Tabs.Achievements.Default.Argent Dawn.Column8"] = "Default.Argent Dawn.Riparium",
["Tabs.Achievements.Default.Argent Dawn.Column1"] = "Default.Argent Dawn.Sverdrup",
["Tabs.Achievements.Default.Argent Dawn.Column6"] = "Default.Argent Dawn.Confluence",
["Tabs.Grids.Default.Argent Dawn.Column7"] = "Default.Argent Dawn.Mangrove",
["Tabs.Achievements.Default.Argent Dawn.Column3"] = "Default.Argent Dawn.Karst",
["UI.Tabs.Grids.Sets.IncludePVE"] = false,
["UI.Tabs.Grids.Companions.CurrentXPack"] = 3,
["Tabs.Achievements.Default.Argent Dawn.Column12"] = "Default.Argent Dawn.Alluvium",
["UI.Tabs.Grids.Sets.PVP.Alliance"] = false,
["UI.Tabs.Grids.Dungeons.CurrentXPack"] = 4,
["UI.Tabs.Grids.Emissaries.CurrentXPack"] = 6,
["Tabs.Grids.Default.Argent Dawn.Column11"] = "Default.Argent Dawn.Confluence",
["UI.Tabs.Grids.Sets.PVP.Combatant I"] = true,
["UI.Tabs.Grids.Sets.PVP.Aspirant"] = true,
["Tabs.Grids.Default.Argent Dawn.Column2"] = "Default.Argent Dawn.Flumina",
["Tabs.Grids.Default.Argent Dawn.Column13"] = "Default.Argent Dawn.Benthos",
["UI.Tabs.Grids.Sets.PVP.Horde"] = false,
["Tabs.Grids.Default.Argent Dawn.Column6"] = "Default.Argent Dawn.Cataracts",
["Tabs.Achievements.Default.Argent Dawn.Column2"] = "Default.Argent Dawn.Flumina",
["Tabs.Grids.Default.Argent Dawn.Column1"] = "Default.Argent Dawn.Riparium",
["Tabs.Achievements.Default.Argent Dawn.Column13"] = "Default.Argent Dawn.Emptyrivers",
["UI.Tabs.Grids.Sets.CurrentXPack"] = 10,
["UI.Tabs.Grids.Sets.PVP.Elite"] = true,
["Tabs.Achievements.Default.Argent Dawn.Column5"] = "Default.Argent Dawn.Mangrove",
["Tabs.Grids.Default.Argent Dawn.Column8"] = "Default.Argent Dawn.Alluvium",
["Tabs.Grids.Default.Argent Dawn.Column10"] = "Default.Argent Dawn.Stream",
["UI.Tabs.Grids.Reputations.CurrentXPack"] = 12,
["Tabs.Grids.Default.Argent Dawn.Column9"] = "Default.Argent Dawn.Headcut",
["Tabs.Achievements.Default.Argent Dawn.Column9"] = "Default.Argent Dawn.Headcut",
["Tabs.Grids.Default.Argent Dawn.Column4"] = "Default.Argent Dawn.Sverdrup",
["UI.VendorColorCoding"] = false,
["UI.Tabs.Grids.Currencies.CurrentTokenType"] = "Unused",
["UI.Tabs.Characters.ViewBagsAllInOne"] = true,
["Tabs.Achievements.Default.Argent Dawn.Column11"] = "Default.Argent Dawn.Cataracts",
["Tabs.Grids.Default.Argent Dawn.Column3"] = "Default.Argent Dawn.Emptyrivers",
["UI.AHColorCoding"] = false,
["Tabs.Achievements.Default.Argent Dawn.Column4"] = "Default.Argent Dawn.Lotic",
["Tabs.Grids.Default.Argent Dawn.Column12"] = "Default.Argent Dawn.Karst",
["UI.Tabs.Grids.Sets.PVP.Honor"] = true,
["Tabs.Achievements.Default.Argent Dawn.Column7"] = "Default.Argent Dawn.Stream",
["UI.Tabs.Grids.Sets.PVP.PVP Rare"] = true,
["UI.Tabs.Grids.Sets.PVP.Gladiator"] = true,
},
},
}
Altoholic_UI_Options = {
["Transparency"] = 1,
["AHColorCoding"] = true,
["Scale"] = 1,
["Mail"] = {
["AutoCompletePriority"] = 1,
["GuildMailWarning"] = true,
["LastExpiryWarning"] = 1718893910,
["AutoCompleteRecipient"] = true,
["TimeToNextWarning"] = 3,
},
["ClampWindowToScreen"] = false,
["VendorColorCoding"] = true,
["Minimap"] = {
["IconAngle"] = 180,
["ShowIcon"] = true,
["IconRadius"] = 102,
},
}
Altoholic_Tooltip_Options = {
["ShowItemSource"] = true,
["ShowTotalItemCount"] = false,
["ShowItemID"] = true,
["ShowMergedRealmsCount"] = true,
["ShowSimpleCount"] = false,
["ShowCouldBeStoredOn"] = false,
["ShowGuildBankRealm"] = false,
["ShowItemXPack"] = false,
["IncludeGuildBankInTotal"] = true,
["ShowGuildBankCountPerTab"] = false,
["HiddenGuilds"] = {
},
["ShowKnownRecipes"] = true,
["ShowAllRealmsCount"] = true,
["ShowHearthstoneCount"] = true,
["ShowGuildBankCount"] = true,
["ShowAllAccountsCount"] = true,
["ShowCrossFactionCount"] = true,
["ShowItemCount"] = false,
["ShowGatheringNodesCount"] = true,
}
Altoholic_Sharing_Options = {
["SharedContent"] = {
},
["GuildBankAutoUpdate"] = false,
["IsEnabled"] = false,
["Domains"] = {
},
["Clients"] = {
},
}
Altoholic_Calendar_Options = {
["WarningsEnabled"] = true,
["WarningType1"] = "30,15,10,5,4,3,2,1",
["UseDialogBoxForWarnings"] = false,
["WarningType2"] = "30,15,10,5,4,3,2,1",
["WarningType3"] = "30,15,10,5,4,3,2,1",
["WarningType4"] = "30,15,10,5,4,3,2,1",
["WeekStartsOnMonday"] = false,
}
