
BetterAddonListDB = {
["sets"] = {
["RIO"] = {
"PremadeApplicantsFilter",
"PremadeGroupsFilter",
"PremadeRegions",
"RaiderIO",
"RaiderIO_DB_US_M",
},
["Talents"] = {
"TalentLoadoutManager",
"TalentTreeTweaks",
},
["Development"] = {
"!BugGrabber",
"AdvancedInterfaceOptions",
"Bisector",
"BugSack",
"DevTool",
"Paste",
"WowLua",
},
["BigWigs"] = {
"BigWigs",
"BigWigs_Aberrus",
"BigWigs_Amirdrassil",
"BigWigs_BattleForAzeroth",
"BigWigs_Classic",
"BigWigs_Core",
"BigWigs_DragonIsles",
"BigWigs_Options",
"BigWigs_Plugins",
"BigWigs_VaultOfTheIncarnates",
"LittleWigs",
"LittleWigs_BattleForAzeroth",
"LittleWigs_BurningCrusade",
"LittleWigs_Cataclysm",
"LittleWigs_Classic",
"LittleWigs_Legion",
"LittleWigs_MistsOfPandaria",
"LittleWigs_Shadowlands",
"LittleWigs_WarlordsOfDraenor",
"LittleWigs_WrathOfTheLichKing",
},
["!Main"] = {
},
["Altoholic"] = {
"AddonFactory",
"Altoholic",
"Altoholic_Achievements",
"Altoholic_Agenda",
"Altoholic_Characters",
"Altoholic_Grids",
"Altoholic_Guild",
"Altoholic_Options",
"Altoholic_Search",
"Altoholic_Summary",
"DataStore",
"DataStore_Achievements",
"DataStore_Agenda",
"DataStore_Auctions",
"DataStore_Characters",
"DataStore_Containers",
"DataStore_Crafts",
"DataStore_Currencies",
"DataStore_Garrisons",
"DataStore_Inventory",
"DataStore_Mails",
"DataStore_Pets",
"DataStore_Quests",
"DataStore_Reputations",
"DataStore_Spells",
"DataStore_Stats",
"DataStore_Talents",
},
["!Casual Content"] = {
"AngrierWorldQuests",
"BattlePetBreedID",
"CandyBuckets",
"DialogKey",
"DynamicCam",
"Immersion",
"InFlight",
"InFlight_Load",
"MinimalArchaeology",
"Rematch",
"TomTom",
"ToyBoxEnhanced",
"TwitchEmotesvKEKL",
"tdBattlePetScript",
},
["ElvUI"] = {
"AddOnSkins",
"ElvUI",
"ElvUI_Libraries",
"ElvUI_Options",
"ElvUI_SLE",
},
["TSM"] = {
"TradeSkillMaster",
"TradeSkillMaster_AppHelper",
},
["WeakAuras"] = {
"CurseBreakerCompanion",
"SharedMedia_Causese",
"WeakAuras",
"WeakAurasArchive",
"WeakAurasCompanion",
"WeakAurasModelPaths",
"WeakAurasOptions",
},
["BetterBags"] = {
"BetterBags",
"BetterBags_Archaeology",
"BetterBags_AzerothianArchives",
"BetterBags_BattlePetItems",
"BetterBags_Dragonflight",
"BetterBags_DragonflightReputationInsignia",
},
["Macros"] = {
"MacroToolkit",
"MacroToolkitIcons",
},
["temp"] = {
"!!!Perfy",
"!BugGrabber",
"AddOnSkins",
"AdvancedInterfaceOptions",
"AdventureArchives",
"AdventureArchives_Dragonflight_Miscs",
"AdventureArchives_Dragonflight_Quests",
"AdventureArchives_Mail",
"AlterEgo",
"AngrierWorldQuests",
"BattlePetBreedID",
"BetterBags_Archaeology",
"BetterBags_AzerothianArchives",
"BetterBags_BattlePetItems",
"BetterBags_Dragonflight",
"BetterBags_DragonflightReputationInsignia",
"BetterBags_WarWithin",
"BetterFishing",
"Bisector",
"BlizzMove",
"BlizzMove_Debug",
"BtWQuests",
"BtWQuestsTheWarWithin",
"BugSack",
"CandyBuckets",
"CurseBreakerCompanion",
"DeleteManaGem",
"Details",
"Details_Compare2",
"Details_DataStorage",
"Details_EncounterDetails",
"Details_RaidCheck",
"Details_Streamer",
"Details_TinyThreat",
"Details_Vanguard",
"DevTool",
"DialogKey_Numy",
"DialogueUI",
"DynamicCam",
"ElvUI",
"ElvUI_Libraries",
"ElvUI_Options",
"ElvUI_SLE",
"FamilyFamiliarHelper",
"FrameCounter",
"GatherMate2",
"GatherMate2_Data",
"Glider",
"HandyNotes",
"HandyNotes_LoosePebbles",
"HandyNotes_TheWarWithin",
"HandyNotes_TreasureHunter",
"Handynotes_Pandaria",
"LiquidReminders",
"LiquidUpdater",
"M6",
"MacroToolkit",
"MacroToolkitIcons",
"MinimalArchaeology",
"MinimapButtonButton",
"MuteSoundFile",
"MuteSoundFile_Options",
"MythicDungeonTools",
"Narcissus",
"Narcissus_Achievements",
"Narcissus_BagFilter",
"Narcissus_Barbershop",
"Narcissus_Database_Item",
"Narcissus_Database_NPC",
"Narcissus_GamePad",
"OPie",
"OPie_ElvUI",
"OmniCD",
"OmniCD_BattleRes",
"Paste",
"Plater",
"Plumber",
"PremadeApplicantsFilter",
"PremadeGroupsFilter",
"PremadeRegions",
"RECrystallize",
"REKeys",
"Rarity",
"Rarity_Options",
"Rematch",
"SavedInstances",
"SharedMedia_Causese",
"Simulationcraft",
"TalentLoadoutManager",
"TalentTreeTweaks",
"TextureAtlasViewer",
"TomTom",
"ToyBoxEnhanced",
"WarpDeplete",
"WeakAuras",
"WeakAurasArchive",
"WeakAurasModelPaths",
"WeakAurasOptions",
"WeakAurasTemplates",
"WeeklyKnowledge",
"WowLua",
"tdBattlePetScript",
},
["!Combat"] = {
"DeleteManaGem",
"MythicDungeonTools",
"OPie",
"OPie_ElvUI",
"OmniCD",
"OmniCD_BattleRes",
"Plater",
"Simulationcraft",
"TalentLoadoutManager",
"TalentTreeTweaks",
},
["Details"] = {
"Details",
"Details_Compare2",
"Details_DataStorage",
"Details_EncounterDetails",
"Details_RaidCheck",
"Details_Streamer",
"Details_TinyThreat",
"Details_Vanguard",
},
},
["nested"] = {
["M+/Raiding"] = {
["RIO"] = true,
["BigWigs"] = true,
["Details"] = true,
["WeakAuras"] = true,
["ElvUI"] = true,
},
["Bisector development"] = {
["Development"] = true,
},
["!Main"] = {
["RIO"] = true,
["Talents"] = true,
["Development"] = true,
["BigWigs"] = true,
["Details"] = true,
["ElvUI"] = true,
["Altoholic"] = true,
["BetterBags"] = true,
["Macros"] = true,
["!Casual Content"] = true,
["WeakAuras"] = true,
["TSM"] = true,
},
["!Casual Content"] = {
["Altoholic"] = true,
["Talents"] = true,
["Macros"] = true,
},
["!Combat"] = {
["Macros"] = true,
["Talents"] = true,
},
["WeakAuras"] = {
["Development"] = true,
},
},
["protected"] = {
},
}
