
BlizzHUDTweaksDB = {
["profileKeys"] = {
["Seep - Kel'Thuzad"] = "Default",
["Loess - Kel'Thuzad"] = "Default",
["Dukasuka - Eredar"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Doneer - Eredar"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Slush - Mal'Ganis"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Bog - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Rime - Kel'Thuzad"] = "Default",
["Surge - Argent Dawn"] = "Default",
["Geyser - Mal'Ganis"] = "Default",
["Quag - Argent Dawn"] = "Default",
["Rivulet - Mal'Ganis"] = "Default",
["Falls - Mal'Ganis"] = "Default",
["Brack - Mal'Ganis"] = "Default",
["Docks - Kel'Thuzad"] = "Default",
["Moraine - Kel'Thuzad"] = "Default",
["Rapids - Argent Dawn"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Brook - Argent Dawn"] = "Default",
["Spume - Argent Dawn"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Fjord - Mal'Ganis"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Baffle - Mal'Ganis"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Lather - Mal'Ganis"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Rill - Kel'Thuzad"] = "Default",
["Cirque - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Mire - Mal'Ganis"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Floe - Mal'Ganis"] = "Default",
["Roberia - Eredar"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["global"] = {
["minimap"] = {
["minimapPos"] = 309.921165279593,
},
},
["profiles"] = {
["Default"] = {
["UtilityCooldownViewer"] = {
["Enabled"] = false,
},
["ActionBar4"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["MiscellaneousFontSizeOverwriteTargetManaBarFontSize"] = 13,
["MiscellaneousFontSizeOverwriteTargetHealthBarFontSize"] = 16,
["MainStatusTrackingBarContainer"] = {
["MouseOverInCombat"] = false,
["OutOfCombatAlpha"] = 0,
["Enabled"] = false,
["FadeInCombat"] = false,
["UseGlobalOptions"] = false,
},
["MicroMenu"] = {
["UseGlobalOptions"] = false,
},
["ClassResourcePositionAnchor_PALADIN_Retribution"] = "BOTTOMRIGHT",
["ClassResourcePositionHide_PALADIN_Holy"] = false,
["ActionBar8LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ExtraActionButtonFrame"] = {
["UseGlobalOptions"] = false,
},
["VehicleSeatIndicator"] = {
["Hidden"] = false,
["displayName"] = "Vehicle Seat Frame",
},
["MiscellaneousActionbarPaddingOverwriteActionbar1Enabled"] = false,
["ActionBar1LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["BagsBar"] = {
["UseGlobalOptions"] = false,
},
["ClassResourcePositionAnchor_PALADIN_Protection"] = "BOTTOMRIGHT",
["TotemFrameOriginalPoint"] = {
["Anchor"] = "LEFT",
["XOffset"] = 0,
["RelativeAnchor"] = "LEFT",
["YOffset"] = 0,
},
["ClassResourcePositionXOffset_PALADIN_Retribution"] = 233,
["ClassResourcePositionXOffset_PALADIN_Holy"] = 233,
["ActionBar2LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["BuffIconCooldownViewer"] = {
["Enabled"] = false,
},
["PartyFrame"] = {
["Enabled"] = false,
},
["MicroMenuLinkedFrames"] = {
["BagsBar"] = true,
["MicroMenu"] = true,
},
["ActionBar3LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ActionBar1"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ActionBar6"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ActionBar5"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ActionBar7"] = {
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0,
},
["BuffBarCooldownViewer"] = {
["Enabled"] = false,
},
["BagsBarLinkedFrames"] = {
["BagsBar"] = true,
["MicroMenu"] = true,
},
["DurabilityFrame"] = {
["Hidden"] = false,
},
["GlobalOptionsMiscellaneousEnabled"] = false,
["PlayerCastingBarFrame"] = {
["description"] = "You can set global values which can be activated for each frame.",
["VehicleAlpha"] = 0.3,
["FadeVehicle"] = false,
["UseGlobalOptions"] = false,
["NeighborhoodAlpha"] = 0.05,
["ByHealthThreshold"] = 98,
["FadeByHealth"] = true,
["ByHealthAlpha"] = 0.75,
["TreatTargetLikeInCombat"] = true,
["UpdateInterval"] = 0.2,
["FadeInNeighborhood"] = true,
["OutOfCombatAlpha"] = 0.3,
["InCombatAlpha"] = 0.75,
},
["ActionBar4LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ClassResourcePositionHide_PALADIN_Protection"] = false,
["ActionBar8"] = {
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0,
},
["MiscellaneousFontSizeOverwritePlayerHealthBarFontSize"] = 16,
["ClassResourcePositionAnchor_PALADIN_Holy"] = "BOTTOMRIGHT",
["ClassResourcePositionEnabled_PALADIN_Protection"] = false,
["MiscellaneousFontSizeOverwritePlayerManaBarFontSize"] = 13,
["ClassResourcePositionYOffset_PALADIN_Protection"] = -30,
["ClassResourcePositionYOffset_PALADIN_Retribution"] = -35,
["ActionBar6LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["TotemFramePositionEnabled"] = false,
["TotemFramePositionAnchor"] = "BOTTOM",
["*Global*"] = {
["VehicleAlpha"] = 0.3,
["FadeByHealth"] = true,
["OutOfCombatAlpha"] = 0.3,
["ByHealthThreshold"] = 98,
["ByHealthAlpha"] = 0.75,
["FadeVehicle"] = false,
["TreatTargetLikeInCombat"] = true,
["UpdateInterval"] = 0.09999999999999999,
["FadeInNeighborhood"] = true,
["FadeDuration"] = 0.1,
["NeighborhoodAlpha"] = 0,
["InCombatAlpha"] = 0.9,
},
["ClassResourcePositionScale_PALADIN_Holy"] = 1.85,
["TotemFramePositionScale"] = 1,
["TotemFrameDetached"] = true,
["MiscellaneousShowHidePlayerName"] = false,
["ActionBar2"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ClassResourcePositionScale_PALADIN_Retribution"] = 1.85,
["MinimapCluster"] = {
["MouseOverInCombat"] = false,
["OutOfCombatAlpha"] = 0.75,
["Enabled"] = false,
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0.75,
},
["ClassResourcePositionScale_PALADIN_Protection"] = 2,
["ClassResourcePositionXOffset_PALADIN_Protection"] = 220,
["CompactRaidFrameContainer"] = {
["Enabled"] = false,
},
["ClassResourcePositionYOffset_PALADIN_Holy"] = -90,
["ActionBar7LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ClassResourcePositionEnabled_PALADIN_Retribution"] = false,
["ActionBar3"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ClassResourcePositionEnabled_PALADIN_Holy"] = false,
["ActionBar5LinkedFrames"] = {
["ActionBar3"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar8"] = true,
["ActionBar2"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["EssentialCooldownViewer"] = {
["Enabled"] = false,
},
},
},
}
