
BlizzHUDTweaksDB = {
["profileKeys"] = {
["Sverdrup - Argent Dawn"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Dukasuka - Eredar"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Doneer - Eredar"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Roberia - Eredar"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["global"] = {
["minimap"] = {
["minimapPos"] = 309.921165279593,
},
},
["profiles"] = {
["Default"] = {
["ActionBar4"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["MiscellaneousFontSizeOverwriteTargetManaBarFontSize"] = 13,
["ClassResourcePositionScale_PALADIN_Retribution"] = 1.85,
["MainStatusTrackingBarContainer"] = {
["Enabled"] = false,
},
["MicroMenu"] = {
["UseGlobalOptions"] = false,
},
["ClassResourcePositionAnchor_PALADIN_Retribution"] = "BOTTOMRIGHT",
["ClassResourcePositionHide_PALADIN_Holy"] = false,
["ActionBar8LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ExtraActionButtonFrame"] = {
["UseGlobalOptions"] = false,
},
["VehicleSeatIndicator"] = {
["Hidden"] = false,
["displayName"] = "Vehicle Seat Frame",
},
["MiscellaneousActionbarPaddingOverwriteActionbar1Enabled"] = false,
["ActionBar1LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["BagsBar"] = {
["UseGlobalOptions"] = false,
},
["ClassResourcePositionAnchor_PALADIN_Protection"] = "BOTTOMRIGHT",
["TotemFrameOriginalPoint"] = {
["Anchor"] = "LEFT",
["XOffset"] = 0,
["RelativeAnchor"] = "LEFT",
["YOffset"] = 0,
},
["ClassResourcePositionXOffset_PALADIN_Retribution"] = 233,
["ClassResourcePositionYOffset_PALADIN_Holy"] = -90,
["ActionBar2LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["MicroMenuLinkedFrames"] = {
["BagsBar"] = true,
["MicroMenu"] = true,
},
["ActionBar3LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ActionBar1"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ActionBar6"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["ActionBar5"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["BagsBarLinkedFrames"] = {
["BagsBar"] = true,
["MicroMenu"] = true,
},
["DurabilityFrame"] = {
["Hidden"] = false,
},
["ClassResourcePositionHide_PALADIN_Protection"] = false,
["ClassResourcePositionEnabled_PALADIN_Retribution"] = false,
["ActionBar4LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ActionBar5LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ActionBar2"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["MiscellaneousFontSizeOverwritePlayerHealthBarFontSize"] = 16,
["ClassResourcePositionAnchor_PALADIN_Holy"] = "BOTTOMRIGHT",
["ClassResourcePositionEnabled_PALADIN_Protection"] = false,
["MiscellaneousFontSizeOverwritePlayerManaBarFontSize"] = 13,
["ClassResourcePositionXOffset_PALADIN_Protection"] = 220,
["ClassResourcePositionYOffset_PALADIN_Retribution"] = -35,
["*Global*"] = {
["VehicleAlpha"] = 0.3,
["FadeByHealth"] = true,
["OutOfCombatAlpha"] = 0.3,
["ByHealthThreshold"] = 98,
["ByHealthAlpha"] = 0.75,
["TreatTargetLikeInCombat"] = true,
["FadeVehicle"] = false,
["InCombatAlpha"] = 0.75,
},
["ClassResourcePositionScale_PALADIN_Holy"] = 1.85,
["TotemFramePositionAnchor"] = "BOTTOM",
["ActionBar7LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["TotemFramePositionScale"] = 1,
["TotemFrameDetached"] = true,
["MiscellaneousFontSizeOverwriteTargetHealthBarFontSize"] = 16,
["ClassResourcePositionEnabled_PALADIN_Holy"] = false,
["MinimapCluster"] = {
["MouseOverInCombat"] = false,
["OutOfCombatAlpha"] = 0.75,
["Enabled"] = false,
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0.75,
},
["CompactRaidFrameContainer"] = {
["Enabled"] = false,
},
["ClassResourcePositionScale_PALADIN_Protection"] = 2,
["ActionBar8"] = {
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0,
},
["MiscellaneousShowHidePlayerName"] = false,
["ActionBar7"] = {
["UseGlobalOptions"] = false,
["InCombatAlpha"] = 0,
},
["ClassResourcePositionYOffset_PALADIN_Protection"] = -30,
["ActionBar6LinkedFrames"] = {
["ActionBar8"] = true,
["ActionBar7"] = true,
["ActionBar5"] = true,
["ActionBar2"] = true,
["ActionBar3"] = true,
["ActionBar1"] = true,
["ActionBar4"] = true,
["ActionBar6"] = true,
},
["ActionBar3"] = {
["FadeInRestedArea"] = true,
["UseGlobalOptions"] = false,
},
["TotemFramePositionEnabled"] = false,
["ClassResourcePositionXOffset_PALADIN_Holy"] = 233,
},
},
}
