
CallToArmsSettings = {
["EnableA Queen's Fall"] = true,
["EnableShadowforge City"] = false,
["EnableCornerstone of Creation"] = true,
["EnableThe Imperial Seat"] = false,
["EnableThe Jailer's Vanguard"] = true,
["MinimizeInGroup"] = true,
["EnableSecrets of Nerub-ar Palace"] = true,
["EnableDomination's Grasp"] = true,
["EnableRandom Dungeon (The War Within)"] = true,
["EnableThe Elemental Overlords"] = false,
["EnableShackles of Fate"] = true,
["GrowDown"] = true,
["EnableRandom Heroic (The War Within: Season 1)"] = true,
["EnableRandom Timewalking Dungeon (Classic)"] = true,
["EnableThe Skittering Battlements"] = true,
["AnnounceStart"] = false,
["EnableThe Reckoning"] = true,
["EnableThe Grand Design"] = true,
["EnableEphemeral Plains"] = true,
["EnableThe Dark Bastille"] = true,
["FilterRole"] = true,
["EnableThe Codex of Chromie"] = true,
["EnableTimewalking"] = true,
}
