
ConsolePortSettings = {
["useCharacterSettings"] = false,
["tutorialProgress"] = 4,
["bindingShowExtraBars"] = false,
["bindingShowSpellMenuGrid"] = true,
["bindingOverlapEnable"] = false,
["UIenableCursor"] = true,
["useGlobalLootTooltip"] = false,
["showAdvancedSettings"] = true,
["keyboardEnable"] = false,
}
ConsolePortDevices = {
["Default"] = {
["Name"] = "Default",
["Config"] = {
["stickConfigs"] = {
{
["deadzone"] = 0.25,
["stick"] = "Left",
["axisX"] = "LStickX",
["axisY"] = "LStickY",
},
{
["deadzone"] = 0.25,
["stick"] = "Right",
["axisX"] = "RStickX",
["axisY"] = "RStickY",
},
{
["deadzone"] = 0.25,
["stick"] = "Gyro",
["axisX"] = "GStickX",
["axisY"] = "GStickY",
},
{
["deadzone"] = 0.25,
["stick"] = "Movement",
["axisX"] = "LStickX",
["axisY"] = "LStickY",
},
{
["deadzone"] = 0.25,
["stick"] = "Camera",
["axisX"] = "RStickX",
["axisY"] = "RStickY",
},
{
["deadzone"] = 0.25,
["stick"] = "Cursor",
["axisX"] = "RStickX",
["axisY"] = "RStickY",
},
},
["axisConfigs"] = {
{
["deadzone"] = 0.05,
["buttonPos"] = "LStickRight",
["buttonThreshold"] = 0.5,
["buttonNeg"] = "LStickLeft",
["axis"] = "LStickX",
},
{
["deadzone"] = 0.05,
["buttonPos"] = "LStickUp",
["buttonThreshold"] = 0.5,
["buttonNeg"] = "LStickDown",
["axis"] = "LStickY",
},
{
["deadzone"] = 0.05,
["buttonPos"] = "RStickRight",
["buttonThreshold"] = 0.5,
["buttonNeg"] = "RStickLeft",
["axis"] = "RStickX",
},
{
["deadzone"] = 0.05,
["buttonPos"] = "RStickUp",
["buttonThreshold"] = 0.5,
["buttonNeg"] = "RStickDown",
["axis"] = "RStickY",
},
{
["deadzone"] = 0.05,
["axis"] = "GStickX",
},
{
["deadzone"] = 0.05,
["axis"] = "GStickY",
},
{
["deadzone"] = 0.12,
["buttonThreshold"] = 0.5,
["buttonPos"] = "LTrigger",
["axis"] = "LTrigger",
},
{
["deadzone"] = 0.12,
["buttonThreshold"] = 0.5,
["buttonPos"] = "RTrigger",
["axis"] = "RTrigger",
},
},
},
["Icons"] = {
},
},
["PlayStation 4"] = {
["Version"] = 5,
["Name"] = "PlayStation 4",
["Active"] = true,
["Theme"] = {
["Colors"] = {
["PAD1"] = "6882A1",
["PAD3"] = "D35280",
["PAD4"] = "62BBB2",
["PAD2"] = "D84E58",
},
["Layout"] = {
["PADRTRIGGER"] = 34,
["PADLTRIGGER"] = 18,
["PADDDOWN"] = 21,
["PAD4"] = 35,
["PADSOCIAL"] = 23,
["PADDRIGHT"] = 22,
["PADDLEFT"] = 20,
["PADSYSTEM"] = 50,
["PADBACK"] = 67,
["PADLSTICK"] = 24,
["PADRSTICK"] = 40,
["PADDUP"] = 19,
["PAD1"] = 37,
["PADFORWARD"] = 39,
["PADRSHOULDER"] = 33,
["PADLSHOULDER"] = 17,
["PAD2"] = 36,
["PAD3"] = 38,
},
["Icons"] = {
["PADRTRIGGER"] = "PlayStation/R2",
["PADLTRIGGER"] = "PlayStation/L2",
["PADDDOWN"] = "All/Down",
["PAD4"] = "PlayStation/Triangle",
["PAD2"] = "PlayStation/Circle",
["PADDRIGHT"] = "All/Right",
["PADDLEFT"] = "All/Left",
["PADSYSTEM"] = "PlayStation/System",
["PADBACK"] = "PlayStation/Back",
["PADLSTICK"] = "PlayStation/L3",
["PADRSTICK"] = "PlayStation/R3",
["PADDUP"] = "All/Up",
["PAD1"] = "PlayStation/Cross",
["PADFORWARD"] = "PlayStation/Options",
["PADRSHOULDER"] = "PlayStation/R1",
["PADLSHOULDER"] = "PlayStation/L1",
["PAD3"] = "PlayStation/Square",
["PADSOCIAL"] = "PlayStation/Share",
},
["Label"] = "SHP",
},
["Preset"] = {
["Variables"] = {
["GamePadAbbreviatedBindingReverse"] = 0,
["GamePadEmulateAlt"] = "none",
["GamePadEmulateCtrl"] = "PADRSHOULDER",
["GamePadCursorRightClick"] = "PADRSTICK",
["GamePadEmulateShift"] = "PADLSHOULDER",
["GamePadCursorLeftClick"] = "PADLSTICK",
["GamePadEmulateEsc"] = "none",
},
["Bindings"] = {
["PADLSTICK"] = {
[""] = "CAMERAORSELECTORMOVE",
},
["PADRSTICK"] = {
[""] = "TURNORACTION",
},
["PADDUP"] = {
[""] = "MULTIACTIONBAR1BUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PAD1"] = {
[""] = "JUMP",
["SHIFT-"] = "INTERACTTARGET",
["CTRL-"] = "ACTIONBUTTON9",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PAD4"] = {
[""] = "ACTIONBUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
[""] = "ACTIONBUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PAD3"] = {
[""] = "ACTIONBUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PADDDOWN"] = {
[""] = "ACTIONBUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADFORWARD"] = {
[""] = "TOGGLEWORLDMAP",
["SHIFT-"] = "CAMERAZOOMOUT",
["CTRL-"] = "CAMERAZOOMIN",
},
["PADRSHOULDER"] = {
[""] = "ACTIONBUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADSOCIAL"] = {
[""] = "OPENALLBAGS",
["SHIFT-"] = "TOGGLECHARACTER0",
["CTRL-"] = "TOGGLESPELLBOOK",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
[""] = "ACTIONBUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
[""] = "MULTIACTIONBAR1BUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADSYSTEM"] = {
[""] = "TOGGLEGAMEMENU",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
["CTRL-"] = "TOGGLEAUTORUN",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADRTRIGGER"] = {
[""] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
},
},
["Icons"] = {
},
["LabelStyle"] = "Shapes",
},
["Steam Deck"] = {
["Version"] = 1,
["Name"] = "Steam Deck",
["Theme"] = {
["Colors"] = {
["PADDRIGHT"] = "FA4451",
["PADDLEFT"] = "00A2FF",
["PADDUP"] = "FFE74F",
["PADDDOWN"] = "52C14E",
},
["Layout"] = {
["PADPADDLE1"] = 24,
["PADRTRIGGER"] = 32,
["PADLTRIGGER"] = 16,
["PADDDOWN"] = 21,
["PAD4"] = 38,
["PAD2"] = 36,
["PADDRIGHT"] = 22,
["PADDLEFT"] = 20,
["PADBACK"] = 23,
["PADLSTICK"] = 18,
["PADRSTICK"] = 34,
["PADDUP"] = 19,
["PAD1"] = 35,
["PADPADDLE2"] = 25,
["PADFORWARD"] = 39,
["PADRSHOULDER"] = 33,
["PADLSHOULDER"] = 17,
["PAD3"] = 37,
["PADPADDLE3"] = 40,
["PADPADDLE4"] = 41,
},
["Icons"] = {
["PADPADDLE1"] = "PlayStation/L1",
["PADRTRIGGER"] = "Xbox/RT",
["PADLTRIGGER"] = "Xbox/LT",
["PADDDOWN"] = "All/Down",
["PAD4"] = "Xbox/Y",
["PAD2"] = "Xbox/B",
["PADDRIGHT"] = "All/Right",
["PADDLEFT"] = "All/Left",
["PADBACK"] = "Xbox/Share",
["PADLSTICK"] = "Xbox/LSB",
["PADRSTICK"] = "Xbox/RSB",
["PADDUP"] = "All/Up",
["PAD1"] = "Xbox/A",
["PADPADDLE2"] = "PlayStation/L2",
["PADPADDLE4"] = "PlayStation/R2",
["PADRSHOULDER"] = "Xbox/RB",
["PADLSHOULDER"] = "Xbox/LB",
["PAD3"] = "Xbox/X",
["PADPADDLE3"] = "PlayStation/R1",
["PADFORWARD"] = "Xbox/Options",
},
["Label"] = "LTR",
},
["Preset"] = {
["Variables"] = {
["GamePadAbbreviatedBindingReverse"] = 0,
["synchronizeSettings"] = 0,
["GamePadEmulateShift"] = "PADLTRIGGER",
["GamePadEmulateCtrl"] = "PADRTRIGGER",
["synchronizeBindings"] = 0,
["GamePadEmulateAlt"] = "none",
["GamePadCursorRightClick"] = "PADRSTICK",
["synchronizeConfig"] = 0,
["synchronizeMacros"] = 1,
["GamePadCursorLeftClick"] = "PADLSTICK",
["GamePadEmulateEsc"] = "none",
},
["Bindings"] = {
["PADLSTICK"] = {
[""] = "CAMERAORSELECTORMOVE",
},
["PADRSTICK"] = {
[""] = "TURNORACTION",
},
["PADDUP"] = {
[""] = "MULTIACTIONBAR1BUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PAD1"] = {
[""] = "JUMP",
["SHIFT-"] = "INTERACTTARGET",
["CTRL-"] = "ACTIONBUTTON9",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADRSHOULDER"] = {
[""] = "ACTIONBUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADLSHOULDER"] = {
[""] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PADDDOWN"] = {
[""] = "ACTIONBUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADFORWARD"] = {
[""] = "TOGGLEGAMEMENU",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
["CTRL-"] = "CAMERAZOOMOUT",
["CTRL-SHIFT-"] = "CAMERAZOOMIN",
},
["PAD4"] = {
[""] = "ACTIONBUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
[""] = "ACTIONBUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PADDRIGHT"] = {
[""] = "ACTIONBUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PAD3"] = {
[""] = "ACTIONBUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PADDLEFT"] = {
[""] = "MULTIACTIONBAR1BUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADBACK"] = {
["CTRL-"] = "TOGGLEWORLDMAP",
["SHIFT-"] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLEAUTORUN",
},
},
},
["Icons"] = {
},
["LabelStyle"] = "Letters",
},
["PlayStation 5"] = {
["Theme"] = {
["Colors"] = {
["PAD1"] = "6882A1",
["PAD3"] = "D35280",
["PAD4"] = "62BBB2",
["PAD2"] = "D84E58",
},
["Layout"] = {
["PADRTRIGGER"] = 34,
["PADLTRIGGER"] = 18,
["PADDDOWN"] = 21,
["PAD4"] = 35,
["PADSOCIAL"] = 23,
["PADDRIGHT"] = 22,
["PADDLEFT"] = 20,
["PADSYSTEM"] = 49,
["PADBACK"] = 65,
["PADLSTICK"] = 24,
["PADRSTICK"] = 40,
["PADDUP"] = 19,
["PAD5"] = 51,
["PAD1"] = 37,
["PADFORWARD"] = 39,
["PADRSHOULDER"] = 33,
["PADLSHOULDER"] = 17,
["PAD6"] = 67,
["PAD2"] = 36,
["PAD3"] = 38,
},
["Icons"] = {
["PADRTRIGGER"] = "PlayStation/R2",
["PADLTRIGGER"] = "PlayStation/L2",
["PADDDOWN"] = "All/Down",
["PAD4"] = "PlayStation/Triangle",
["PAD2"] = "PlayStation/Circle",
["PADDRIGHT"] = "All/Right",
["PADDLEFT"] = "All/Left",
["PADSYSTEM"] = "PlayStation/System",
["PADBACK"] = "PlayStation/Back",
["PADLSTICK"] = "PlayStation/L3",
["PADRSTICK"] = "PlayStation/R3",
["PADDUP"] = "All/Up",
["PAD5"] = "Xbox/Options",
["PAD1"] = "PlayStation/Cross",
["PADFORWARD"] = "PlayStation/Options",
["PADRSHOULDER"] = "PlayStation/R1",
["PADLSHOULDER"] = "PlayStation/L1",
["PAD6"] = "PlayStation/Back2",
["PAD3"] = "PlayStation/Square",
["PADSOCIAL"] = "PlayStation/Share",
},
["Label"] = "SHP",
},
["Name"] = "PlayStation 5",
["Version"] = 5,
["StyleNameSubStrs"] = {
"PS5",
"DS5",
"DualShock 5",
"PlayStation 5",
},
["Preset"] = {
["Variables"] = {
["GamePadAbbreviatedBindingReverse"] = 0,
["GamePadEmulateAlt"] = "none",
["GamePadEmulateCtrl"] = "PADLTRIGGER",
["GamePadCursorRightClick"] = "PADRSTICK",
["GamePadEmulateShift"] = "PADLSHOULDER",
["GamePadCursorLeftClick"] = "PADLSTICK",
["GamePadEmulateEsc"] = "none",
},
["Bindings"] = {
["PADLSTICK"] = {
[""] = "CAMERAORSELECTORMOVE",
},
["PADRSTICK"] = {
[""] = "TURNORACTION",
},
["PADDUP"] = {
[""] = "MULTIACTIONBAR1BUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PAD1"] = {
[""] = "JUMP",
["SHIFT-"] = "INTERACTTARGET",
["CTRL-"] = "ACTIONBUTTON9",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PAD4"] = {
[""] = "ACTIONBUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
[""] = "ACTIONBUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PAD3"] = {
[""] = "ACTIONBUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PADDDOWN"] = {
[""] = "ACTIONBUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADFORWARD"] = {
[""] = "TOGGLEWORLDMAP",
["SHIFT-"] = "CAMERAZOOMOUT",
["CTRL-"] = "CAMERAZOOMIN",
},
["PADRSHOULDER"] = {
[""] = "ACTIONBUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADSOCIAL"] = {
[""] = "OPENALLBAGS",
["SHIFT-"] = "TOGGLECHARACTER0",
["CTRL-"] = "TOGGLESPELLBOOK",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
[""] = "ACTIONBUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
[""] = "MULTIACTIONBAR1BUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADSYSTEM"] = {
[""] = "TOGGLEGAMEMENU",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
["CTRL-"] = "TOGGLEAUTORUN",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADRTRIGGER"] = {
[""] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
},
},
["Icons"] = {
},
["LabelStyle"] = "Shapes",
},
["Xbox"] = {
["Version"] = 3,
["Name"] = "Xbox",
["Theme"] = {
["Colors"] = {
["PADDRIGHT"] = "FA4451",
["PADDLEFT"] = "00A2FF",
["PADDUP"] = "FFE74F",
["PADDDOWN"] = "52C14E",
},
["Layout"] = {
["PADRTRIGGER"] = 33,
["PADLTRIGGER"] = 17,
["PADDDOWN"] = 22,
["PAD4"] = 35,
["PAD2"] = 36,
["PADDRIGHT"] = 23,
["PADDLEFT"] = 21,
["PADSYSTEM"] = 50,
["PADBACK"] = 24,
["PADLSTICK"] = 19,
["PADRSTICK"] = 39,
["PADDUP"] = 20,
["PAD1"] = 37,
["PADFORWARD"] = 40,
["PADRSHOULDER"] = 34,
["PADLSHOULDER"] = 18,
["PAD3"] = 38,
},
["Icons"] = {
["PADPADDLE1"] = "PlayStation/L1",
["PADRTRIGGER"] = "Xbox/RT",
["PADLTRIGGER"] = "Xbox/LT",
["PADDDOWN"] = "All/Down",
["PAD4"] = "Xbox/Y",
["PAD2"] = "Xbox/B",
["PADDRIGHT"] = "All/Right",
["PADDLEFT"] = "All/Left",
["PADSYSTEM"] = "Xbox/System",
["PADBACK"] = "Xbox/Back",
["PADLSTICK"] = "Xbox/LSB",
["PADRSTICK"] = "Xbox/RSB",
["PADDUP"] = "All/Up",
["PAD1"] = "Xbox/A",
["PADPADDLE2"] = "PlayStation/L2",
["PADPADDLE4"] = "PlayStation/R2",
["PADRSHOULDER"] = "Xbox/RB",
["PADLSHOULDER"] = "Xbox/LB",
["PAD3"] = "Xbox/X",
["PADPADDLE3"] = "PlayStation/R1",
["PADFORWARD"] = "Xbox/Forward",
["PADSOCIAL"] = "Xbox/Share",
},
["Label"] = "LTR",
},
["Preset"] = {
["Variables"] = {
["GamePadAbbreviatedBindingReverse"] = 0,
["GamePadEmulateAlt"] = "none",
["GamePadEmulateCtrl"] = "PADRTRIGGER",
["GamePadCursorRightClick"] = "PADRSTICK",
["GamePadEmulateShift"] = "PADLTRIGGER",
["GamePadCursorLeftClick"] = "PADLSTICK",
["GamePadEmulateEsc"] = "none",
},
["Bindings"] = {
["PADLSTICK"] = {
[""] = "CAMERAORSELECTORMOVE",
},
["PADRSTICK"] = {
[""] = "TURNORACTION",
},
["PADDUP"] = {
[""] = "MULTIACTIONBAR1BUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PAD1"] = {
[""] = "JUMP",
["SHIFT-"] = "INTERACTTARGET",
["CTRL-"] = "ACTIONBUTTON9",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADRSHOULDER"] = {
[""] = "ACTIONBUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADLSHOULDER"] = {
[""] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PADDDOWN"] = {
[""] = "ACTIONBUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADFORWARD"] = {
[""] = "TOGGLEGAMEMENU",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
["CTRL-"] = "CAMERAZOOMOUT",
["CTRL-SHIFT-"] = "CAMERAZOOMIN",
},
["PAD4"] = {
[""] = "ACTIONBUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
[""] = "ACTIONBUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PADDRIGHT"] = {
[""] = "ACTIONBUTTON12",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PAD3"] = {
[""] = "ACTIONBUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PADDLEFT"] = {
[""] = "MULTIACTIONBAR1BUTTON11",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADBACK"] = {
["CTRL-"] = "TOGGLEWORLDMAP",
["SHIFT-"] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLEAUTORUN",
},
},
},
["Icons"] = {
},
["LabelStyle"] = "Letters",
},
}
ConsolePortShared = {
["Sverdrup (Brewmaster) Argent Dawn"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Sverdrup",
["Class"] = "MONK",
["Icon"] = 608951,
["Spec"] = 268,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADRTRIGGER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "ACTIONBUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["SHIFT-"] = "ACTIONBUTTON6",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
[""] = "MULTIACTIONBAR1BUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "ACTIONBUTTON9",
["SHIFT-"] = "INTERACTTARGET",
[""] = "JUMP",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
[""] = "MULTIACTIONBAR1BUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
[""] = "ACTIONBUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD3"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
},
},
["Rosefin () Argent Dawn"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Rosefin",
["Class"] = "MONK",
["Icon"] = 608953,
["Spec"] = 1450,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADRTRIGGER"] = {
["CTRL-"] = "TARGETSCANENEMY",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON12",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "TARGETNEARESTENEMY",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON11",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON9",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
[""] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
},
["PAD2"] = {
["CTRL-"] = "ACTIONBUTTON6",
["SHIFT-"] = "ACTIONBUTTON9",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
[""] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON7",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
[""] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON5",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "INTERACTTARGET",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "JUMP",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
[""] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON6",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD3"] = {
["CTRL-"] = "ACTIONBUTTON4",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
},
},
["Darick () Eredar"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Darick",
["Class"] = "DRUID",
["Icon"] = 136096,
["Spec"] = 1447,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRTRIGGER"] = {
["CTRL-"] = "TARGETSCANENEMY",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON12",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "TARGETNEARESTENEMY",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON11",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
[""] = "MULTIACTIONBAR3BUTTON10",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON7",
},
["PAD3"] = {
["CTRL-"] = "ACTIONBUTTON4",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "INTERACTTARGET",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "JUMP",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
[""] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON6",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
[""] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON5",
},
["PAD2"] = {
["CTRL-"] = "ACTIONBUTTON6",
["SHIFT-"] = "ACTIONBUTTON9",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON9",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
[""] = "MULTIACTIONBAR2BUTTON8",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
},
},
["Dukasuka (Enhancement) Eredar"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Dukasuka",
["Class"] = "SHAMAN",
["Icon"] = 237581,
["Spec"] = 263,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRTRIGGER"] = {
["CTRL-"] = "TARGETSCANENEMY",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON12",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON10",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON11",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "ACTIONBUTTON5",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
[""] = "MULTIACTIONBAR1BUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON6",
},
["PAD3"] = {
["CTRL-"] = "ACTIONBUTTON4",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "INTERACTTARGET",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "JUMP",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
[""] = "MULTIACTIONBAR1BUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON5",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "TARGETFOCUS",
[""] = "TARGETNEARESTENEMY",
["CTRL-SHIFT-"] = "",
},
["PADLSHOULDER"] = {
["CTRL-"] = "FOCUSTARGET",
["SHIFT-"] = "",
[""] = "TARGETPREVIOUSENEMY",
["CTRL-SHIFT-"] = "",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
[""] = "MULTIACTIONBAR1BUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
},
["PAD2"] = {
["CTRL-"] = "ACTIONBUTTON6",
["SHIFT-"] = "ACTIONBUTTON9",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
[""] = "MULTIACTIONBAR2BUTTON7",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
},
},
["Riptides (Enhancement) Argent Dawn"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Riptides",
["Class"] = "SHAMAN",
["Icon"] = 237581,
["Spec"] = 263,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADRTRIGGER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "ACTIONBUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PAD3"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
[""] = "BONUSACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PAD2"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
[""] = "MULTIACTIONBAR4BUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
[""] = "MULTIACTIONBAR1BUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "ACTIONBUTTON9",
["SHIFT-"] = "INTERACTTARGET",
[""] = "JUMP",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
[""] = "MULTIACTIONBAR1BUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
[""] = "ACTIONBUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
},
},
["Estuary (Subtlety) Argent Dawn"] = {
["Meta"] = {
["Class"] = "ROGUE",
["Spec"] = 261,
["Icon"] = 132320,
["Name"] = "Estuary",
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRTRIGGER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "ACTIONBUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PAD3"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["SHIFT-"] = "ACTIONBUTTON6",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
[""] = "MULTIACTIONBAR1BUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "ACTIONBUTTON9",
["SHIFT-"] = "INTERACTTARGET",
[""] = "JUMP",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
[""] = "MULTIACTIONBAR1BUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON4",
["SHIFT-"] = "TARGETSCANENEMY",
[""] = "ACTIONBUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD2"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
},
["Bar"] = {
["scale"] = 0.9,
["layout"] = {
["PADDUP"] = {
["size"] = 64,
["point"] = {
"LEFT",
240,
100,
},
["dir"] = "up",
},
["PAD1"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-240,
16,
},
["dir"] = "down",
},
["PADRTRIGGER"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-396,
16,
},
["dir"] = "down",
},
["PADLTRIGGER"] = {
["size"] = 64,
["point"] = {
"LEFT",
456,
56,
},
["dir"] = "right",
},
["PADDDOWN"] = {
["size"] = 64,
["point"] = {
"LEFT",
240,
16,
},
["dir"] = "down",
},
["PADRSHOULDER"] = {
["size"] = 64,
["point"] = {
"LEFT",
396,
16,
},
["dir"] = "down",
},
["PAD4"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-240,
100,
},
["dir"] = "up",
},
["PAD2"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-176,
56,
},
["dir"] = "right",
},
["PADDRIGHT"] = {
["size"] = 64,
["point"] = {
"LEFT",
306,
56,
},
["dir"] = "right",
},
["PAD3"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-306,
56,
},
["dir"] = "left",
},
["PADDLEFT"] = {
["size"] = 64,
["point"] = {
"LEFT",
176,
56,
},
["dir"] = "left",
},
["PADLSHOULDER"] = {
["size"] = 64,
["point"] = {
"RIGHT",
-456,
56,
},
["dir"] = "left",
},
},
["watchbars"] = true,
["width"] = 1100,
["showline"] = true,
["lock"] = true,
["eye"] = true,
["showbuttons"] = false,
["flashart"] = true,
},
},
["Dannius () Argent Dawn"] = {
["Meta"] = {
["Type"] = "PlayStation 4",
["Name"] = "Dannius",
["Class"] = "WARLOCK",
["Icon"] = 136145,
["Spec"] = 1454,
},
["Bindings"] = {
["PADLSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE1"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRTRIGGER"] = {
["CTRL-"] = "TARGETSCANENEMY",
["SHIFT-"] = "ACTIONBUTTON10",
[""] = "ACTIONBUTTON5",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON10",
},
["PAD3"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON1",
["SHIFT-"] = "ACTIONBUTTON8",
[""] = "ACTIONBUTTON1",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON6",
},
["PAD6"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLTRIGGER"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON5",
["SHIFT-"] = "ACTIONBUTTON9",
[""] = "ACTIONBUTTON4",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON9",
},
["PADDDOWN"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON8",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON4",
[""] = "ACTIONBUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON12",
},
["PADLSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD4"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON2",
["SHIFT-"] = "ACTIONBUTTON7",
[""] = "ACTIONBUTTON2",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON7",
},
["PADSOCIAL"] = {
["CTRL-"] = "TOGGLESPELLBOOK",
["SHIFT-"] = "TOGGLECHARACTER0",
[""] = "OPENALLBAGS",
["CTRL-SHIFT-"] = "TOGGLETALENTS",
},
["PADDRIGHT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON7",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON3",
[""] = "ACTIONBUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON11",
},
["PADDLEFT"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON5",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON1",
[""] = "MULTIACTIONBAR1BUTTON11",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON9",
},
["PADSYSTEM"] = {
["CTRL-"] = "TOGGLEAUTORUN",
["SHIFT-"] = "CLICK ConsolePortRaidCursorToggle:LeftButton",
[""] = "TOGGLEGAMEMENU",
["CTRL-SHIFT-"] = "OPENCHAT",
},
["PADBACK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "CAMERAORSELECTORMOVE",
["CTRL-SHIFT-"] = "",
},
["PADRSTICK"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "TURNORACTION",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE3"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD5"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD1"] = {
["CTRL-"] = "INTERACTTARGET",
["SHIFT-"] = "MULTIACTIONBAR1BUTTON4",
[""] = "JUMP",
["CTRL-SHIFT-"] = "CLICK ConsolePortUtilityToggle:LeftButton",
},
["PADRSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKDOWN"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE2"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADDUP"] = {
["CTRL-"] = "MULTIACTIONBAR2BUTTON6",
["SHIFT-"] = "MULTIACTIONBAR2BUTTON2",
[""] = "MULTIACTIONBAR1BUTTON12",
["CTRL-SHIFT-"] = "MULTIACTIONBAR2BUTTON10",
},
["PADFORWARD"] = {
["CTRL-"] = "CAMERAZOOMIN",
["SHIFT-"] = "CAMERAZOOMOUT",
[""] = "TOGGLEWORLDMAP",
["CTRL-SHIFT-"] = "",
},
["PADRSHOULDER"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKRIGHT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADRSTICKUP"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADPADDLE4"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PADLSTICKLEFT"] = {
["CTRL-"] = "",
["SHIFT-"] = "",
[""] = "",
["CTRL-SHIFT-"] = "",
},
["PAD2"] = {
["CTRL-"] = "MULTIACTIONBAR1BUTTON3",
["SHIFT-"] = "ACTIONBUTTON6",
[""] = "ACTIONBUTTON3",
["CTRL-SHIFT-"] = "MULTIACTIONBAR1BUTTON8",
},
},
},
}
ConsolePortBindingIcons = {
}
