
ConsolePort_BarPresets = {
["experiments"] = {
["name"] = "experiments",
["settings"] = {
["LABcolorsMana"] = "ff8080ff",
["showMainIcons"] = true,
["clusterShowAll"] = false,
["LABhideElementsMacro"] = false,
["LABclickOnDown"] = true,
["clusterShowFlyoutIcons"] = true,
["swipeColor"] = "ffff97c5",
["clusterFullStateModifier"] = false,
},
["children"] = {
["Bar 3"] = {
["offset"] = 1,
["type"] = "Page",
["paddingX"] = 4,
["paddingY"] = 4,
["opacity"] = "100",
["hotkeys"] = true,
["rescale"] = "100",
["stride"] = 3,
["override"] = "shown",
["page"] = "5",
["reverse"] = false,
["orientation"] = "HORIZONTAL",
["slots"] = 12,
["visibility"] = "[vehicleui][overridebar] hide; show",
["pos"] = {
["y"] = 120,
["strata"] = "MEDIUM",
["offsetscale"] = false,
["point"] = "BOTTOM",
["level"] = 2,
["x"] = 270,
["relPoint"] = "BOTTOM",
},
},
["Bar 2"] = {
["offset"] = 1,
["type"] = "Page",
["paddingX"] = 4,
["paddingY"] = 4,
["opacity"] = "100",
["hotkeys"] = true,
["rescale"] = "100",
["stride"] = 3,
["override"] = "shown",
["page"] = "6",
["reverse"] = false,
["orientation"] = "HORIZONTAL",
["slots"] = 12,
["visibility"] = "[vehicleui][overridebar] hide; show",
["pos"] = {
["y"] = 120,
["strata"] = "MEDIUM",
["offsetscale"] = false,
["point"] = "BOTTOM",
["level"] = 2,
["x"] = -270,
["relPoint"] = "BOTTOM",
},
},
["Bar 1"] = {
["offset"] = 1,
["type"] = "Page",
["paddingX"] = 4,
["paddingY"] = 4,
["opacity"] = "100",
["hotkeys"] = true,
["rescale"] = "100",
["stride"] = 12,
["override"] = "shown",
["page"] = "dynamic",
["reverse"] = false,
["orientation"] = "HORIZONTAL",
["slots"] = 12,
["visibility"] = "show",
["pos"] = {
["y"] = 68,
["strata"] = "MEDIUM",
["offsetscale"] = false,
["point"] = "BOTTOM",
["level"] = 2,
["x"] = 0,
["relPoint"] = "BOTTOM",
},
},
["Petring"] = {
["type"] = "Petring",
["fade"] = true,
["status"] = true,
["vehicle"] = true,
["scale"] = 0.7,
["pos"] = {
["y"] = 100,
["strata"] = "MEDIUM",
["offsetscale"] = false,
["point"] = "BOTTOM",
["level"] = 2,
["x"] = 504,
["relPoint"] = "BOTTOM",
},
},
["Toolbar"] = {
["type"] = "Toolbar",
["menu"] = {
["eye"] = true,
["micromenu"] = true,
},
["castbar"] = {
["enabled"] = true,
},
["width"] = 725,
["totem"] = {
["enabled"] = true,
["hidden"] = false,
["pos"] = {
["y"] = 190,
["relPoint"] = "BOTTOM",
["point"] = "BOTTOM",
["x"] = 0,
},
},
["pos"] = {
["y"] = 0,
["relPoint"] = "BOTTOM",
["point"] = "BOTTOM",
["x"] = 0,
},
},
},
["visibility"] = "[petbattle] hide; show",
["desc"] = "",
},
}
