
CooldownManagerCenteredDB = {
["profileKeys"] = {
["Seep - Kel'Thuzad"] = "Default",
["Loess - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Cirque - Kel'Thuzad"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Docks - Kel'Thuzad"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Bwaagh - Feathermoon"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Quag - Argent Dawn"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Slush - Mal'Ganis"] = "Default",
["Levee - Argent Dawn"] = "Default",
["Mire - Mal'Ganis"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Brack - Mal'Ganis"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Bog - Kel'Thuzad"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Rivulet - Mal'Ganis"] = "Default",
["Talamahyn - Kel'Thuzad"] = "Default",
["Surge - Argent Dawn"] = "Default",
["Geyser - Mal'Ganis"] = "Default",
["Rime - Kel'Thuzad"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Falls - Mal'Ganis"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Bayou - Kel'Thuzad"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Fathom - Argent Dawn"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Spume - Argent Dawn"] = "Default",
["Moraine - Kel'Thuzad"] = "Default",
["Fjord - Mal'Ganis"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Baffle - Mal'Ganis"] = "Default",
["Rapids - Argent Dawn"] = "Default",
["Bwaagh - Mal'Ganis"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Brook - Argent Dawn"] = "Default",
["Lather - Mal'Ganis"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Rill - Kel'Thuzad"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Brine - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Floe - Mal'Ganis"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["cooldownManager_stackAnchorBuffIcons_enabled"] = true,
["cooldownManager_stackAnchorUtility_enabled"] = true,
["cooldownManager_stackAnchorEssential_enabled"] = true,
["cooldownManager_cooldownFontName"] = "Fira Sans Condensed Black",
["cooldownManager_stackAnchorUtility_point"] = "TOP",
["cooldownManager_visibility_perViewer"] = {
["BuffIconCooldownViewer"] = {
},
["CMCTracker2"] = {
},
["CMCTracker1"] = {
},
["UtilityCooldownViewer"] = {
},
["EssentialCooldownViewer"] = {
},
["BuffBarCooldownViewer"] = {
},
},
["buffContainers"] = {
["assignments"] = {
},
},
["cooldownManager_stackAnchorEssential_point"] = "TOP",
["_bug_warning_displayed"] = 20260310,
["cooldownManager_stackFontName"] = "Fira Sans Condensed Black",
["cooldownManager_stackAnchorBuffIcons_point"] = "TOP",
},
},
}
