
CoolLineDB = {
	["bgcolor"] = {
		["a"] = 0,
		["b"] = 0,
		["g"] = 0,
		["r"] = 0,
	},
	["border"] = "None",
	["borderinset"] = 4,
	["h"] = 16,
	["fontsize"] = 10,
	["block"] = {
		["Hearthstone"] = true,
		["Power Strikes"] = true,
	},
	["iconplus"] = 2,
	["spellcolor"] = {
		["a"] = 1,
		["r"] = 0.8,
		["g"] = 0.4,
		["b"] = 0,
	},
	["nospellcolor"] = {
		["a"] = 1,
		["r"] = 0,
		["g"] = 0,
		["b"] = 0,
	},
	["inactivealpha"] = 0.5,
	["bordercolor"] = {
		["a"] = 1,
		["r"] = 1,
		["g"] = 1,
		["b"] = 1,
	},
	["w"] = 814.000061035156,
	["activealpha"] = 1,
	["y"] = -530,
	["x"] = 2,
	["dbinit"] = 3,
	["statusbar"] = "ElvUI Norm",
	["font"] = "PT Sans Narrow",
	["bordersize"] = 16,
	["fontcolor"] = {
		["a"] = 0.8,
		["r"] = 1,
		["g"] = 1,
		["b"] = 1,
	},
	["vertical"] = false,
}
