
DBM_AllSavedOptions = {
["Default"] = {
["DontShowFarWarnings"] = true,
["SpamSpecRolestack"] = false,
["DontRestoreIcons"] = false,
["EnableTooltip"] = false,
["DontShowNameplateIcons"] = false,
["SpecialWarningFlash5"] = true,
["NPIconTextMaxLen"] = 7,
["SpecialWarningFlash1"] = true,
["DontPlayTrivialSpecialWarningSound"] = true,
["SWarnNameInNote"] = true,
["SpecialWarningSound2"] = 543587,
["InfoFramePoint"] = "CENTER",
["EventSoundMusicCombined"] = false,
["LogDelves"] = false,
["WorldBossAlert"] = false,
["SpamSpecInformationalOnly"] = false,
["WorldBuffAlert"] = false,
["SpamSpecRoledispel"] = false,
["DisableMusic"] = false,
["ShowGuildMessages"] = true,
["ShowAllVersions"] = true,
["SpecialWarningSound3"] = "Interface\\AddOns\\DBM-Core\\sounds\\AirHorn.ogg",
["SpamSpecRolesoak"] = false,
["ShowWarningsInChat"] = true,
["InfoFrameFontStyle"] = "None",
["WarningFontStyle"] = "None",
["ChatFrame"] = "DEFAULT_CHAT_FRAME",
["CastNPIconGlowBehavior"] = 1,
["RangeFrameRadarX"] = 100,
["LogCurrentRaids"] = true,
["InfoFrameCols"] = 0,
["NPIconTimerEnabled"] = true,
["LatencyThreshold"] = 250,
["ShowGuildMessagesPlus"] = false,
["LFDEnhance"] = false,
["LogCurrentMythicRaids"] = true,
["DontPlayPrivateAuraSound"] = true,
["HideBossEmoteFrame2"] = true,
["DisableChatBubbles"] = false,
["HideObjectivesFrame"] = true,
["SpecialWarningShortText"] = true,
["DontShowPTText"] = false,
["FilterBInterruptHealer"] = false,
["SpecialWarningFontSize2"] = 35,
["SpecialWarningFlashCol5"] = {
0.2,
1,
1,
},
["NewsMessageShown2"] = 2,
["NPIconTextFont"] = "standardFont",
["EventSoundPullTimer"] = "None",
["NPIconTimerFontStyle"] = "None",
["SpecialWarningVibrate2"] = false,
["SpecialWarningFlashCount2"] = 1,
["NPAuraText"] = true,
["EventSoundDungeonBGM"] = "None",
["AutoAcceptGuildInvite"] = false,
["SpecialWarningFlashDura3"] = 1,
["WarningShortText"] = true,
["SpecialWarningFlash4"] = true,
["DisableSFX"] = false,
["SpecialWarningFlashDura4"] = 0.7,
["SpecialWarningFlashCol3"] = {
1,
0,
0,
},
["ModelSoundValue"] = "Short",
["SpecialWarningY"] = 75,
["ReplaceMyConfigOnOverride"] = false,
["LogTrivialDungeons"] = false,
["RaidWarningSound"] = "",
["CustomSounds"] = 0,
["RoleSpecAlert"] = true,
["LogCurrentMPlus"] = true,
["DontPlayPTCountdown"] = false,
["HideMovieInstanceAnywhere"] = false,
["WarningIconLeft"] = true,
["RangeFrameLocked"] = false,
["HealthWarningLow"] = false,
["SpamSpecRolegtfo"] = false,
["SpecialWarningFlashDura2"] = 0.4,
["LogTrivialRaids"] = false,
["FilterVoidFormSay2"] = false,
["VPReplacesSADefault"] = false,
["GroupOptionsExcludeIcon"] = false,
["FilterBTargetFocus"] = true,
["RecordOnlyBosses"] = false,
["ShowBerserkWarnings"] = true,
["DontPlayCountdowns"] = true,
["OverrideBossIcon"] = false,
["SpecialWarningFlashAlph1"] = 0.3,
["ShowDefeatMessage"] = true,
["FilterCrowdControl"] = true,
["InfoFrameShowSelf"] = false,
["WarningFontShadow"] = true,
["DontShowBossTimers"] = false,
["SpecialWarningFontStyle"] = "THICKOUTLINE",
["InfoFrameLines"] = 0,
["WarningIconChat"] = true,
["HideGuildChallengeUpdates"] = true,
["ShowPizzaMessage"] = true,
["RangeFrameSound2"] = "none",
["HideTooltips"] = false,
["LogCurrentMythicZero"] = false,
["GUIWidth"] = 902.9102783203125,
["NPIconTextFontSize"] = 10,
["EventSoundMusic"] = "None",
["LogTWRaids"] = false,
["NoTimerOverridee"] = true,
["HelpMessageVersion"] = 3,
["SpecialWarningFlashAlph2"] = 0.3,
["DontShowHudMap2"] = false,
["SpecialWarningFlashCount4"] = 2,
["ShowSWarningsInChat"] = true,
["HideMovieDuringFight"] = false,
["RangeFrameRadarY"] = -100,
["OverrideBossAnnounce"] = false,
["CoreSavedRevision"] = 20250808133035,
["RangeFrameX"] = 50,
["NPIconGrowthDirection"] = "CENTER",
["RangeFrameY"] = -50,
["SpecialWarningFlashAlph3"] = 0.4,
["FilterTInterruptHealer"] = false,
["FakeBWVersion"] = false,
["ZoneCombatSyncing"] = false,
["WarningAlphabetical"] = true,
["SpamSpecRoletaunt"] = false,
["FilterBInterruptCooldown"] = true,
["CheckGear"] = true,
["NPIconTextEnabled"] = true,
["SpecialWarningX"] = 0,
["DontShowPT2"] = false,
["MoviesSeen"] = {
},
["ShowQueuePop"] = true,
["SpecialWarningFlashCol4"] = {
1,
0,
1,
},
["DebugMode"] = false,
["DisableGuildStatus"] = false,
["ShowReminders"] = true,
["SpecialWarningFontCol"] = {
1,
0.7,
0,
},
["NPIconTimerFont"] = "standardFont",
["AFKHealthWarning2"] = false,
["SpecialWarningVibrate1"] = false,
["EventSoundEngage2"] = "None",
["InfoFrameY"] = -75,
["SpecialWarningSound"] = 569200,
["WarningIconRight"] = true,
["UseSoundChannel"] = "Master",
["ShowRespawn"] = true,
["HideMovieNonInstanceAnywhere"] = false,
["DontAutoGossip"] = false,
["LeavingCombatAlert"] = false,
["AlwaysKeepNPs"] = true,
["AlwaysShowSpeedKillTimer2"] = false,
["NoAnnounceOverride"] = true,
["DebugLevel"] = 1,
["BadTimerAlert"] = false,
["HideMovieOnlyAfterSeen"] = false,
["HideGarrisonToasts"] = true,
["RangeFramePoint"] = "CENTER",
["SpecialWarningFontShadow"] = false,
["NPIconTimerFontSize"] = 18,
["SpecialWarningFlashCol1"] = {
1,
1,
0,
},
["DontShowNameplateIconsCD"] = false,
["SWarnClassColor"] = true,
["UseNameplateHandoff"] = true,
["DontShowNameplateIconsCast"] = false,
["SpecialWarningFlashAlph4"] = 0.4,
["PTCountThreshold2"] = 5,
["VPReplacesAnnounce"] = false,
["LogChallenges"] = false,
["oRA3AnnounceConsumables"] = false,
["CountdownVoice2"] = "Kolt",
["NPIconAnchorPoint"] = "TOP",
["ArrowPosX"] = 0,
["LogTWDungeons"] = false,
["SpecialWarningSound4"] = 552035,
["DontShowTrashTimers"] = false,
["AutologBosses"] = false,
["LogCurrentHeroic"] = false,
["SpecialWarningFlashDura5"] = 1,
["GUIX"] = 241.8778381347656,
["WarningColors"] = {
{
["b"] = 0.94,
["g"] = 0.8,
["r"] = 0.41,
},
{
["b"] = 0,
["g"] = 0.95,
["r"] = 0.95,
},
{
["b"] = 0,
["g"] = 0.5,
["r"] = 1,
},
{
["b"] = 0.1,
["g"] = 0.1,
["r"] = 1,
},
},
["SpamSpecRoleswitch"] = false,
["SWarningAlphabetical"] = true,
["OverrideBossTimer"] = false,
["BlockNoteShare"] = false,
["OverrideBossSay"] = false,
["FilterTInterruptCooldown"] = true,
["DontPlaySpecialWarningSound"] = true,
["NPIconOffsetX"] = 0,
["FilterDispel"] = true,
["NPIconSize"] = 30,
["NPIconGlowBehavior"] = 1,
["GroupOptionsExcludePA"] = false,
["DontShowInfoFrame"] = false,
["AutoReplySound"] = true,
["DisableAmbiance"] = false,
["GUIHeight"] = 625.7296752929688,
["ShowWAKeys"] = true,
["RangeFrameUpdates"] = "Average",
["RangeFrameRadarPoint"] = "CENTER",
["DontRestoreRange"] = false,
["InfoFrameFontSize"] = 12,
["SpecialWarningFlashCount3"] = 3,
["DontShowUserTimers"] = false,
["WhisperStats"] = false,
["SilentMode"] = false,
["WarningDuration2"] = 1.5,
["AdvancedAutologBosses"] = false,
["SpecialWarningFlashAlph5"] = 0.5,
["SpecialWarningDuration2"] = 9.783366203308105,
["ShortTimerText"] = true,
["WarningFontSize"] = 20,
["ShowEngageMessage"] = true,
["RangeFrameSound1"] = "none",
["RLReadyCheckSound"] = true,
["FilterTTargetFocus"] = true,
["EventSoundVictory2"] = "None",
["AutoExpandSpellGroups"] = false,
["LastRevision"] = 0,
["GUIPoint"] = "TOP",
["SettingsMessageShown"] = true,
["SpamSpecRoledefensive"] = false,
["EnableTooltipInCombat"] = true,
["EventSoundWipe"] = "None",
["InfoFrameX"] = 75,
["DontSetIcons"] = false,
["WarningY"] = 260,
["FilterInterruptNoteName"] = false,
["CountdownVoice"] = "Corsica",
["EnableModels"] = true,
["SpecialWarningVibrate3"] = true,
["CountdownVoice3"] = "Smooth",
["WorldBossNearAlert"] = false,
["SpecialWarningFlashCol2"] = {
1,
0.5,
0,
},
["DisableStatusWhisper"] = false,
["EventDungMusicMythicFilter"] = false,
["GUIY"] = -35.3051643371582,
["RangeFrameFrames"] = "radar",
["WarningFont"] = "standardFont",
["DontShowTargetAnnouncements"] = true,
["SpecialWarningIcon"] = true,
["InfoFrameFont"] = "standardFont",
["EnteringCombatAlert"] = false,
["WarningPoint"] = "CENTER",
["SpecialWarningFlashCount5"] = 3,
["SpecialWarningVibrate5"] = true,
["EventMusicNoBuiltIn"] = false,
["ArrowPosY"] = -150,
["ArrowPoint"] = "TOP",
["DontShowBossAnnounces"] = true,
["DontShowSpecialWarningText"] = true,
["SpecialWarningPoint"] = "CENTER",
["AutoRespond"] = false,
["DontShowSpecialWarningFlash"] = false,
["DontDoSpecialWarningVibrate"] = false,
["NPIconSpacing"] = 0,
["DontSendBossGUIDs"] = false,
["ChosenVoicePack2"] = "VEM",
["CDNPIconGlowType"] = 1,
["DebugSound"] = true,
["AutoAcceptFriendInvite"] = false,
["NPIconOffsetY"] = 20,
["SpecialWarningFlashCount1"] = 1,
["PullVoice"] = "Corsica",
["SpecialWarningSound5"] = 554236,
["DontSendYells"] = false,
["SpamSpecRoleinterrupt"] = false,
["SpecialWarningFlash2"] = true,
["NPIconTextFontStyle"] = "None",
["SpecialWarningFlash3"] = true,
["SpecialWarningFlashDura1"] = 0.3,
["Enabled"] = true,
["EventMusicMythicFilter"] = false,
["DontShowEventTimers"] = false,
["SpecialWarningVibrate4"] = true,
["DontShowRangeFrame"] = false,
["DisableRaidIcons"] = false,
["EnableWBSharing"] = false,
["FilterTrashWarnings2"] = true,
["StripServerName"] = true,
["NoCombatScanningFeatures"] = false,
["SpecialWarningFont"] = "standardFont",
["CastNPIconGlowType2"] = 4,
["DoNotLogLFG"] = true,
["WarningX"] = 0,
["EnableTooltipHeader"] = true,
["DontShowPTNoID"] = false,
},
}
DBM_MinimapIcon = {
["showInCompartment"] = true,
}
DBM_AnnoyingPopupDisables = nil
DBM_ModsToLoadWithFullTestSupport = {
["addonsWithTests"] = {
},
["bossModsWithTests"] = {
},
}
