
Details_StreamerDB = {
["characters"] = {
["Calestin - Sargeras"] = "Ailisuul - Arthas",
["Strid - Kel'Thuzad"] = "Ailisuul - Arthas",
["Sverdrup - Argent Dawn"] = "Sverdrup - Argent Dawn",
["Remaxxing - Kel'Thuzad"] = "Ailisuul - Arthas",
["Virga - Kel'Thuzad"] = "Ailisuul - Arthas",
["Docks - Kel'Thuzad"] = "Ailisuul - Arthas",
["Mangrove - Argent Dawn"] = "Ailisuul - Arthas",
["Bwaagh - Feathermoon"] = "Ailisuul - Arthas",
["Flumina - Argent Dawn"] = "Ailisuul - Arthas",
["Neva - Kel'Thuzad"] = "Ailisuul - Arthas",
["Quag - Argent Dawn"] = "Ailisuul - Arthas",
["Slush - Mal'Ganis"] = "Ailisuul - Arthas",
["Aquifer - Kel'Thuzad"] = "Ailisuul - Arthas",
["Moraine - Kel'Thuzad"] = "Ailisuul - Arthas",
["Gelae - Kel'Thuzad"] = "Ailisuul - Arthas",
["Riptides - Argent Dawn"] = "Ailisuul - Arthas",
["Testrivers - Arthas"] = "Ailisuul - Arthas",
["Talamahyn - Kel'Thuzad"] = "Ailisuul - Arthas",
["Darick - Eredar"] = "Ailisuul - Arthas",
["Falls - Mal'Ganis"] = "Ailisuul - Arthas",
["Fathom - Argent Dawn"] = "Ailisuul - Arthas",
["Spume - Argent Dawn"] = "Ailisuul - Arthas",
["Cataracts - Argent Dawn"] = "Ailisuul - Arthas",
["Mahntaiaga - Arthas"] = "Ailisuul - Arthas",
["Baffle - Mal'Ganis"] = "Ailisuul - Arthas",
["Geosmin - Kel'Thuzad"] = "Ailisuul - Arthas",
["Asperos - Kel'Thuzad"] = "Ailisuul - Arthas",
["Lather - Mal'Ganis"] = "Ailisuul - Arthas",
["Mothugeon - Argent Dawn"] = "Ailisuul - Arthas",
["Emptyrivers - Argent Dawn"] = "Ailisuul - Arthas",
["Karst - Argent Dawn"] = "Ailisuul - Arthas",
["Roberia - Eredar"] = "Ailisuul - Arthas",
["Estuary - Argent Dawn"] = "Ailisuul - Arthas",
["Garumn - Arthas"] = "Ailisuul - Arthas",
["Loess - Kel'Thuzad"] = "Ailisuul - Arthas",
["Dukasuka - Eredar"] = "Ailisuul - Arthas",
["Stream - Argent Dawn"] = "Ailisuul - Arthas",
["Cirque - Kel'Thuzad"] = "Ailisuul - Arthas",
["Naturerivers - Korgath"] = "Ailisuul - Arthas",
["Cascades - Kel'Thuzad"] = "Ailisuul - Arthas",
["Doneer - Eredar"] = "Ailisuul - Arthas",
["Glaciers - Kel'Thuzad"] = "Ailisuul - Arthas",
["Temprivers - Kel'Thuzad"] = "Ailisuul - Arthas",
["Inundito - Kel'Thuzad"] = "Ailisuul - Arthas",
["Ochrian - Argent Dawn"] = "Ailisuul - Arthas",
["Flumes - Kel'Thuzad"] = "Ailisuul - Arthas",
["Alluvium - Argent Dawn"] = "Ailisuul - Arthas",
["Headcut - Argent Dawn"] = "Ailisuul - Arthas",
["Gyre - Kel'Thuzad"] = "Ailisuul - Arthas",
["Asperse - Kel'Thuzad"] = "Ailisuul - Arthas",
["Benthos - Argent Dawn"] = "Ailisuul - Arthas",
["Emptyrivers - Arthas"] = "Ailisuul - Arthas",
["Mire - Mal'Ganis"] = "Ailisuul - Arthas",
["Alandere - Argent Dawn"] = "Ailisuul - Arthas",
["Rime - Kel'Thuzad"] = "Ailisuul - Arthas",
["Surge - Argent Dawn"] = "Ailisuul - Arthas",
["Rosefin - Argent Dawn"] = "Ailisuul - Arthas",
["Ailisuul - Arthas"] = "Ailisuul - Arthas",
["Seep - Kel'Thuzad"] = "Ailisuul - Arthas",
["Fjord - Mal'Ganis"] = "Ailisuul - Arthas",
["Geyser - Mal'Ganis"] = "Ailisuul - Arthas",
["Bayou - Kel'Thuzad"] = "Ailisuul - Arthas",
["Wildeadoriah - The Scryers"] = "Ailisuul - Arthas",
["Brook - Argent Dawn"] = "Ailisuul - Arthas",
["Lotic - Argent Dawn"] = "Ailisuul - Arthas",
["Evilrivers - Kel'Thuzad"] = "Ailisuul - Arthas",
["Dannius - Argent Dawn"] = "Ailisuul - Arthas",
["Shoal - Kel'Thuzad"] = "Ailisuul - Arthas",
["Saellindris - Kel'Thuzad"] = "Ailisuul - Arthas",
["Weir - Kel'Thuzad"] = "Ailisuul - Arthas",
["Dussrasande - Kel'Thuzad"] = "Ailisuul - Arthas",
["Confluence - Argent Dawn"] = "Ailisuul - Arthas",
["Emptyrivers - Sargeras"] = "Ailisuul - Arthas",
["Bwaagh - Mal'Ganis"] = "Ailisuul - Arthas",
["Meander - Kel'Thuzad"] = "Ailisuul - Arthas",
["Emptystreams - Argent Dawn"] = "Ailisuul - Arthas",
["Beefyrivers - Arthas"] = "Ailisuul - Arthas",
["Esker - Kel'Thuzad"] = "Ailisuul - Arthas",
["Bog - Kel'Thuzad"] = "Ailisuul - Arthas",
["Rill - Kel'Thuzad"] = "Ailisuul - Arthas",
["Rapids - Argent Dawn"] = "Ailisuul - Arthas",
["Riparium - Argent Dawn"] = "Ailisuul - Arthas",
["Brine - Argent Dawn"] = "Ailisuul - Arthas",
["Rivulet - Mal'Ganis"] = "Ailisuul - Arthas",
["Brack - Mal'Ganis"] = "Ailisuul - Arthas",
["Floe - Mal'Ganis"] = "Ailisuul - Arthas",
["Zimuures - Argent Dawn"] = "Ailisuul - Arthas",
["Levee - Argent Dawn"] = "Ailisuul - Arthas",
},
["profiles"] = {
["Ailisuul - Arthas"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["main_frame_size"] = {
300,
500.000030517578,
},
["arrow_anchor_y"] = 0,
["minimap"] = {
["minimapPos"] = 303.234030123659,
["radius"] = 160,
["hide"] = false,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["author"] = "Details! Team",
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["font_size"] = 10,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["use_spark"] = true,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 3.0517578125e-05,
["x"] = 3.0517578125e-05,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["y"] = 4.57763671875e-05,
["x"] = 0,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["point"] = "CENTER",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["scale"] = 1,
},
["Sverdrup - Argent Dawn"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["arrow_anchor_y"] = 0,
["main_frame_size"] = {
300,
500.0000305175781,
},
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = false,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 3.0517578125e-05,
["x"] = -3.0517578125e-05,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["author"] = "Terciob",
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["font_size"] = 10,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["y"] = 0,
["use_spark"] = true,
["x"] = -3.0517578125e-05,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["point"] = "CENTER",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["scale"] = 1,
},
},
}
