
Details_StreamerDB = {
["characters"] = {
["Calestin - Sargeras"] = "Ailisuul - Arthas",
["Strid - Kel'Thuzad"] = "Ailisuul - Arthas",
["Esker - Kel'Thuzad"] = "Ailisuul - Arthas",
["Naturerivers - Korgath"] = "Ailisuul - Arthas",
["Ailisuul - Arthas"] = "Ailisuul - Arthas",
["Mangrove - Argent Dawn"] = "Ailisuul - Arthas",
["Inundito - Kel'Thuzad"] = "Ailisuul - Arthas",
["Flumina - Argent Dawn"] = "Ailisuul - Arthas",
["Emptystreams - Argent Dawn"] = "Ailisuul - Arthas",
["Alluvium - Argent Dawn"] = "Ailisuul - Arthas",
["Headcut - Argent Dawn"] = "Ailisuul - Arthas",
["Confluence - Argent Dawn"] = "Ailisuul - Arthas",
["Gelae - Kel'Thuzad"] = "Ailisuul - Arthas",
["Zimuures - Argent Dawn"] = "Ailisuul - Arthas",
["Testrivers - Arthas"] = "Ailisuul - Arthas",
["Alandere - Argent Dawn"] = "Ailisuul - Arthas",
["Beefyrivers - Arthas"] = "Ailisuul - Arthas",
["Saellindris - Kel'Thuzad"] = "Ailisuul - Arthas",
["Cataracts - Argent Dawn"] = "Ailisuul - Arthas",
["Garumn - Arthas"] = "Ailisuul - Arthas",
["Emptyrivers - Sargeras"] = "Ailisuul - Arthas",
["Ochrian - Argent Dawn"] = "Ailisuul - Arthas",
["Lotic - Argent Dawn"] = "Ailisuul - Arthas",
["Emptyrivers - Arthas"] = "Ailisuul - Arthas",
["Asperos - Kel'Thuzad"] = "Ailisuul - Arthas",
["Mahntaiaga - Arthas"] = "Ailisuul - Arthas",
["Mothugeon - Argent Dawn"] = "Ailisuul - Arthas",
["Evilrivers - Kel'Thuzad"] = "Ailisuul - Arthas",
["Riparium - Argent Dawn"] = "Ailisuul - Arthas",
["Wildeadoriah - The Scryers"] = "Ailisuul - Arthas",
["Benthos - Argent Dawn"] = "Ailisuul - Arthas",
["Emptyrivers - Argent Dawn"] = "Ailisuul - Arthas",
["Karst - Argent Dawn"] = "Ailisuul - Arthas",
["Sverdrup - Argent Dawn"] = "Sverdrup - Argent Dawn",
["Stream - Argent Dawn"] = "Ailisuul - Arthas",
["Estuary - Argent Dawn"] = "Ailisuul - Arthas",
},
["profiles"] = {
["Ailisuul - Arthas"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["scale"] = 1,
["arrow_anchor_y"] = 0,
["minimap"] = {
["minimapPos"] = 303.234030123659,
["radius"] = 160,
["hide"] = false,
},
["row_height"] = 20,
["arrow_anchor_x"] = 0,
["font_color"] = {
1,
1,
1,
1,
},
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["point"] = "CENTER",
["main_frame_strata"] = "LOW",
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["font_size"] = 10,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 3.0517578125e-05,
["x"] = 3.0517578125e-05,
["size"] = 32,
["update_speed"] = 0.05,
["attribute_type"] = 1,
},
["use_spark"] = true,
["x"] = 0,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["y"] = 4.57763671875e-05,
["author"] = "Details! Team",
["main_frame_locked"] = false,
["main_frame_size"] = {
300,
500.000030517578,
},
},
["Sverdrup - Argent Dawn"] = {
["use_square_mode"] = false,
["is_first_run"] = false,
["arrow_color"] = {
1,
1,
1,
0.5,
},
["main_frame_size"] = {
300,
500.0000305175781,
},
["arrow_anchor_y"] = 0,
["minimap"] = {
["minimapPos"] = 160,
["radius"] = 160,
["hide"] = false,
},
["main_frame_locked"] = false,
["arrow_anchor_x"] = 0,
["author"] = "Terciob",
["row_texture"] = "Details Serenity",
["square_grow_direction"] = "right",
["font_size"] = 10,
["row_color"] = {
0.1,
0.1,
0.1,
0.4,
},
["square_amount"] = 5,
["enabled"] = false,
["arrow_size"] = 10,
["use_spark"] = true,
["row_spacement"] = 21,
["main_frame_color"] = {
0,
0,
0,
0.2,
},
["main_frame_strata"] = "LOW",
["arrow_texture"] = "Interface\\CHATFRAME\\ChatFrameExpandArrow",
["per_second"] = {
["enabled"] = false,
["point"] = "CENTER",
["scale"] = 1,
["font_shadow"] = true,
["y"] = 3.0517578125e-05,
["x"] = -3.0517578125e-05,
["attribute_type"] = 1,
["update_speed"] = 0.05,
["size"] = 32,
},
["y"] = 0,
["x"] = -3.0517578125e-05,
["font_face"] = "Friz Quadrata TT",
["square_size"] = 32,
["point"] = "CENTER",
["font_color"] = {
1,
1,
1,
1,
},
["row_height"] = 20,
["scale"] = 1,
},
},
}
