
DevToolDatabase = {
["profileKeys"] = {
["Calestin - Sargeras"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Naturerivers - Korgath"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Lotic - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Inundito - Kel'Thuzad"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Saellindris - Kel'Thuzad"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Zimuures - Argent Dawn"] = "Default",
["Emptystreams - Argent Dawn"] = "Default",
["Emptyrivers - Sargeras"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Asperos - Kel'Thuzad"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Mothugeon - Argent Dawn"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Wildeadoriah - The Scryers"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Alandere - Argent Dawn"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Calestin - Sargeras"] = {
},
["Strid - Kel'Thuzad"] = {
},
["Stream - Argent Dawn"] = {
},
["Naturerivers - Korgath"] = {
},
["Esker - Kel'Thuzad"] = {
["isSideBarOpen"] = false,
["fontSize"] = 15,
["history"] = {
"Enum",
"foo",
"C_TransmogCollection",
"Enum.TransmogType",
"C_Transmog",
"TransmogUtil",
"C_Item",
"RemixCheckListDump",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9993896484375,
},
["Inundito - Kel'Thuzad"] = {
["fontSize"] = 17,
["history"] = {
"Enum.TooltipDataLineType",
"ITEM_QUALITY_COLORS",
"RemixChecklistFrame",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0003662109375,
},
["Lotic - Argent Dawn"] = {
},
["Mangrove - Argent Dawn"] = {
},
["Cataracts - Argent Dawn"] = {
},
["Zimuures - Argent Dawn"] = {
},
["Saellindris - Kel'Thuzad"] = {
},
["Flumina - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"WeakAuras",
"WeakAurasPrivate",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0003662109375,
},
["Default"] = {
["fontSize"] = 14,
["history"] = {
"_detalhes_database",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9935302734375,
},
["Emptystreams - Argent Dawn"] = {
},
["Emptyrivers - Sargeras"] = {
},
["Alluvium - Argent Dawn"] = {
["fontSize"] = 17,
["history"] = {
"DataStore.IsQuestCompletedBy(DataStore:GetCharacterTable(\"DataStore_Quests\", \"Headcut\"), 70516)",
"ASDFJKL",
"LibOpenRaid",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9998779296875,
},
["Riptides - Argent Dawn"] = {
},
["Riparium - Argent Dawn"] = {
["fontSize"] = 16,
["history"] = {
"Enum",
"Troubleshooter2",
"Troubleshooter",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.002685546875,
},
["Asperos - Kel'Thuzad"] = {
},
["Headcut - Argent Dawn"] = {
["collResizeWidth"] = 481.63525390625,
["fontSize"] = 16,
},
["Confluence - Argent Dawn"] = {
["history"] = {
"BisectorSaved",
"BISECT_DBG",
"TradeSkillMasterDB",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
},
["Mothugeon - Argent Dawn"] = {
},
["Gelae - Kel'Thuzad"] = {
["history"] = {
"NumberFontNormal",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["fontSize"] = 16,
},
["Wildeadoriah - The Scryers"] = {
},
["Benthos - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"DetailsFramework",
"RAID_CLASS_COLORS",
"_G",
nil,
"DevTool.settings.history",
"DevTool",
"find LFR",
"find SLASH",
"startswith DevTool",
},
["collResizeWidth"] = 249.9991455078125,
},
["Emptyrivers - Argent Dawn"] = {
["fontSize"] = 17,
["history"] = {
"RAID_CLASS_COLORS",
"BisectorResults",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
},
["Karst - Argent Dawn"] = {
["fontSize"] = 16,
["history"] = {
"BisectorResults",
"BisectorResultsFrame",
"MultiLineEditBox1Edit",
"find SLASH",
"DevTool",
"find LFR",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0001220703125,
},
["Alandere - Argent Dawn"] = {
},
["Sverdrup - Argent Dawn"] = {
["fontSize"] = 15,
["history"] = {
"BISECT_DBG",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9996337890625,
},
["Estuary - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"Enum.ItemModification",
"C_BattleNet",
"WeeklyKnowledgeDB",
"Enum.PowerType",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 284.2579345703125,
},
},
}
