
DevToolDatabase = {
["profileKeys"] = {
["Calestin - Sargeras"] = "Calestin - Sargeras",
["Strid - Kel'Thuzad"] = "Strid - Kel'Thuzad",
["Stream - Argent Dawn"] = "Stream - Argent Dawn",
["Naturerivers - Korgath"] = "Naturerivers - Korgath",
["Esker - Kel'Thuzad"] = "Esker - Kel'Thuzad",
["Lotic - Argent Dawn"] = "Lotic - Argent Dawn",
["Mangrove - Argent Dawn"] = "Mangrove - Argent Dawn",
["Saellindris - Kel'Thuzad"] = "Saellindris - Kel'Thuzad",
["Cataracts - Argent Dawn"] = "Cataracts - Argent Dawn",
["Inundito - Kel'Thuzad"] = "Inundito - Kel'Thuzad",
["Flumina - Argent Dawn"] = "Flumina - Argent Dawn",
["Zimuures - Argent Dawn"] = "Zimuures - Argent Dawn",
["Emptystreams - Argent Dawn"] = "Emptystreams - Argent Dawn",
["Emptyrivers - Sargeras"] = "Emptyrivers - Sargeras",
["Alluvium - Argent Dawn"] = "Alluvium - Argent Dawn",
["Riparium - Argent Dawn"] = "Riparium - Argent Dawn",
["Riptides - Argent Dawn"] = "Riptides - Argent Dawn",
["Asperos - Kel'Thuzad"] = "Asperos - Kel'Thuzad",
["Headcut - Argent Dawn"] = "Headcut - Argent Dawn",
["Confluence - Argent Dawn"] = "Confluence - Argent Dawn",
["Mothugeon - Argent Dawn"] = "Mothugeon - Argent Dawn",
["Gelae - Kel'Thuzad"] = "Gelae - Kel'Thuzad",
["Wildeadoriah - The Scryers"] = "Wildeadoriah - The Scryers",
["Benthos - Argent Dawn"] = "Benthos - Argent Dawn",
["Emptyrivers - Argent Dawn"] = "Emptyrivers - Argent Dawn",
["Karst - Argent Dawn"] = "Karst - Argent Dawn",
["Alandere - Argent Dawn"] = "Alandere - Argent Dawn",
["Sverdrup - Argent Dawn"] = "Sverdrup - Argent Dawn",
["Estuary - Argent Dawn"] = "Estuary - Argent Dawn",
},
["profiles"] = {
["Calestin - Sargeras"] = {
},
["Strid - Kel'Thuzad"] = {
},
["Stream - Argent Dawn"] = {
},
["Naturerivers - Korgath"] = {
},
["Esker - Kel'Thuzad"] = {
["isSideBarOpen"] = false,
["fontSize"] = 15,
["history"] = {
"Enum",
"foo",
"C_TransmogCollection",
"Enum.TransmogType",
"C_Transmog",
"TransmogUtil",
"C_Item",
"RemixCheckListDump",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9993896484375,
},
["Lotic - Argent Dawn"] = {
},
["Mangrove - Argent Dawn"] = {
},
["Saellindris - Kel'Thuzad"] = {
},
["Cataracts - Argent Dawn"] = {
},
["Inundito - Kel'Thuzad"] = {
["fontSize"] = 17,
["history"] = {
"Enum.TooltipDataLineType",
"ITEM_QUALITY_COLORS",
"RemixChecklistFrame",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0003662109375,
},
["Flumina - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"WeakAuras",
"WeakAurasPrivate",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0003662109375,
},
["Zimuures - Argent Dawn"] = {
},
["Emptystreams - Argent Dawn"] = {
},
["Emptyrivers - Sargeras"] = {
},
["Alluvium - Argent Dawn"] = {
["fontSize"] = 17,
["history"] = {
"DataStore.IsQuestCompletedBy(DataStore:GetCharacterTable(\"DataStore_Quests\", \"Headcut\"), 70516)",
"ASDFJKL",
"LibOpenRaid",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9998779296875,
},
["Riparium - Argent Dawn"] = {
["fontSize"] = 16,
["history"] = {
"Enum",
"Troubleshooter2",
"Troubleshooter",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.002685546875,
},
["Riptides - Argent Dawn"] = {
},
["Asperos - Kel'Thuzad"] = {
},
["Headcut - Argent Dawn"] = {
["collResizeWidth"] = 481.63525390625,
["fontSize"] = 16,
},
["Confluence - Argent Dawn"] = {
["history"] = {
"BisectorSaved",
"BISECT_DBG",
"TradeSkillMasterDB",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
},
["Mothugeon - Argent Dawn"] = {
},
["Gelae - Kel'Thuzad"] = {
["fontSize"] = 16,
["history"] = {
"NumberFontNormal",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
},
["Wildeadoriah - The Scryers"] = {
},
["Benthos - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"DetailsFramework",
"RAID_CLASS_COLORS",
"_G",
nil,
"DevTool.settings.history",
"DevTool",
"find LFR",
"find SLASH",
"startswith DevTool",
},
["collResizeWidth"] = 249.9991455078125,
},
["Emptyrivers - Argent Dawn"] = {
["history"] = {
"RAID_CLASS_COLORS",
"BisectorResults",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["fontSize"] = 17,
},
["Karst - Argent Dawn"] = {
["fontSize"] = 16,
["history"] = {
"BisectorResults",
"BisectorResultsFrame",
"MultiLineEditBox1Edit",
"find SLASH",
"DevTool",
"find LFR",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 250.0001220703125,
},
["Alandere - Argent Dawn"] = {
},
["Sverdrup - Argent Dawn"] = {
["fontSize"] = 15,
["history"] = {
"BISECT_DBG",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 249.9996337890625,
},
["Estuary - Argent Dawn"] = {
["isSideBarOpen"] = false,
["fontSize"] = 16,
["history"] = {
"C_BattleNet",
"WeeklyKnowledgeDB",
"Enum.PowerType",
"DevTool",
"find LFR",
"find SLASH",
"find Data DevTool",
"startswith DevTool",
"DevTool.settings.history",
},
["collResizeWidth"] = 347.49658203125,
},
},
}
