
DialogueUI_DB = {
	["CameraChangeFov"] = true,
	["HideUnitNames"] = false,
	["TTSUseHotkey"] = true,
	["QuestTypeText"] = true,
	["TTSAutoStop"] = true,
	["SimplifyCurrencyReward"] = true,
	["AutoSelectGossip"] = false,
	["FontSizeBase"] = 1,
	["MarkHighestSellPrice"] = true,
	["ShowNPCNameOnPage"] = false,
	["FrameSize"] = 2,
	["NameplateDialogEnabled"] = false,
	["TooltipShowItemComparison"] = true,
	["ShowCopyTextButton"] = true,
	["Theme"] = 2,
	["QuestItemDisplayHideSeen"] = false,
	["QuestItemDisplay"] = false,
	["Tutorial_OpenSettings"] = true,
	["TTSAutoPlay"] = false,
	["CameraMovementDisableInstance"] = false,
	["PrimaryControlKey"] = 1,
	["ForceGossip"] = false,
	["InputDevice"] = 1,
	["CameraMovement1MaintainPosition"] = false,
	["CameraMovement"] = 1,
	["ScrollDownThenAcceptQuest"] = false,
	["CameraMovementMountedCamera"] = true,
	["HideUI"] = true,
	["TTSEnabled"] = false,
	["UseRoleplayName"] = false,
	["installTime"] = 1711280000,
	["CameraMovement2MaintainPosition"] = true,
}
DialogueUI_Saves = {
}
