
DialogKeyDB = {
	["profileKeys"] = {
		["Savattellir - Arthas"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Holyrivers - Sargeras"] = "Default",
		["Shachein - Arthas"] = "Default",
		["Serenerivers - Sargeras"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Feralrivers - Sargeras"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Boringrivers - Bleeding Hollow"] = "Default",
		["Emptyrivers - Arthas"] = "Default",
		["Crazyrivers - Sargeras"] = "Default",
		["Dammedrivers - Exodar"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Crazyrivers - Arthas"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
		["Eysta - Sargeras"] = "Default",
		["Testrivers - Bleeding Hollow"] = "Default",
		["Emptyrivers - Bleeding Hollow"] = "Default",
		["Wildrivers - Bleeding Hollow"] = "Default",
		["Kdajshtlaiuw - Bleeding Hollow"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Testes - Arthas"] = "Default",
		["Crazyrivers - Bleeding Hollow"] = "Default",
		["Riversticks - Bleeding Hollow"] = "Default",
		["Evilrivers - Sargeras"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Tinyrivers - Sargeras"] = "Default",
		["Serenerivers - Bleeding Hollow"] = "Default",
		["Mindrivers - Korgath"] = "Default",
	},
	["global"] = {
		["shownBindWarning"] = true,
	},
}
