
DialogKeyDFDB = {
	["profileKeys"] = {
		["Stream - Argent Dawn"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Lotic - Argent Dawn"] = "Default",
		["Mangrove - Argent Dawn"] = "Default",
		["Flumina - Argent Dawn"] = "Default",
		["Emptystreams - Argent Dawn"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Alluvium - Argent Dawn"] = "Default",
		["Cataracts - Argent Dawn"] = "Default",
		["Mothugeon - Argent Dawn"] = "Default",
		["Headcut - Argent Dawn"] = "Default",
		["Confluence - Argent Dawn"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Ochrian - Argent Dawn"] = "Default",
		["Riparium - Argent Dawn"] = "Default",
		["Zimuures - Argent Dawn"] = "Default",
		["Emptyrivers - Arthas"] = "Default",
		["Emptyrivers - Argent Dawn"] = "Default",
		["Alandere - Argent Dawn"] = "Default",
		["Sverdrup - Argent Dawn"] = "Default",
		["Estuary - Argent Dawn"] = "Default",
	},
	["global"] = {
		["dontClickSummons"] = true,
		["showGlow"] = false,
		["dontPostAuctions"] = false,
	},
}
