
EllesmereUIDB = {
["unlockGridMode"] = "dimmed",
["specProfiles"] = {
},
["profileOrder"] = {
"Custom",
},
["sidebarUnlockTipSeen"] = true,
["profiles"] = {
["Custom"] = {
["fonts"] = {
["global"] = "Expressway",
["outlineMode"] = "shadow",
},
["customColors"] = {
},
["addons"] = {
["EllesmereUICooldownManager"] = {
["utilityScale"] = 1,
["specProfiles"] = {
["252"] = {
["barSpells"] = {
},
},
},
["spec"] = {
["252"] = {
["mappings"] = {
{
["enabled"] = false,
["actionButton"] = 1,
["cdmSlot"] = 1,
["actionBar"] = 1,
["glowColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0.1,
},
["name"] = "Buff Name (eg: Divine Purpose)",
["mode"] = "ACTIVE",
["glowStyle"] = 1,
["hideFromCDM"] = false,
},
},
["selectedMapping"] = 1,
},
},
["reskinBorders"] = true,
["buffBars"] = {
["showTimer"] = true,
["borderB"] = 0,
["bgAlpha"] = 0.4,
["barG"] = 0.82,
["borderSize"] = 1,
["borderR"] = 0,
["spacing"] = 2,
["locked"] = false,
["filterMode"] = "all",
["showIcon"] = true,
["barR"] = 0.05,
["borderA"] = 1,
["filterList"] = "",
["offsetX"] = 300,
["maxBars"] = 8,
["width"] = 200,
["barB"] = 0.62,
["growUp"] = false,
["enabled"] = false,
["borderG"] = 0,
["height"] = 18,
["offsetY"] = -200,
["useClassColor"] = false,
["iconSize"] = 18,
},
["_capturedOnce"] = true,
["cdmBars"] = {
["enabled"] = true,
["bars"] = {
{
["borderThickness"] = "thin",
["barBgB"] = 0,
["chargeFontSize"] = 11,
["stackCountB"] = 1,
["numRows"] = 1,
["activeAnimClassColor"] = false,
["bgB"] = 0.08,
["borderA"] = 1,
["key"] = "cooldowns",
["keybindA"] = 0.9,
["swipeAlpha"] = 0.7,
["desaturateOnCD"] = true,
["anchorOffsetY"] = 0,
["barBgEnabled"] = false,
["enabled"] = true,
["stackCountR"] = 1,
["iconShape"] = "none",
["keybindB"] = 1,
["barVisibility"] = "always",
["activeAnimB"] = 0,
["cooldownFontSize"] = 12,
["barScale"] = 1,
["activeAnimG"] = 0.85,
["activeAnimR"] = 1,
["name"] = "Cooldowns",
["borderG"] = 0,
["anchorTo"] = "none",
["showStackCount"] = false,
["stackCountG"] = 1,
["anchorPosition"] = "left",
["bgR"] = 0.08,
["borderClassColor"] = false,
["borderB"] = 0,
["activeStateAnim"] = "blizzard",
["stackCountY"] = 0,
["borderR"] = 0,
["keybindR"] = 1,
["verticalOrientation"] = false,
["showTooltip"] = false,
["borderSize"] = 1,
["keybindG"] = 1,
["spacing"] = 0,
["iconSize"] = 50,
["showCharges"] = true,
["anchorOffsetX"] = 0,
["showCooldownText"] = true,
["bgA"] = 0.6,
["barBgAlpha"] = 1,
["growDirection"] = "RIGHT",
["housingHideEnabled"] = true,
["keybindOffsetY"] = -2,
["hideBuffsWhenInactive"] = true,
["trackedSpells"] = {
55090,
85948,
47541,
207317,
1247378,
1233448,
42650,
},
["keybindSize"] = 10,
["stackCountSize"] = 11,
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["stackCountX"] = 0,
["showKeybind"] = false,
["keybindOffsetX"] = 2,
},
{
["borderThickness"] = "thin",
["barBgB"] = 0,
["chargeFontSize"] = 11,
["stackCountB"] = 1,
["numRows"] = 2,
["activeAnimClassColor"] = false,
["bgB"] = 0.08,
["borderA"] = 1,
["key"] = "utility",
["keybindA"] = 0.9,
["swipeAlpha"] = 0.7,
["desaturateOnCD"] = true,
["anchorOffsetY"] = 0,
["barBgEnabled"] = false,
["enabled"] = true,
["stackCountR"] = 1,
["iconShape"] = "none",
["keybindB"] = 1,
["barVisibility"] = "always",
["activeAnimB"] = 0,
["cooldownFontSize"] = 12,
["barScale"] = 1,
["activeAnimG"] = 0.85,
["activeAnimR"] = 1,
["name"] = "Utility",
["borderG"] = 0,
["anchorTo"] = "none",
["showStackCount"] = false,
["stackCountG"] = 1,
["anchorPosition"] = "left",
["bgR"] = 0.08,
["borderClassColor"] = false,
["borderB"] = 0,
["activeStateAnim"] = "blizzard",
["stackCountY"] = 0,
["borderR"] = 0,
["keybindR"] = 1,
["verticalOrientation"] = false,
["showTooltip"] = false,
["borderSize"] = 1,
["keybindG"] = 1,
["spacing"] = 0,
["iconSize"] = 30,
["showCharges"] = true,
["anchorOffsetX"] = 0,
["showCooldownText"] = true,
["bgA"] = 0.6,
["barBgAlpha"] = 1,
["growDirection"] = "RIGHT",
["housingHideEnabled"] = true,
["keybindOffsetY"] = -2,
["hideBuffsWhenInactive"] = true,
["trackedSpells"] = {
47528,
221562,
207167,
49576,
48707,
48792,
51052,
49039,
48265,
61999,
46584,
49998,
},
["keybindSize"] = 10,
["stackCountSize"] = 11,
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["stackCountX"] = 0,
["showKeybind"] = false,
["keybindOffsetX"] = 2,
},
{
["borderThickness"] = "thin",
["barBgB"] = 0,
["chargeFontSize"] = 11,
["stackCountB"] = 1,
["numRows"] = 1,
["showTooltip"] = false,
["keybindA"] = 0.9,
["borderA"] = 1,
["key"] = "buffs",
["desaturateOnCD"] = true,
["keybindOffsetX"] = 2,
["barBgEnabled"] = false,
["anchorOffsetY"] = 0,
["stackCountR"] = 1,
["enabled"] = true,
["stackCountSize"] = 11,
["iconShape"] = "none",
["keybindB"] = 1,
["barVisibility"] = "always",
["activeAnimB"] = 0,
["cooldownFontSize"] = 12,
["barScale"] = 1,
["activeAnimG"] = 0.85,
["activeAnimR"] = 1,
["name"] = "Buffs",
["borderG"] = 0,
["anchorTo"] = "none",
["showStackCount"] = true,
["stackCountG"] = 1,
["anchorPosition"] = "left",
["bgR"] = 0.08,
["borderClassColor"] = false,
["borderB"] = 0,
["activeStateAnim"] = "blizzard",
["stackCountY"] = 0,
["borderR"] = 0,
["keybindR"] = 1,
["verticalOrientation"] = false,
["bgB"] = 0.08,
["borderSize"] = 1,
["activeAnimClassColor"] = false,
["spacing"] = 1,
["iconSize"] = 40,
["showCharges"] = true,
["anchorOffsetX"] = 0,
["showCooldownText"] = true,
["bgA"] = 0.6,
["barBgAlpha"] = 1,
["keybindG"] = 1,
["growDirection"] = "RIGHT",
["keybindOffsetY"] = -2,
["housingHideEnabled"] = true,
["hideBuffsWhenInactive"] = true,
["keybindSize"] = 10,
["trackedSpells"] = {
77575,
77575,
455397,
49530,
},
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["stackCountX"] = 0,
["showKeybind"] = false,
["swipeAlpha"] = 0.7,
},
},
["hideBlizzard"] = true,
["barDefaults"] = {
["borderThickness"] = "thin",
["keybindB"] = 1,
["chargeFontSize"] = 11,
["stackCountB"] = 1,
["numRows"] = 1,
["borderA"] = 1,
["keybindOffsetX"] = 2,
["anchorOffsetY"] = 0,
["borderG"] = 0,
["keybindA"] = 0.9,
["desaturateOnCD"] = true,
["hideBuffsWhenInactive"] = true,
["stackCountR"] = 1,
["barVisibility"] = "always",
["housingHideEnabled"] = true,
["cooldownFontSize"] = 12,
["stackCountSize"] = 11,
["activeAnimG"] = 0.85,
["activeAnimR"] = 1,
["iconShape"] = "none",
["barBgEnabled"] = false,
["barBgB"] = 0,
["showStackCount"] = false,
["stackCountG"] = 1,
["activeAnimB"] = 0,
["bgR"] = 0.08,
["borderClassColor"] = false,
["borderB"] = 0,
["activeStateAnim"] = "blizzard",
["anchorTo"] = "none",
["anchorPosition"] = "left",
["stackCountY"] = 0,
["keybindG"] = 1,
["growDirection"] = "RIGHT",
["borderSize"] = 1,
["activeAnimClassColor"] = false,
["bgB"] = 0.08,
["iconSize"] = 36,
["showCharges"] = true,
["verticalOrientation"] = false,
["showCooldownText"] = true,
["bgA"] = 0.6,
["barBgAlpha"] = 1,
["showTooltip"] = false,
["keybindR"] = 1,
["keybindOffsetY"] = -2,
["anchorOffsetX"] = 0,
["spacing"] = 2,
["keybindSize"] = 10,
["borderR"] = 0,
["barBgR"] = 0,
["iconZoom"] = 0.08,
["bgG"] = 0.08,
["barBgG"] = 0,
["stackCountX"] = 0,
["showKeybind"] = false,
["swipeAlpha"] = 0.7,
},
},
["cdmBarPositions"] = {
["cooldowns"] = {
["y"] = -236.0451354980469,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["buffs"] = {
["y"] = -120.0451049804688,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
["utility"] = {
["y"] = -291.0451354980469,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 0,
},
},
["buffBarScale"] = 1,
["cooldownBarScale"] = 1,
["activeSpecKey"] = "252",
["tbbPositions"] = {
},
["barGlows"] = {
["enabled"] = true,
["selectedBar"] = 1,
["selectedAssignment"] = 1,
["assignments"] = {
},
},
},
["EllesmereUINameplates"] = {
["friendlyShowDefaultNames"] = false,
["textSlotRight"] = "healthPercent",
["topSlotSize"] = 26,
["focusColorEnabled"] = true,
["showFriendlyNPCs"] = false,
["castBarUninterruptible"] = {
["r"] = 0.45,
["g"] = 0.45,
["b"] = 0.45,
},
["leftSlotXOffset"] = 0,
["debuffIconSize"] = 26,
["castBarHeight"] = 17,
["textSlotTop"] = "enemyName",
["auraDurationTextSize"] = 11,
["topleftSlotGrowth"] = "left",
["font"] = "Interface\\AddOns\\EllesmereUI\\media\\fonts\\Expressway.TTF",
["friendlyNameOnlyYOffset"] = -20,
["healthBarTexture"] = "none",
["raidMarkerSize"] = 24,
["nameYOffset"] = 0,
["hpNumberPos"] = "none",
["auraDurationTextColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["showCastIcon"] = true,
["classPowerCustomColor"] = {
["r"] = 1,
["g"] = 0.84,
["b"] = 0.3,
},
["topSlotYOffset"] = 0,
["pandemicGlowSpeed"] = 4,
["buffIconSize"] = 24,
["leftSlotSize"] = 24,
["textSlotRightSize"] = 10,
["questMobColorEnabled"] = false,
["topleftSlotXOffset"] = 0,
["rightSlotSize"] = 24,
["focusOverlayAlpha"] = 0.4,
["rareEliteIconSize"] = 20,
["classPowerEmptyColor"] = {
["r"] = 0.2,
["g"] = 0.2,
["b"] = 0.2,
},
["miniboss"] = {
["r"] = 0.518,
["g"] = 0.243,
["b"] = 0.984,
},
["buffTimerPosition"] = "topleft",
["auraStackTextColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["hashLinePercent"] = 30,
["bottomSlotXOffset"] = 0,
["raidMarkerPos"] = "topright",
["enemyInCombat"] = {
["r"] = 0.8,
["g"] = 0.137,
["b"] = 0.137,
},
["debuffTextWhite"] = false,
["auraStackTextSize"] = 11,
["topSlotXOffset"] = 0,
["toprightSlotSize"] = 24,
["textSlotRightXOffset"] = 0,
["tankHasAggro"] = {
["r"] = 0.05,
["g"] = 0.82,
["b"] = 0.62,
},
["ccIconSize"] = 24,
["textSlotRightYOffset"] = 0,
["topleftSlotSize"] = 24,
["textSlotLeft"] = "none",
["castNameSize"] = 10,
["bottomSlotSize"] = 26,
["castIconScale"] = 1,
["enemyNamePos"] = "top",
["rareEliteIconXOffset"] = 0,
["buffTextColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["ccTimerPosition"] = "topleft",
["friendlyPlateYOffset"] = 0,
["castNameColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["classPowerXOffset"] = 0,
["kickTickEnabled"] = true,
["targetArrowScale"] = 1,
["castBar"] = {
["r"] = 0.7,
["g"] = 0.4,
["b"] = 0.9,
},
["enemyNameTextSize"] = 11,
["borderColor"] = {
["r"] = 0.067,
["g"] = 0.067,
["b"] = 0.067,
},
["classPowerBgColor"] = {
["r"] = 0.082,
["g"] = 0.082,
["b"] = 0.082,
},
["tankLosingAggro"] = {
["r"] = 0.81,
["g"] = 0.72,
["b"] = 0.19,
},
["buffSlot"] = "left",
["sideAuraXOffset"] = 2,
["classPowerClassColors"] = true,
["borderStyle"] = "ellesmere",
["tankHasAggroEnabled"] = false,
["pandemicGlow"] = false,
["buffTextSize"] = 12,
["rightSlotXOffset"] = 0,
["classPowerGap"] = 2,
["kickTickColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["showFriendlyPlayers"] = true,
["dpsNearAggro"] = {
["r"] = 0.81,
["g"] = 0.72,
["b"] = 0.19,
},
["enemyNameColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["textSlotLeftYOffset"] = 0,
["focus"] = {
["r"] = 0.051,
["g"] = 0.82,
["b"] = 0.62,
},
["toprightSlotGrowth"] = "right",
["textSlotCenterSize"] = 10,
["textSlotTopYOffset"] = 0,
["pandemicGlowColor"] = {
["r"] = 1,
["g"] = 0.8,
["b"] = 0.329,
},
["textSlotCenterColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["debuffYOffset"] = 2,
["textSlotCenterYOffset"] = 0,
["questMobColor"] = {
["r"] = 0.157,
["g"] = 0.855,
["b"] = 0.475,
},
["neutral"] = {
["r"] = 0.81,
["g"] = 0.72,
["b"] = 0.19,
},
["focusCastHeight"] = 100,
["healthBarWidth"] = 6,
["classPowerPos"] = "bottom",
["textSlotLeftColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["textSlotTopColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["nameplateOverlapV"] = 1.05,
["classColorFriendly"] = true,
["targetGlowStyle"] = "ellesmereui",
["showAllDebuffs"] = false,
["showTargetGlow"] = true,
["leftSlotYOffset"] = 0,
["classPowerYOffset"] = 1,
["textSlotTopXOffset"] = 0,
["textSlotRightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["bottomSlotYOffset"] = 0,
["textSlotCenterXOffset"] = 0,
["topleftSlotYOffset"] = 0,
["textSlotLeftXOffset"] = 0,
["classPowerScale"] = 1,
["pandemicGlowThickness"] = 1,
["textSlotTopSize"] = 10,
["rareEliteIconYOffset"] = 0,
["auraSpacing"] = 2,
["healthTextSize"] = 10,
["debuffTimerColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["focusOverlayColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["focusOverlayTexture"] = "striped-v2",
["ccTextColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["textSlotCenter"] = "none",
["raidMarkerYOffset"] = 2,
["healthBarHeight"] = 17,
["dpsHasAggro"] = {
["r"] = 1,
["g"] = 0.5,
["b"] = 0,
},
["hashLineEnabled"] = false,
["friendlyHealthBarHeight"] = 17,
["hashLineColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["tankNoAggro"] = {
["r"] = 1,
["g"] = 0.22,
["b"] = 0.17,
},
["ccTextSize"] = 12,
["pandemicGlowLines"] = 8,
["castScale"] = 100,
["hpPercentPos"] = "right",
["nameplateYOffset"] = 0,
["castTargetColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["castTargetClassColor"] = true,
["castTargetSize"] = 10,
["classificationSlot"] = "topleft",
["hostile"] = {
["r"] = 0.39,
["g"] = 0.11,
["b"] = 0.09,
},
["healthTextColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["friendlyHealthBarWidth"] = 150,
["toprightSlotXOffset"] = 0,
["rightSlotYOffset"] = 0,
["showTargetArrows"] = false,
["showHealthNumber"] = false,
["debuffSlot"] = "top",
["tapped"] = {
["r"] = 0.5,
["g"] = 0.5,
["b"] = 0.5,
},
["showEnemyPets"] = false,
["debuffTextPosition"] = "topleft",
["debuffTimerPosition"] = "topleft",
["ccSlot"] = "right",
["toprightSlotYOffset"] = 0,
["auraTextPosition"] = "topleft",
["friendlyNameOnly"] = true,
["pandemicGlowStyle"] = 1,
["caster"] = {
["r"] = 0.231,
["g"] = 0.51,
["b"] = 0.965,
},
["showClassPower"] = false,
["stackSpacingScale"] = 100,
["textSlotLeftSize"] = 10,
["interruptReady"] = {
["r"] = 0.92,
["g"] = 0.35,
["b"] = 0.2,
},
},
["EllesmereUICursor"] = {
["hex"] = "0CD29D",
["scale"] = 1,
["trail"] = false,
["gcd"] = {
["hex"] = "FFFFFF",
["radius"] = 21,
["scale"] = 100,
["attached"] = true,
["enabled"] = false,
["ringTex"] = "light",
["instanceOnly"] = false,
["useClassColor"] = false,
["alpha"] = 80,
},
["instanceOnly"] = false,
["enabled"] = true,
["castCircle"] = {
["hex"] = "3FA7FF",
["radius"] = 30,
["scale"] = 100,
["attached"] = true,
["enabled"] = false,
["sparkEnabled"] = true,
["ringTex"] = "normal",
["instanceOnly"] = false,
["useClassColor"] = true,
["alpha"] = 80,
},
["useClassColor"] = true,
["texture"] = "ring_normal",
},
["EllesmereUIAuraBuffReminders"] = {
["consumables"] = {
["enabled"] = {
["es"] = true,
["augment_rune"] = true,
["tstrike"] = true,
["instant"] = true,
["ls"] = true,
["wound"] = true,
["inky_black"] = true,
["ws"] = true,
["atrophic"] = true,
["numbing"] = true,
["earthliving"] = true,
["flask"] = true,
["deadly"] = true,
["windfury"] = true,
["food"] = true,
["amplifying"] = true,
["rite_adj"] = true,
["flametongue"] = true,
["rite_sanc"] = true,
["weapon_enchant"] = true,
["crippling"] = true,
},
["preferredFlask"] = "last_used",
["showSpecialsNonInstanced"] = true,
["preferredWeaponEnchant"] = "last_used",
["scale"] = 1,
["preferredFood"] = "last_used",
["runeDisplayMode"] = "mythic",
["inkyBlackZones"] = "",
},
["talentReminders"] = {
},
["display"] = {
["textFont"] = "Expressway",
["glowType"] = 0,
["scale"] = 1,
["opacity"] = 1,
["cursorAttach"] = false,
["yOffset"] = 200,
["glowColor"] = {
["r"] = 1,
["g"] = 0.776,
["b"] = 0.376,
},
["iconSpacing"] = 14,
["showText"] = true,
["textYOffset"] = -5,
["xOffset"] = 0,
["textXOffset"] = 0,
["textSize"] = 12,
["textColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["auras"] = {
["scale"] = 1,
["enabled"] = {
["bol"] = true,
["shadowform"] = true,
["som"] = true,
["symbiotic"] = true,
["berserk_stance"] = true,
["devo_aura"] = true,
["bof"] = true,
["def_stance"] = true,
},
["showNonInstanced"] = true,
},
["raidBuffs"] = {
["showNonInstanced"] = false,
["enabled"] = {
["ai"] = true,
["sky"] = true,
["bshout"] = true,
["motw"] = true,
["bronze"] = true,
["fort"] = true,
},
["scale"] = 1,
["showOthersMissing"] = true,
},
["talentReminderYOffset"] = -50,
},
["EllesmereUIActionBars"] = {
["pushedCustomColor"] = {
["a"] = 1,
["r"] = 0.973,
["g"] = 0.839,
["b"] = 0.604,
},
["pushedUseClassColor"] = false,
["hideCastingAnimations"] = true,
["cooldownEdgeColor"] = {
["a"] = 1,
["r"] = 0.973,
["g"] = 0.839,
["b"] = 0.604,
},
["cooldownEdgeUseClassColor"] = false,
["pushedBorderSize"] = 4,
["selectedBar"] = "MainBar",
["barPositions"] = {
["Bar3"] = {
["y"] = -703.7417602539062,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -435.833740234375,
},
["Bar6"] = {
["y"] = -703.7418111165365,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 727.1668497721355,
},
["ExtraActionButton"] = {
["y"] = -242.9450988769531,
["relPoint"] = "TOPLEFT",
["point"] = "CENTER",
["x"] = 961.5023803710938,
},
["Bar2"] = {
["y"] = -703.7417602539062,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -581.500244140625,
},
["Bar8"] = {
["y"] = 1030.090087890625,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -900.0046997070312,
},
["Bar5"] = {
["y"] = -703.7419001261394,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 581.5003458658855,
},
["MainBar"] = {
["y"] = -727.2418036996287,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -727.1667845871195,
},
["EncounterBar"] = {
["y"] = -177.8000793457031,
["relPoint"] = "TOPLEFT",
["point"] = "CENTER",
["x"] = 961.5024108886719,
},
["Bar7"] = {
["y"] = 1030.090087890625,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -1188.004760742188,
},
["BagBar"] = {
["y"] = -1009.190172195435,
["relPoint"] = "TOPLEFT",
["point"] = "CENTER",
["x"] = 1550.304992675781,
},
["MicroBar"] = {
["y"] = -1059.190183639526,
["relPoint"] = "TOPLEFT",
["point"] = "CENTER",
["x"] = 1459.804626464844,
},
["StanceBar"] = {
["y"] = -314.3834092881945,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -372.1112060546875,
},
["PetBar"] = {
["y"] = -331.445068359375,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = -399,
},
["Bar4"] = {
["y"] = -703.7419001261394,
["relPoint"] = "CENTER",
["point"] = "CENTER",
["x"] = 435.8336385091146,
},
},
["highlightBorderSize"] = 4,
["_capturedOnce"] = true,
["procGlowUseClassColor"] = false,
["useBlizzardDataBars"] = false,
["procGlowScale"] = 1,
["squareIcons"] = true,
["pushedTextureType"] = 2,
["procGlowType"] = 1,
["font"] = "Interface\\AddOns\\EllesmereUI\\media\\fonts\\Expressway.TTF",
["procGlowColor"] = {
["r"] = 1,
["g"] = 0.776,
["b"] = 0.376,
},
["highlightUseClassColor"] = false,
["iconZoom"] = 5.5,
["highlightTextureType"] = 2,
["highlightCustomColor"] = {
["a"] = 1,
["r"] = 0.973,
["g"] = 0.839,
["b"] = 0.604,
},
["bars"] = {
["Bar3"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 10,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["shapeBorderEnabled"] = true,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
["Bar6"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["shapeBorderEnabled"] = true,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["numIcons"] = 12,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
["ExtraActionButton"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
},
["Bar2"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 1,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["shapeBorderEnabled"] = true,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
["RepBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["width"] = 400,
["mouseoverAlpha"] = 1,
["clickThrough"] = true,
["height"] = 18,
["mouseoverSpeed"] = 0.15,
["housingHideEnabled"] = false,
["orientation"] = "HORIZONTAL",
},
["Bar8"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 2,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.5,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 1,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["shapeBorderEnabled"] = true,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
["Bar5"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 10,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["shapeBorderEnabled"] = true,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
["XPBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["combatHideEnabled"] = false,
["width"] = 400,
["mouseoverAlpha"] = 1,
["clickThrough"] = true,
["height"] = 18,
["mouseoverSpeed"] = 0.15,
["housingHideEnabled"] = false,
["orientation"] = "HORIZONTAL",
},
["MainBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["keybindOffsetX"] = 0,
["enabled"] = true,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["shapeBorderEnabled"] = true,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["numIcons"] = 12,
["clickThrough"] = false,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["alwaysShowButtons"] = true,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
},
["EncounterBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
},
["Bar7"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 2,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["keybindOffsetX"] = 0,
["enabled"] = true,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.5,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["shapeBorderEnabled"] = true,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["numIcons"] = 12,
["clickThrough"] = false,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["alwaysShowButtons"] = true,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
},
["BagBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
},
["MicroBar"] = {
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
["combatShowEnabled"] = false,
["housingHideEnabled"] = false,
["combatHideEnabled"] = false,
["mouseoverSpeed"] = 0.15,
["mouseoverAlpha"] = 1,
["clickThrough"] = false,
},
["StanceBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 1,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["keybindOffsetX"] = 0,
["enabled"] = true,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.9,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["shapeBorderEnabled"] = true,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["numIcons"] = 12,
["clickThrough"] = false,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["alwaysShowButtons"] = true,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["alwaysHidden"] = false,
["mouseoverEnabled"] = false,
},
["PetBar"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 2,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["keybindOffsetX"] = 0,
["alwaysHidden"] = true,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 1,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["hideKeybind"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 10,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["shapeBorderEnabled"] = true,
["clickThrough"] = false,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["alwaysShowButtons"] = true,
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["enabled"] = true,
["mouseoverEnabled"] = false,
},
["Bar4"] = {
["countOffsetY"] = 0,
["borderThickness"] = "thin",
["combatShowEnabled"] = false,
["bgEnabled"] = false,
["numRows"] = 4,
["countFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["clickThrough"] = false,
["keybindOffsetX"] = 0,
["alwaysHidden"] = false,
["keybindFontColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["barScale"] = 0.6,
["housingHideEnabled"] = false,
["keybindFontSize"] = 12,
["alwaysShowButtons"] = false,
["countFontSize"] = 12,
["borderClassColor"] = false,
["combatHideEnabled"] = false,
["bgColor"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderSize"] = 1,
["shapeBorderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["growDirection"] = "up",
["numIcons"] = 9,
["countOffsetX"] = 0,
["buttonPadding"] = 2,
["keybindOffsetY"] = 0,
["shapeBorderSize"] = 7,
["enabled"] = true,
["shapeBorderEnabled"] = true,
["borderEnabled"] = true,
["mouseoverAlpha"] = 1,
["buttonShape"] = "none",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["orientation"] = "horizontal",
["mouseoverSpeed"] = 0.15,
["mouseoverEnabled"] = false,
["hideKeybind"] = false,
},
},
["cooldownEdgeSize"] = 2.1,
["procGlowEnabled"] = false,
},
["EllesmereUIUnitFrames"] = {
["portraitStyle"] = "attached",
["boss"] = {
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["selectedFont"] = "Expressway",
["powerPosition"] = "below",
["powerHeight"] = 6,
["healthBarOpacity"] = 0.9,
["borderSize"] = 1,
["powerPercentY"] = 0,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["powerPercentSize"] = 9,
["showPortrait"] = false,
["powerPercentX"] = 0,
["powerPercentPowerColor"] = false,
["powerY"] = 0,
["centerTextContent"] = "none",
["healthHeight"] = 34,
["frameWidth"] = 160,
["powerX"] = 0,
["portraitMode"] = "2d",
["powerWidth"] = 0,
["castbarHeight"] = 14,
["healthDisplay"] = "perhp",
["powerBarOpacity"] = 1,
["healthBarTexture"] = "none",
["textSize"] = 12,
["leftTextContent"] = "name",
["frameScale"] = 100,
["rightTextContent"] = "perhp",
["powerPercentText"] = "none",
},
["healthBarOpacity"] = 0.9,
["target"] = {
["onlyPlayerDebuffs"] = false,
["detachedPortraitShape"] = "portrait",
["portraitX"] = 0,
["btbLeftClassColor"] = false,
["portraitSize"] = 0,
["powerPercentY"] = 0,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["leftTextX"] = 0,
["castbarHeight"] = 14,
["btbClassIconX"] = 0,
["castbarClassColored"] = false,
["rightTextClassColor"] = false,
["castDurationColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["leftTextSize"] = 12,
["bottomTextBar"] = false,
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["leftTextContent"] = "name",
["powerPercentText"] = "none",
["centerTextX"] = 0,
["powerPosition"] = "below",
["btbCenterX"] = 0,
["btbClassIconLocation"] = "left",
["powerHeight"] = 6,
["showCastIcon"] = true,
["btbCenterSize"] = 11,
["btbBgOpacity"] = 1,
["btbY"] = 0,
["btbPosition"] = "bottom",
["powerPercentPowerColor"] = false,
["buffAnchor"] = "topleft",
["healthHeight"] = 46,
["detachedPortraitClassColor"] = true,
["healthTextPosition"] = "right",
["castSpellNameColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["healthDisplay"] = "both",
["btbCenterY"] = 0,
["maxBuffs"] = 20,
["btbLeftContent"] = "none",
["rightTextContent"] = "both",
["btbBgColor"] = {
["r"] = 0.2,
["g"] = 0.2,
["b"] = 0.2,
},
["selectedFont"] = "Expressway",
["btbRightClassColor"] = false,
["castDurationSize"] = 11,
["showInRaid"] = true,
["btbClassIcon"] = "none",
["powerWidth"] = 0,
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["btbRightSize"] = 11,
["showSolo"] = true,
["rightTextSize"] = 12,
["btbClassIconSize"] = 14,
["centerTextSize"] = 12,
["showInParty"] = true,
["powerY"] = 0,
["leftTextY"] = 0,
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["detachedPortraitBorder"] = true,
["debuffAnchor"] = "bottomleft",
["detachedPortraitBorderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["btbLeftSize"] = 11,
["frameWidth"] = 181,
["powerBarOpacity"] = 1,
["detachedPortraitBorderOpacity"] = 100,
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["portraitSide"] = "right",
["frameScale"] = 100,
["bottomTextBarHeight"] = 16,
["centerTextY"] = 0,
["buffGrowth"] = "auto",
["btbLeftY"] = 0,
["portraitMode"] = "2d",
["btbRightPowerColor"] = false,
["centerTextContent"] = "none",
["showBuffs"] = true,
["namePosition"] = "left",
["btbCenterContent"] = "none",
["powerPercentSize"] = 9,
["borderSize"] = 1,
["showCastbar"] = true,
["healthBarOpacity"] = 0.9,
["btbLeftPowerColor"] = false,
["showPortrait"] = true,
["powerPercentX"] = 0,
["btbClassIconY"] = 0,
["btbCenterPowerColor"] = false,
["powerX"] = 0,
["rightTextY"] = 0,
["rightTextX"] = 0,
["portraitY"] = 0,
["castbarFillColor"] = {
["r"] = 0.863,
["g"] = 0.82,
["b"] = 0.639,
},
["detachedPortraitBorderSize"] = 7,
["btbRightX"] = 0,
["classThemeStyle"] = "modern",
["healthBarTexture"] = "none",
["btbWidth"] = 0,
["centerTextClassColor"] = false,
["textSize"] = 12,
["btbX"] = 0,
["btbRightContent"] = "none",
["maxDebuffs"] = 20,
},
["darkTheme"] = false,
["positions"] = {
["playerCastbar"] = {
["y"] = -250,
["x"] = 0,
["point"] = "CENTER",
},
["targettarget"] = {
["y"] = -152.5,
["x"] = 383,
["point"] = "CENTER",
},
["player"] = {
["y"] = -193.5,
["x"] = -317,
["point"] = "CENTER",
},
["pet"] = {
["y"] = -260,
["x"] = -300,
["point"] = "CENTER",
},
["focus"] = {
["y"] = -285,
["x"] = 0,
["point"] = "CENTER",
},
["target"] = {
["y"] = -201,
["x"] = 317,
["point"] = "CENTER",
},
["classPower"] = {
["y"] = -220,
["x"] = 0,
["point"] = "CENTER",
},
["boss"] = {
["y"] = 251,
["x"] = -326,
["point"] = "RIGHT",
},
["focustarget"] = {
["y"] = -261,
["x"] = 50,
["point"] = "CENTER",
},
},
["castbarOpacity"] = 1,
["bossSpacing"] = 60,
["pet"] = {
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["centerTextContent"] = "none",
["healthHeight"] = 25,
["powerPosition"] = "none",
["leftTextContent"] = "name",
["portraitMode"] = "2d",
["frameWidth"] = 101,
["showPortrait"] = false,
["selectedFont"] = "Expressway",
["borderSize"] = 1,
["healthBarOpacity"] = 0.9,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["healthBarTexture"] = "none",
["frameScale"] = 100,
["rightTextContent"] = "none",
["textSize"] = 12,
},
["castbarColor"] = {
["r"] = 0.114,
["g"] = 0.655,
["b"] = 0.514,
},
["showPortrait"] = true,
["player"] = {
["leftTextContent"] = "name",
["detachedPortraitShape"] = "portrait",
["portraitX"] = 0,
["btbLeftClassColor"] = false,
["rightTextClassColor"] = false,
["leftTextSize"] = 12,
["portraitSize"] = 0,
["powerPercentY"] = 0,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["classPowerBgColor"] = {
["a"] = 1,
["r"] = 0.082,
["g"] = 0.082,
["b"] = 0.082,
},
["leftTextX"] = 0,
["lockClassPowerToFrame"] = true,
["btbClassIconX"] = 0,
["castbarClassColored"] = false,
["detachedPortraitBorderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["btbY"] = 0,
["classPowerSize"] = 8,
["castDurationSize"] = 11,
["combatIndicatorY"] = 0,
["castDurationColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["showInRaid"] = true,
["classPowerCustomColor"] = {
["r"] = 1,
["g"] = 0.82,
["b"] = 0,
},
["classThemeStyle"] = "modern",
["bottomTextBar"] = false,
["combatIndicatorPosition"] = "healthbar",
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["combatIndicatorColor"] = "custom",
["powerPercentText"] = "none",
["centerTextX"] = 0,
["healthTextPosition"] = "right",
["classPowerStyle"] = "none",
["powerPosition"] = "below",
["btbCenterX"] = 0,
["btbCenterPowerColor"] = false,
["btbClassIconLocation"] = "left",
["powerHeight"] = 6,
["combatIndicatorX"] = 0,
["btbLeftY"] = 0,
["btbCenterSize"] = 11,
["btbBgOpacity"] = 1,
["classPowerBarY"] = 0,
["btbPosition"] = "bottom",
["btbClassIcon"] = "none",
["powerPercentPowerColor"] = false,
["buffAnchor"] = "topleft",
["centerTextContent"] = "none",
["healthHeight"] = 46,
["detachedPortraitClassColor"] = true,
["btbRightPowerColor"] = false,
["playerCastbarHeight"] = 0,
["castSpellNameColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["centerTextSize"] = 12,
["healthDisplay"] = "both",
["btbCenterY"] = 0,
["maxBuffs"] = 4,
["debuffAnchor"] = "bottomleft",
["btbLeftContent"] = "none",
["powerPercentX"] = 0,
["rightTextContent"] = "both",
["portraitSide"] = "left",
["showSolo"] = true,
["powerPercentSize"] = 9,
["selectedFont"] = "Expressway",
["btbRightClassColor"] = false,
["playerCastbarY"] = 0,
["combatIndicatorCustomColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["classPowerEmptyColor"] = {
["a"] = 1,
["r"] = 0.2,
["g"] = 0.2,
["b"] = 0.2,
},
["btbCenterContent"] = "none",
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["btbRightSize"] = 11,
["textSize"] = 12,
["portraitY"] = 0,
["btbClassIconSize"] = 14,
["classPowerClassColor"] = true,
["showInParty"] = true,
["powerY"] = 0,
["classPowerSpacing"] = 2,
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["detachedPortraitBorder"] = true,
["portraitMode"] = "2d",
["showPlayerAbsorb"] = false,
["btbLeftSize"] = 11,
["powerWidth"] = 0,
["powerBarOpacity"] = 1,
["lockCastbarToFrame"] = true,
["btbRightX"] = 0,
["bottomTextBarHeight"] = 16,
["frameScale"] = 100,
["frameWidth"] = 181,
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["buffGrowth"] = "auto",
["healthBarTexture"] = "none",
["centerTextY"] = 0,
["classPowerBarX"] = 0,
["classPowerPosition"] = "top",
["showBuffs"] = false,
["namePosition"] = "left",
["showPlayerCastIcon"] = true,
["btbBgColor"] = {
["r"] = 0.2,
["g"] = 0.2,
["b"] = 0.2,
},
["borderSize"] = 1,
["rightTextSize"] = 12,
["healthBarOpacity"] = 0.9,
["btbLeftPowerColor"] = false,
["showPortrait"] = true,
["btbClassIconY"] = 0,
["combatIndicatorStyle"] = "class",
["btbWidth"] = 0,
["powerX"] = 0,
["rightTextY"] = 0,
["rightTextX"] = 0,
["combatIndicatorSize"] = 22,
["castbarFillColor"] = {
["r"] = 0.863,
["g"] = 0.82,
["b"] = 0.639,
},
["detachedPortraitBorderSize"] = 7,
["leftTextY"] = 0,
["showPlayerCastbar"] = false,
["showClassPowerBar"] = false,
["playerCastbarX"] = 0,
["centerTextClassColor"] = false,
["playerCastbarWidth"] = 0,
["btbX"] = 0,
["btbRightContent"] = "none",
["detachedPortraitBorderOpacity"] = 100,
},
["_playerTargetMigrated"] = true,
["powerBarOpacity"] = 1,
["playerTarget"] = {
["onlyPlayerDebuffs"] = false,
["playerCastbarWidth"] = 0,
["showBuffs"] = true,
["maxDebuffs"] = 20,
["powerHeight"] = 6,
["powerPercentY"] = 0,
["powerPercentSize"] = 9,
["powerPercentX"] = 0,
["powerPercentPowerColor"] = false,
["healthHeight"] = 46,
["classPowerBarY"] = 0,
["playerCastbarY"] = 0,
["playerCastbarHeight"] = 0,
["showPlayerAbsorb"] = false,
["castbarHeight"] = 14,
["healthDisplay"] = "both",
["showClassPowerBar"] = false,
["maxBuffs"] = 20,
["showPlayerCastbar"] = false,
["playerCastbarX"] = 0,
["classPowerBarX"] = 0,
["frameWidth"] = 181,
["powerPercentText"] = "none",
},
["totPet"] = {
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["centerTextContent"] = "none",
["healthHeight"] = 25,
["powerPosition"] = "none",
["leftTextContent"] = "name",
["portraitMode"] = "2d",
["frameWidth"] = 101,
["showPortrait"] = false,
["selectedFont"] = "Expressway",
["borderSize"] = 1,
["healthBarOpacity"] = 0.9,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["healthBarTexture"] = "none",
["frameScale"] = 100,
["rightTextContent"] = "none",
["textSize"] = 12,
},
["focus"] = {
["onlyPlayerDebuffs"] = true,
["detachedPortraitShape"] = "portrait",
["portraitX"] = 0,
["portraitSide"] = "right",
["portraitSize"] = 0,
["powerPercentY"] = 0,
["centerTextClassColor"] = false,
["leftTextX"] = 0,
["castbarHeight"] = 14,
["btbClassIconX"] = 0,
["castbarClassColored"] = false,
["rightTextClassColor"] = false,
["castDurationColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["castDurationSize"] = 11,
["bottomTextBar"] = false,
["debuffGrowth"] = "auto",
["castSpellNameSize"] = 11,
["leftTextContent"] = "name",
["powerPercentText"] = "none",
["centerTextX"] = 0,
["powerPosition"] = "below",
["btbCenterX"] = 0,
["btbClassIconLocation"] = "left",
["powerHeight"] = 6,
["showCastIcon"] = true,
["btbCenterSize"] = 11,
["btbBgOpacity"] = 1,
["btbY"] = 0,
["btbPosition"] = "bottom",
["powerPercentPowerColor"] = false,
["healthHeight"] = 34,
["detachedPortraitClassColor"] = true,
["btbRightPowerColor"] = false,
["castSpellNameColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["healthDisplay"] = "perhp",
["btbCenterY"] = 0,
["btbLeftContent"] = "none",
["rightTextContent"] = "perhp",
["showSolo"] = true,
["selectedFont"] = "Expressway",
["btbRightClassColor"] = false,
["powerWidth"] = 0,
["btbCenterClassColor"] = false,
["btbLeftX"] = 0,
["btbRightSize"] = 11,
["rightTextSize"] = 12,
["btbClassIconSize"] = 14,
["centerTextSize"] = 12,
["showInParty"] = true,
["powerY"] = 0,
["leftTextSize"] = 12,
["leftTextClassColor"] = false,
["btbRightY"] = 0,
["detachedPortraitBorder"] = true,
["portraitMode"] = "2d",
["btbLeftY"] = 0,
["btbLeftSize"] = 11,
["showInRaid"] = true,
["powerBarOpacity"] = 1,
["frameWidth"] = 160,
["borderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["debuffAnchor"] = "bottomleft",
["frameScale"] = 100,
["bottomTextBarHeight"] = 16,
["btbRightX"] = 0,
["centerTextY"] = 0,
["healthBarTexture"] = "none",
["btbBgColor"] = {
["r"] = 0.2,
["g"] = 0.2,
["b"] = 0.2,
},
["btbCenterPowerColor"] = false,
["detachedPortraitBorderOpacity"] = 100,
["detachedPortraitBorderColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["portraitY"] = 0,
["btbLeftPowerColor"] = false,
["centerTextContent"] = "none",
["borderSize"] = 1,
["showCastbar"] = true,
["healthBarOpacity"] = 0.9,
["powerPercentSize"] = 9,
["showPortrait"] = true,
["powerPercentX"] = 0,
["btbClassIcon"] = "none",
["btbClassIconY"] = 0,
["powerX"] = 0,
["rightTextY"] = 0,
["rightTextX"] = 0,
["btbCenterContent"] = "none",
["castbarFillColor"] = {
["r"] = 0.863,
["g"] = 0.82,
["b"] = 0.639,
},
["detachedPortraitBorderSize"] = 7,
["leftTextY"] = 0,
["classThemeStyle"] = "modern",
["highlightColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["maxDebuffs"] = 10,
["btbWidth"] = 0,
["btbLeftClassColor"] = false,
["btbX"] = 0,
["btbRightContent"] = "none",
["textSize"] = 12,
},
["enabledFrames"] = {
["boss"] = true,
["pet"] = true,
["focus"] = true,
["target"] = true,
["focustarget"] = false,
["targettarget"] = true,
["player"] = true,
},
},
["EllesmereUIResourceBars"] = {
["castBar"] = {
["iconY"] = 0,
["gradientEnabled"] = false,
["borderA"] = 1,
["enabled"] = true,
["gradientG"] = 0.2,
["gradientA"] = 1,
["anchorX"] = 0,
["fillB"] = 0.23,
["borderG"] = 0,
["height"] = 20,
["anchorY"] = -50,
["bgR"] = 0,
["showTimer"] = true,
["borderB"] = 0,
["iconX"] = 0,
["scale"] = 1,
["showSpark"] = true,
["timerY"] = 0,
["borderSize"] = 1,
["showIcon"] = true,
["timerX"] = 0,
["iconSize"] = 20,
["texture"] = "none",
["bgA"] = 0.7,
["timerSize"] = 11,
["gradientR"] = 0.2,
["iconAttach"] = true,
["width"] = 220,
["bgG"] = 0,
["gradientB"] = 0.8,
["gradientDir"] = "HORIZONTAL",
["fillA"] = 1,
["fillR"] = 0.77,
["borderR"] = 0,
["bgB"] = 0,
["fillG"] = 0.12,
},
["health"] = {
["bgR"] = 0.06666666666666667,
["borderB"] = 0,
["scale"] = 1,
["customColored"] = false,
["orientation"] = "HORIZONTAL",
["borderSize"] = 0,
["borderR"] = 0,
["bgB"] = 0.06666666666666667,
["barAlpha"] = 1,
["darkTheme"] = false,
["textSize"] = 11,
["textXOffset"] = 0,
["enabled"] = false,
["textFormat"] = "none",
["fillR"] = 0.77,
["borderG"] = 0,
["fillA"] = 1,
["offsetX"] = 0,
["width"] = 214,
["fillB"] = 0.23,
["bgA"] = 0.75,
["borderA"] = 1,
["textYOffset"] = 0,
["bgG"] = 0.06666666666666667,
["height"] = 16,
["offsetY"] = -64,
["visibility"] = "always",
["fillG"] = 0.12,
},
["primary"] = {
["bgR"] = 0.06666666666666667,
["borderB"] = 0,
["scale"] = 1,
["customColored"] = false,
["orientation"] = "HORIZONTAL",
["borderSize"] = 1,
["borderR"] = 0,
["bgB"] = 0.06666666666666667,
["barAlpha"] = 1,
["darkTheme"] = false,
["textSize"] = 10,
["textXOffset"] = 0,
["enabled"] = true,
["textFormat"] = "perpp",
["fillR"] = 0,
["borderG"] = 0,
["fillA"] = 1,
["offsetX"] = 0,
["width"] = 214,
["fillB"] = 1,
["bgA"] = 0.75,
["borderA"] = 1,
["textYOffset"] = 0,
["bgG"] = 0.06666666666666667,
["height"] = 14,
["offsetY"] = -52,
["visibility"] = "always",
["fillG"] = 0.82,
},
["general"] = {
["anchorX"] = 0,
["orientation"] = "HORIZONTAL",
["barTexture"] = "none",
["unlocked"] = false,
["anchorY"] = -100,
},
["secondary"] = {
["thresholdEnabled"] = false,
["barBgB"] = 0,
["textYOffset"] = 0,
["barBgA"] = 0.5,
["borderA"] = 1,
["offsetX"] = 0,
["classColored"] = true,
["darkTheme"] = false,
["textSize"] = 11,
["enabled"] = true,
["thresholdR"] = 0.04705882352941176,
["thresholdA"] = 1,
["fillB"] = 0.6,
["thresholdB"] = 0.615686274509804,
["showText"] = true,
["borderG"] = 0,
["offsetY"] = -38,
["barAlpha"] = 1,
["bgR"] = 1,
["borderB"] = 0,
["scale"] = 1,
["chargedA"] = 1,
["pipWidth"] = 214,
["borderR"] = 0,
["bgB"] = 1,
["visibility"] = "always",
["borderSize"] = 1,
["pipHeight"] = 20,
["bgA"] = 0.1,
["textXOffset"] = 0,
["fillR"] = 0.95,
["fillA"] = 1,
["chargedB"] = 1,
["thresholdPartialOnly"] = false,
["pipSpacing"] = 1,
["chargedG"] = 0.77,
["thresholdCount"] = 3,
["barBgR"] = 0,
["thresholdG"] = 0.8235294117647058,
["bgG"] = 1,
["barBgG"] = 0,
["chargedR"] = 0.44,
["oocAlpha"] = 1,
["fillG"] = 0.9,
},
},
},
},
},
["fonts"] = {
["outlineMode"] = "shadow",
["global"] = "Expressway",
},
["dismissedConflicts"] = {
},
["customColors"] = {
},
["unlockSnapEnabled"] = true,
["activeProfile"] = "Custom",
}
