
EllesmereUINameplatesDB = {
["hashLineColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textSlotRight"] = "healthPercent",
["topSlotSize"] = 26,
["focusColorEnabled"] = true,
["showFriendlyNPCs"] = false,
["castBarUninterruptible"] = {
["b"] = 0.45,
["g"] = 0.45,
["r"] = 0.45,
},
["leftSlotXOffset"] = 0,
["toprightSlotXOffset"] = 0,
["castBarHeight"] = 17,
["textSlotTop"] = "enemyName",
["auraDurationTextSize"] = 11,
["topleftSlotGrowth"] = "left",
["tapped"] = {
["b"] = 0.5,
["g"] = 0.5,
["r"] = 0.5,
},
["friendlyNameOnlyYOffset"] = -20,
["healthBarTexture"] = "none",
["raidMarkerSize"] = 24,
["nameYOffset"] = 0,
["textSlotRightColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["auraDurationTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textSlotTopXOffset"] = 0,
["classPowerCustomColor"] = {
["b"] = 0.3,
["g"] = 0.84,
["r"] = 1,
},
["topSlotYOffset"] = 0,
["pandemicGlowSpeed"] = 4,
["buffIconSize"] = 24,
["leftSlotSize"] = 24,
["targetGlowStyle"] = "ellesmereui",
["questMobColorEnabled"] = false,
["textSlotTopColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["rightSlotSize"] = 24,
["focusOverlayAlpha"] = 0.4,
["rareEliteIconSize"] = 20,
["classPowerEmptyColor"] = {
["b"] = 0.2,
["g"] = 0.2,
["r"] = 0.2,
},
["classPowerPos"] = "bottom",
["buffTimerPosition"] = "topleft",
["auraStackTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["focusCastHeight"] = 100,
["bottomSlotXOffset"] = 0,
["raidMarkerPos"] = "topright",
["enemyInCombat"] = {
["b"] = 0.137,
["g"] = 0.137,
["r"] = 0.8,
},
["debuffTextWhite"] = false,
["auraStackTextSize"] = 11,
["topSlotXOffset"] = 0,
["toprightSlotSize"] = 24,
["textSlotRightXOffset"] = 0,
["tankHasAggro"] = {
["b"] = 0.62,
["g"] = 0.82,
["r"] = 0.05,
},
["textSlotCenterYOffset"] = 0,
["textSlotRightYOffset"] = 0,
["topleftSlotSize"] = 24,
["textSlotLeft"] = "none",
["castNameSize"] = 10,
["bottomSlotSize"] = 26,
["castIconScale"] = 1,
["enemyNamePos"] = "top",
["rareEliteIconXOffset"] = 0,
["buffTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["ccTimerPosition"] = "topleft",
["friendlyPlateYOffset"] = 0,
["castNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["classPowerXOffset"] = 0,
["kickTickEnabled"] = true,
["targetArrowScale"] = 1,
["castBar"] = {
["b"] = 0.9,
["g"] = 0.4,
["r"] = 0.7,
},
["enemyNameTextSize"] = 11,
["borderColor"] = {
["b"] = 0.067,
["g"] = 0.067,
["r"] = 0.067,
},
["classPowerBgColor"] = {
["b"] = 0.082,
["g"] = 0.082,
["r"] = 0.082,
},
["tankLosingAggro"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["buffSlot"] = "left",
["sideAuraXOffset"] = 2,
["classPowerClassColors"] = true,
["borderStyle"] = "ellesmere",
["tankHasAggroEnabled"] = false,
["pandemicGlow"] = false,
["buffTextSize"] = 12,
["rightSlotXOffset"] = 0,
["textSlotCenterXOffset"] = 0,
["kickTickColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["showFriendlyPlayers"] = true,
["dpsNearAggro"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["enemyNameColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textSlotLeftYOffset"] = 0,
["focus"] = {
["b"] = 0.62,
["g"] = 0.82,
["r"] = 0.051,
},
["toprightSlotGrowth"] = "right",
["textSlotCenterSize"] = 10,
["textSlotTopYOffset"] = 0,
["showTargetGlow"] = true,
["interruptReady"] = {
["b"] = 0.2,
["g"] = 0.35,
["r"] = 0.92,
},
["textSlotLeftSize"] = 10,
["font"] = "Interface\\AddOns\\EllesmereUI\\media\\fonts\\Expressway.TTF",
["questMobColor"] = {
["b"] = 0.475,
["g"] = 0.855,
["r"] = 0.157,
},
["showClassPower"] = false,
["caster"] = {
["b"] = 0.965,
["g"] = 0.51,
["r"] = 0.231,
},
["healthBarWidth"] = 6,
["classPowerGap"] = 2,
["friendlyNameOnly"] = true,
["auraTextPosition"] = "topleft",
["nameplateOverlapV"] = 1.05,
["classColorFriendly"] = true,
["hashLinePercent"] = 30,
["ccSlot"] = "right",
["textSlotTopSize"] = 10,
["leftSlotYOffset"] = 0,
["classPowerYOffset"] = 1,
["debuffTimerPosition"] = "topleft",
["focusOverlayColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["bottomSlotYOffset"] = 0,
["focusOverlayTexture"] = "striped-v2",
["topleftSlotYOffset"] = 0,
["debuffSlot"] = "top",
["auraSpacing"] = 2,
["showTargetArrows"] = false,
["debuffTextPosition"] = "topleft",
["rareEliteIconYOffset"] = 0,
["showEnemyPets"] = false,
["healthTextSize"] = 10,
["pandemicGlowColor"] = {
["b"] = 0.329,
["g"] = 0.8,
["r"] = 1,
},
["showHealthNumber"] = false,
["debuffTimerColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["dpsHasAggro"] = {
["b"] = 0,
["g"] = 0.5,
["r"] = 1,
},
["textSlotCenter"] = "none",
["raidMarkerYOffset"] = 2,
["ccTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["healthBarHeight"] = 17,
["friendlyHealthBarHeight"] = 17,
["healthTextColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["friendlyShowDefaultNames"] = false,
["tankNoAggro"] = {
["b"] = 0.17,
["g"] = 0.22,
["r"] = 1,
},
["ccTextSize"] = 12,
["classificationSlot"] = "topleft",
["castScale"] = 100,
["castTargetSize"] = 10,
["castTargetClassColor"] = true,
["castTargetColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["nameplateYOffset"] = 0,
["hpPercentPos"] = "right",
["pandemicGlowLines"] = 8,
["hostile"] = {
["b"] = 0.09,
["g"] = 0.11,
["r"] = 0.39,
},
["hashLineEnabled"] = false,
["friendlyHealthBarWidth"] = 150,
["debuffIconSize"] = 26,
["rightSlotYOffset"] = 0,
["pandemicGlowThickness"] = 1,
["textSlotLeftColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textSlotLeftXOffset"] = 0,
["textSlotRightSize"] = 10,
["neutral"] = {
["b"] = 0.19,
["g"] = 0.72,
["r"] = 0.81,
},
["hpNumberPos"] = "none",
["showCastIcon"] = true,
["showAllDebuffs"] = false,
["toprightSlotYOffset"] = 0,
["classPowerScale"] = 1,
["topleftSlotXOffset"] = 0,
["pandemicGlowStyle"] = 1,
["debuffYOffset"] = 2,
["miniboss"] = {
["b"] = 0.984,
["g"] = 0.243,
["r"] = 0.518,
},
["stackSpacingScale"] = 100,
["ccIconSize"] = 24,
["textSlotCenterColor"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
}
