
GFW_FactionFriend_DB = {
	["profileKeys"] = {
		["Boringrivers - Korgath"] = "Default",
		["Rapidrivers - Arthas"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Treesurgeon - Korgath"] = "Default",
		["Yandanderex - Moon Guard"] = "Default",
		["Mindrivers - Korgath"] = "Default",
		["Bittydots - Korgath"] = "Default",
		["Sacredrivers - Korgath"] = "Default",
		["Emptyrivers - Korgath"] = "Default",
		["Wildrivers - Korgath"] = "Default",
		["Teenybubbles - Madoran"] = "Default",
		["Deadrivers - Korgath"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
		["Hulyon - Kel'Thuzad"] = "Default",
		["Littlerivers - Kel'Thuzad"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Spicydremer - Korgath"] = "Default",
		["Caladiir - Kel'Thuzad"] = "Default",
		["Hiddenrivers - Korgath"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Elakai - Korgath"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Blindrivers - Korgath"] = "Default",
		["Evilrivers - Korgath"] = "Default",
		["Notariver - Arthas"] = "Default",
		["Edgyrivers - Kel'Thuzad"] = "Default",
		["Tinyrivers - Arthas"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Sneakyrivers - Korgath"] = "Default",
		["Angryrivers - Korgath"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Sassyrivers - Arthas"] = "Default",
		["Beefyrivers - Thrall"] = "Default",
		["Toofattohide - Kel'Thuzad"] = "Default",
		["Serenerivers - Korgath"] = "Default",
		["Smaz - Mug'thol"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Brightrivers - Korgath"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Luckyrivers - Korgath"] = "Default",
		["Magicrivers - Korgath"] = "Default",
		["Imnotamonk - Korgath"] = "Default",
		["Serenerivers - Arthas"] = "Default",
		["Skankyrivers - Arthas"] = "Default",
		["Elakai - Kel'Thuzad"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["MoveExaltedInactive"] = true,
			["ReputationColors"] = true,
			["NoGuildAutoswitch"] = true,
			["CountRepeatGains"] = true,
		},
	},
}
