
HandyNotes_TheWarWithinDB = {
["profileKeys"] = {
["Strid - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["icon_display_back_to_the_wall"] = false,
["icon_display_lost_and_found"] = false,
["icon_display_smelling_history"] = false,
["icon_display_mereldar_menace"] = false,
["icon_display_biblo_archivist"] = false,
["icon_display_missing_lynx"] = false,
["icon_alpha_profession_treasures"] = 1,
["icon_display_vendors"] = false,
["show_rep_rewards"] = false,
["icon_display_misc"] = true,
["icon_display_pet_battles"] = false,
["hide_done_rares"] = true,
["icon_display_khaz_algar_lore_hunter"] = false,
["icon_display_beacon_of_hope"] = false,
["icon_display_delve_rewards"] = false,
["icon_display_rocked_to_sleep"] = false,
["icon_display_no_harm_from_reading"] = true,
["icon_display_notable_machines"] = false,
["hide_done_treasures"] = true,
["icon_display_not_so_quick_fix"] = false,
["icon_display_disturbed_earth"] = true,
["icon_display_rares"] = true,
["icon_display_treasures"] = true,
["icon_display_profession_treasures"] = false,
["icon_display_itsy_bitsy_spider"] = true,
["icon_scale_profession_treasures"] = 1,
["icon_display_for_the_collective"] = true,
["icon_display_flamegards_hope"] = true,
["icon_display_critter_love"] = false,
["icon_display_skittershaw_spin"] = true,
},
},
}
