
HandyNotes_TheWarWithinDB = {
["profileKeys"] = {
["Alluvium - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["icon_display_pet_battles"] = false,
["icon_display_vendors"] = true,
["show_rep_rewards"] = false,
["show_completed_nodes"] = true,
["hide_done_rares"] = true,
["icon_display_delve_rewards"] = true,
["icon_scale_profession_treasures"] = 1,
["hide_done_treasures"] = true,
["icon_display_disturbed_earth"] = false,
["icon_display_rares"] = true,
["icon_display_treasures"] = true,
["icon_display_profession_treasures"] = false,
["icon_alpha_profession_treasures"] = 1,
["icon_display_misc"] = false,
},
},
}
