
HandyNotes_ShadowlandsDB = {
["profileKeys"] = {
["Loess - Kel'Thuzad"] = "Default",
["Dukasuka - Eredar"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Doneer - Eredar"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Darick - Eredar"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Dannius - Argent Dawn"] = "Default",
["Rosefin - Argent Dawn"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Roberia - Eredar"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["icon_display_hymns"] = true,
["icon_display_blessings"] = true,
["icon_display_squirrels"] = true,
["icon_display_vespers"] = true,
["icon_display_safari"] = true,
["icon_display_anima_shard"] = true,
},
},
}
