
iEETConfig = {
	["autoSave"] = true,
	["version"] = 1.606,
	["autoDiscard"] = 600,
	["filtering"] = {
		["requireAll"] = false,
		["showTime"] = false,
		["timeBasedFiltering"] = {
		},
		["req"] = {
		},
	},
	["colors"] = {
		["main"] = {
			["bg"] = {
				["a"] = 0.9,
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 0.1,
			},
			["border"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0,
			},
		},
		["options"] = {
			["bg"] = {
				["a"] = 0.9,
				["b"] = 0.1,
				["g"] = 0.1,
				["r"] = 0.1,
			},
			["border"] = {
				["a"] = 1,
				["b"] = 0,
				["g"] = 0,
				["r"] = 0.64,
			},
		},
	},
	["tracking"] = {
		["SPELL_PERIODIC_CAST_FAILED"] = true,
		["SPELL_SUMMON"] = true,
		["SPELL_AURA_REMOVED"] = true,
		["UNIT_SPELLCAST_CHANNEL_START"] = true,
		["SPELL_PERIODIC_CAST_SUCCESS"] = true,
		["UNIT_SPELLCAST_INTERRUPTIBLE"] = true,
		["SPELL_PERIODIC_AURA_APPLIED"] = true,
		["UNIT_DIED"] = true,
		["UNIT_SPELLCAST_SUCCEEDED"] = true,
		["SPELL_PERIODIC_AURA_REMOVED_DOSE"] = true,
		["SPELL_PERIODIC_AURA_REMOVED"] = true,
		["SPELL_PERIODIC_HEAL"] = true,
		["SPELL_PERIODIC_SUMMON"] = true,
		["SPELL_AURA_APPLIED"] = true,
		["SPELL_DISPEL"] = true,
		["SPELL_PERIODIC_CAST_START"] = true,
		["SPELL_AURA_APPLIED_DOSE"] = true,
		["SPELL_CAST_START"] = true,
		["UNIT_POWER"] = true,
		["UNIT_SPELLCAST_START"] = true,
		["PLAYER_REGEN_DISABLED"] = true,
		["MANUAL_LOGGING_START"] = true,
		["MANUAL_LOGGING_END"] = true,
		["PLAYER_REGEN_ENABLED"] = true,
		["SPELL_AURA_REFRESH"] = true,
		["RAID_BOSS_EMOTE"] = true,
		["RAID_BOSS_WHISPER"] = true,
		["SPELL_PERIODIC_AURA_REFRESH"] = true,
		["ENCOUNTER_END"] = true,
		["SPELL_CAST_FAILED"] = true,
		["SPELL_AURA_REMOVED_DOSE"] = true,
		["ENCOUNTER_START"] = true,
		["INSTANCE_ENCOUNTER_ENGAGE_UNIT"] = true,
		["UNIT_TARGET"] = true,
		["SPELL_PERIODIC_AURA_APPLIED_DOSE"] = true,
		["MONSTER_SAY"] = true,
		["MONSTER_EMOTE"] = true,
		["SPELL_CREATE"] = true,
		["SPELL_CAST_SUCCESS"] = true,
		["SPELL_HEAL"] = true,
		["UNIT_SPELLCAST_NOT_INTERRUPTIBLE"] = true,
		["MONSTER_YELL"] = true,
		["SPELL_PERIODIC_CREATE"] = true,
		["SPELL_INTERRUPT"] = true,
	},
	["classColors"] = false,
}
iEET_Data = {
}
iEET_ExportFromWTF = nil
