
KeystonePercentageHelperDB = nil
KeystonePolarisDB = {
["profileKeys"] = {
["Seep - Kel'Thuzad"] = "Default",
["Mire - Mal'Ganis"] = "Default",
["Cirque - Kel'Thuzad"] = "Default",
["Docks - Kel'Thuzad"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Rapids - Argent Dawn"] = "Default",
["Quag - Argent Dawn"] = "Default",
["Slush - Mal'Ganis"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Moraine - Kel'Thuzad"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Brack - Mal'Ganis"] = "Default",
["Surge - Argent Dawn"] = "Default",
["Geyser - Mal'Ganis"] = "Default",
["Falls - Mal'Ganis"] = "Default",
["Spume - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Baffle - Mal'Ganis"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Lather - Mal'Ganis"] = "Default",
["Rime - Kel'Thuzad"] = "Default",
["Rill - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Brook - Argent Dawn"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Rivulet - Mal'Ganis"] = "Default",
["Fjord - Mal'Ganis"] = "Default",
["Floe - Mal'Ganis"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Bog - Kel'Thuzad"] = "Default",
},
["profiles"] = {
["Default"] = {
["lastSeasonCheck"] = "2026-04-15",
["groupReminder"] = {
["showPlaystyle"] = true,
["popupXOffset"] = 404.8822631835938,
["showPopupWhenGroupIsFull"] = true,
["popupYOffset"] = 378.5914306640625,
},
["text"] = {
["font"] = "Fira Sans Condensed Black",
},
["general"] = {
["minimap"] = {
["minimapPos"] = 225,
["showInCompartment"] = true,
["hide"] = false,
},
["positioningShowGrid"] = true,
["mobPercentagesMigrationVersion"] = "3.8",
["lastVersionCheck"] = "3.8-fix1",
["yOffset"] = -521.3140335083008,
},
},
},
}
