
MuteSoundFileDB = {
["profileKeys"] = {
["Loess - Kel'Thuzad"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["soundList"] = {
["raid warning"] = 567397,
},
},
},
}
