
MuteSoundFileDB = {
["profileKeys"] = {
["Seep - Kel'Thuzad"] = "Default",
["Loess - Kel'Thuzad"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Docks - Kel'Thuzad"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Slush - Mal'Ganis"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Bog - Kel'Thuzad"] = "Default",
["Brack - Mal'Ganis"] = "Default",
["Mire - Mal'Ganis"] = "Default",
["Surge - Argent Dawn"] = "Default",
["Geyser - Mal'Ganis"] = "Default",
["Rime - Kel'Thuzad"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Falls - Mal'Ganis"] = "Default",
["Rivulet - Mal'Ganis"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Quag - Argent Dawn"] = "Default",
["Rapids - Argent Dawn"] = "Default",
["Cirque - Kel'Thuzad"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Spume - Argent Dawn"] = "Default",
["Brook - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Fjord - Mal'Ganis"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Baffle - Mal'Ganis"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Lather - Mal'Ganis"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Rill - Kel'Thuzad"] = "Default",
["Moraine - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Floe - Mal'Ganis"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["soundList"] = {
["raid warning"] = 567397,
},
},
},
}
