
MythicPlusTweaksDB = {
["inlineConfig"] = false,
["modules"] = {
["ImproveKeystoneLink"] = true,
["PartyRating"] = true,
["SortDungeonIcons"] = true,
["DungeonIconTooltip"] = true,
["MistHelperSync"] = true,
["DungeonIconText"] = true,
["AlwaysShowAffixes"] = true,
["KeystoneSharing-core"] = true,
["ShowOwnRatingOnLFGTooltip"] = true,
["DungeonTeleports"] = true,
["miscQoL"] = true,
["ShowScoreOnKeystoneTooltip"] = true,
},
["moduleDb"] = {
["ImproveKeystoneLink"] = {
},
["PartyRating"] = {
["showZeroScoreDungeons"] = true,
["sortMode"] = "score",
},
["SortDungeonIcons"] = {
["sortStyle"] = "overall_score",
["sortDirection"] = "desc",
},
["DungeonIconTooltip"] = {
["showPartyScore"] = true,
["showMapID"] = true,
},
["DungeonScoreTooltipFix"] = {
},
["DungeonIconText"] = {
["dash"] = false,
["name"] = "middle",
["hideSeasonBest"] = false,
},
["MistHelperSync"] = {
},
["AlwaysShowAffixes"] = {
},
["KeystoneSharing-core"] = {
["modules"] = {
["KeystoneSharing-AstralKeys"] = true,
["KeystoneSharing-AngryKeystones"] = true,
},
["moduleDB"] = {
["KeystoneSharing-AstralKeys"] = {
},
["KeystoneSharing-AngryKeystones"] = {
},
},
["altStore"] = {
["Kel'Thuzad"] = {
["Remaxxing"] = {
["mapID"] = 0,
["week"] = 456,
["name"] = "Remaxxing",
["faction"] = "Alliance",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 451211,
["weeklyBest"] = 0,
},
["Cascades"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Cascades",
["faction"] = "Alliance",
["class"] = "DEMONHUNTER",
["level"] = 0,
["timestamp"] = 369882,
["weeklyBest"] = 0,
},
["Talamahyn"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Talamahyn",
["faction"] = "Horde",
["class"] = "SHAMAN",
["level"] = 0,
["timestamp"] = 116674,
["weeklyBest"] = 0,
},
["Flumes"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Flumes",
["faction"] = "Horde",
["timestamp"] = 114686,
["class"] = "SHAMAN",
["level"] = 0,
["weeklyBest"] = 0,
},
["Neva"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Neva",
["faction"] = "Horde",
["class"] = "HUNTER",
["level"] = 0,
["timestamp"] = 361929,
["weeklyBest"] = 0,
},
["Rime"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Rime",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 366356,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
},
["Moraine"] = {
["mapID"] = 0,
["week"] = 467,
["name"] = "Moraine",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 376724,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Loess"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Loess",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 362012,
["class"] = "MAGE",
["weeklyBest"] = 0,
},
["Glaciers"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Glaciers",
["faction"] = "Horde",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 114187,
["weeklyBest"] = 0,
},
["Cirque"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Cirque",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 350407,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Aquifer"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Aquifer",
["faction"] = "Horde",
["timestamp"] = 115557,
["class"] = "ROGUE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Shoal"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Shoal",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 115944,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
},
["Seep"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Seep",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 114615,
["class"] = "MONK",
["weeklyBest"] = 0,
},
["Meander"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Meander",
["faction"] = "Alliance",
["timestamp"] = 114125,
["class"] = "PALADIN",
["level"] = 0,
["weeklyBest"] = 0,
},
["Dussrasande"] = {
["mapID"] = 0,
["week"] = 433,
["name"] = "Dussrasande",
["faction"] = "Horde",
["timestamp"] = 195670,
["class"] = "MAGE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Asperse"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Asperse",
["faction"] = "Alliance",
["class"] = "PRIEST",
["level"] = 0,
["timestamp"] = 361578,
["weeklyBest"] = 0,
},
["Bayou"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Bayou",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 114250,
["class"] = "HUNTER",
["weeklyBest"] = 0,
},
["Weir"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Weir",
["faction"] = "Alliance",
["class"] = "DRUID",
["level"] = 0,
["timestamp"] = 114753,
["weeklyBest"] = 0,
},
["Temprivers"] = {
["week"] = 433,
["mapID"] = 0,
["name"] = "Temprivers",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 196332,
["class"] = "DEATHKNIGHT",
["weeklyBest"] = 0,
},
["Gelae"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Gelae",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 361174,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Docks"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Docks",
["faction"] = "Horde",
["class"] = "DRUID",
["level"] = 0,
["timestamp"] = 114010,
["weeklyBest"] = 0,
},
["Gyre"] = {
["week"] = 468,
["mapID"] = 0,
["name"] = "Gyre",
["faction"] = "Alliance",
["timestamp"] = 43409,
["class"] = "DEATHKNIGHT",
["level"] = 0,
["weeklyBest"] = 0,
},
["Rill"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Rill",
["faction"] = "Alliance",
["timestamp"] = 114301,
["class"] = "MAGE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Virga"] = {
["mapID"] = 0,
["week"] = 449,
["name"] = "Virga",
["faction"] = "Horde",
["timestamp"] = 206160,
["class"] = "EVOKER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Esker"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "WARRIOR",
["weeklyBest"] = 0,
["week"] = 467,
["name"] = "Esker",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 368645,
},
["Geosmin"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Geosmin",
["faction"] = "Alliance",
["class"] = "MONK",
["level"] = 0,
["timestamp"] = 114354,
["weeklyBest"] = 0,
},
["Bog"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Bog",
["faction"] = "Horde",
["class"] = "EVOKER",
["level"] = 0,
["timestamp"] = 114569,
["weeklyBest"] = 0,
},
},
["Mal'Ganis"] = {
["Fjord"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Fjord",
["faction"] = "Alliance",
["timestamp"] = 115343,
["class"] = "HUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Geyser"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Geyser",
["faction"] = "Horde",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 115865,
["weeklyBest"] = 0,
},
["Lather"] = {
["week"] = 467,
["mapID"] = 0,
["name"] = "Lather",
["faction"] = "Horde",
["timestamp"] = 384765,
["class"] = "SHAMAN",
["level"] = 0,
["weeklyBest"] = 0,
},
["Falls"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Falls",
["faction"] = "Alliance",
["class"] = "DEMONHUNTER",
["level"] = 0,
["timestamp"] = 361169,
["weeklyBest"] = 0,
},
["Mire"] = {
["mapID"] = 0,
["class"] = "EVOKER",
["weeklyBest"] = 0,
["week"] = 468,
["name"] = "Mire",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 303819,
},
["Baffle"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Baffle",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 114812,
["class"] = "DRUID",
["weeklyBest"] = 0,
},
["Floe"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Floe",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 113796,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Rivulet"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Rivulet",
["faction"] = "Alliance",
["class"] = "PALADIN",
["level"] = 0,
["timestamp"] = 130140,
["weeklyBest"] = 0,
},
["Slush"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Slush",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 117649,
["class"] = "ROGUE",
["weeklyBest"] = 0,
},
["Brack"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Brack",
["faction"] = "Horde",
["timestamp"] = 115800,
["class"] = "DEATHKNIGHT",
["level"] = 0,
["weeklyBest"] = 0,
},
["Bwaagh"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Bwaagh",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 342050,
["class"] = "SHAMAN",
["weeklyBest"] = 0,
},
},
["Feathermoon"] = {
["Bwaagh"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Bwaagh",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 381511,
["class"] = "SHAMAN",
["weeklyBest"] = 0,
},
},
["Argent Dawn"] = {
["Quag"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Quag",
["faction"] = "Alliance",
["class"] = "EVOKER",
["level"] = 0,
["timestamp"] = 377815,
["weeklyBest"] = 0,
},
["Sverdrup"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Sverdrup",
["faction"] = "Horde",
["timestamp"] = 360277,
["class"] = "MONK",
["level"] = 0,
["weeklyBest"] = 0,
},
["Mangrove"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Mangrove",
["faction"] = "Alliance",
["class"] = "DRUID",
["level"] = 0,
["timestamp"] = 117507,
["weeklyBest"] = 0,
},
["Levee"] = {
["week"] = 467,
["mapID"] = 0,
["name"] = "Levee",
["faction"] = "Alliance",
["timestamp"] = 552311,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
["Surge"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Surge",
["faction"] = "Horde",
["timestamp"] = 314600,
["class"] = "MONK",
["level"] = 0,
["weeklyBest"] = 0,
},
["Riptides"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "SHAMAN",
["weeklyBest"] = 0,
["week"] = 467,
["name"] = "Riptides",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 484581,
},
["Cataracts"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "DEMONHUNTER",
["weeklyBest"] = 0,
["week"] = 467,
["name"] = "Cataracts",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 458515,
},
["Alluvium"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Alluvium",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 360769,
["class"] = "EVOKER",
["weeklyBest"] = 0,
},
["Emptyrivers"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Emptyrivers",
["faction"] = "Horde",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 440962,
["weeklyBest"] = 0,
},
["Benthos"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Benthos",
["faction"] = "Horde",
["class"] = "DEATHKNIGHT",
["level"] = 0,
["timestamp"] = 361073,
["weeklyBest"] = 0,
},
["Rapids"] = {
["mapID"] = 557,
["guild"] = "House Stalwart",
["class"] = "WARLOCK",
["weeklyBest"] = 0,
["week"] = 468,
["name"] = "Rapids",
["faction"] = "Alliance",
["level"] = 13,
["timestamp"] = 129416,
},
["Brine"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Brine",
["faction"] = "Horde",
["class"] = "DEATHKNIGHT",
["level"] = 0,
["timestamp"] = 115419,
["weeklyBest"] = 0,
},
["Confluence"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "PALADIN",
["weeklyBest"] = 0,
["week"] = 466,
["name"] = "Confluence",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 113245,
},
["Fathom"] = {
["mapID"] = 0,
["week"] = 467,
["name"] = "Fathom",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 521299,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Riparium"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Riparium",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 360220,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
},
["Estuary"] = {
["mapID"] = 0,
["week"] = 467,
["name"] = "Estuary",
["faction"] = "Alliance",
["class"] = "ROGUE",
["level"] = 0,
["timestamp"] = 553160,
["weeklyBest"] = 0,
},
["Brook"] = {
["mapID"] = 0,
["week"] = 466,
["name"] = "Brook",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 115484,
["class"] = "MAGE",
["weeklyBest"] = 0,
},
["Spume"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Spume",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 119805,
["class"] = "WARRIOR",
["weeklyBest"] = 0,
},
["Stream"] = {
["week"] = 466,
["mapID"] = 0,
["name"] = "Stream",
["faction"] = "Horde",
["timestamp"] = 115112,
["class"] = "HUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
},
},
["shareAlts"] = true,
},
["miscQoL"] = {
["respondToGuild"] = true,
["autoSlotKeystone"] = true,
["groupFormedMessage"] = true,
["groupFormedMessageKeystoneOnly"] = true,
["respondToRaid"] = true,
["removeHoverBlockFromLFGApplicationViewer"] = true,
["respondToParty"] = true,
},
["ShowOwnRatingOnLFGTooltip"] = {
},
["DungeonTeleports"] = {
["mage_teleport"] = "main_on_cooldown",
["hearthstone"] = "main_on_cooldown",
["teleportOnKeystoneCtrlClick"] = true,
["toy"] = "main_on_cooldown",
["shuffleSharedCooldown"] = true,
["showAlternates"] = true,
["dungeon_portal"] = "main_unknown",
},
["ShowScoreOnKeystoneTooltip"] = {
},
},
}
