
MythicPlusTweaksDB = {
["inlineConfig"] = false,
["moduleDb"] = {
["ImproveKeystoneLink"] = {
},
["PartyRating"] = {
["showZeroScoreDungeons"] = true,
["sortMode"] = "score",
},
["SortDungeonIcons"] = {
["sortStyle"] = "overall_score",
["sortDirection"] = "desc",
},
["DungeonIconTooltip"] = {
["showPartyScore"] = true,
["showMapID"] = true,
},
["DungeonScoreTooltipFix"] = {
},
["DungeonIconText"] = {
["dash"] = false,
["name"] = "middle",
["hideSeasonBest"] = false,
},
["MistHelperSync"] = {
},
["AlwaysShowAffixes"] = {
},
["KeystoneSharing-core"] = {
["modules"] = {
["KeystoneSharing-AstralKeys"] = true,
["KeystoneSharing-AngryKeystones"] = true,
},
["moduleDB"] = {
["KeystoneSharing-AstralKeys"] = {
},
["KeystoneSharing-AngryKeystones"] = {
},
},
["altStore"] = {
["Kel'Thuzad"] = {
["Remaxxing"] = {
["week"] = 434,
["mapID"] = 0,
["name"] = "Remaxxing",
["faction"] = "Alliance",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 490560,
["weeklyBest"] = 0,
},
["Cascades"] = {
["week"] = 445,
["mapID"] = 0,
["name"] = "Cascades",
["faction"] = "Alliance",
["class"] = "DEMONHUNTER",
["level"] = 0,
["timestamp"] = 375794,
["weeklyBest"] = 0,
},
["Flumes"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "SHAMAN",
["weeklyBest"] = 0,
["week"] = 443,
["name"] = "Flumes",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 272512,
},
["Neva"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Neva",
["faction"] = "Horde",
["timestamp"] = 136413,
["class"] = "HUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Loess"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Loess",
["faction"] = "Alliance",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 136233,
["weeklyBest"] = 0,
},
["Shoal"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Shoal",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 136109,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
},
["Aquifer"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Aquifer",
["faction"] = "Horde",
["class"] = "ROGUE",
["level"] = 0,
["timestamp"] = 136534,
["weeklyBest"] = 0,
},
["Meander"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Meander",
["faction"] = "Alliance",
["class"] = "PALADIN",
["level"] = 0,
["timestamp"] = 136035,
["weeklyBest"] = 0,
},
["Asperse"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Asperse",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 382098,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Dussrasande"] = {
["week"] = 433,
["mapID"] = 0,
["name"] = "Dussrasande",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 195670,
["class"] = "MAGE",
["weeklyBest"] = 0,
},
["Gelae"] = {
["week"] = 428,
["mapID"] = 0,
["name"] = "Gelae",
["faction"] = "Horde",
["class"] = "PRIEST",
["level"] = 0,
["timestamp"] = 531993,
["weeklyBest"] = 0,
},
["Virga"] = {
["week"] = 445,
["mapID"] = 0,
["name"] = "Virga",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 458775,
["class"] = "EVOKER",
["weeklyBest"] = 0,
},
["Temprivers"] = {
["mapID"] = 0,
["week"] = 433,
["name"] = "Temprivers",
["faction"] = "Alliance",
["class"] = "DEATHKNIGHT",
["level"] = 0,
["timestamp"] = 196332,
["weeklyBest"] = 0,
},
["Gyre"] = {
["mapID"] = 0,
["week"] = 441,
["name"] = "Gyre",
["faction"] = "Alliance",
["timestamp"] = 518486,
["class"] = "DEATHKNIGHT",
["level"] = 0,
["weeklyBest"] = 0,
},
["Geosmin"] = {
["mapID"] = 0,
["week"] = 441,
["name"] = "Geosmin",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 523557,
["class"] = "MONK",
["weeklyBest"] = 0,
},
["Weir"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Weir",
["faction"] = "Alliance",
["timestamp"] = 136176,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
["Esker"] = {
["mapID"] = 0,
["week"] = 439,
["name"] = "Esker",
["faction"] = "Horde",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 41134,
["weeklyBest"] = 0,
},
["Glaciers"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Glaciers",
["faction"] = "Horde",
["timestamp"] = 136724,
["class"] = "WARRIOR",
["level"] = 0,
["weeklyBest"] = 0,
},
},
["Argent Dawn"] = {
["Sverdrup"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Sverdrup",
["faction"] = "Horde",
["class"] = "MONK",
["level"] = 0,
["timestamp"] = 560978,
["weeklyBest"] = 0,
},
["Mangrove"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "DRUID",
["weeklyBest"] = 0,
["week"] = 428,
["name"] = "Mangrove",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 525707,
},
["Benthos"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Benthos",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 556271,
["class"] = "DEATHKNIGHT",
["weeklyBest"] = 0,
},
["Confluence"] = {
["mapID"] = 0,
["guild"] = "House Stalwart",
["class"] = "PALADIN",
["weeklyBest"] = 0,
["week"] = 444,
["name"] = "Confluence",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 213278,
},
["Stream"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Stream",
["faction"] = "Horde",
["timestamp"] = 573435,
["class"] = "HUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Riptides"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Riptides",
["faction"] = "Alliance",
["timestamp"] = 563072,
["class"] = "SHAMAN",
["level"] = 0,
["weeklyBest"] = 0,
},
["Riparium"] = {
["mapID"] = 0,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
["week"] = 448,
["name"] = "Riparium",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 530132,
},
["Estuary"] = {
["week"] = 438,
["mapID"] = 0,
["name"] = "Estuary",
["faction"] = "Alliance",
["class"] = "ROGUE",
["level"] = 0,
["timestamp"] = 573758,
["weeklyBest"] = 0,
},
["Cataracts"] = {
["week"] = 428,
["mapID"] = 0,
["name"] = "Cataracts",
["faction"] = "Horde",
["timestamp"] = 533600,
["class"] = "DEMONHUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Alluvium"] = {
["mapID"] = 0,
["week"] = 438,
["name"] = "Alluvium",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 574267,
["class"] = "EVOKER",
["weeklyBest"] = 0,
},
["Emptyrivers"] = {
["mapID"] = 0,
["week"] = 428,
["name"] = "Emptyrivers",
["faction"] = "Horde",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 523751,
["weeklyBest"] = 0,
},
},
},
["shareAlts"] = true,
},
["DungeonTeleports"] = {
["dungeon_portal"] = "main_unknown",
["showAlternates"] = true,
["hearthstone"] = "main_on_cooldown",
["toy"] = "main_on_cooldown",
["shuffleSharedCooldown"] = true,
["teleportOnKeystoneCtrlClick"] = true,
["mage_teleport"] = "main_on_cooldown",
},
["ShowOwnRatingOnLFGTooltip"] = {
},
["miscQoL"] = {
["respondToGuild"] = true,
["groupFormedMessageKeystoneOnly"] = true,
["groupFormedMessage"] = true,
["respondToParty"] = true,
["respondToRaid"] = true,
["removeHoverBlockFromLFGApplicationViewer"] = true,
["autoSlotKeystone"] = true,
},
["ShowScoreOnKeystoneTooltip"] = {
},
},
["modules"] = {
["ImproveKeystoneLink"] = true,
["PartyRating"] = true,
["SortDungeonIcons"] = true,
["DungeonIconTooltip"] = true,
["MistHelperSync"] = true,
["DungeonIconText"] = true,
["AlwaysShowAffixes"] = true,
["KeystoneSharing-core"] = true,
["ShowOwnRatingOnLFGTooltip"] = true,
["miscQoL"] = true,
["DungeonTeleports"] = true,
["ShowScoreOnKeystoneTooltip"] = true,
},
}
