
MythicPlusTweaksDB = {
["inlineConfig"] = false,
["moduleDb"] = {
["ImproveKeystoneLink"] = {
},
["PartyRating"] = {
["showZeroScoreDungeons"] = true,
["sortMode"] = "score",
},
["SortDungeonIcons"] = {
["sortStyle"] = "overall_score",
["sortDirection"] = "desc",
},
["DungeonIconTooltip"] = {
["showPartyScore"] = true,
["showMapID"] = true,
},
["DungeonScoreTooltipFix"] = {
},
["DungeonIconText"] = {
["dash"] = false,
["name"] = "middle",
["hideSeasonBest"] = false,
},
["MistHelperSync"] = {
},
["AlwaysShowAffixes"] = {
},
["KeystoneSharing-core"] = {
["modules"] = {
["KeystoneSharing-AstralKeys"] = true,
["KeystoneSharing-AngryKeystones"] = true,
},
["moduleDB"] = {
["KeystoneSharing-AstralKeys"] = {
},
["KeystoneSharing-AngryKeystones"] = {
},
},
["altStore"] = {
["Kel'Thuzad"] = {
["Remaxxing"] = {
["week"] = 456,
["mapID"] = 0,
["name"] = "Remaxxing",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 451211,
["class"] = "WARRIOR",
["weeklyBest"] = 0,
},
["Cascades"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Cascades",
["faction"] = "Alliance",
["timestamp"] = 361716,
["class"] = "DEMONHUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Flumes"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Flumes",
["faction"] = "Horde",
["class"] = "SHAMAN",
["level"] = 0,
["timestamp"] = 359463,
["weeklyBest"] = 0,
},
["Neva"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Neva",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 361929,
["class"] = "HUNTER",
["weeklyBest"] = 0,
},
["Rime"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Rime",
["faction"] = "Alliance",
["class"] = "WARLOCK",
["level"] = 0,
["timestamp"] = 434940,
["weeklyBest"] = 0,
},
["Moraine"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Moraine",
["faction"] = "Alliance",
["timestamp"] = 556721,
["class"] = "PRIEST",
["level"] = 0,
["weeklyBest"] = 0,
},
["Loess"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Loess",
["faction"] = "Alliance",
["timestamp"] = 362012,
["class"] = "MAGE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Bog"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Bog",
["faction"] = "Horde",
["class"] = "EVOKER",
["level"] = 0,
["timestamp"] = 377039,
["weeklyBest"] = 0,
},
["Geosmin"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Geosmin",
["faction"] = "Alliance",
["timestamp"] = 368486,
["class"] = "MONK",
["level"] = 0,
["weeklyBest"] = 0,
},
["Shoal"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Shoal",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 377485,
["class"] = "WARLOCK",
["weeklyBest"] = 0,
},
["Seep"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Seep",
["faction"] = "Alliance",
["class"] = "MONK",
["level"] = 0,
["timestamp"] = 473318,
["weeklyBest"] = 0,
},
["Meander"] = {
["timestamp"] = 560686,
["mapID"] = 0,
["name"] = "Meander",
["faction"] = "Alliance",
["level"] = 0,
["class"] = "PALADIN",
["week"] = 458,
["weeklyBest"] = 0,
},
["Esker"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Esker",
["faction"] = "Horde",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 558900,
["weeklyBest"] = 0,
},
["Asperse"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Asperse",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 361578,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Dussrasande"] = {
["week"] = 433,
["mapID"] = 0,
["name"] = "Dussrasande",
["faction"] = "Horde",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 195670,
["weeklyBest"] = 0,
},
["Virga"] = {
["week"] = 449,
["mapID"] = 0,
["name"] = "Virga",
["faction"] = "Horde",
["class"] = "EVOKER",
["level"] = 0,
["timestamp"] = 206160,
["weeklyBest"] = 0,
},
["Temprivers"] = {
["mapID"] = 0,
["week"] = 433,
["name"] = "Temprivers",
["faction"] = "Alliance",
["timestamp"] = 196332,
["class"] = "DEATHKNIGHT",
["level"] = 0,
["weeklyBest"] = 0,
},
["Gelae"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Gelae",
["faction"] = "Horde",
["timestamp"] = 361174,
["class"] = "PRIEST",
["level"] = 0,
["weeklyBest"] = 0,
},
["Docks"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Docks",
["faction"] = "Horde",
["timestamp"] = 472970,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
["Gyre"] = {
["mapID"] = 556,
["class"] = "DEATHKNIGHT",
["weeklyBest"] = 15,
["week"] = 458,
["name"] = "Gyre",
["faction"] = "Alliance",
["level"] = 14,
["timestamp"] = 569840,
},
["Rill"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Rill",
["faction"] = "Alliance",
["timestamp"] = 554943,
["class"] = "MAGE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Weir"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Weir",
["faction"] = "Alliance",
["timestamp"] = 474397,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
["Cirque"] = {
["level"] = 0,
["mapID"] = 0,
["name"] = "Cirque",
["faction"] = "Horde",
["week"] = 458,
["timestamp"] = 560010,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Aquifer"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Aquifer",
["faction"] = "Horde",
["class"] = "ROGUE",
["level"] = 0,
["timestamp"] = 377685,
["weeklyBest"] = 0,
},
["Glaciers"] = {
["mapID"] = 0,
["week"] = 457,
["name"] = "Glaciers",
["faction"] = "Horde",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 360320,
["weeklyBest"] = 0,
},
},
["Mal'Ganis"] = {
["Fjord"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Fjord",
["faction"] = "Alliance",
["class"] = "HUNTER",
["level"] = 0,
["timestamp"] = 289318,
["weeklyBest"] = 0,
},
["Geyser"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Geyser",
["faction"] = "Horde",
["class"] = "MAGE",
["level"] = 0,
["timestamp"] = 549719,
["weeklyBest"] = 0,
},
["Lather"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Lather",
["faction"] = "Horde",
["timestamp"] = 547344,
["class"] = "SHAMAN",
["level"] = 0,
["weeklyBest"] = 0,
},
["Falls"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Falls",
["faction"] = "Alliance",
["timestamp"] = 437971,
["class"] = "DEMONHUNTER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Mire"] = {
["mapID"] = 0,
["week"] = 457,
["name"] = "Mire",
["faction"] = "Horde",
["timestamp"] = 474092,
["class"] = "EVOKER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Floe"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Floe",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 438252,
["class"] = "PRIEST",
["weeklyBest"] = 0,
},
["Rivulet"] = {
["mapID"] = 0,
["week"] = 457,
["name"] = "Rivulet",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 388970,
["class"] = "PALADIN",
["weeklyBest"] = 0,
},
["Slush"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Slush",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 545684,
["class"] = "ROGUE",
["weeklyBest"] = 0,
},
["Brack"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Brack",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 473959,
["class"] = "DEATHKNIGHT",
["weeklyBest"] = 0,
},
["Baffle"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Baffle",
["faction"] = "Horde",
["timestamp"] = 471587,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
},
["Argent Dawn"] = {
["Quag"] = {
["week"] = 456,
["mapID"] = 0,
["name"] = "Quag",
["faction"] = "Alliance",
["class"] = "EVOKER",
["level"] = 0,
["timestamp"] = 389049,
["weeklyBest"] = 0,
},
["Sverdrup"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Sverdrup",
["faction"] = "Horde",
["class"] = "MONK",
["level"] = 0,
["timestamp"] = 360277,
["weeklyBest"] = 0,
},
["Mangrove"] = {
["week"] = 458,
["mapID"] = 0,
["name"] = "Mangrove",
["faction"] = "Alliance",
["timestamp"] = 552914,
["class"] = "DRUID",
["level"] = 0,
["weeklyBest"] = 0,
},
["Benthos"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Benthos",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 361073,
["class"] = "DEATHKNIGHT",
["weeklyBest"] = 0,
},
["Rapids"] = {
["mapID"] = 0,
["week"] = 457,
["name"] = "Rapids",
["faction"] = "Alliance",
["timestamp"] = 460709,
["class"] = "WARLOCK",
["level"] = 0,
["weeklyBest"] = 0,
},
["Brook"] = {
["week"] = 456,
["mapID"] = 0,
["name"] = "Brook",
["faction"] = "Horde",
["timestamp"] = 349891,
["class"] = "MAGE",
["level"] = 0,
["weeklyBest"] = 0,
},
["Spume"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Spume",
["faction"] = "Alliance",
["class"] = "WARRIOR",
["level"] = 0,
["timestamp"] = 295307,
["weeklyBest"] = 0,
},
["Surge"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Surge",
["faction"] = "Horde",
["class"] = "MONK",
["level"] = 0,
["timestamp"] = 460804,
["weeklyBest"] = 0,
},
["Stream"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Stream",
["faction"] = "Horde",
["class"] = "HUNTER",
["level"] = 0,
["timestamp"] = 360495,
["weeklyBest"] = 0,
},
["Confluence"] = {
["mapID"] = 0,
["week"] = 458,
["name"] = "Confluence",
["faction"] = "Alliance",
["class"] = "PALADIN",
["level"] = 0,
["timestamp"] = 556991,
["weeklyBest"] = 0,
},
["Riptides"] = {
["week"] = 457,
["mapID"] = 0,
["name"] = "Riptides",
["faction"] = "Alliance",
["class"] = "SHAMAN",
["level"] = 0,
["timestamp"] = 474181,
["weeklyBest"] = 0,
},
["Riparium"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Riparium",
["faction"] = "Alliance",
["timestamp"] = 360220,
["class"] = "WARLOCK",
["level"] = 0,
["weeklyBest"] = 0,
},
["Estuary"] = {
["week"] = 455,
["mapID"] = 0,
["name"] = "Estuary",
["faction"] = "Alliance",
["level"] = 0,
["timestamp"] = 360639,
["class"] = "ROGUE",
["weeklyBest"] = 0,
},
["Cataracts"] = {
["week"] = 456,
["mapID"] = 0,
["name"] = "Cataracts",
["faction"] = "Horde",
["class"] = "DEMONHUNTER",
["level"] = 0,
["timestamp"] = 349173,
["weeklyBest"] = 0,
},
["Alluvium"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Alluvium",
["faction"] = "Alliance",
["timestamp"] = 360769,
["class"] = "EVOKER",
["level"] = 0,
["weeklyBest"] = 0,
},
["Emptyrivers"] = {
["mapID"] = 0,
["week"] = 455,
["name"] = "Emptyrivers",
["faction"] = "Horde",
["level"] = 0,
["timestamp"] = 440962,
["class"] = "MAGE",
["weeklyBest"] = 0,
},
},
},
["shareAlts"] = true,
},
["DungeonTeleports"] = {
["dungeon_portal"] = "main_unknown",
["teleportOnKeystoneCtrlClick"] = true,
["showAlternates"] = true,
["toy"] = "main_on_cooldown",
["shuffleSharedCooldown"] = true,
["hearthstone"] = "main_on_cooldown",
["mage_teleport"] = "main_on_cooldown",
},
["ShowOwnRatingOnLFGTooltip"] = {
},
["miscQoL"] = {
["respondToGuild"] = true,
["groupFormedMessageKeystoneOnly"] = true,
["groupFormedMessage"] = true,
["respondToParty"] = true,
["respondToRaid"] = true,
["removeHoverBlockFromLFGApplicationViewer"] = true,
["autoSlotKeystone"] = true,
},
["ShowScoreOnKeystoneTooltip"] = {
},
},
["modules"] = {
["ImproveKeystoneLink"] = true,
["PartyRating"] = true,
["SortDungeonIcons"] = true,
["DungeonIconTooltip"] = true,
["MistHelperSync"] = true,
["DungeonIconText"] = true,
["AlwaysShowAffixes"] = true,
["KeystoneSharing-core"] = true,
["ShowOwnRatingOnLFGTooltip"] = true,
["miscQoL"] = true,
["DungeonTeleports"] = true,
["ShowScoreOnKeystoneTooltip"] = true,
},
}
