
OPieElvUIDB = {
["profileKeys"] = {
["Calestin - Sargeras"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Naturerivers - Korgath"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Doneer - Eredar"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Saellindris - Kel'Thuzad"] = "Default",
["Ochrian - Argent Dawn"] = "Default",
["Inundito - Kel'Thuzad"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Emptystreams - Argent Dawn"] = "Default",
["Emptyrivers - Sargeras"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Wildeadoriah - The Scryers"] = "Default",
["Zimuures - Argent Dawn"] = "Default",
["Asperos - Kel'Thuzad"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Mothugeon - Argent Dawn"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Alandere - Argent Dawn"] = "Default",
["Lotic - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
}
