
OPieElvUIDB = {
	["profileKeys"] = {
		["Stream - Argent Dawn"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Lotic - Argent Dawn"] = "Default",
		["Mangrove - Argent Dawn"] = "Default",
		["Ochrian - Argent Dawn"] = "Default",
		["Emptystreams - Argent Dawn"] = "Default",
		["Alluvium - Argent Dawn"] = "Default",
		["Flumina - Argent Dawn"] = "Default",
		["Cataracts - Argent Dawn"] = "Default",
		["Headcut - Argent Dawn"] = "Default",
		["Confluence - Argent Dawn"] = "Default",
		["Mothugeon - Argent Dawn"] = "Default",
		["Zimuures - Argent Dawn"] = "Default",
		["Riparium - Argent Dawn"] = "Default",
		["Benthos - Argent Dawn"] = "Default",
		["Emptyrivers - Argent Dawn"] = "Default",
		["Karst - Argent Dawn"] = "Default",
		["Alandere - Argent Dawn"] = "Default",
		["Sverdrup - Argent Dawn"] = "Default",
		["Estuary - Argent Dawn"] = "Default",
	},
}
