
PawnCommon = {
	["ShowUpgradesOnTooltips"] = true,
	["AlignNumbersRight"] = false,
	["ShowBagUpgradeAdvisor"] = true,
	["ShowItemID"] = false,
	["ShowRelicUpgrades"] = true,
	["ShowValuesForUpgradesOnly"] = true,
	["Digits"] = 1,
	["IgnoreGemsWhileLeveling"] = true,
	["ColorTooltipBorder"] = false,
	["ShowTooltipIcons"] = true,
	["ShowLootUpgradeAdvisor"] = true,
	["ShowSocketingAdvisor"] = true,
	["Scales"] = {
		["\"MrRobot\":HUNTER3"] = {
			["IconTexturePath"] = 461113,
			["PerCharacterOptions"] = {
			},
			["Color"] = "abd473",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Survival",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "809f56",
		},
		["\"MrRobot\":WARLOCK1"] = {
			["IconTexturePath"] = 136145,
			["PerCharacterOptions"] = {
				["Sassyrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8788ee",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Affliction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "6566b2",
		},
		["\"MrRobot\":SHAMAN1"] = {
			["IconTexturePath"] = 136048,
			["PerCharacterOptions"] = {
				["Emptyrivers-Sargeras"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "0070de",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Elemental",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "0054a6",
		},
		["\"MrRobot\":PRIEST1"] = {
			["IconTexturePath"] = 135940,
			["PerCharacterOptions"] = {
				["Littlerivers-Kel'Thuzad"] = {
					["Visible"] = true,
				},
				["Yandanderex-Moon Guard"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ffffff",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Discipline",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bfbfbf",
		},
		["\"MrRobot\":PRIEST3"] = {
			["IconTexturePath"] = 136207,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ffffff",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Shadow",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bfbfbf",
		},
		["\"MrRobot\":MAGE3"] = {
			["IconTexturePath"] = 135846,
			["PerCharacterOptions"] = {
				["Tinyrivers-Sargeras"] = {
					["Visible"] = true,
				},
				["Tinyrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "3fc7eb",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "2f95b0",
		},
		["\"MrRobot\":MAGE2"] = {
			["IconTexturePath"] = 135810,
			["PerCharacterOptions"] = {
			},
			["Color"] = "3fc7eb",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Fire",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "2f95b0",
		},
		["\"MrRobot\":WARLOCK3"] = {
			["IconTexturePath"] = 136186,
			["PerCharacterOptions"] = {
				["Evilrivers-Kel'Thuzad"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "8788ee",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Destruction",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "6566b2",
		},
		["\"MrRobot\":ROGUE2"] = {
			["IconTexturePath"] = 135340,
			["PerCharacterOptions"] = {
			},
			["Color"] = "fff569",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Outlaw",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bfb74e",
		},
		["\"MrRobot\":MONK1"] = {
			["IconTexturePath"] = 608951,
			["PerCharacterOptions"] = {
				["Serenerivers-Arthas"] = {
					["Visible"] = true,
				},
				["Serenerivers-Sargeras"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00ff96",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Brewmaster",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "00bf70",
		},
		["\"MrRobot\":DEMONHUNTER1"] = {
			["IconTexturePath"] = 1247264,
			["PerCharacterOptions"] = {
				["Edgyrivers-Kel'Thuzad"] = {
					["Visible"] = true,
				},
				["Blindrivers-Korgath"] = {
					["Visible"] = true,
				},
				["Blindrivers-Sargeras"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "a330c9",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Havoc",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "7a2496",
		},
		["\"MrRobot\":DRUID4"] = {
			["IconTexturePath"] = 136041,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff7d0a",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 4,
			["UnenchantedColor"] = "bf5d07",
		},
		["Arcane"] = {
			["PerCharacterOptions"] = {
				["Rapidrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["UpgradesFollowSpecialization"] = true,
			["Color"] = "ff6bf8",
			["UnenchantedColor"] = "bf50ba",
			["Values"] = {
				["Intellect"] = 10.69,
				["HasteRating"] = 8.59,
				["MasteryRating"] = 8.45,
				["Versatility"] = 8.71,
				["CritRating"] = 8.38,
			},
		},
		["\"MrRobot\":ROGUE3"] = {
			["IconTexturePath"] = 132320,
			["PerCharacterOptions"] = {
				["Luckyrivers-Sargeras"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fff569",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Subtlety",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bfb74e",
		},
		["\"MrRobot\":PALADIN1"] = {
			["IconTexturePath"] = 135920,
			["PerCharacterOptions"] = {
			},
			["Color"] = "f58cba",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "b7698b",
		},
		["Glacial Spike"] = {
			["IconTexturePath"] = "Interface\\Icons\\Spell_Frost_FrostBolt02",
			["PerCharacterOptions"] = {
				["Rapidrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["UpgradesFollowSpecialization"] = true,
			["Color"] = "3fc7eb",
			["SpecID"] = 3,
			["ClassID"] = 8,
			["Values"] = {
				["Intellect"] = 14.15,
				["IsFist"] = -1000000,
				["Is2HMace"] = -1000000,
				["IsMace"] = -1000000,
				["CritRating"] = 13.53,
				["HasteRating"] = 12.15,
				["MasteryRating"] = 11.04,
				["Versatility"] = 13.12,
				["IsPolearm"] = -1000000,
				["IsGun"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsAxe"] = -1000000,
				["IsBow"] = -1000000,
				["IsMail"] = -1000000,
				["IsPlate"] = -1000000,
				["IsLeather"] = -1000000,
				["IsOffHand"] = -1000000,
				["IsWarglaive"] = -1000000,
				["Is2HSword"] = -1000000,
				["IsCrossbow"] = -1000000,
				["IsShield"] = -1000000,
			},
		},
		["\"MrRobot\":WARRIOR3"] = {
			["IconTexturePath"] = 132341,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c79c6e",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "957552",
		},
		["\"MrRobot\":PRIEST2"] = {
			["IconTexturePath"] = 237542,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ffffff",
			["ClassID"] = 5,
			["LocalizedName"] = "Priest: Holy",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bfbfbf",
		},
		["Thermal Void"] = {
			["Values"] = {
				["Intellect"] = 7.88,
				["HasteRating"] = 6.81,
				["MasteryRating"] = 8.23,
				["CritRating"] = 7.68,
				["Versatility"] = 6.96,
			},
			["PerCharacterOptions"] = {
				["Rapidrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["UpgradesFollowSpecialization"] = true,
		},
		["\"MrRobot\":PALADIN3"] = {
			["IconTexturePath"] = 135873,
			["PerCharacterOptions"] = {
			},
			["Color"] = "f58cba",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Retribution",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "b7698b",
		},
		["\"MrRobot\":DEMONHUNTER2"] = {
			["IconTexturePath"] = 1247265,
			["PerCharacterOptions"] = {
			},
			["Color"] = "a330c9",
			["ClassID"] = 12,
			["LocalizedName"] = "Demon Hunter: Vengeance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "7a2496",
		},
		["\"MrRobot\":WARRIOR1"] = {
			["IconTexturePath"] = 132355,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c79c6e",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Arms",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "957552",
		},
		["\"MrRobot\":WARLOCK2"] = {
			["IconTexturePath"] = 136172,
			["PerCharacterOptions"] = {
			},
			["Color"] = "8788ee",
			["ClassID"] = 9,
			["LocalizedName"] = "Warlock: Demonology",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "6566b2",
		},
		["\"MrRobot\":DRUID2"] = {
			["IconTexturePath"] = 132115,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff7d0a",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Feral",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bf5d07",
		},
		["\"MrRobot\":MAGE1"] = {
			["IconTexturePath"] = 135932,
			["PerCharacterOptions"] = {
			},
			["Color"] = "3fc7eb",
			["ClassID"] = 8,
			["LocalizedName"] = "Mage: Arcane",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "2f95b0",
		},
		["\"MrRobot\":PALADIN2"] = {
			["IconTexturePath"] = 236264,
			["PerCharacterOptions"] = {
			},
			["Color"] = "f58cba",
			["ClassID"] = 2,
			["LocalizedName"] = "Paladin: Protection",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "b7698b",
		},
		["\"MrRobot\":ROGUE1"] = {
			["IconTexturePath"] = 236270,
			["PerCharacterOptions"] = {
				["Skankyrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "fff569",
			["ClassID"] = 4,
			["LocalizedName"] = "Rogue: Assassination",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bfb74e",
		},
		["\"MrRobot\":HUNTER1"] = {
			["IconTexturePath"] = 461112,
			["PerCharacterOptions"] = {
				["Mecharivers-Sargeras"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "abd473",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Beast Mastery",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "809f56",
		},
		["\"MrRobot\":DEATHKNIGHT3"] = {
			["IconTexturePath"] = 135775,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Unholy",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":HUNTER2"] = {
			["IconTexturePath"] = 236179,
			["PerCharacterOptions"] = {
			},
			["Color"] = "abd473",
			["ClassID"] = 3,
			["LocalizedName"] = "Hunter: Marksmanship",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "809f56",
		},
		["\"MrRobot\":WARRIOR2"] = {
			["IconTexturePath"] = 132347,
			["PerCharacterOptions"] = {
			},
			["Color"] = "c79c6e",
			["ClassID"] = 1,
			["LocalizedName"] = "Warrior: Fury",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "957552",
		},
		["\"MrRobot\":MONK2"] = {
			["IconTexturePath"] = 608952,
			["PerCharacterOptions"] = {
				["Serenerivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00ff96",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Mistweaver",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "00bf70",
		},
		["\"MrRobot\":DEATHKNIGHT2"] = {
			["IconTexturePath"] = 135773,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Frost",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "bf3950",
		},
		["Tinyrivers"] = {
			["IconTexturePath"] = 135846,
			["Values"] = {
				["IsOffHand"] = -1000000,
				["IsFist"] = -1000000,
				["Is2HMace"] = -1000000,
				["IsWarglaive"] = -1000000,
				["CritRating"] = 15.95,
				["HasteRating"] = 14.98,
				["MasteryRating"] = 11.65,
				["Versatility"] = 13.85,
				["IsPolearm"] = -1000000,
				["IsGun"] = -1000000,
				["Is2HAxe"] = -1000000,
				["IsAxe"] = -1000000,
				["IsBow"] = -1000000,
				["IsMail"] = -1000000,
				["IsPlate"] = -1000000,
				["IsLeather"] = -1000000,
				["Intellect"] = 16.26,
				["IsMace"] = -1000000,
				["Is2HSword"] = -1000000,
				["IsCrossbow"] = -1000000,
				["IsShield"] = -1000000,
			},
			["Color"] = "3fc7eb",
			["ClassID"] = 8,
			["Role"] = "DAMAGER",
			["UpgradesFollowSpecialization"] = true,
			["SpecID"] = 3,
			["PerCharacterOptions"] = {
				["Tinyrivers-Kel'Thuzad"] = {
					["Visible"] = true,
				},
			},
		},
		["\"MrRobot\":SHAMAN3"] = {
			["IconTexturePath"] = 136052,
			["PerCharacterOptions"] = {
			},
			["Color"] = "0070de",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Restoration",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "HEALER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "0054a6",
		},
		["\"MrRobot\":DEATHKNIGHT1"] = {
			["IconTexturePath"] = 135770,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff4d6b",
			["ClassID"] = 6,
			["LocalizedName"] = "Death Knight: Blood",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bf3950",
		},
		["\"MrRobot\":DRUID3"] = {
			["IconTexturePath"] = 132276,
			["PerCharacterOptions"] = {
			},
			["Color"] = "ff7d0a",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Guardian",
			["DoNotShow1HUpgrades"] = true,
			["Role"] = "TANK",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "bf5d07",
		},
		["\"MrRobot\":DRUID1"] = {
			["IconTexturePath"] = 136096,
			["PerCharacterOptions"] = {
				["Wildrivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "ff7d0a",
			["ClassID"] = 11,
			["LocalizedName"] = "Druid: Balance",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = false,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 1,
			["UnenchantedColor"] = "bf5d07",
		},
		["\"MrRobot\":SHAMAN2"] = {
			["IconTexturePath"] = 237581,
			["PerCharacterOptions"] = {
			},
			["Color"] = "0070de",
			["ClassID"] = 7,
			["LocalizedName"] = "Shaman: Enhancement",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 2,
			["UnenchantedColor"] = "0054a6",
		},
		["\"MrRobot\":MONK3"] = {
			["IconTexturePath"] = 608953,
			["PerCharacterOptions"] = {
				["Serenerivers-Arthas"] = {
					["Visible"] = true,
				},
			},
			["Color"] = "00ff96",
			["ClassID"] = 10,
			["LocalizedName"] = "Monk: Windwalker",
			["DoNotShow1HUpgrades"] = false,
			["Role"] = "DAMAGER",
			["DoNotShow2HUpgrades"] = true,
			["UpgradesFollowSpecialization"] = true,
			["Provider"] = "MrRobot",
			["SpecID"] = 3,
			["UnenchantedColor"] = "00bf70",
		},
	},
	["ShowSpecIcons"] = true,
	["ButtonPosition"] = 2,
	["Debug"] = false,
	["ShowQuestUpgradeAdvisor"] = true,
	["LastVersion"] = 2.0204,
	["ShownGettingStarted"] = true,
}
