
PetLeash3DB = {
	["namespaces"] = {
		["SpecialItems"] = {
			["global"] = {
				["localeCache"] = {
					["enUS"] = {
						["item:31815"] = "Zeppit's Crystal",
						["item:36936"] = "Golem Control Unit",
						["item:46831"] = "Macabre Marionette",
						["item:71137"] = "Brewfest Keg Pony",
						["item:18598"] = "Human Orphan Whistle",
						["item:31881"] = "Draenei Orphan Whistle",
						["item:12185"] = "Bloodsail Admiral's Hat",
						["item:30803"] = "Felhound Whistle",
						["item:32834"] = "Nether Ray Cage",
						["item:31880"] = "Blood Elf Orphan Whistle",
						["item:40110"] = "Haunted Memento",
						["item:38506"] = "Don Carlos' Famous Hat",
						["item:34971"] = "Warsong Flare Gun",
						["item:18597"] = "Orcish Orphan Whistle",
						["item:46396"] = "Wolvar Orphan Whistle",
						["item:46397"] = "Oracle Orphan Whistle",
						["item:68646"] = "Winterspring Cub",
						["item:46362"] = "Venomhide Hatchling",
					},
				},
			},
		},
	},
	["profileKeys"] = {
		["Boringrivers - Korgath"] = "Default",
		["Rapidrivers - Arthas"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Beefyrivers - Thrall"] = "Default",
		["Yandanderex - Moon Guard"] = "Default",
		["Mindrivers - Korgath"] = "Default",
		["Serenerivers - Arthas"] = "Default",
		["Sacredrivers - Korgath"] = "Default",
		["Emptyrivers - Korgath"] = "Default",
		["Blindrivers - Sargeras"] = "Default",
		["Tinyrivers - Kel'Thuzad"] = "Default",
		["Wildrivers - Korgath"] = "Default",
		["Sassyrivers - Arthas"] = "Default",
		["Serenerivers - Kel'Thuzad"] = "Default",
		["Deadrivers - Korgath"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Hulyon - Kel'Thuzad"] = "Default",
		["Littlerivers - Kel'Thuzad"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Hiddenrivers - Korgath"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Evilrivers - Korgath"] = "Default",
		["Notariver - Arthas"] = "Default",
		["Tinyrivers - Arthas"] = "Default",
		["Serenerivers - Sargeras"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Mecharivers - Sargeras"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Edgyrivers - Kel'Thuzad"] = "Default",
		["Toofattohide - Kel'Thuzad"] = "Default",
		["Serenerivers - Korgath"] = "Default",
		["Blindrivers - Korgath"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Angryrivers - Korgath"] = "Default",
		["Smaz - Mug'thol"] = "Default",
		["Brightrivers - Korgath"] = "Default",
		["Magicrivers - Korgath"] = "Default",
		["Luckyrivers - Korgath"] = "Default",
		["Tinyrivers - Sargeras"] = "Default",
		["Skankyrivers - Arthas"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["sets"] = {
				["$Default"] = {
					["defaultValue"] = 0,
					["pets"] = {
						["BattlePet-0-0000052A338B"] = 1,
						["BattlePet-0-00000420E917"] = 1,
						["BattlePet-0-00000420E86D"] = 1,
						["BattlePet-0-000005F16FD4"] = 1,
						["BattlePet-0-000005F172EA"] = 0,
						["BattlePet-0-000005E9439E"] = 1,
						["BattlePet-0-000005AC8195"] = 1,
					},
				},
			},
			["overrideSetLoadout"] = true,
			["nearPEWOnly"] = true,
		},
	},
}
