
PlumberDB = {
	["TalkingHead_HideInInstance"] = false,
	["RogueHandyLockpick"] = true,
	["AzerothianArchives"] = true,
	["WorldMapPinSeedPlanting"] = true,
	["settingsOpenTime"] = 1705635859,
	["GossipFrameMedal"] = true,
	["TrackItemUpgradeCurrency"] = true,
	["TrackerBarInsideSeparateBag"] = false,
	["PlayerChoiceFrameToken"] = true,
	["BlizzFixEventToast"] = false,
	["AlternativePlayerChoiceUI"] = true,
	["TalkingHead_MasterSwitch"] = true,
	["DreamseedChestABTesting"] = false,
	["BackpackTrackedItems"] = {
	},
	["MapPinSize"] = 1,
	["HideZeroCountItem"] = true,
	["HandyLockpick"] = true,
	["EmeraldBountySeedList"] = true,
	["Navigator_Dreamseed"] = true,
	["Technoscryers"] = true,
	["TalkingHead_HideWorldQuest"] = false,
	["DruidModelFix"] = true,
	["TalkingHead_FontSize"] = 120,
	["installTime"] = 1696553418,
	["TalkingHead_PositionX"] = -1,
	["AutoJoinEvents"] = true,
	["BlizzFixWardrobeTrackingTip"] = true,
	["TalkingHead_TextOutline"] = true,
	["BackpackItemTracker"] = false,
	["TalkingHead_InstantText"] = false,
	["TooltipShowExtraInfoCrest"] = false,
	["TalkingHead_PositionY"] = 469,
	["Navigator_MasterSwitch"] = true,
	["ConciseTokenTooltip"] = true,
}
