
PlumberDB = {
	["ConciseTokenTooltip"] = true,
	["RogueHandyLockpick"] = true,
	["Navigator_MasterSwitch"] = true,
	["MapPinSize"] = 1,
	["settingsOpenTime"] = 1704176811,
	["GossipFrameMedal"] = true,
	["AutoJoinEvents"] = true,
	["HandyLockpick"] = true,
	["TrackItemUpgradeCurrency"] = true,
	["BackpackTrackedItems"] = {
	},
	["TalkingHead_MasterSwitch"] = false,
	["HideZeroCountItem"] = true,
	["Navigator_Dreamseed"] = true,
	["TalkingHead_FontSize"] = 100,
	["TalkingHead_HideWorldQuest"] = false,
	["AzerothianArchives"] = true,
	["EmeraldBountySeedList"] = true,
	["PlayerChoiceFrameToken"] = true,
	["DruidModelFix"] = true,
	["BlizzFixEventToast"] = true,
	["WorldMapPinSeedPlanting"] = true,
	["AlternativePlayerChoiceUI"] = true,
	["BackpackItemTracker"] = false,
	["TalkingHead_InstantText"] = false,
	["TooltipShowExtraInfoCrest"] = false,
	["TalkingHead_HideInInstance"] = false,
	["installTime"] = 1696553418,
	["DreamseedChestABTesting"] = false,
}
