
RaiderIO_Config = {
["replayAlpha"] = 1,
["enableKeystoneTooltips"] = true,
["profilePoint"] = {
["y"] = 0,
["x"] = -16,
["point"] = "TOPLEFT",
},
["enableReplay"] = false,
["enableLFGDropdown"] = true,
["displayWeeklyGuildBest"] = false,
["mplusHeadlineMode"] = 0,
["showMainsScore"] = true,
["showRaidEncountersInProfile"] = true,
["showAverageScore"] = true,
["enableWhoMessages"] = true,
["useEnglishAbbreviations"] = false,
["replayStyle"] = "MODERN",
["lockReplay"] = false,
["replayPoint"] = {
["y"] = 0,
["x"] = 0,
["point"] = "TOPLEFT",
},
["disableScoreColors"] = false,
["showMainBestScore"] = true,
["allowClientToControlCombatLog"] = true,
["minimapIcon"] = {
["minimapPos"] = 180,
["showInCompartment"] = true,
["lock"] = false,
["hide"] = false,
},
["replayBackground"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["dockReplay"] = false,
["showSimpleScoreColors"] = false,
["replayTiming"] = "DUNGEON",
["replaySelection"] = "user_best_replay",
["enableCombatLogTracking"] = false,
["enableGuildTooltips"] = true,
["hidePersonalRaiderIOProfile"] = false,
["enableLFGTooltips"] = true,
["showScoreModifier"] = false,
["positionProfileAuto"] = true,
["showRoleIcons"] = true,
["enableFriendsTooltips"] = true,
["inverseProfileModifier"] = false,
["showDropDownCopyURL"] = true,
["enableUnitTooltips"] = true,
["enableProfileModifier"] = true,
["enableClientEnhancements"] = true,
["showRaiderIOProfile"] = false,
["lockProfile"] = false,
["showScoreInCombat"] = true,
["enableWhoTooltips"] = true,
["showClientGuildBest"] = true,
}
RaiderIO_LastCharacter = "us-Emptyrivers-argent-dawn"
RaiderIO_MissingCharacters = {
["us-Lombris-kirin-tor"] = true,
["us-Hexavier-steamwheedle-cartel"] = true,
["us-Vìshnu-earthen-ring"] = true,
["us-Jiyung-sentinels"] = true,
["us-Gargao-earthen-ring"] = true,
["us-Receita-the-scryers"] = true,
["us-Nomesacan-earthen-ring"] = true,
["us-Brassie-argent-dawn"] = true,
["us-Mactosh-kirin-tor"] = true,
["us-Bronndek-sentinels"] = true,
["us-Rickjames-kirin-tor"] = true,
["us-Tuskatron-argent-dawn"] = true,
["us-Xekairn-argent-dawn"] = true,
["us-Gowron-earthen-ring"] = true,
["us-Baelin-maelstrom"] = true,
["us-Arcra-argent-dawn"] = true,
["us-Druxi-sentinels"] = true,
["us-Luxy-argent-dawn"] = true,
["us-Emptyrivers-argent-dawn"] = true,
["us-Roddric-the-scryers"] = true,
["us-Moodu-lightninghoof"] = true,
["us-Soulbain-steamwheedle-cartel"] = true,
["us-Boomë-steamwheedle-cartel"] = true,
}
RaiderIO_MissingServers = {
}
RaiderIO_CachedRuns = nil
RaiderIO_RWF = {
}
RaiderIO_CompletedReplays = {
}
