
RaiderIO_Config = {
["replayAlpha"] = 1,
["enableKeystoneTooltips"] = true,
["profilePoint"] = {
["y"] = 0,
["x"] = -16,
["point"] = "TOPLEFT",
},
["enableReplay"] = false,
["enableLFGDropdown"] = true,
["displayWeeklyGuildBest"] = false,
["mplusHeadlineMode"] = 0,
["showMainsScore"] = true,
["showRaidEncountersInProfile"] = true,
["showAverageScore"] = true,
["enableWhoMessages"] = true,
["useEnglishAbbreviations"] = false,
["replayStyle"] = "MODERN",
["lockReplay"] = false,
["replayPoint"] = {
["y"] = 0,
["x"] = 0,
["point"] = "TOPLEFT",
},
["disableScoreColors"] = false,
["showMainBestScore"] = true,
["allowClientToControlCombatLog"] = true,
["minimapIcon"] = {
["minimapPos"] = 180,
["showInCompartment"] = true,
["hide"] = false,
["lock"] = false,
},
["replaySelection"] = "user_best_replay",
["dockReplay"] = false,
["showScoreInCombat"] = true,
["lockProfile"] = false,
["enableWhoTooltips"] = true,
["showRaiderIOProfile"] = false,
["enableGuildTooltips"] = true,
["enableClientEnhancements"] = true,
["enableProfileModifier"] = true,
["showRoleIcons"] = true,
["enableFriendsTooltips"] = true,
["enableUnitTooltips"] = true,
["positionProfileAuto"] = true,
["inverseProfileModifier"] = false,
["showDropDownCopyURL"] = true,
["showScoreModifier"] = false,
["enableLFGTooltips"] = true,
["hidePersonalRaiderIOProfile"] = false,
["enableCombatLogTracking"] = false,
["replayTiming"] = "DUNGEON",
["showSimpleScoreColors"] = false,
["replayBackground"] = {
["a"] = 0.5,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["showClientGuildBest"] = true,
}
RaiderIO_LastCharacter = "us-Estuary-argent-dawn"
RaiderIO_MissingCharacters = {
["us-Balthster-earthen-ring"] = true,
["us-Ashkyn-argent-dawn"] = true,
["us-Bopanda-earthen-ring"] = true,
["us-Bernadette-the-scryers"] = true,
["us-Hrunn-argent-dawn"] = true,
["us-Kargath-argent-dawn"] = true,
["us-Zumira-earthen-ring"] = true,
["us-Estuary-argent-dawn"] = true,
["us-Serendippy-argent-dawn"] = true,
["us-Svarog-the-scryers"] = true,
["us-Halbarad-sentinels"] = true,
["us-Shabushabu-argent-dawn"] = true,
["us-Craru-kirin-tor"] = true,
["us-Errai-argent-dawn"] = true,
["us-Kangcheori-kirin-tor"] = true,
["us-Kaiu-earthen-ring"] = true,
["us-Kianthanie-earthen-ring"] = true,
["us-Estuary-Argent Dawn"] = true,
["us-Loothak-the-scryers"] = true,
["us-Speeds-argent-dawn"] = true,
}
RaiderIO_MissingServers = {
}
RaiderIO_CachedRuns = nil
RaiderIO_RWF = {
}
RaiderIO_CompletedReplays = {
}
