
RaiderIO_Config = {
["replayAlpha"] = 1,
["enableKeystoneTooltips"] = true,
["profilePoint"] = {
["y"] = 0,
["x"] = -16,
["point"] = "TOPLEFT",
},
["enableReplay"] = false,
["enableLFGDropdown"] = true,
["displayWeeklyGuildBest"] = false,
["mplusHeadlineMode"] = 0,
["showMainsScore"] = true,
["showRaidEncountersInProfile"] = true,
["showAverageScore"] = true,
["enableWhoMessages"] = true,
["minimapIcon"] = {
["minimapPos"] = 180,
["showInCompartment"] = true,
["lock"] = false,
["hide"] = false,
},
["useEnglishAbbreviations"] = false,
["replayStyle"] = "MODERN",
["lockReplay"] = false,
["replayPoint"] = {
["y"] = 0,
["x"] = 0,
["point"] = "TOPLEFT",
},
["disableScoreColors"] = false,
["showMainBestScore"] = true,
["allowClientToControlCombatLog"] = false,
["replayBackground"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["showSimpleScoreColors"] = false,
["replayTiming"] = "DUNGEON",
["dockReplay"] = false,
["enableCombatLogTracking"] = false,
["hidePersonalRaiderIOProfile"] = false,
["showWarbandScore"] = true,
["enableLFGTooltips"] = true,
["enableGuildTooltips"] = true,
["showScoreModifier"] = false,
["inverseProfileModifier"] = false,
["enableUnitTooltips"] = true,
["enableLFGExportButton"] = false,
["showRoleIcons"] = true,
["positionProfileAuto"] = true,
["enableFriendsTooltips"] = true,
["showDropDownCopyURL"] = true,
["showRaiderIOProfile"] = false,
["enableProfileModifier"] = true,
["enableClientEnhancements"] = true,
["replaySelection"] = "user_best_replay",
["lockProfile"] = false,
["showScoreInCombat"] = true,
["enableWhoTooltips"] = true,
["showClientGuildBest"] = false,
}
RaiderIO_LastCharacter = "us-Sverdrup-argent-dawn"
RaiderIO_MissingCharacters = {
["us-Themiddleman-argent-dawn"] = true,
["us-Ap-sentinels"] = true,
["us-Sanagral-earthen-ring"] = true,
["us-Kaunaz-sentinels"] = true,
["us-Nykko-the-scryers"] = true,
["us-Kraeger-kirin-tor"] = true,
["us-Jupiterchild-the-scryers"] = true,
["us-Strïker-earthen-ring"] = true,
["us-Zendos-earthen-ring"] = true,
["us-Nomza-argent-dawn"] = true,
["us-Nurgle-kirin-tor"] = true,
["us-Peenshooter-the-scryers"] = true,
["us-Deathschild-steamwheedle-cartel"] = true,
["us-Marinka-argent-dawn"] = true,
["us-Aule-argent-dawn"] = true,
["us-Aezer-earthen-ring"] = true,
["us-Rilker-sentinels"] = true,
["us-Hellraizzed-earthen-ring"] = true,
["us-Aatus-sentinels"] = true,
["us-Subsidiary-earthen-ring"] = true,
["us-Zyrcis-argent-dawn"] = true,
["us-Mz-kirin-tor"] = true,
["us-Kysleia-the-scryers"] = true,
["us-Deerslayer-argent-dawn"] = true,
["us-Elamue-sentinels"] = true,
["us-Mirar-kirin-tor"] = true,
["us-Cindress-the-scryers"] = true,
["us-Shelob-argent-dawn"] = true,
["us-Saradine-earthen-ring"] = true,
}
RaiderIO_MissingServers = {
}
RaiderIO_CachedRuns = nil
RaiderIO_RWF = {
}
RaiderIO_CompletedReplays = {
}
