
RavenDB = {
	["global"] = {
		["SpellLists"] = {
			["PlayerInclusions"] = {
			},
			["ClassBuffs"] = {
			},
			["PlayerDebuffExclusions"] = {
			},
			["PlayerExclusions"] = {
			},
			["TargetExclusions"] = {
			},
		},
		["FilterBuff"] = {
			["PlayerBuffs"] = {
			},
			["PlayerBuffsExtra"] = {
			},
			["TargetBuffs"] = {
			},
		},
		["DefaultCooldownColor"] = {
			["r"] = 0.843137254901961,
			["g"] = 0.780392156862745,
			["b"] = 0.254901960784314,
		},
		["FilterDebuff"] = {
			["TargetDebuffs"] = {
			},
		},
		["Settings"] = {
			["WeaponEnchants"] = {
				["backdropFill"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["pointH"] = 14.9999726577209,
				["pointYT"] = 0.485714346305957,
				["pointW"] = 168.999988542952,
				["borderColor"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["pointX"] = 0.5,
				["pointXR"] = 0.399404770677294,
				["backdropColor"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["showNoDuration"] = true,
				["pointY"] = 0.499999965725923,
			},
			["Buffs"] = {
				["backdropFill"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["growDirection"] = false,
				["showNoDuration"] = true,
				["detectBuffsCastBy"] = "anyone",
				["timeOffset"] = 14,
				["spacingX"] = -9,
				["anchorX"] = -3,
				["reverseSort"] = true,
				["i_spacingX"] = 3,
				["detectBuffs"] = true,
				["pointW"] = 37.0000186264884,
				["hideLabel"] = true,
				["spacingY"] = -9,
				["checkDuration"] = true,
				["iconSize"] = 37,
				["checkTimeLeft"] = true,
				["filterDuration"] = 60,
				["barWidth"] = 20,
				["timeAlign"] = "LEFT",
				["iconAlign"] = "RIGHT",
				["borderColor"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["barHeight"] = 5,
				["i_spacingY"] = 15,
				["pointX"] = 0.9775,
				["pointH"] = 37.0000186264884,
				["sor"] = "T",
				["filterTimeLeft"] = 60,
				["maxBars"] = 40,
				["timeInset"] = 16,
				["configuration"] = 9,
				["pointXR"] = 0.00119044043730982,
				["wrap"] = 20,
				["timeFormat"] = 23,
				["iconInset"] = -15,
				["anchorY"] = -3,
				["backdropColor"] = {
					["a"] = 1,
					["b"] = 1,
					["g"] = 1,
					["r"] = 1,
				},
				["pointY"] = 0.9638,
				["hideBar"] = true,
				["pointYT"] = 0.0019047046996955,
				["i_iconSize"] = 30,
				["iconOffset"] = 8,
			},
		},
		["DefaultPoisonColor"] = {
			["a"] = 1,
			["g"] = 0.631372549019608,
		},
		["HighlightsEnabled"] = false,
		["Defaults"] = {
			["timeMono"] = true,
			["iconFSize"] = 8,
			["spacingY"] = 1,
			["bgAlpha"] = 0,
			["iconSize"] = 22,
			["hideClock"] = true,
			["borderOffset"] = 0,
			["timeFont"] = "pixel_large",
			["borderWidth"] = 1,
			["labelShadow"] = false,
			["iconFont"] = "pixel_large",
			["texture"] = "Plain",
			["labelFont"] = "pixel_large",
			["labelMono"] = true,
			["i_iconSize"] = 35,
			["iconMono"] = true,
			["timeOutline"] = true,
			["i_spacingX"] = -9,
			["bgtexture"] = "Plain",
			["iconShadow"] = false,
			["labelFSize"] = 8,
			["i_spacingY"] = -9,
			["timeShadow"] = false,
			["labelOutline"] = true,
			["i_hideClock"] = true,
			["timeFSize"] = 8,
			["hideSpark"] = true,
			["iconOffsetX"] = -1,
			["barWidth"] = 158,
		},
		["SpellTypes"] = {
			[157644] = "Magic",
			[226757] = "Magic",
			[980] = "Curse",
			[194316] = "Magic",
			[48438] = "Magic",
			[235450] = "Magic",
			[212799] = "Magic",
			[12654] = "Magic",
			[194522] = "Magic",
			[123725] = "Magic",
			[48108] = "Magic",
		},
		["ButtonFacade"] = true,
		["DefaultDebuffColor"] = {
			["r"] = 0.647058823529412,
			["g"] = 0,
			["b"] = 0,
		},
		["DefaultMagicColor"] = {
			["a"] = 1,
			["b"] = 0.71764705882353,
			["g"] = 0.43921568627451,
			["r"] = 0.145098039215686,
		},
		["DefaultBuffColor"] = {
			["r"] = 0.52156862745098,
			["g"] = 0.796078431372549,
			["b"] = 0.2,
		},
		["Minimap"] = {
			["hide"] = true,
		},
		["Version"] = "7",
		["DefaultDiseaseColor"] = {
			["a"] = 1,
		},
		["DefaultCurseColor"] = {
			["a"] = 1,
			["b"] = 0.694117647058824,
			["r"] = 0.419607843137255,
		},
	},
	["profileKeys"] = {
		["Blindrivers - Arthas"] = "Blindrivers - Arthas",
		["Feralrivers - Sargeras"] = "RealUI",
		["Wildrivers - Arthas"] = "RealUI",
		["Evilrivers - Sargeras"] = "RealUI",
		["Real - Zul'jin"] = "RealUI",
		["Tinyrivers - Sargeras"] = "RealUI",
		["Serenerivers - Sargeras"] = "RealUI",
		["Blindrivers - Sargeras"] = "RealUI",
	},
	["profiles"] = {
		["Blindrivers - Arthas"] = {
			["Conditions"] = {
				["DEMONHUNTER"] = {
				},
			},
		},
		["Feralrivers - Sargeras"] = {
		},
		["Evilrivers - Sargeras"] = {
			["Durations"] = {
				[2479] = 30,
			},
		},
		["RealUI"] = {
			["BarGroups"] = {
				["PlayerDebuffs"] = {
					["detectDebuffsCastBy"] = "anyone",
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["parentFrame"] = "RealUIPlayerFrame",
					["iconInset"] = 2,
					["showNoDuration"] = true,
					["name"] = "PlayerDebuffs",
					["auto"] = true,
					["pointYT"] = 0.507407395882206,
					["i_iconSize"] = 30,
					["i_spacingX"] = 3,
					["pointW"] = 179.999969482422,
					["labelInset"] = -1,
					["filterDebuffTable"] = "PlayerDebuffExclusions",
					["filterCooldownTable"] = "PlayerExclusions",
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["pointX"] = 0.210937468210856,
					["configuration"] = 8,
					["sor"] = "T",
					["maxBars"] = 10,
					["timeInset"] = 4,
					["pointH"] = 15.0000133514404,
					["pointXR"] = 0.695312547683716,
					["wrap"] = 10,
					["timeFormat"] = 23,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["detectDebuffs"] = true,
					["filterDebuffSpells"] = true,
					["pointY"] = 0.478703701296624,
					["timeSort"] = false,
				},
				["FocusDebuffs"] = {
					["detectDebuffsCastBy"] = "anyone",
					["noPlayerDebuffs"] = true,
					["backdropFill"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["hideSpark"] = false,
					["pointH"] = 35,
					["parentFrame"] = "RealUIFocusFrame",
					["useDefaultFontsAndTextures"] = false,
					["showNoDuration"] = true,
					["name"] = "FocusDebuffs",
					["timeOffset"] = 14,
					["timeSort"] = false,
					["spacingX"] = -9,
					["auto"] = true,
					["pointYT"] = 0.614814799535093,
					["i_spacingX"] = -8,
					["pointW"] = 35,
					["iconOffsetX"] = 0,
					["hideLabel"] = true,
					["spacingY"] = -9,
					["iconSize"] = 35,
					["filterDebuffTable"] = "PlayerExclusions",
					["timeFont"] = "pixel_small",
					["iconFont"] = "pixel_small",
					["barWidth"] = 20,
					["barHeight"] = 5,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = -8,
					["iconAlign"] = "RIGHT",
					["pointX"] = 0.302083301544189,
					["noTargetDebuffs"] = true,
					["configuration"] = 9,
					["labelFont"] = "pixel_small",
					["detectDebuffsMonitor"] = "focus",
					["sor"] = "T",
					["maxBars"] = 7,
					["timeInset"] = 16,
					["growDirection"] = false,
					["pointXR"] = 0.679687531789144,
					["iconInset"] = -15,
					["wrap"] = 7,
					["timeFormat"] = 23,
					["backdropColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["detectDebuffs"] = true,
					["borderColor"] = {
						["a"] = 1,
						["r"] = 1,
						["g"] = 1,
						["b"] = 1,
					},
					["pointY"] = 0.352777789394553,
					["hideBar"] = true,
					["iconOffset"] = 7,
				},
				["PlayerBuffsExtra"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["name"] = "PlayerBuffsExtra",
					["filterBuffList"] = {
					},
					["auto"] = true,
					["pointYT"] = 1.306887173901270e-007,
					["i_iconSize"] = 30,
					["filterBuff"] = false,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 180.000030517578,
					["merged"] = true,
					["bars"] = {
					},
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["showBuff"] = true,
					["pointX"] = 0.906249872843425,
					["showNoDuration"] = true,
					["pointH"] = 14.9999809265137,
					["pointXR"] = 1.112620035807290e-007,
					["mergeInto"] = "PlayerBuffs",
					["detectBuffsCastBy"] = "anyone",
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerInclusions",
					["pointY"] = 0.986110996513197,
					["filterBuffSpells"] = true,
				},
				["ToTDebuffs"] = {
					["noTargetDebuffs"] = true,
					["noPlayerDebuffs"] = true,
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["hideSpark"] = false,
					["parentFrame"] = "RealUITargetTargetFrame",
					["iconInset"] = -15,
					["name"] = "ToTDebuffs",
					["timeOffset"] = 14,
					["timeSort"] = false,
					["spacingX"] = -9,
					["barHeight"] = 5,
					["auto"] = true,
					["pointYT"] = 0.590740779254012,
					["i_spacingX"] = -8,
					["pointW"] = 35,
					["iconOffsetX"] = 0,
					["hideLabel"] = true,
					["detectOtherDebuffs"] = false,
					["spacingY"] = -9,
					["iconSize"] = 35,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = -8,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["iconAlign"] = "RIGHT",
					["showNoDuration"] = true,
					["pointX"] = 0.679687436421712,
					["noFocusDebuffs"] = false,
					["sor"] = "T",
					["configuration"] = 9,
					["filterDebuffTypes"] = false,
					["detectDebuffsMonitor"] = "targettarget",
					["maxBars"] = 7,
					["timeInset"] = 16,
					["pointH"] = 35,
					["pointXR"] = 0.302083396911621,
					["filterDebuffTable"] = "PlayerExclusions",
					["wrap"] = 7,
					["timeFormat"] = 23,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["barWidth"] = 20,
					["filterBuffTable"] = "PlayerExclusions",
					["detectDebuffs"] = true,
					["pointY"] = 0.376851809675633,
					["hideBar"] = true,
					["iconOffset"] = 7,
				},
				["FocusBuffsExtra"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["mergeInto"] = "FocusBuffs",
					["detectBuffsCastBy"] = "anyone",
					["name"] = "FocusBuffsExtra",
					["minimumDuration"] = false,
					["filterBuffTypes"] = true,
					["auto"] = true,
					["pointYT"] = 1.306887173901270e-007,
					["i_iconSize"] = 30,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 180.000030517578,
					["filterDebuffTable"] = "PlayerExclusions",
					["filterCooldownTable"] = "PlayerExclusions",
					["filterDuration"] = 30,
					["merged"] = true,
					["noPlayerBuffs"] = true,
					["detectStealable"] = true,
					["bars"] = {
					},
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["pointX"] = 0.906249872843425,
					["pointH"] = 14.9999809265137,
					["detectNPCBuffs"] = true,
					["detectVehicleBuffs"] = true,
					["pointXR"] = 1.112620035807290e-007,
					["detectBuffsMonitor"] = "focus",
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["pointY"] = 0.986110996513197,
				},
				["TargetBuffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["hideSpark"] = false,
					["parentFrame"] = "RealUITargetFrame",
					["iconInset"] = -15,
					["detectBuffsMonitor"] = "target",
					["name"] = "TargetBuffs",
					["timeOffset"] = 14,
					["timeSort"] = false,
					["spacingX"] = -5,
					["filterBuffList"] = {
					},
					["filterBuffTypes"] = false,
					["auto"] = true,
					["pointYT"] = 0.521296326960396,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 35,
					["iconOffsetX"] = 0,
					["hideLabel"] = true,
					["useDefaultDimensions"] = false,
					["spacingY"] = -5,
					["iconSize"] = 35,
					["filterDebuffTable"] = "PlayerExclusions",
					["playerSort"] = true,
					["filterCooldownTable"] = "PlayerExclusions",
					["barHeight"] = 5,
					["barWidth"] = 20,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["iconAlign"] = "RIGHT",
					["detectBuffsCastBy"] = "anyone",
					["pointX"] = 0.695312436421712,
					["i_iconSize"] = 30,
					["desaturateFriend"] = true,
					["configuration"] = 9,
					["maxBars"] = 12,
					["timeInset"] = 16,
					["sor"] = "T",
					["pointH"] = 35,
					["pointXR"] = 0.286458396911621,
					["wrap"] = 6,
					["timeFormat"] = 23,
					["showNoDuration"] = true,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "TargetExclusions",
					["desaturate"] = true,
					["pointY"] = 0.44629626196925,
					["hideBar"] = true,
					["filterBuffSpells"] = true,
					["iconOffset"] = 7,
				},
				["FocusBuffs"] = {
					["desaturateFriend"] = true,
					["detectDebuffsCastBy"] = "anyone",
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["hideSpark"] = false,
					["growDirection"] = false,
					["parentFrame"] = "RealUIFocusFrame",
					["iconInset"] = -15,
					["name"] = "FocusBuffs",
					["timeOffset"] = 14,
					["spacingX"] = -9,
					["auto"] = true,
					["pointYT"] = 0.590740779254012,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 35,
					["iconOffsetX"] = 0,
					["hideLabel"] = true,
					["spacingY"] = -9,
					["iconSize"] = 35,
					["filterDebuffTable"] = "PlayerExclusions",
					["filterCooldownTable"] = "PlayerExclusions",
					["noPlayerBuffs"] = true,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["iconAlign"] = "RIGHT",
					["pointX"] = 0.302083301544189,
					["desaturate"] = true,
					["configuration"] = 9,
					["timeSort"] = false,
					["filterDebuffTypes"] = true,
					["detectDebuffsMonitor"] = "focus",
					["sor"] = "T",
					["maxBars"] = 7,
					["timeInset"] = 16,
					["pointH"] = 35,
					["pointXR"] = 0.679687531789144,
					["wrap"] = 7,
					["timeFormat"] = 23,
					["detectBuffsMonitor"] = "focus",
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["barHeight"] = 5,
					["noTargetBuffs"] = false,
					["pointY"] = 0.376851809675633,
					["i_iconSize"] = 30,
					["hideBar"] = true,
					["barWidth"] = 20,
					["iconOffset"] = 7,
				},
				["Buffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["hideSpark"] = false,
					["growDirection"] = false,
					["showNoDuration"] = true,
					["detectBuffsCastBy"] = "anyone",
					["name"] = "Buffs",
					["timeOffset"] = 14,
					["timeSort"] = false,
					["spacingX"] = -9,
					["barHeight"] = 5,
					["auto"] = true,
					["reverseSort"] = true,
					["pointYT"] = 0.000925918966326561,
					["i_spacingX"] = 3,
					["detectBuffs"] = true,
					["pointW"] = 36.0000076293945,
					["iconOffsetX"] = 0,
					["anchorPoint"] = "TOPRIGHT",
					["hideLabel"] = true,
					["useDefaultDimensions"] = false,
					["spacingY"] = -9,
					["iconSize"] = 36,
					["checkTimeLeft"] = true,
					["filterDuration"] = 60,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["iconAlign"] = "RIGHT",
					["pointX"] = 0.980729039510091,
					["iconInset"] = -15,
					["filterDebuffTable"] = "PlayerDebuffExclusions",
					["configuration"] = 9,
					["pointH"] = 36.0000076293945,
					["filterTimeLeft"] = 60,
					["sor"] = "T",
					["anchorFrame"] = "RealUIPositionersBuffs",
					["maxBars"] = 40,
					["timeInset"] = 16,
					["pointXR"] = 0.000520956516265869,
					["wrap"] = 20,
					["timeFormat"] = 23,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["pointY"] = 0.965740736868483,
					["barWidth"] = 20,
					["hideBar"] = true,
					["i_iconSize"] = 30,
					["iconOffset"] = 7,
				},
				["PlayerBuffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["hideSpark"] = false,
					["pointH"] = 35,
					["parentFrame"] = "RealUIPlayerFrame",
					["name"] = "PlayerBuffs",
					["timeOffset"] = 14,
					["timeSort"] = false,
					["spacingX"] = -5,
					["anchorX"] = -63,
					["minimumDuration"] = false,
					["filterBuffList"] = {
					},
					["auto"] = true,
					["pointYT"] = 0.521296326960396,
					["i_iconSize"] = 25,
					["i_spacingX"] = 2,
					["detectBuffs"] = true,
					["pointW"] = 35,
					["iconOffsetX"] = 0,
					["anchorPoint"] = "LEFT",
					["hideLabel"] = true,
					["useDefaultDimensions"] = false,
					["spacingY"] = -5,
					["iconSize"] = 35,
					["filterDebuffTable"] = "PlayerExclusions",
					["playerSort"] = true,
					["checkTimeLeft"] = true,
					["i_hideClock"] = false,
					["filterDuration"] = 67,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["barWidth"] = 20,
					["bars"] = {
					},
					["timeAlign"] = "LEFT",
					["i_spacingY"] = 15,
					["iconAlign"] = "RIGHT",
					["pointX"] = 0.286458269755046,
					["filterBuffSpells"] = true,
					["configuration"] = 9,
					["minimumTimeLeft"] = false,
					["filterTimeLeft"] = 67,
					["sor"] = "T",
					["maxBars"] = 12,
					["timeInset"] = 16,
					["growDirection"] = false,
					["pointXR"] = 0.695312563578288,
					["wrap"] = 6,
					["timeFormat"] = 23,
					["desaturate"] = true,
					["detectBuffsCastBy"] = "anyone",
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["barHeight"] = 5,
					["pointY"] = 0.44629626196925,
					["iconInset"] = -15,
					["hideBar"] = true,
					["iconOffset"] = 7,
				},
				["TargetDebuffsExtra"] = {
					["detectDebuffsCastBy"] = "other",
					["detectNPCDebuffs"] = true,
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterDebuffTypes"] = true,
					["showNoDuration"] = true,
					["name"] = "TargetDebuffsExtra",
					["auto"] = true,
					["pointYT"] = 1.306887173901270e-007,
					["filterDebuffBars"] = true,
					["i_spacingX"] = 3,
					["filterDebuffBarGroup"] = "TargetDebuffs",
					["filterDebuffTable"] = "TargetExclusions",
					["pointW"] = 180.000030517578,
					["merged"] = true,
					["bars"] = {
					},
					["mergeInto"] = "TargetDebuffs",
					["i_spacingY"] = 15,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["detectInflictable"] = true,
					["pointX"] = 0.906249872843425,
					["detectDispellable"] = true,
					["detectVehicleDebuffs"] = true,
					["detectBoss"] = true,
					["detectDebuffsMonitor"] = "target",
					["pointH"] = 14.9999809265137,
					["pointXR"] = 1.112620035807290e-007,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["detectDebuffs"] = true,
					["pointY"] = 0.986110996513197,
					["i_iconSize"] = 30,
				},
				["ToTDebuffsExtra"] = {
					["detectDebuffsCastBy"] = "anyone",
					["detectNPCDebuffs"] = true,
					["noPlayerDebuffs"] = true,
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["mergeInto"] = "ToTDebuffs",
					["name"] = "ToTDebuffsExtra",
					["auto"] = true,
					["pointYT"] = 1.306887173901270e-007,
					["i_spacingX"] = -8,
					["pointW"] = 180.000030517578,
					["filterDebuffTable"] = "PlayerExclusions",
					["detectDispellable"] = true,
					["merged"] = true,
					["bars"] = {
					},
					["i_spacingY"] = -8,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["detectInflictable"] = true,
					["showNoDuration"] = true,
					["pointX"] = 0.906249872843425,
					["noTargetDebuffs"] = true,
					["filterDebuffTypes"] = true,
					["detectDebuffsMonitor"] = "targettarget",
					["detectVehicleDebuffs"] = true,
					["pointH"] = 14.9999809265137,
					["pointXR"] = 1.112620035807290e-007,
					["detectBoss"] = true,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["detectDebuffs"] = true,
					["pointY"] = 0.986110996513197,
				},
				["TargetDebuffs"] = {
					["backdropFill"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["parentFrame"] = "RealUITargetFrame",
					["showNoDuration"] = true,
					["name"] = "TargetDebuffs",
					["barColors"] = "Standard",
					["auto"] = true,
					["pointYT"] = 0.507407395882206,
					["i_iconSize"] = 30,
					["i_spacingX"] = 3,
					["pointW"] = 180.000030517578,
					["labelInset"] = 3,
					["detectOtherDebuffs"] = false,
					["iconColors"] = "Normal",
					["filterDebuffTable"] = "TargetExclusions",
					["filterDebuffList"] = {
					},
					["desaturate"] = true,
					["bars"] = {
					},
					["timeAlign"] = "RIGHT",
					["iconInset"] = 2,
					["i_spacingY"] = 15,
					["pointX"] = 0.695833269755046,
					["pointH"] = 15.0000133514404,
					["sor"] = "T",
					["filterDebuffTypes"] = false,
					["detectDebuffsMonitor"] = "target",
					["maxBars"] = 8,
					["pointXR"] = 0.210416714350382,
					["wrap"] = 10,
					["timeFormat"] = 23,
					["timeSort"] = false,
					["backdropColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterBuffTable"] = "PlayerExclusions",
					["detectDebuffs"] = true,
					["borderColor"] = {
						["a"] = 1,
						["b"] = 1,
						["g"] = 1,
						["r"] = 1,
					},
					["filterDebuffSpells"] = true,
					["pointY"] = 0.478703701296624,
				},
			},
			["Durations"] = {
				["Evasion"] = 15,
				[980] = 18,
				["Blade Twisting"] = 8,
				[121253] = 15,
				[130] = 30,
				[215479] = 21.839,
				["Jade Spirit"] = 12,
				[235450] = 60,
				[246261] = 15,
				[225719] = 12,
				["Grace"] = 15,
				["Food"] = 20,
				["Anticipation"] = 15,
				["Windswept Pages"] = 20,
				[122278] = 10,
				[12654] = 8.251,
				[118635] = 3,
				["Arcane Missiles!"] = 20,
				[212799] = 13,
				[48108] = 15,
				[240692] = 6,
				["Revealing Strike"] = 15,
				["Paralytic Poison"] = 15,
				["Leeching Poison"] = 3600.022,
				["Shallow Insight"] = 15,
				["Recently Bandaged"] = 60,
				[196608] = 10.4,
				["River's Song"] = 7,
				["Kidney Shot"] = 2,
				["Deserter"] = 900,
				["Enlightenment"] = 10,
				["First Aid"] = 8,
				[48438] = 7,
				["Adrenaline Rush"] = 20,
				[12051] = 4.639,
				["Rejuvenation"] = 12.597,
				["Cheap Shot"] = 4,
				[108366] = 15,
				["Cloak of Shadows"] = 5,
				["Garrote"] = 18,
				[48107] = 7.601,
				[226757] = 8.409,
				["Earthbind"] = 5,
				["Tricks of the Trade"] = 6,
				[225774] = 12,
				["Rupture"] = 12,
				["Combat Readiness"] = 20,
				[225574] = 4,
				[194316] = 6,
				["Dancing Steel"] = 12,
				["Vendetta"] = 20,
				["Honorless Target"] = 30,
				["Drink"] = 20,
				[2479] = 30,
				[124274] = 12.999,
				[123725] = 16,
				[213341] = 21,
				[214373] = 4.5,
				[157644] = 15.002,
				[207472] = 30,
				[225776] = 8,
				["Deep Insight"] = 15,
				["Recuperate"] = 24,
				["Weakened Soul"] = 15,
				[119085] = 10,
				[195630] = 10,
				["Hurricane"] = 12,
				["Sprint"] = 8,
				[195472] = 20,
				["Hand of Protection"] = 10,
				[124275] = 0.999,
				[194329] = 6,
				["Frostbolt"] = 9,
				["Slice and Dice"] = 27,
				["Killing Spree"] = 2,
				["Plague of Ages"] = 9,
				["Resurrection Sickness"] = 600,
				["Deadly Poison"] = 3600.022,
				[210824] = 6,
				["Blind"] = 60,
				[228128] = 60,
				["Moderate Insight"] = 15,
				["Eye of Vengeance"] = 10,
				[213063] = 6,
				[79683] = 20,
				["Blindside"] = 10,
				["Harmony"] = 20,
				[116189] = 3,
				["Arrow of Time"] = 20,
				["Forbearance"] = 60,
				["Vanish"] = 3,
				[194522] = 11.7,
				[120954] = 15,
				["Power Word: Shield"] = 15,
				[116847] = 7.116,
				["Paralysis"] = 4,
				[227678] = 3,
				[213177] = 15,
				[214326] = 3,
			},
			["muteSFX"] = true,
			["Conditions"] = {
				["HUNTER"] = {
					["Check Aspect!"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["levelRanged"] = 1,
								["minComboPoints"] = 5,
								["level"] = 80,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["Aspect Missing"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["levelRanged"] = 1,
								["minComboPoints"] = 5,
								["level"] = 80,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["No Pet!"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["levelRanged"] = 1,
								["minComboPoints"] = 5,
								["level"] = 80,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["Trueshot Aura Missing"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["levelRanged"] = 1,
								["minComboPoints"] = 5,
								["level"] = 80,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
				},
				["DEMONHUNTER"] = {
				},
				["ROGUE"] = {
					["Lethal Poison Missing"] = {
						["associatedSpell"] = "#2823",
						["tests"] = {
							["Player Status"] = {
								["inInstance"] = true,
								["isMounted"] = 0,
								["inGroup"] = true,
								["inCombat"] = 0,
								["checkLevel"] = true,
								["inArena"] = true,
								["inBattleground"] = true,
							},
						},
					},
					["Non-Lethal Poison Missing"] = {
						["associatedSpell"] = "#5761",
						["tests"] = {
							["Player Status"] = {
								["inInstance"] = true,
								["isMounted"] = 0,
								["inGroup"] = true,
								["checkLevel"] = true,
								["inArena"] = true,
								["inBattleground"] = true,
							},
						},
					},
				},
				["SHAMAN"] = {
					["Weapon Buff Missing"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["level"] = 80,
								["minComboPoints"] = 5,
								["levelRanged"] = 1,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["Cleanse Spirit (Curse)"] = {
						["tests"] = {
							["Debuff Type"] = {
								["toggle"] = false,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["Shield Missing"] = {
						["tests"] = {
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["level"] = 80,
								["minComboPoints"] = 5,
								["levelRanged"] = 1,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
					["Cleanse Spirit (Magic)"] = {
						["tests"] = {
							["Debuff Type"] = {
								["toggle"] = false,
							},
							["Spell Ready"] = {
								["notUsable"] = false,
								["gcd"] = false,
							},
							["Player Status"] = {
								["levelOffHand"] = 1,
								["minShards"] = 1,
								["levelMainHand"] = 1,
								["minEclipsePower"] = 0,
								["minHolyPower"] = 1,
								["level"] = 80,
								["minComboPoints"] = 5,
								["levelRanged"] = 1,
								["minPower"] = 100,
								["minHealth"] = 100,
							},
						},
						["result"] = false,
						["testResult"] = false,
					},
				},
			},
		},
		["Wildrivers - Arthas"] = {
		},
		["Serenerivers - Sargeras"] = {
		},
		["Blindrivers - Sargeras"] = {
			["Conditions"] = {
				["DEMONHUNTER"] = {
				},
			},
		},
	},
}
