
REKeysSettings = {
	["MinimapButtonSettings"] = {
		["hide"] = false,
	},
	["OfflinePlayers"] = false,
	["ResetTimestamp"] = 228061,
	["FullDungeonName"] = false,
	["PinnedCharacters"] = {
	},
	["ChatQueryGuild"] = true,
	["CurrentWeek"] = 3,
	["ServerTimestamp"] = 1703012232,
	["ChatQuery"] = true,
	["ChatQueryGroup"] = true,
	["Sorting"] = 1,
}
REKeysDB2 = {
	["Keydan"] = {
		["MapID"] = 464,
		["Rating"] = 2741,
		["Faction"] = "",
		["Fresh"] = true,
		["Level"] = 20,
		["Class"] = "DRUID",
		["Group"] = false,
	},
	["Urklesnurkle"] = {
		["MapID"] = 463,
		["Group"] = false,
		["Faction"] = "",
		["Fresh"] = true,
		["Rating"] = 2588,
		["Class"] = "MAGE",
		["Level"] = 23,
	},
	["Flumina"] = {
		["MapID"] = 456,
		["Group"] = false,
		["Faction"] = "Horde",
		["Fresh"] = false,
		["Rating"] = 68,
		["Class"] = "PRIEST",
		["Level"] = 2,
	},
	["Errsa"] = {
		["MapID"] = 198,
		["Fresh"] = false,
		["Faction"] = "",
		["Group"] = false,
		["Level"] = 23,
		["Class"] = "DRUID",
		["Rating"] = 2871,
	},
	["Sunfyre"] = {
		["MapID"] = 464,
		["Level"] = 18,
		["Faction"] = "",
		["Group"] = false,
		["Rating"] = 2586,
		["Class"] = "EVOKER",
		["Fresh"] = false,
	},
	["Headcut"] = {
		["MapID"] = 464,
		["Rating"] = 2286,
		["Faction"] = "Alliance",
		["Fresh"] = false,
		["Level"] = 17,
		["Class"] = "SHAMAN",
		["Group"] = true,
	},
	["Erixi"] = {
		["MapID"] = 456,
		["Group"] = false,
		["Faction"] = "",
		["Fresh"] = false,
		["Rating"] = 2516,
		["Class"] = "SHAMAN",
		["Level"] = 19,
	},
	["Xerimok"] = {
		["MapID"] = 248,
		["Rating"] = 2506,
		["Faction"] = "",
		["Fresh"] = true,
		["Level"] = 20,
		["Class"] = "EVOKER",
		["Group"] = false,
	},
	["Kadria"] = {
		["MapID"] = 244,
		["Fresh"] = true,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 19,
		["Class"] = "DRUID",
		["Rating"] = 2829,
	},
	["Riparium"] = {
		["MapID"] = 199,
		["Fresh"] = true,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 21,
		["Class"] = "WARLOCK",
		["Rating"] = 2964,
	},
	["Rylacus"] = {
		["MapID"] = 456,
		["Level"] = 21,
		["Faction"] = "",
		["Group"] = true,
		["Rating"] = 2425,
		["Class"] = "ROGUE",
		["Fresh"] = false,
	},
	["Giulietta"] = {
		["MapID"] = 463,
		["Group"] = false,
		["Faction"] = "",
		["Fresh"] = true,
		["Rating"] = 2830,
		["Class"] = "WARRIOR",
		["Level"] = 21,
	},
	["Heikuro"] = {
		["MapID"] = 464,
		["Rating"] = 2876,
		["Faction"] = "",
		["Fresh"] = false,
		["Level"] = 21,
		["Class"] = "DEMONHUNTER",
		["Group"] = true,
	},
	["Emptyrivers"] = {
		["MapID"] = 248,
		["Group"] = false,
		["Faction"] = "Horde",
		["Fresh"] = false,
		["Rating"] = 352,
		["Class"] = "MAGE",
		["Level"] = 7,
	},
}
