
REKeysSettings = {
	["MinimapButtonSettings"] = {
		["hide"] = false,
	},
	["OfflinePlayers"] = false,
	["ResetTimestamp"] = 150501,
	["FullDungeonName"] = false,
	["PinnedCharacters"] = {
	},
	["ChatQueryGuild"] = true,
	["CurrentWeek"] = 0,
	["ServerTimestamp"] = 1686080120,
	["ChatQuery"] = true,
	["ChatQueryGroup"] = true,
	["Sorting"] = 1,
}
REKeysDB2 = {
	["Keydan"] = {
		["MapID"] = 404,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 19,
		["Class"] = "DRUID",
		["Rating"] = 2333,
	},
	["Flumina"] = {
		["MapID"] = 245,
		["Group"] = false,
		["Faction"] = "Horde",
		["Fresh"] = true,
		["Rating"] = 2352,
		["Class"] = "PRIEST",
		["Level"] = 20,
	},
	["Sunfyre"] = {
		["MapID"] = 404,
		["Rating"] = 2154,
		["Fresh"] = false,
		["Level"] = 20,
		["Class"] = "EVOKER",
		["Group"] = true,
	},
	["Malleuss"] = {
		["MapID"] = 404,
		["Fresh"] = true,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 19,
		["Class"] = "PALADIN",
		["Rating"] = 2483,
	},
	["Euryi"] = {
		["MapID"] = 404,
		["Fresh"] = false,
		["Faction"] = "Horde",
		["Group"] = false,
		["Level"] = 20,
		["Class"] = "MONK",
		["Rating"] = 2427,
	},
	["Xerimok"] = {
		["MapID"] = 251,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 16,
		["Class"] = "EVOKER",
		["Rating"] = 1759,
	},
	["Kadria"] = {
		["MapID"] = 405,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 20,
		["Class"] = "DRUID",
		["Rating"] = 2482,
	},
	["Erixi"] = {
		["MapID"] = 406,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 16,
		["Class"] = "SHAMAN",
		["Rating"] = 1613,
	},
	["Rylacus"] = {
		["MapID"] = 251,
		["Group"] = false,
		["Fresh"] = false,
		["Rating"] = 215,
		["Class"] = "ROGUE",
		["Level"] = 13,
	},
	["Giulietta"] = {
		["MapID"] = 438,
		["Fresh"] = true,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 18,
		["Class"] = "WARRIOR",
		["Rating"] = 2046,
	},
	["Tinoke"] = {
		["MapID"] = 406,
		["Group"] = false,
		["Fresh"] = false,
		["Rating"] = 0,
		["Class"] = "PRIEST",
		["Level"] = 2,
	},
}
