
REKeysSettings = {
	["MinimapButtonSettings"] = {
		["hide"] = false,
	},
	["OfflinePlayers"] = false,
	["ResetTimestamp"] = 409814,
	["FullDungeonName"] = false,
	["PinnedCharacters"] = {
	},
	["ChatQueryGuild"] = true,
	["CurrentWeek"] = 0,
	["ServerTimestamp"] = 1686080120,
	["ChatQuery"] = true,
	["ChatQueryGroup"] = true,
	["Sorting"] = 1,
}
REKeysDB2 = {
	["Keydan"] = {
		["MapID"] = 404,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 19,
		["Class"] = "DRUID",
		["Rating"] = 2333,
	},
	["Xerimok"] = {
		["MapID"] = 251,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 16,
		["Class"] = "EVOKER",
		["Rating"] = 1759,
	},
	["Flumina"] = {
		["MapID"] = 251,
		["Group"] = false,
		["Faction"] = "Horde",
		["Fresh"] = true,
		["Rating"] = 2339,
		["Class"] = "PRIEST",
		["Level"] = 19,
	},
	["Erixi"] = {
		["MapID"] = 406,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 16,
		["Class"] = "SHAMAN",
		["Rating"] = 1613,
	},
	["Kadria"] = {
		["MapID"] = 438,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 19,
		["Class"] = "DRUID",
		["Rating"] = 2339,
	},
	["Giulietta"] = {
		["MapID"] = 206,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = true,
		["Level"] = 17,
		["Class"] = "WARRIOR",
		["Rating"] = 1831,
	},
	["Euryi"] = {
		["MapID"] = 404,
		["Fresh"] = false,
		["Faction"] = "Horde",
		["Group"] = true,
		["Level"] = 20,
		["Class"] = "MONK",
		["Rating"] = 2333,
	},
	["Malleuss"] = {
		["MapID"] = 404,
		["Fresh"] = false,
		["Faction"] = "Alliance",
		["Group"] = false,
		["Level"] = 19,
		["Class"] = "PALADIN",
		["Rating"] = 2380,
	},
}
