
SenseiClassResourceBarDB = {
["_Settings"] = {
["HealthColors"] = {
},
["PowerColors"] = {
},
},
["SecondaryResourceBarDB"] = {
["Modern"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["hideManaOnRole"] = {
},
["tickThickness"] = 1,
["textFormat"] = "Current",
["maskAndBorderStyle"] = "Thin",
["y"] = -40,
["font"] = "Fonts\\FRIZQT__.TTF",
["showText"] = true,
["height"] = 15,
["barStrata"] = "MEDIUM",
["showTicks"] = true,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideBlizzardSecondaryResourceUi"] = false,
["showFragmentedPowerBarText"] = false,
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["backgroundStyle"] = "SCRB Semi-transparent",
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["width"] = 200,
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["hideWhileMountedOrVehicule"] = false,
["widthMode"] = "Manual",
["useResourceAtlas"] = false,
["foregroundStyle"] = "SCRB FG Fade Left",
["textAlign"] = "CENTER",
["x"] = 0,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["gamepad"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["showManaAsPercent"] = true,
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["hideManaOnRole"] = {
["DAMAGER"] = true,
},
["tickThickness"] = 1,
["textFormat"] = "Current",
["maskAndBorderStyle"] = "Thin",
["y"] = -234,
["font"] = "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSansCondensed-Heavy.ttf",
["showText"] = true,
["height"] = 15,
["barStrata"] = "MEDIUM",
["showTicks"] = true,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 0.97,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideBlizzardSecondaryResourceUi"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["backgroundStyle"] = "SCRB Semi-transparent",
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["width"] = 200,
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["hideWhileMountedOrVehicule"] = false,
["widthMode"] = "Sync With Essential Cooldowns",
["useResourceAtlas"] = true,
["foregroundStyle"] = "SCRB FG Fade Left",
["textAlign"] = "CENTER",
["x"] = 0,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["Main"] = {
["backgroundStyle"] = "SCRB Semi-transparent",
["showManaAsPercent"] = false,
["barVisible"] = "Always Visible",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideManaOnRole"] = {
},
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = -40,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 15,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["showTicks"] = true,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["hideBlizzardSecondaryResourceUi"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textPrecision"] = "12",
["textFormat"] = "Current",
["tickThickness"] = 1,
["font"] = "Fonts\\FRIZQT__.TTF",
["width"] = 200,
["fragmentedPowerBarTextPrecision"] = "12.3",
["fontOutline"] = "OUTLINE",
["widthMode"] = "Manual",
["positionMode"] = "Self",
["useResourceAtlas"] = false,
["textAlign"] = "CENTER",
["hideWhileMountedOrVehicule"] = false,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
},
["healthBarDB"] = {
["Modern"] = {
["backgroundStyle"] = "SCRB Semi-transparent",
["barVisible"] = "Hidden",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["textFormat"] = "Current",
["maskAndBorderStyle"] = "Thin",
["y"] = 40,
["font"] = "Fonts\\FRIZQT__.TTF",
["showText"] = true,
["height"] = 15,
["barStrata"] = "MEDIUM",
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["hideHealthOnRole"] = {
},
["showFragmentedPowerBarText"] = false,
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["hideBlizzardPlayerContainerUi"] = false,
["width"] = 200,
["fragmentedPowerBarTextPrecision"] = "12.3",
["fontOutline"] = "OUTLINE",
["hideWhileMountedOrVehicule"] = false,
["x"] = 0,
["widthMode"] = "Manual",
["textAlign"] = "CENTER",
["useClassColor"] = true,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["gamepad"] = {
["backgroundStyle"] = "SCRB Semi-transparent",
["barVisible"] = "Always Visible",
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["textFormat"] = "Percent%",
["maskAndBorderStyle"] = "Thin",
["y"] = -265,
["font"] = "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSansCondensed-Heavy.ttf",
["showText"] = true,
["height"] = 17,
["barStrata"] = "MEDIUM",
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 0.9699999690055847,
["minWidth"] = 0,
["smoothProgress"] = true,
["hideHealthOnRole"] = {
},
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12.3",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["foregroundStyle"] = "Clean",
["hideBlizzardPlayerContainerUi"] = false,
["width"] = 200,
["fragmentedPowerBarTextPrecision"] = "12.3",
["fontOutline"] = "OUTLINE",
["hideWhileMountedOrVehicule"] = false,
["x"] = 0,
["widthMode"] = "Sync With Essential Cooldowns",
["textAlign"] = "CENTER",
["useClassColor"] = true,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["Main"] = {
["backgroundStyle"] = "SCRB Semi-transparent",
["barVisible"] = "Hidden",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = 40,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 15,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["hideHealthOnRole"] = {
},
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textPrecision"] = "12",
["positionMode"] = "Self",
["textFormat"] = "Current",
["hideBlizzardPlayerContainerUi"] = false,
["width"] = 200,
["font"] = "Fonts\\FRIZQT__.TTF",
["fragmentedPowerBarTextPrecision"] = "12.3",
["fontOutline"] = "OUTLINE",
["widthMode"] = "Manual",
["hideWhileMountedOrVehicule"] = false,
["textAlign"] = "CENTER",
["useClassColor"] = true,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
},
["PrimaryResourceBarDB"] = {
["Modern"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["showManaAsPercent"] = false,
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["hideManaOnRole"] = {
},
["tickThickness"] = 1,
["textFormat"] = "Current",
["maskAndBorderStyle"] = "Thin",
["y"] = 0,
["font"] = "Fonts\\FRIZQT__.TTF",
["showText"] = true,
["height"] = 15,
["barStrata"] = "MEDIUM",
["showTicks"] = true,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["backgroundStyle"] = "SCRB Semi-transparent",
["width"] = 200,
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["widthMode"] = "Manual",
["useResourceAtlas"] = false,
["foregroundStyle"] = "SCRB FG Fade Left",
["textAlign"] = "CENTER",
["x"] = 0,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["gamepad"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["showManaAsPercent"] = true,
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["hideManaOnRole"] = {
},
["tickThickness"] = 1,
["textFormat"] = "Current",
["maskAndBorderStyle"] = "Thin",
["y"] = -249,
["font"] = "Interface\\AddOns\\WeakAuras_SharedMedia\\Fonts\\FiraSansCondensed-Heavy.ttf",
["showText"] = true,
["height"] = 15,
["barStrata"] = "MEDIUM",
["showTicks"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 0.97,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["textColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["backgroundStyle"] = "SCRB Semi-transparent",
["width"] = 200,
["backgroundColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["widthMode"] = "Sync With Essential Cooldowns",
["useResourceAtlas"] = true,
["foregroundStyle"] = "Clean",
["textAlign"] = "CENTER",
["x"] = 0,
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
["Main"] = {
["backgroundStyle"] = "SCRB Semi-transparent",
["showManaAsPercent"] = false,
["barVisible"] = "Always Visible",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["hideManaOnRole"] = {
},
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = 0,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 15,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["showTicks"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["scale"] = 1,
["minWidth"] = 0,
["smoothProgress"] = true,
["tickColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["textFormat"] = "Current",
["width"] = 200,
["useResourceAtlas"] = false,
["font"] = "Fonts\\FRIZQT__.TTF",
["fragmentedPowerBarTextPrecision"] = "12.3",
["fontOutline"] = "OUTLINE",
["widthMode"] = "Manual",
["textAlign"] = "CENTER",
["tickThickness"] = 1,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
},
["tertiaryResourceBarDB"] = {
["Modern"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = -80,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 15,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["widthMode"] = "Manual",
["minWidth"] = 0,
["smoothProgress"] = true,
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["width"] = 200,
["textFormat"] = "Current",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Fonts\\FRIZQT__.TTF",
["backgroundStyle"] = "SCRB Semi-transparent",
["scale"] = 1,
["textAlign"] = "CENTER",
["useResourceAtlas"] = false,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["gamepad"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = -223,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 3,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["widthMode"] = "Sync With Essential Cooldowns",
["minWidth"] = 0,
["smoothProgress"] = true,
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["width"] = 200,
["textFormat"] = "Current",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Fonts\\FRIZQT__.TTF",
["backgroundStyle"] = "SCRB Semi-transparent",
["scale"] = 0.97,
["textAlign"] = "CENTER",
["useResourceAtlas"] = false,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
["Main"] = {
["fragmentedPowerBarTextPrecision"] = "12.3",
["barVisible"] = "Always Visible",
["fontOutline"] = "OUTLINE",
["backgroundColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["foregroundStyle"] = "SCRB FG Fade Left",
["maskAndBorderStyle"] = "Thin",
["y"] = -80,
["x"] = 0,
["showText"] = true,
["relativeFrame"] = "UIParent",
["height"] = 15,
["barStrata"] = "MEDIUM",
["useStatusBarColorForBackgroundColor"] = false,
["fontSize"] = 12,
["point"] = "CENTER",
["fasterUpdates"] = true,
["widthMode"] = "Manual",
["minWidth"] = 0,
["smoothProgress"] = true,
["hideWhileMountedOrVehicule"] = false,
["showFragmentedPowerBarText"] = false,
["relativePoint"] = "CENTER",
["enableOverlayToggle"] = true,
["settingsMaxHeight"] = 864,
["fillDirection"] = "Left to Right",
["textPrecision"] = "12",
["fragmentedPowerBarTextColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["width"] = 200,
["textFormat"] = "Current",
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Fonts\\FRIZQT__.TTF",
["backgroundStyle"] = "SCRB Semi-transparent",
["scale"] = 1,
["textAlign"] = "CENTER",
["useResourceAtlas"] = false,
["textColor"] = {
["a"] = 1,
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
},
},
}
