
SexyMap2DB = {
["Emptyrivers-Argent Dawn"] = "global",
["global"] = {
["ping"] = {
["showPing"] = false,
["showAt"] = "map",
},
["coordinates"] = {
["enabled"] = false,
["fontColor"] = {
},
["xOffset"] = 0,
["monochrome"] = false,
["updateRate"] = 1,
["yOffset"] = 10,
["font"] = "Friz Quadrata TT",
["borderColor"] = {
},
["coordPrecision"] = "%d,%d",
["backgroundColor"] = {
},
["outline"] = "NONE",
},
["buttons"] = {
["radius"] = 10,
["lockDragging"] = false,
["allowDragging"] = true,
["scale"] = 1,
["dragPositions"] = {
["MiniMapInstanceDifficulty"] = 189.3120598655419,
["MiniMapMailFrame"] = 117.4664340830166,
["GarrisonLandingPageMinimapButton"] = 68.75580893550124,
["GameTimeFrame"] = -17.20790834338396,
["MiniMapTracking"] = 53.32499422175006,
["AddonCompartmentFrame"] = -69.6121590897964,
},
["visibilitySettings"] = {
["AddonCompartmentFrame"] = "never",
["LibDBIcon10_BugSack"] = "always",
["LibDBIcon10_RaiderIO"] = "always",
["LibDBIcon10_BlizzHUDTweaks"] = "always",
["CraftingOrder"] = "always",
["LibDBIcon10_MythicDungeonTools"] = "always",
["GarrisonLandingPageMinimapButton"] = "hover",
["LibDBIcon10_Details"] = "always",
["LibDBIcon10_tdBattlePetScript"] = "always",
["MiniMapMailFrame"] = "always",
["LibDBIcon10_MinArch"] = "always",
["LibDBIcon10_SavedInstances"] = "always",
["LibDBIcon10_AlterEgo"] = "always",
["MiniMapInstanceDifficulty"] = "hover",
["LibDBIcon10_WeeklyKnowledge"] = "always",
["MinimapZoomIn"] = "never",
["LibDBIcon10_BountyHelper"] = "always",
["MinimapZoomOut"] = "never",
["GameTimeFrame"] = "never",
["MiniMapWorldMapButton"] = "never",
["TimeManagerClockButton"] = "always",
["SexyMapZoneTextButton"] = "always",
["LibDBIcon10_NumyAddonProfiler"] = "always",
["LibDBIcon10_SimulationCraft"] = "always",
["LibDBIcon10_DetailsStreamer"] = "always",
["MiniMapTracking"] = "hover",
["LibDBIcon10_CopyPasta2"] = "always",
["LibDBIcon10_WeakAuras"] = "always",
["LibDBIcon10_Plater"] = "always",
},
["controlVisibility"] = true,
},
["movers"] = {
["lockTopWidget"] = false,
["moveTopWidget"] = false,
["lockCaptureBar"] = false,
["moveCaptureBar"] = false,
["moverPositions"] = {
},
},
["clock"] = {
["bgColor"] = {
["a"] = 0.5215672254562378,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Fira Sans Condensed Black",
["fontColor"] = {
},
["borderColor"] = {
["a"] = 0.4980928599834442,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["xOffset"] = 0,
["monochrome"] = false,
["outline"] = "NONE",
["yOffset"] = 160,
},
["borders"] = {
["applyPreset"] = false,
["borders"] = {
},
["backdrop"] = {
["show"] = true,
["textureColor"] = {
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["settings"] = {
["edgeSize"] = 17,
["edgeFile"] = 137057,
["bgFile"] = 137056,
["tile"] = false,
["insets"] = {
["top"] = 4,
["right"] = 4,
["left"] = 4,
["bottom"] = 4,
},
},
["borderColor"] = {
},
["scale"] = 1.07,
},
["hideBlizzard"] = true,
},
["zonetext"] = {
["outline"] = "OUTLINE",
["fontColor"] = {
["a"] = 1,
["b"] = 0.9411765336990356,
["g"] = 0.8000000715255737,
["r"] = 0.4117647409439087,
},
["xOffset"] = 0,
["monochrome"] = false,
["yOffset"] = -145,
["bgColor"] = {
["a"] = 0.3044307231903076,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Fira Sans Black",
["useSecureButton"] = false,
["borderColor"] = {
["a"] = 0,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["width"] = 138,
["fontsize"] = 9,
},
["core"] = {
["clamp"] = true,
["point"] = "BOTTOMRIGHT",
["relpoint"] = "BOTTOMRIGHT",
["autoZoom"] = 5,
["northTag"] = true,
["y"] = 5.375280857086182,
["x"] = -8.71573543548584,
["lock"] = false,
["scale"] = 1.71,
["shape"] = 130871,
["rightClickToConfig"] = true,
},
},
["Esker-Kel'Thuzad"] = "global",
["Estuary-Argent Dawn"] = {
["core"] = {
["clamp"] = true,
["lock"] = false,
["shape"] = "Interface\\AddOns\\SexyMap\\shapes\\circle.tga",
["northTag"] = true,
["autoZoom"] = 5,
["rightClickToConfig"] = true,
},
["coordinates"] = {
["enabled"] = true,
["fontColor"] = {
},
["xOffset"] = 0,
["monochrome"] = false,
["updateRate"] = 1,
["yOffset"] = 10,
["font"] = "Friz Quadrata TT",
["borderColor"] = {
},
["coordPrecision"] = "%d,%d",
["backgroundColor"] = {
},
["outline"] = "NONE",
},
["movers"] = {
["lockTopWidget"] = false,
["moveTopWidget"] = false,
["lockCaptureBar"] = false,
["moveCaptureBar"] = false,
["moverPositions"] = {
},
},
["buttons"] = {
["radius"] = 10,
["lockDragging"] = false,
["allowDragging"] = true,
["scale"] = 1,
["dragPositions"] = {
},
["visibilitySettings"] = {
["MinimapZoomIn"] = "never",
["MiniMapMailFrame"] = "always",
["MiniMapWorldMapButton"] = "never",
["MinimapZoomOut"] = "never",
["AddonCompartmentFrame"] = "never",
["GarrisonLandingPageMinimapButton"] = "always",
["CraftingOrder"] = "always",
["TimeManagerClockButton"] = "always",
["SexyMapZoneTextButton"] = "always",
},
["controlVisibility"] = true,
},
["clock"] = {
["bgColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Friz Quadrata TT",
["fontColor"] = {
},
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["xOffset"] = 0,
["monochrome"] = false,
["outline"] = "NONE",
["yOffset"] = 0,
},
["borders"] = {
["applyPreset"] = false,
["borders"] = {
{
["name"] = "Rune 1",
["r"] = 0.3098039215686275,
["scale"] = 1.4,
["rotSpeed"] = -30,
["g"] = 0.4784313725490196,
["texture"] = 165630,
},
{
["a"] = 0.3799999952316284,
["rotSpeed"] = 60,
["r"] = 0.196078431372549,
["scale"] = 2.1,
["name"] = "Rune 2",
["g"] = 0.2901960784313725,
["texture"] = 165638,
},
{
["a"] = 0.3,
["name"] = "Fade",
["r"] = 0,
["scale"] = 1.6,
["g"] = 0.2235294117647059,
["texture"] = 167062,
},
},
["backdrop"] = {
["show"] = false,
["textureColor"] = {
},
["settings"] = {
["bgFile"] = "Interface\\Tooltips\\UI-Tooltip-Background",
["edgeFile"] = "Interface\\Tooltips\\UI-Tooltip-Border",
["tile"] = false,
["edgeSize"] = 16,
["insets"] = {
["top"] = 4,
["right"] = 4,
["left"] = 4,
["bottom"] = 4,
},
},
["borderColor"] = {
},
["scale"] = 1,
},
["hideBlizzard"] = true,
},
["zonetext"] = {
["outline"] = "NONE",
["fontColor"] = {
},
["xOffset"] = 0,
["monochrome"] = false,
["yOffset"] = 0,
["bgColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
["font"] = "Friz Quadrata TT",
["useSecureButton"] = false,
["borderColor"] = {
["a"] = 1,
["b"] = 0,
["g"] = 0,
["r"] = 0,
},
},
["ping"] = {
["showPing"] = true,
["showAt"] = "map",
},
},
["presets"] = {
},
}
