
ShadowedUFDB = {
["namespaces"] = {
},
["global"] = {
["infoID"] = 3,
},
["profileKeys"] = {
["Loess - Kel'Thuzad"] = "Default",
["Dukasuka - Eredar"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Doneer - Eredar"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["profiles"] = {
["Default"] = {
["powerColors"] = {
["FUEL"] = {
["r"] = 0.85,
["g"] = 0.47,
["b"] = 0.36,
},
["ALTERNATE"] = {
["r"] = 0.815,
["g"] = 0.941,
["b"] = 1,
},
["FOCUS"] = {
["r"] = 1,
["g"] = 0.5,
["b"] = 0.25,
},
["STAGGER_GREEN"] = {
["r"] = 0.52,
["g"] = 1,
["b"] = 0.52,
},
["CHI"] = {
["r"] = 0.71,
["g"] = 1,
["b"] = 0.92,
},
["STAGGER_RED"] = {
["r"] = 1,
["g"] = 0.42,
["b"] = 0.42,
},
["ARCANECHARGES"] = {
["r"] = 0.1,
["g"] = 0.1,
["b"] = 0.98,
},
["COMBOPOINTS"] = {
["r"] = 1,
["g"] = 0.8,
["b"] = 0,
},
["RUNES"] = {
["r"] = 0.5,
["g"] = 0.5,
["b"] = 0.5,
},
["RUNEOFPOWER"] = {
["r"] = 0.35,
["g"] = 0.45,
["b"] = 0.6,
},
["ENERGY"] = {
["r"] = 1,
["g"] = 0.85,
["b"] = 0.1,
},
["MANA"] = {
["r"] = 0.3,
["g"] = 0.5,
["b"] = 0.85,
},
["AURAPOINTS"] = {
["r"] = 1,
["g"] = 0.8,
["b"] = 0,
},
["MUSHROOMS"] = {
["r"] = 0.2,
["g"] = 0.9,
["b"] = 0.2,
},
["INSANITY"] = {
["r"] = 0.4,
["g"] = 0,
["b"] = 0.8,
},
["MAELSTROM"] = {
["r"] = 0,
["g"] = 0.5,
["b"] = 1,
},
["FURY"] = {
["r"] = 0.788,
["g"] = 0.259,
["b"] = 0.992,
},
["SOULSHARDS"] = {
["r"] = 0.58,
["g"] = 0.51,
["b"] = 0.79,
},
["RUNIC_POWER"] = {
["b"] = 0.6,
["g"] = 0.45,
["r"] = 0.35,
},
["AMMOSLOT"] = {
["r"] = 0.85,
["g"] = 0.6,
["b"] = 0.55,
},
["LUNAR_POWER"] = {
["r"] = 0.3,
["g"] = 0.52,
["b"] = 0.9,
},
["PAIN"] = {
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
["STATUE"] = {
["r"] = 0.35,
["g"] = 0.45,
["b"] = 0.6,
},
["ESSENCE"] = {
["r"] = 0.4,
["g"] = 0.8,
["b"] = 1,
},
["HOLYPOWER"] = {
["r"] = 0.95,
["g"] = 0.9,
["b"] = 0.6,
},
["STAGGER_YELLOW"] = {
["r"] = 1,
["g"] = 0.98,
["b"] = 0.72,
},
["RAGE"] = {
["r"] = 0.9,
["g"] = 0.2,
["b"] = 0.3,
},
},
["advanced"] = true,
["healthColors"] = {
["aggro"] = {
["r"] = 0.9,
["g"] = 0,
["b"] = 0,
},
["yellow"] = {
["r"] = 0.93,
["g"] = 0.93,
["b"] = 0,
},
["neutral"] = {
["r"] = 0.93,
["g"] = 0.93,
["b"] = 0,
},
["static"] = {
["r"] = 0.7,
["g"] = 0.2,
["b"] = 0.9,
},
["friendly"] = {
["r"] = 0.2,
["g"] = 0.9,
["b"] = 0.2,
},
["offline"] = {
["r"] = 0.5,
["g"] = 0.5,
["b"] = 0.5,
},
["incAbsorb"] = {
["r"] = 0.93,
["g"] = 0.75,
["b"] = 0.09,
},
["tapped"] = {
["r"] = 0.5,
["g"] = 0.5,
["b"] = 0.5,
},
["hostile"] = {
["r"] = 0.9,
["g"] = 0,
["b"] = 0,
},
["green"] = {
["r"] = 0.2,
["g"] = 0.9,
["b"] = 0.2,
},
["enemyUnattack"] = {
["r"] = 0.6,
["g"] = 0.2,
["b"] = 0.2,
},
["healAbsorb"] = {
["r"] = 0.68,
["g"] = 0.47,
["b"] = 1,
},
["inc"] = {
["r"] = 0,
["g"] = 0.35,
["b"] = 0.23,
},
["red"] = {
["r"] = 0.9,
["g"] = 0,
["b"] = 0,
},
},
["xpColors"] = {
["normal"] = {
["r"] = 0.58,
["g"] = 0,
["b"] = 0.55,
},
["rested"] = {
["r"] = 0,
["g"] = 0.39,
["b"] = 0.88,
},
},
["locked"] = true,
["auraIndicators"] = {
["indicators"] = {
["tr"] = {
["width"] = 14,
["height"] = 14,
},
["tl"] = {
["width"] = 10,
["height"] = 10,
},
["bl"] = {
["width"] = 10,
["height"] = 10,
},
["br"] = {
["width"] = 10,
["height"] = 10,
},
},
["auras"] = {
["156322"] = "{b=0.48627454042435;group=\"Paladin\";indicator=\"tl\";g=0.76862752437592;alpha=1;player=true;r=0.83529418706894;missing=false;duration=true;priority=0;icon=false;iconTexture=135433;}",
["53563"] = "{r=0.64313725490196;group=\"Paladin\";indicator=\"tr\";g=0.24705882352941;player=true;b=0.73333333333333;alpha=1;duration=false;priority=100;icon=true;iconTexture=\"Interface\\\\Icons\\\\Ability_Paladin_BeaconofLight\";}",
["156910"] = "{r=0;group=\"Paladin\";indicator=\"tr\";g=0;player=true;b=0;priority=0;icon=true;iconTexture=1030095;}",
},
},
["positions"] = {
["arenatarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["mainassisttarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["targettargettarget"] = {
["anchorPoint"] = "RC",
["anchorTo"] = "#SUFUnittargettarget",
},
["arenatargettarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["targettarget"] = {
["anchorPoint"] = "TL",
["anchorTo"] = "#SUFUnittarget",
},
["arenapet"] = {
["anchorPoint"] = "RB",
["anchorTo"] = "$parent",
},
["mainassisttargettarget"] = {
["anchorPoint"] = "RT",
["x"] = 150,
["anchorTo"] = "$parent",
},
["party"] = {
["y"] = 301.7499908804894,
["x"] = -248.4999924898148,
["point"] = "BOTTOMRIGHT",
["bottom"] = 334.2767132251011,
["top"] = 511.0667728845801,
["relativePoint"] = "BOTTOM",
},
["maintanktarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["focus"] = {
["y"] = -131.9833906339909,
["x"] = -267.5831269838836,
["point"] = "RIGHT",
["relativePoint"] = "RIGHT",
},
["target"] = {
["y"] = 230.7499930262566,
["x"] = 177.499994635582,
["point"] = "BOTTOMLEFT",
["relativePoint"] = "BOTTOM",
},
["raid"] = {
["top"] = 332.7667932267887,
["x"] = -255.599992275238,
["point"] = "BOTTOMRIGHT",
["relativePoint"] = "BOTTOM",
["bottom"] = 304.3668374200552,
["y"] = 301.7499908804894,
},
["partytargettarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["boss"] = {
["top"] = 482.1331903849896,
["x"] = 212.9999935626984,
["point"] = "BOTTOMLEFT",
["relativePoint"] = "BOTTOM",
["y"] = 301.7499908804894,
["bottom"] = 304.6332824193269,
},
["maintank"] = {
["anchorPoint"] = "C",
},
["battlegroundtargettarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["bosstargettarget"] = {
["anchorPoint"] = "RB",
["anchorTo"] = "$parent",
},
["raidpet"] = {
["anchorPoint"] = "C",
},
["bosstarget"] = {
["anchorPoint"] = "RB",
["anchorTo"] = "$parent",
},
["focustarget"] = {
["anchorPoint"] = "TL",
["anchorTo"] = "#SUFUnitfocus",
},
["pettarget"] = {
["anchorPoint"] = "C",
},
["maintanktargettarget"] = {
["anchorPoint"] = "RT",
["x"] = 150,
["anchorTo"] = "$parent",
},
["player"] = {
["y"] = 230.7499930262566,
["x"] = -188.1499943137169,
["point"] = "BOTTOMRIGHT",
["relativePoint"] = "BOTTOM",
},
["mainassist"] = {
["anchorPoint"] = "C",
},
["pet"] = {
["anchorPoint"] = "TL",
["anchorTo"] = "#SUFUnitplayer",
},
["battlegroundpet"] = {
["anchorPoint"] = "RB",
["anchorTo"] = "$parent",
},
["arena"] = {
["top"] = 466.3087798524939,
["x"] = 212.9999935626984,
["point"] = "BOTTOMLEFT",
["relativePoint"] = "BOTTOM",
["y"] = 301.7499908804894,
["bottom"] = 306.5587630129903,
},
["battlegroundtarget"] = {
["anchorPoint"] = "RT",
["anchorTo"] = "$parent",
},
["battleground"] = {
["top"] = 399.5668317963318,
["x"] = 1053.233486235506,
["point"] = "TOPLEFT",
["relativePoint"] = "BOTTOMLEFT",
["y"] = 399.5668317963318,
["bottom"] = 300.1668564678857,
},
},
["revision"] = 63,
["castColors"] = {
["cast"] = {
["r"] = 1,
["g"] = 0.7,
["b"] = 0.3,
},
["finished"] = {
["r"] = 0.1,
["g"] = 1,
["b"] = 0.1,
},
["channel"] = {
["r"] = 0.25,
["g"] = 0.25,
["b"] = 1,
},
["uninterruptible"] = {
["r"] = 0.71,
["g"] = 0,
["b"] = 1,
},
["interrupted"] = {
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
},
["auras"] = {
["borderType"] = "light",
},
["loadedLayout"] = true,
["hidden"] = {
["playerPower"] = false,
},
["units"] = {
["arenatarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["mainassisttarget"] = {
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[level( )][classification( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 150,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 40,
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["targettargettarget"] = {
["enabled"] = false,
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "RIGHT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["height"] = 0.5,
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["range"] = {
["height"] = 0.5,
},
["width"] = 80,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["text"] = {
{
["width"] = 1,
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "",
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
},
["height"] = 30,
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["partytarget"] = {
["highlight"] = {
["size"] = 10,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 25,
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
},
["arenatargettarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["battlegroundtarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["arenapet"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 25,
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
},
["mainassisttargettarget"] = {
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[level( )][classification( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 150,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 40,
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["party"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["phase"] = {
["anchorPoint"] = "RC",
["x"] = -11,
["anchorTo"] = "$parent",
["size"] = 14,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TC",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["ready"] = {
["y"] = 0,
["x"] = 35,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 24,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["showPlayer"] = true,
["range"] = {
["enabled"] = true,
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["y"] = 0,
["anchorPoint"] = "BL",
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["portrait"] = {
["type"] = "2D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["debuff"] = true,
["height"] = 0.5,
["alpha"] = 1,
["aggro"] = true,
["attention"] = false,
["mouseover"] = true,
["size"] = 39,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["incAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["hideAnyRaid"] = true,
["incHeal"] = {
["height"] = 0.5,
["cap"] = 1,
},
["offset"] = 0,
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[level( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["hideSemiRaid"] = false,
["fader"] = {
["height"] = 0.5,
},
["attribAnchorPoint"] = "LEFT",
["unitsPerColumn"] = 5,
["width"] = 200,
["height"] = 50,
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["columnSpacing"] = 30,
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["auraIndicators"] = {
["enabled"] = true,
["Food"] = true,
["height"] = 0.5,
["Hellfire Citadel"] = true,
},
["attribPoint"] = "BOTTOM",
},
["maintanktargettarget"] = {
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[classification( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 150,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 40,
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["focus"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["height"] = 0.5,
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["questBoss"] = {
["y"] = 14,
["x"] = 7,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["enabled"] = false,
["size"] = 22,
},
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["incAbsorb"] = {
["height"] = 0.5,
},
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
{
["text"] = "[curhp]",
},
{
["text"] = "[perpp]",
},
{
["text"] = "[curpp]",
},
{
["text"] = "[(()afk() )][name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["width"] = 120,
["fader"] = {
["height"] = 0.5,
},
["incHeal"] = {
["height"] = 0.5,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["height"] = 28,
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
},
["target"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = -39,
["anchorTo"] = "$parent",
["anchorPoint"] = "RC",
["size"] = 28,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["height"] = 0.5,
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["questBoss"] = {
["y"] = 24,
["x"] = 9,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 22,
},
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["enabled"] = true,
["y"] = 0,
["x"] = 0,
["anchorPoint"] = "BL",
["size"] = 16,
},
["buffs"] = {
["enabled"] = true,
["y"] = 0,
["x"] = 0,
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["castBar"] = {
["enabled"] = true,
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["autoHide"] = true,
["order"] = 60,
["background"] = true,
["icon"] = "LEFT",
["height"] = 1,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["comboPoints"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -3,
["spacing"] = -4,
["height"] = 0.4,
["y"] = 8,
["size"] = 14,
},
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[level( )][classification( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["incAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["width"] = 200,
["portrait"] = {
["type"] = "3D",
["alignment"] = "RIGHT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["incHeal"] = {
["height"] = 0.5,
["cap"] = 1,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["enabled"] = false,
["height"] = 0.5,
},
["height"] = 50,
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
},
["raid"] = {
["portrait"] = {
["type"] = "2D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["frameSplit"] = true,
["groupSpacing"] = 0,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["offset"] = -1,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "none",
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["maxColumns"] = 8,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 40,
["attribPoint"] = "RIGHT",
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["masterLoot"] = {
["anchorPoint"] = "TR",
["x"] = -2,
["anchorTo"] = "$parent",
["y"] = -10,
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TC",
["size"] = 14,
},
["role"] = {
["enabled"] = false,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["y"] = 14,
["size"] = 14,
},
["ready"] = {
["anchorPoint"] = "LC",
["x"] = 25,
["anchorTo"] = "$parent",
["y"] = 0,
["size"] = 24,
},
["height"] = 0.5,
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["pvp"] = {
["anchorPoint"] = "BL",
["x"] = 0,
["anchorTo"] = "$parent",
["y"] = 11,
["size"] = 22,
},
},
["range"] = {
["height"] = 0.5,
["oorAlpha"] = 0.5,
["enabled"] = true,
},
["incAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["incHeal"] = {
["height"] = 0.5,
["cap"] = 1,
},
["attribAnchorPoint"] = "BOTTOM",
["text"] = {
{
["text"] = "[(()afk() )][name]",
["size"] = -2,
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[(()afk() )][name]",
},
},
["width"] = 60,
["groupsPerRow"] = 8,
["auraIndicators"] = {
["height"] = 0.5,
["enabled"] = true,
},
["fader"] = {
["height"] = 0.5,
},
["combatText"] = {
["height"] = 0.5,
},
["columnSpacing"] = -7,
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["unitsPerColumn"] = 8,
["highlight"] = {
["debuff"] = true,
["height"] = 0.5,
["alpha"] = 1,
["aggro"] = true,
["attention"] = false,
["mouseover"] = true,
["size"] = 39,
},
},
["partytargettarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["arena"] = {
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["perRow"] = 9,
["y"] = 0,
["enabled"] = true,
["x"] = 0,
["anchorPoint"] = "BL",
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["perRow"] = 9,
["x"] = 0,
["y"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["enabled"] = true,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["text"] = {
[3] = {
["text"] = "[perpp]",
},
[5] = {
["text"] = "[name]",
},
},
["width"] = 170,
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["height"] = 50,
["portrait"] = {
["type"] = "class",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["indicators"] = {
["arenaSpec"] = {
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["height"] = 0.5,
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["attribPoint"] = "BOTTOM",
},
["battlegroundpet"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 25,
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
},
["battlegroundtargettarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["bosstargettarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["targettarget"] = {
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "RIGHT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["range"] = {
["height"] = 0.5,
},
["width"] = 110,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "[perpp]",
},
{
["text"] = "[curpp]",
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
},
["height"] = 30,
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
},
["bosstarget"] = {
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 25,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["focustarget"] = {
["highlight"] = {
["height"] = 0.5,
["size"] = 10,
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["enabled"] = false,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[(()afk() )][name]",
},
},
["width"] = 120,
["fader"] = {
["height"] = 0.5,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["height"] = 25,
["portrait"] = {
["type"] = "3D",
["alignment"] = "RIGHT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
},
},
["pettarget"] = {
["text"] = {
[3] = {
["text"] = "[perpp]",
},
[5] = {
["text"] = "[name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 190,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["height"] = 30,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.7,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["partypet"] = {
["highlight"] = {
["size"] = 10,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.6,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 90,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 25,
["healAbsorb"] = {
["cap"] = 1,
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["text"] = {
nil,
{
["text"] = "[curhp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
},
["mainassist"] = {
["highlight"] = {
["size"] = 10,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["ready"] = {
["y"] = 0,
["x"] = 35,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 24,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["height"] = 40,
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[level( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["incAbsorb"] = {
["cap"] = 1,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["offset"] = 5,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["unitsPerColumn"] = 5,
["incHeal"] = {
["cap"] = 1,
},
["attribAnchorPoint"] = "LEFT",
["width"] = 150,
["maxColumns"] = 1,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["columnSpacing"] = 5,
["healAbsorb"] = {
["cap"] = 1,
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
},
["player"] = {
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["runeBar"] = {
["enabled"] = true,
["background"] = false,
["order"] = 70,
["height"] = 0.4,
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["powerBar"] = {
["colorType"] = "type",
["order"] = 20,
["background"] = true,
["height"] = 0.4,
},
["healthBar"] = {
["colorType"] = "class",
["reactionType"] = "npc",
["background"] = true,
["height"] = 1,
["order"] = 10,
},
["essence"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -8,
["spacing"] = -2,
["height"] = 0.4,
["y"] = 6,
["size"] = 12,
},
["text"] = {
{
["text"] = "[(()afk() )][name][( ()group())]",
},
nil,
{
["text"] = "[perpp]",
},
nil,
{
["text"] = "[(()afk() )][name][( ()group())]",
},
nil,
{
["anchorTo"] = "$totemBar",
["text"] = "[totem:timer]",
["width"] = 1,
["name"] = "Timer Text",
["block"] = true,
},
{
["anchorTo"] = "$runeBar",
["text"] = "[rune:timer]",
["width"] = 1,
["name"] = "Timer Text",
["block"] = true,
},
{
["anchorTo"] = "$staggerBar",
["text"] = "[monk:abs:stagger]",
["width"] = 1,
["name"] = "Text",
},
},
["priestBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 70,
},
["height"] = 50,
["auraPoints"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -3,
["spacing"] = -4,
["height"] = 0.4,
["y"] = 8,
["size"] = 14,
},
["xpBar"] = {
["height"] = 0.25,
["background"] = true,
["order"] = 55,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["lfdRole"] = {
["y"] = 14,
["x"] = 3,
["anchorTo"] = "$parent",
["anchorPoint"] = "BR",
["size"] = 14,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["ready"] = {
["y"] = 0,
["x"] = 35,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 24,
},
["height"] = 0.5,
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["totemBar"] = {
["secure"] = true,
["order"] = 70,
["reverse"] = false,
["height"] = 0.4,
["background"] = false,
["icon"] = false,
["vertical"] = false,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["comboPoints"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -3,
["spacing"] = -4,
["height"] = 0.4,
["y"] = 8,
["size"] = 14,
},
["druidBar"] = {
["enabled"] = true,
["background"] = true,
["order"] = 70,
["height"] = 0.4,
},
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
["shamanBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 70,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["enabled"] = true,
["y"] = 0,
["x"] = 0,
["maxRows"] = 1,
["anchorPoint"] = "BL",
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["x"] = 0,
["y"] = 0,
["maxRows"] = 1,
["size"] = 16,
},
},
["holyPower"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -3,
["spacing"] = -4,
["height"] = 0.4,
["y"] = 6,
["size"] = 14,
},
["soulShards"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -8,
["spacing"] = -2,
["height"] = 0.4,
["y"] = 6,
["size"] = 12,
},
["staggerBar"] = {
["height"] = 0.3,
["background"] = true,
["order"] = 70,
},
["width"] = 200,
["chi"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -3,
["spacing"] = -4,
["height"] = 0.4,
["y"] = 6,
["size"] = 14,
},
["incAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["fader"] = {
["inactiveAlpha"] = 0.6,
["enabled"] = true,
["combatAlpha"] = 1,
["height"] = 0.5,
},
["combatText"] = {
["height"] = 0.5,
},
["incHeal"] = {
["height"] = 0.5,
["cap"] = 1,
},
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["arcaneCharges"] = {
["anchorTo"] = "$parent",
["order"] = 60,
["showAlways"] = true,
["growth"] = "LEFT",
["anchorPoint"] = "BR",
["x"] = -8,
["spacing"] = -2,
["height"] = 0.4,
["y"] = 6,
["size"] = 12,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
},
["maintanktarget"] = {
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[classification( )][perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 150,
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
},
["height"] = 40,
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
},
["pet"] = {
["xpBar"] = {
["height"] = 0.25,
["background"] = true,
["order"] = 55,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["height"] = 0.5,
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "none",
},
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["text"] = {
[3] = {
["text"] = "[perpp]",
},
[5] = {
["text"] = "[name]",
},
},
["incAbsorb"] = {
["height"] = 0.5,
},
["width"] = 190,
["fader"] = {
["height"] = 0.5,
},
["incHeal"] = {
["height"] = 0.5,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["height"] = 30,
["healAbsorb"] = {
["height"] = 0.5,
["cap"] = 1,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
},
["raidpet"] = {
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["groupSpacing"] = 0,
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.3,
["background"] = true,
["order"] = 20,
},
["groupsPerRow"] = 8,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "none",
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["maxColumns"] = 8,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["height"] = 30,
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
},
["scale"] = 0.85,
["incAbsorb"] = {
["cap"] = 1,
},
["columnSpacing"] = 5,
["attribAnchorPoint"] = "LEFT",
["unitsPerColumn"] = 8,
["width"] = 90,
["incHeal"] = {
["cap"] = 1,
},
["healAbsorb"] = {
["cap"] = 1,
},
["text"] = {
nil,
{
["text"] = "[missinghp]",
},
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["highlight"] = {
["size"] = 10,
},
},
["maintank"] = {
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["highlight"] = {
["size"] = 10,
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["auras"] = {
["debuffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["y"] = 0,
["x"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["incHeal"] = {
["cap"] = 1,
},
["incAbsorb"] = {
["cap"] = 1,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 1,
["background"] = true,
["order"] = 20,
},
["text"] = {
{
["text"] = "[(()afk() )][name]",
},
[3] = {
["text"] = "[perpp]",
},
[5] = {
["text"] = "[(()afk() )][name]",
},
},
["offset"] = 5,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1.2,
["reactionType"] = "npc",
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["sumPending"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 40,
},
["resurrect"] = {
["y"] = -1,
["x"] = 37,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 28,
},
["masterLoot"] = {
["y"] = -10,
["x"] = 16,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 12,
},
["leader"] = {
["y"] = -12,
["x"] = 2,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["role"] = {
["y"] = -11,
["x"] = 30,
["anchorTo"] = "$parent",
["anchorPoint"] = "TL",
["size"] = 14,
},
["status"] = {
["y"] = -2,
["x"] = 12,
["anchorTo"] = "$parent",
["anchorPoint"] = "LB",
["size"] = 16,
},
["ready"] = {
["y"] = 0,
["x"] = 35,
["anchorTo"] = "$parent",
["anchorPoint"] = "LC",
["size"] = 24,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["pvp"] = {
["y"] = -21,
["x"] = 11,
["anchorTo"] = "$parent",
["anchorPoint"] = "TR",
["size"] = 22,
},
},
["height"] = 40,
["attribAnchorPoint"] = "LEFT",
["width"] = 150,
["maxColumns"] = 1,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["columnSpacing"] = 5,
["healAbsorb"] = {
["cap"] = 1,
},
["unitsPerColumn"] = 5,
},
["boss"] = {
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["perRow"] = 8,
["y"] = 0,
["enabled"] = true,
["x"] = 0,
["anchorPoint"] = "RB",
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["perRow"] = 8,
["x"] = 0,
["y"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 40,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["enabled"] = true,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["text"] = {
[3] = {
["text"] = "[perpp]",
},
[5] = {
["text"] = "[name]",
},
},
["width"] = 160,
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["height"] = 50,
["portrait"] = {
["type"] = "3D",
["alignment"] = "LEFT",
["fullAfter"] = 100,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
},
["attribPoint"] = "BOTTOM",
},
["battleground"] = {
["indicators"] = {
["raidTarget"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "C",
["size"] = 20,
},
["class"] = {
["y"] = 0,
["x"] = 0,
["anchorTo"] = "$parent",
["anchorPoint"] = "BL",
["size"] = 16,
},
["height"] = 0.5,
["pvp"] = {
["anchorPoint"] = "LC",
["x"] = 16,
["anchorTo"] = "$parent",
["y"] = -8,
["size"] = 40,
},
},
["range"] = {
["height"] = 0.5,
},
["auras"] = {
["height"] = 0.5,
["debuffs"] = {
["perRow"] = 9,
["y"] = 0,
["anchorPoint"] = "BL",
["x"] = 0,
["size"] = 16,
},
["buffs"] = {
["anchorPoint"] = "BL",
["perRow"] = 9,
["x"] = 0,
["y"] = 0,
["size"] = 16,
},
},
["castBar"] = {
["time"] = {
["enabled"] = true,
["x"] = -1,
["anchorTo"] = "$parent",
["y"] = 0,
["anchorPoint"] = "CRI",
["size"] = 0,
},
["name"] = {
["y"] = 0,
["x"] = 1,
["anchorTo"] = "$parent",
["size"] = 0,
["enabled"] = true,
["anchorPoint"] = "CLI",
["rank"] = true,
},
["order"] = 60,
["background"] = true,
["icon"] = "HIDE",
["height"] = 0.6,
},
["auraIndicators"] = {
["height"] = 0.5,
},
["powerBar"] = {
["colorType"] = "type",
["height"] = 0.4,
["background"] = true,
["order"] = 20,
},
["enabled"] = true,
["healthBar"] = {
["colorType"] = "class",
["order"] = 10,
["background"] = true,
["height"] = 1,
["reactionType"] = "npc",
},
["text"] = {
nil,
nil,
{
["text"] = "",
},
{
["text"] = "",
},
{
["text"] = "[name]",
},
},
["emptyBar"] = {
["order"] = 0,
["background"] = true,
["reactionType"] = "none",
["height"] = 1,
},
["width"] = 140,
["altPowerBar"] = {
["height"] = 0.4,
["background"] = true,
["order"] = 100,
},
["combatText"] = {
["height"] = 0.5,
},
["height"] = 35,
["highlight"] = {
["height"] = 0.5,
["mouseover"] = true,
["size"] = 10,
},
["portrait"] = {
["type"] = "class",
["alignment"] = "LEFT",
["fullAfter"] = 50,
["height"] = 0.5,
["fullBefore"] = 0,
["order"] = 15,
["width"] = 0.22,
},
},
},
["font"] = {
["extra"] = "",
["name"] = "Fira Sans Condensed Black",
["color"] = {
["a"] = 1,
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["shadowColor"] = {
["a"] = 1,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["shadowY"] = -1,
["shadowX"] = 1,
["size"] = 11,
},
["wowBuild"] = 110207,
["classColors"] = {
["HUNTER"] = {
["r"] = 0.67,
["g"] = 0.83,
["b"] = 0.45,
},
["WARRIOR"] = {
["r"] = 0.78,
["g"] = 0.61,
["b"] = 0.43,
},
["PALADIN"] = {
["r"] = 0.96,
["g"] = 0.55,
["b"] = 0.73,
},
["MAGE"] = {
["r"] = 0.41,
["g"] = 0.8,
["b"] = 0.94,
},
["ROGUE"] = {
["r"] = 1,
["g"] = 0.96,
["b"] = 0.41,
},
["VEHICLE"] = {
["r"] = 0.23,
["g"] = 0.41,
["b"] = 0.23,
},
["PRIEST"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
["MONK"] = {
["r"] = 0,
["g"] = 1,
["b"] = 0.59,
},
["SHAMAN"] = {
["r"] = 0.14,
["g"] = 0.35,
["b"] = 1,
},
["WARLOCK"] = {
["r"] = 0.58,
["g"] = 0.51,
["b"] = 0.79,
},
["DEMONHUNTER"] = {
["r"] = 0.64,
["g"] = 0.19,
["b"] = 0.79,
},
["PET"] = {
["r"] = 0.2,
["g"] = 0.9,
["b"] = 0.2,
},
["DRUID"] = {
["r"] = 1,
["g"] = 0.49,
["b"] = 0.04,
},
["EVOKER"] = {
["r"] = 0.2,
["g"] = 0.58,
["b"] = 0.5,
},
["DEATHKNIGHT"] = {
["r"] = 0.77,
["g"] = 0.12,
["b"] = 0.23,
},
},
["backdrop"] = {
["clip"] = 1,
["edgeSize"] = 5,
["tileSize"] = 1,
["borderTexture"] = "None",
["inset"] = 3,
["backgroundTexture"] = "Chat Frame",
["backgroundColor"] = {
["a"] = 0.8,
["r"] = 0,
["g"] = 0,
["b"] = 0,
},
["borderColor"] = {
["a"] = 1,
["r"] = 0.3,
["g"] = 0.3,
["b"] = 0.5,
},
},
["bars"] = {
["texture"] = "Minimalist",
["backgroundAlpha"] = 0.2,
["alpha"] = 1,
["spacing"] = -1.25,
},
["auraColors"] = {
["removable"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
},
},
}
