
TalentTreeTweaksDB = {
["modules"] = {
["InspectDiff"] = true,
["ClickableExportStringsInChat"] = true,
["SearchForIds"] = true,
["UnlockRestrictions"] = true,
["MiniTreeInTooltip"] = true,
["ReduceTaint"] = true,
["ExportInspectedBuild"] = true,
["TooltipIds"] = true,
["ImportIntoCurrentLoadout"] = true,
["ReduceSpam"] = true,
["ChangeBackground"] = true,
["CopyTalentButtonInfo"] = true,
["HeroTalents"] = true,
["Drive Auto Purchaser"] = true,
["Skyriding Auto Purchaser"] = true,
["HighlightCascadeRepurchable"] = true,
["DebugNodeInfo"] = true,
["RespecButtons"] = true,
["ScaleTalentFrame"] = true,
["MiscFixes"] = true,
["AlwaysShowGates"] = true,
},
["moduleDb"] = {
["InspectDiff"] = {
["colorYellow"] = {
["a"] = 0.75,
["r"] = 1,
["g"] = 0.67,
["b"] = 0,
},
["colorGreen"] = {
["a"] = 0.58,
["r"] = 0,
["g"] = 1,
["b"] = 0.3,
},
["colorRed"] = {
["a"] = 0.5,
["r"] = 1,
["g"] = 0,
["b"] = 0,
},
["enableTalentTreeViewerDiff"] = true,
},
["ClickableExportStringsInChat"] = {
["disableDetectionFromStrings"] = true,
},
["SearchForIds"] = {
},
["DragonRiding Auto Purchaser"] = {
["reportPurchases"] = true,
["rideAlongCache"] = {
["Riparium-Argent Dawn"] = 1,
["Esker-Kel'Thuzad"] = 1,
},
["rideAlong"] = 1,
},
["UnlockRestrictions"] = {
["unlockInCombatSpending"] = true,
["unlockShareButton"] = true,
},
["MiniTreeInTooltip"] = {
["diffOrange"] = {
["b"] = 0,
["g"] = 1,
["r"] = 1,
},
["displayStyle"] = "simple-default-diff",
["upgradedDisplayStyle"] = 1,
["diffRed"] = {
["b"] = 0,
["g"] = 0,
["r"] = 1,
},
["scale"] = 1,
["inactiveSubTreeAlpha"] = 0.5,
["diffYellow"] = {
["b"] = 1,
["g"] = 1,
["r"] = 1,
},
["diffGreen"] = {
["b"] = 0,
["g"] = 1,
["r"] = 0,
},
},
["ReduceTaint"] = {
["disableMultiActionBarShowHide"] = true,
["disableCastbar"] = true,
["alwaysReplaceShareButton"] = false,
},
["ExportInspectedBuild"] = {
["showLinkInChatButton"] = true,
["inspectTalentsMenuItem"] = true,
["exportOnDropdownRightClick"] = true,
},
["TooltipIds"] = {
["professionTooltip"] = {
["enabled"] = true,
["nodeId"] = true,
["spellId"] = true,
["definitionId"] = false,
["entryId"] = true,
},
["talentTooltip"] = {
["enabled"] = true,
["nodeId"] = true,
["spellId"] = true,
["definitionId"] = false,
["entryId"] = true,
["rowColInfo"] = false,
},
},
["AlwaysShowGates"] = {
["shiftHeroTrees"] = false,
},
["ReduceSpam"] = {
},
["ChangeBackground"] = {
["showAlphaInSpellbookUI"] = true,
["showAlphaInViewerUI"] = true,
["spellbookAlpha"] = 1,
["showAlphaInUI"] = true,
["alpha"] = 0.6000000238418579,
},
["CopyTalentButtonInfo"] = {
},
["MiscFixes"] = {
["dropdownUpdateOnLoadConfigFix"] = true,
["passThroughDisableOverlay"] = true,
["linkChoiceNodeInChatFix"] = true,
["dropdownFixOrder"] = true,
},
["Drive Auto Purchaser"] = {
["node-103882"] = 128290,
["node-103881"] = 128288,
["node-103880"] = 128285,
["node-104094"] = 128608,
["node-103879"] = 128282,
["reportPurchases"] = true,
},
["Skyriding Auto Purchaser"] = {
["reshiiWrapsEnabled"] = true,
["rideAlongCache"] = {
["Fjord-Mal'Ganis"] = 1,
["Strid-Kel'Thuzad"] = 1,
["Temprivers-Kel'Thuzad"] = 1,
["Dukasuka-Eredar"] = 1,
["Aquifer-Kel'Thuzad"] = 1,
["Asperse-Kel'Thuzad"] = 1,
["Mangrove-Argent Dawn"] = 1,
["Weir-Kel'Thuzad"] = 1,
["Docks-Kel'Thuzad"] = 1,
["Bog-Kel'Thuzad"] = 1,
["Brack-Mal'Ganis"] = 1,
["Gyre-Kel'Thuzad"] = 1,
["Baffle-Mal'Ganis"] = 1,
["Flumina-Argent Dawn"] = 1,
["Rime-Kel'Thuzad"] = 1,
["Loess-Kel'Thuzad"] = 1,
["Stream-Argent Dawn"] = 1,
["Shoal-Kel'Thuzad"] = 1,
["Mire-Mal'Ganis"] = 1,
["Spume-Argent Dawn"] = 1,
["Falls-Mal'Ganis"] = 1,
["Remaxxing-Kel'Thuzad"] = 1,
["Estuary-Argent Dawn"] = 1,
["Karst-Argent Dawn"] = 1,
["Cirque-Kel'Thuzad"] = 1,
["Cataracts-Argent Dawn"] = 1,
["Benthos-Argent Dawn"] = 1,
["Cascades-Kel'Thuzad"] = 1,
["Seep-Kel'Thuzad"] = 1,
["Quag-Argent Dawn"] = 1,
["Virga-Kel'Thuzad"] = 1,
["Rivulet-Mal'Ganis"] = 1,
["Alluvium-Argent Dawn"] = 1,
["Sverdrup-Argent Dawn"] = 1,
["Neva-Kel'Thuzad"] = 1,
["Geyser-Mal'Ganis"] = 1,
["Meander-Kel'Thuzad"] = 1,
["Esker-Kel'Thuzad"] = 1,
["Dannius-Argent Dawn"] = 1,
["Brook-Argent Dawn"] = 1,
["Gelae-Kel'Thuzad"] = 1,
["Geosmin-Kel'Thuzad"] = 1,
["Slush-Mal'Ganis"] = 1,
["Floe-Mal'Ganis"] = 1,
["Roberia-Eredar"] = 1,
["Dussrasande-Kel'Thuzad"] = 1,
["Glaciers-Kel'Thuzad"] = 1,
["Riptides-Argent Dawn"] = 1,
["Doneer-Eredar"] = 1,
["Riparium-Argent Dawn"] = 1,
["Emptyrivers-Argent Dawn"] = 1,
["Lather-Mal'Ganis"] = 1,
["Headcut-Argent Dawn"] = 1,
["Moraine-Kel'Thuzad"] = 1,
["Rill-Kel'Thuzad"] = 1,
["Flumes-Kel'Thuzad"] = 1,
["Confluence-Argent Dawn"] = 1,
},
["horrificVisionsEnabled"] = true,
["overchargedTitanConsoleEnabled"] = true,
["rideAlong"] = 1,
["surge"] = 1,
["skyridingEnabled"] = true,
["reportPurchases"] = true,
["surgeCache"] = {
["Geosmin-Kel'Thuzad"] = 1,
["Temprivers-Kel'Thuzad"] = 1,
["Dukasuka-Eredar"] = 1,
["Asperse-Kel'Thuzad"] = 1,
["Headcut-Argent Dawn"] = 1,
["Gyre-Kel'Thuzad"] = 1,
["Mangrove-Argent Dawn"] = 1,
["Brack-Mal'Ganis"] = 1,
["Riparium-Argent Dawn"] = 1,
["Baffle-Mal'Ganis"] = 1,
["Shoal-Kel'Thuzad"] = 1,
["Bog-Kel'Thuzad"] = 1,
["Confluence-Argent Dawn"] = 1,
["Loess-Kel'Thuzad"] = 1,
["Aquifer-Kel'Thuzad"] = 1,
["Glaciers-Kel'Thuzad"] = 1,
["Mire-Mal'Ganis"] = 1,
["Falls-Mal'Ganis"] = 1,
["Remaxxing-Kel'Thuzad"] = 1,
["Estuary-Argent Dawn"] = 1,
["Karst-Argent Dawn"] = 1,
["Cataracts-Argent Dawn"] = 1,
["Cirque-Kel'Thuzad"] = 1,
["Roberia-Eredar"] = 1,
["Cascades-Kel'Thuzad"] = 1,
["Quag-Argent Dawn"] = 1,
["Seep-Kel'Thuzad"] = 1,
["Flumina-Argent Dawn"] = 1,
["Rivulet-Mal'Ganis"] = 1,
["Alluvium-Argent Dawn"] = 1,
["Sverdrup-Argent Dawn"] = 1,
["Virga-Kel'Thuzad"] = 1,
["Geyser-Mal'Ganis"] = 1,
["Meander-Kel'Thuzad"] = 1,
["Esker-Kel'Thuzad"] = 1,
["Dannius-Argent Dawn"] = 1,
["Brook-Argent Dawn"] = 1,
["Gelae-Kel'Thuzad"] = 1,
["Weir-Kel'Thuzad"] = 1,
["Strid-Kel'Thuzad"] = 1,
["Floe-Mal'Ganis"] = 1,
["Neva-Kel'Thuzad"] = 1,
["Dussrasande-Kel'Thuzad"] = 1,
["Benthos-Argent Dawn"] = 1,
["Riptides-Argent Dawn"] = 1,
["Doneer-Eredar"] = 1,
["Spume-Argent Dawn"] = 1,
["Emptyrivers-Argent Dawn"] = 1,
["Lather-Mal'Ganis"] = 1,
["Stream-Argent Dawn"] = 1,
["Moraine-Kel'Thuzad"] = 1,
["Rill-Kel'Thuzad"] = 1,
["Flumes-Kel'Thuzad"] = 1,
["Docks-Kel'Thuzad"] = 1,
},
["lemixLimitsUnboundEnabled"] = true,
},
["HighlightCascadeRepurchable"] = {
["color"] = {
["a"] = 0.5,
["r"] = 0,
["g"] = 0,
["b"] = 1,
},
},
["DebugNodeInfo"] = {
["addButtonToTable"] = true,
["luaBrowser"] = true,
["slashDump"] = false,
["viragDevTool"] = true,
["tinspect"] = true,
},
["RespecButtons"] = {
["inverseHighlight"] = false,
},
["ScaleTalentFrame"] = {
["scale"] = 1,
},
["HeroTalents"] = {
},
["ImportIntoCurrentLoadout"] = {
["defaultCheckboxState"] = false,
["unlockImportButton"] = true,
},
},
}
