
ATVDB = {
["profileKeys"] = {
["Loess - Kel'Thuzad"] = "Default",
["Dukasuka - Eredar"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Remaxxing - Kel'Thuzad"] = "Default",
["Cascades - Kel'Thuzad"] = "Default",
["Doneer - Eredar"] = "Default",
["Glaciers - Kel'Thuzad"] = "Default",
["Temprivers - Kel'Thuzad"] = "Default",
["Inundito - Kel'Thuzad"] = "Default",
["Flumina - Argent Dawn"] = "Default",
["Flumes - Kel'Thuzad"] = "Default",
["Weir - Kel'Thuzad"] = "Default",
["Alluvium - Argent Dawn"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Gyre - Kel'Thuzad"] = "Default",
["Asperse - Kel'Thuzad"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riptides - Argent Dawn"] = "Default",
["Darick - Eredar"] = "Default",
["Virga - Kel'Thuzad"] = "Default",
["Dussrasande - Kel'Thuzad"] = "Default",
["Saellindris - Kel'Thuzad"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Rosefin - Argent Dawn"] = "Default",
["Meander - Kel'Thuzad"] = "Default",
["Dannius - Argent Dawn"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Shoal - Kel'Thuzad"] = "Default",
["Geosmin - Kel'Thuzad"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Neva - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Karst - Argent Dawn"] = "Default",
["Aquifer - Kel'Thuzad"] = "Default",
["Roberia - Eredar"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["global"] = {
["settings"] = {
["backgroundColor"] = {
["r"] = 1,
["g"] = 1,
["b"] = 1,
},
},
},
}
