
TomTomDB = {
	["profileKeys"] = {
		["Boringrivers - Korgath"] = "Default",
		["Rapidrivers - Arthas"] = "Default",
		["Treesurgeon - Korgath"] = "Default",
		["Serenerivers - Arthas"] = "Default",
		["Emptyrivers - Korgath"] = "Default",
		["Naturerivers - Korgath"] = "Default",
		["Wildrivers - Korgath"] = "Default",
		["Crazyrivers - Bleeding Hollow"] = "Default",
		["Greedyrivers - Arthas"] = "Default",
		["Beefyrivers - Thrall"] = "Default",
		["Yandanderex - Moon Guard"] = "Default",
		["Mindrivers - Korgath"] = "Default",
		["Bittydots - Korgath"] = "Default",
		["Sacredrivers - Korgath"] = "Default",
		["Dammedrivers - Exodar"] = "Default",
		["Hulyon - Kel'Thuzad"] = "Default",
		["Blindrivers - Sargeras"] = "Default",
		["Tinyrivers - Kel'Thuzad"] = "Default",
		["Edgyrivers - Arthas"] = "Default",
		["Testrivers - Bleeding Hollow"] = "Default",
		["Sassyrivers - Arthas"] = "Default",
		["Wildrivers - Bleeding Hollow"] = "Default",
		["Serenerivers - Kel'Thuzad"] = "Default",
		["Deadrivers - Korgath"] = "Default",
		["Blindrivers - Arthas"] = "Default",
		["Smaz - Mug'thol"] = "Default",
		["Brightrivers - Korgath"] = "Default",
		["Emptyrivers - Arthas"] = "Default",
		["Littlerivers - Kel'Thuzad"] = "Default",
		["Luckyrivers - Sargeras"] = "Default",
		["Spicydremer - Korgath"] = "Default",
		["Blindrivers - Korgath"] = "Default",
		["Caladiir - Kel'Thuzad"] = "Default",
		["Hiddenrivers - Korgath"] = "Default",
		["Edgyrivers - Kel'Thuzad"] = "Default",
		["Boringrivers - Bleeding Hollow"] = "Default",
		["Shachein - Arthas"] = "Default",
		["Elakai - Korgath"] = "Default",
		["Wildrivers - Arthas"] = "Default",
		["Toofattohide - Kel'Thuzad"] = "Default",
		["Beefyrivers - Arthas"] = "Default",
		["Evilrivers - Korgath"] = "Default",
		["Ragingrivers - Arthas"] = "Default",
		["Notariver - Arthas"] = "Default",
		["Emptyrivers - Sargeras"] = "Default",
		["Tinyrivers - Arthas"] = "Default",
		["Serenerivers - Sargeras"] = "Default",
		["Sneakyrivers - Korgath"] = "Default",
		["Angryrivers - Korgath"] = "Default",
		["Mecharivers - Sargeras"] = "Default",
		["Luckyrivers - Korgath"] = "Default",
		["Crazyrivers - Arthas"] = "Default",
		["Emptyrivers - Bleeding Hollow"] = "Default",
		["Serenerivers - Korgath"] = "Default",
		["Kdajshtlaiuw - Bleeding Hollow"] = "Default",
		["Evilrivers - Kel'Thuzad"] = "Default",
		["Testes - Arthas"] = "Default",
		["Savattellir - Arthas"] = "Default",
		["Riversticks - Bleeding Hollow"] = "Default",
		["Magicrivers - Korgath"] = "Default",
		["Imnotamonk - Korgath"] = "Default",
		["Tinyrivers - Sargeras"] = "Default",
		["Skankyrivers - Arthas"] = "Default",
		["Serenerivers - Bleeding Hollow"] = "Default",
	},
	["profiles"] = {
		["Default"] = {
			["arrow"] = {
				["closestusecontinent"] = true,
			},
			["mapcoords"] = {
				["playerenable"] = false,
				["cursorenable"] = false,
			},
			["block"] = {
				["enable"] = false,
			},
		},
	},
}
TomTomWaypoints = nil
TomTomWaypointsM = {
	["profileKeys"] = {
		["Savattellir - Arthas"] = "Savattellir - Arthas",
		["Luckyrivers - Sargeras"] = "Luckyrivers - Sargeras",
		["Emptyrivers - Arthas"] = "Emptyrivers - Arthas",
	},
	["profiles"] = {
		["Savattellir - Arthas"] = {
		},
		["Luckyrivers - Sargeras"] = {
		},
		["Emptyrivers - Arthas"] = {
		},
	},
}
