
WarbandMiserDB = {
["Thousands"] = {
["Key"] = 2,
["Seperator"] = ",",
},
["Toons"] = {
["Kel'Thuzad"] = {
["Remaxxing"] = {
["GoldCap"] = 500,
["Defaults"] = true,
["Gold"] = 0,
["Include"] = true,
["Level"] = 53,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cascades"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 34984100,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Talamahyn"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 0,
["Level"] = 1,
["Include"] = true,
},
["Flumes"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Neva"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 28765769,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rime"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 71919846,
["Level"] = 82,
["Include"] = true,
},
["Moraine"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100309800,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Loess"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 18593208,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Glaciers"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cirque"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 95710964,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Aquifer"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Shoal"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 120000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Seep"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 13586,
["Level"] = 10,
["Include"] = true,
},
["Meander"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Bayou"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100725532,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Asperse"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 28359373,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Dussrasande"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10000,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Geosmin"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Temprivers"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 2000,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Gelae"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 355722897,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Docks"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 1000000,
["Include"] = true,
["Level"] = 11,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Esker"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 184244937,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rill"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Virga"] = {
["GoldCap"] = 100,
["Defaults"] = true,
["Gold"] = 2102088,
["Include"] = true,
["Level"] = 16,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Gyre"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 76944698,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Weir"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Bog"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 399724,
["Level"] = 15,
["Include"] = true,
},
},
["Mal'Ganis"] = {
["Fjord"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 17733,
["Level"] = 10,
["Include"] = true,
},
["Geyser"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 3129777,
["Include"] = true,
["Level"] = 20,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Lather"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 489650,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Falls"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 104121991,
["Include"] = true,
["Level"] = 83,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Mire"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 4718763,
["Level"] = 42,
["Include"] = true,
},
["Baffle"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10400,
["Level"] = 10,
["Include"] = true,
},
["Floe"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 138418,
["Level"] = 13,
["Include"] = true,
},
["Rivulet"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 1000000,
["Include"] = true,
["Level"] = 24,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Slush"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 523760,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Brack"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 12000,
["Level"] = 10,
["Include"] = true,
},
["Bwaagh"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 0,
["Level"] = 1,
["Include"] = true,
},
},
["Feathermoon"] = {
["Bwaagh"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 0,
["Level"] = 1,
["Include"] = true,
},
},
["ArgentDawn"] = {
["Quag"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 119071677,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Sverdrup"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Mangrove"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Levee"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 20700,
["Level"] = 10,
["Include"] = true,
},
["Surge"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 111011493,
["Level"] = 81,
["Include"] = true,
},
["Riptides"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 220791725,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cataracts"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 366494362,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Alluvium"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 247048339,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Emptyrivers"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 244116149,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Benthos"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 241356421,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rapids"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 26941343,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Brine"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Level"] = 80,
["Include"] = true,
},
["Confluence"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 96995027,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Fathom"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 9478,
["Level"] = 7,
["Include"] = true,
},
["Riparium"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 180406526,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Estuary"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Brook"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 0,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Spume"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10000,
["Level"] = 10,
["Include"] = true,
},
["Stream"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
},
},
["Settings"] = {
["Bracket1"] = 50,
["Bracket2"] = 100,
["Bracket6"] = 10000,
["Servers"] = {
["Kel'Thuzad"] = {
["Default"] = 0,
["Include"] = true,
},
["Mal'Ganis"] = {
["Default"] = 0,
},
["Feathermoon"] = {
["Default"] = 0,
},
["ArgentDawn"] = {
["Default"] = 0,
["Include"] = true,
},
},
["Bracket3"] = 300,
["IncludeNew"] = true,
["DepositOnly"] = false,
["MinGold"] = 2000,
["Bracket5"] = 1000,
["Range"] = {
{
["low"] = 1,
["high"] = 10,
},
{
["low"] = 11,
["high"] = 25,
},
{
["low"] = 26,
["high"] = 50,
},
{
["low"] = 51,
["high"] = 70,
},
{
["low"] = 71,
["high"] = 79,
},
{
["low"] = 80,
["high"] = 90,
},
},
["Bracket4"] = 500,
},
["wbMinumum"] = 0,
}
WarbandMiserIcon = {
["Visible"] = true,
}
