
WarbandMiserDB = {
["Thousands"] = {
["Key"] = 2,
["Seperator"] = ",",
},
["Settings"] = {
["Bracket1"] = 50,
["Bracket2"] = 100,
["Bracket6"] = 10000,
["Servers"] = {
["Kel'Thuzad"] = {
["Default"] = 0,
["Include"] = true,
},
["Mal'Ganis"] = {
["Default"] = 0,
},
["ArgentDawn"] = {
["Default"] = 0,
["Include"] = true,
},
},
["Bracket3"] = 300,
["IncludeNew"] = true,
["DepositOnly"] = false,
["MinGold"] = 2000,
["Bracket5"] = 1000,
["Bracket4"] = 500,
["Range"] = {
{
["low"] = 1,
["high"] = 10,
},
{
["low"] = 11,
["high"] = 25,
},
{
["low"] = 26,
["high"] = 50,
},
{
["low"] = 51,
["high"] = 70,
},
{
["low"] = 71,
["high"] = 79,
},
{
["low"] = 80,
["high"] = 90,
},
},
},
["Toons"] = {
["Kel'Thuzad"] = {
["Remaxxing"] = {
["GoldCap"] = 500,
["Defaults"] = true,
["Gold"] = 0,
["Include"] = true,
["Level"] = 53,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cascades"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 361438,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Flumes"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 50643526,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Neva"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 28765769,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rime"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 21468,
["Level"] = 10,
["Include"] = true,
},
["Moraine"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Loess"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 18593208,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Bog"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 399724,
["Level"] = 15,
["Include"] = true,
},
["Weir"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 39530435,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Shoal"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 23128658,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Seep"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 13586,
["Level"] = 10,
["Include"] = true,
},
["Meander"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 68262979,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Gyre"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 83060389,
["Include"] = true,
["Level"] = 90,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Asperse"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 28359373,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Dussrasande"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10000,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Virga"] = {
["GoldCap"] = 100,
["Defaults"] = true,
["Gold"] = 2102088,
["Include"] = true,
["Level"] = 16,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Temprivers"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 2000,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Gelae"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 355722897,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Docks"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 20400,
["Level"] = 11,
["Include"] = true,
},
["Esker"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 308024238,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rill"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Geosmin"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 17986111,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cirque"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 397348353,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Aquifer"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 23654228,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Glaciers"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 29007862,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
},
["Mal'Ganis"] = {
["Fjord"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 17733,
["Level"] = 10,
["Include"] = true,
},
["Geyser"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 3129777,
["Include"] = true,
["Level"] = 20,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Lather"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 489650,
["Include"] = true,
["Level"] = 10,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Falls"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10400,
["Level"] = 10,
["Include"] = true,
},
["Mire"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 413071,
["Level"] = 15,
["Include"] = true,
},
["Floe"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 21726,
["Level"] = 10,
["Include"] = true,
},
["Rivulet"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 22400,
["Level"] = 19,
["Include"] = true,
},
["Slush"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 523760,
["Include"] = true,
["Level"] = 9,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Brack"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 12000,
["Level"] = 10,
["Include"] = true,
},
["Baffle"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10400,
["Level"] = 10,
["Include"] = true,
},
},
["ArgentDawn"] = {
["Quag"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 247048339,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Sverdrup"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Mangrove"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 181645636,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Benthos"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 241356421,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Rapids"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 180406526,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Confluence"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Spume"] = {
["GoldCap"] = 50,
["Defaults"] = true,
["Gold"] = 10000,
["Level"] = 10,
["Include"] = true,
},
["Surge"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 100000000,
["Level"] = 80,
["Include"] = true,
},
["Stream"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 244547226,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Brook"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 292481343,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Riptides"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 126994120,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Riparium"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 180406526,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Estuary"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 359785261,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Cataracts"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 244255732,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Alluvium"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 247048339,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
["Emptyrivers"] = {
["GoldCap"] = 10000,
["Defaults"] = true,
["Gold"] = 244116149,
["Include"] = true,
["Level"] = 80,
["ServerDefault"] = false,
["AllGold"] = false,
},
},
},
["wbMinumum"] = 0,
}
WarbandMiserIcon = {
["Visible"] = true,
}
