
WeeklyKnowledgeDB = {
["profileKeys"] = {
["Alluvium - Argent Dawn"] = "Default",
["Strid - Kel'Thuzad"] = "Default",
["Esker - Kel'Thuzad"] = "Default",
["Headcut - Argent Dawn"] = "Default",
["Confluence - Argent Dawn"] = "Default",
["Mangrove - Argent Dawn"] = "Default",
["Gelae - Kel'Thuzad"] = "Default",
["Riparium - Argent Dawn"] = "Default",
["Benthos - Argent Dawn"] = "Default",
["Emptyrivers - Argent Dawn"] = "Default",
["Stream - Argent Dawn"] = "Default",
["Cataracts - Argent Dawn"] = "Default",
["Sverdrup - Argent Dawn"] = "Default",
["Estuary - Argent Dawn"] = "Default",
},
["global"] = {
["DBVersion"] = 7,
["main"] = {
["hiddenColumns"] = {
["Skill"] = false,
["Realm"] = true,
},
["checklistHelpTipClosed"] = true,
},
["characters"] = {
["Player-75-0F48ED55"] = {
["GUID"] = "Player-75-0F48ED55",
["enabled"] = true,
["factionEnglish"] = "Horde",
["raceName"] = "Zandalari Troll",
["raceEnglish"] = "ZandalariTroll",
["realmName"] = "Argent Dawn",
["classID"] = 6,
["classFile"] = "DEATHKNIGHT",
["completed"] = {
[83062] = true,
[83909] = true,
[83913] = true,
[83728] = true,
[83106] = true,
[29511] = true,
[83870] = true,
[82614] = true,
[83063] = true,
[83260] = true,
[29518] = true,
[83906] = true,
[83910] = true,
[84229] = true,
[83733] = true,
[83867] = true,
[83871] = true,
[83261] = true,
[83907] = true,
[83911] = true,
[84230] = true,
[83868] = true,
[83872] = true,
[84128] = true,
[82632] = true,
[83049] = true,
[83054] = true,
[83050] = true,
[83908] = true,
[83912] = true,
[83053] = true,
[83052] = true,
[83051] = true,
[83866] = true,
[83869] = true,
[83873] = true,
[81390] = true,
},
["professions"] = {
{
["knowledgeMaxLevel"] = 500,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 138,
["specializations"] = {
{
["rootNodeID"] = 100085,
["highlights"] = {
{
["description"] = "Gain increases to skill to acquire higher quality ore when mining the ores you have chosen to specialize in.",
},
{
["description"] = "Learn Refinement recipes which allow you to improve the quality of small quantities of ore.",
},
{
["description"] = "Improve your ability to harvest the elusive Null Stones.",
},
{
["description"] = "Improve the speed at which you mine ore, so you have time to mine even more!",
},
},
["description"] = "Specialize in the acquisition of various ores scattered upon and beneath Khaz Algar.",
["knowledgeLevel"] = 78,
["rootIconID"] = 876371,
["configID"] = 51148797,
["state"] = 1,
["treeID"] = 982,
["knowledgeMaxLevel"] = 185,
["name"] = "Plethora of Ore",
},
{
["rootNodeID"] = 100111,
["highlights"] = {
{
["description"] = "Learn how to mine ore deposits while mounted.",
},
{
["description"] = "Improve your finesse, deftness, and perception when mining in Khaz Algar.",
},
{
["description"] = "Chunks of ore dislodged while mining can be mined for additional yield.",
},
},
["description"] = "Specialize in nuanced mining methodology to improve your techniques. Knowledge in this area will allow you to get the most out of your rich and seam deposits discoveries.",
["knowledgeLevel"] = 60,
["rootIconID"] = 4620679,
["configID"] = 51148797,
["state"] = 1,
["treeID"] = 983,
["knowledgeMaxLevel"] = 110,
["name"] = "Mining Fundamentals",
},
{
["rootNodeID"] = 100162,
["highlights"] = {
{
["description"] = "Gain significant cooldown reduction to Overload while mining.",
},
{
["description"] = "Learn how to protect yourself and improve yield from unusual deposits found across Khaz Algar.",
},
{
["description"] = "Gain an additional charge of Overload.",
},
},
["description"] = "Specialize in mining unusual deposits across Khaz Algar, such as those touched by ominous forces.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554440,
["configID"] = 51148797,
["state"] = 1,
["treeID"] = 984,
["knowledgeMaxLevel"] = 205,
["name"] = "Mastering the Mysterious",
},
},
["skillLineID"] = 186,
["level"] = 100,
["knowledgeUnspent"] = 0,
},
{
["knowledgeMaxLevel"] = 480,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 127,
["specializations"] = {
{
["rootNodeID"] = 100765,
["highlights"] = {
{
["description"] = "Gain significant skill bonuses when crafting equipment of all types.",
},
{
["description"] = "Unlock new combat and profession equipment schematics.",
},
{
["description"] = "Learn how to enhance your equipment crafts with Embellishments, Missives, and Cogwheels.",
},
},
["description"] = "Create marvels of Algari engineering to be utilized in both combat and tradeskills alike!",
["knowledgeLevel"] = 0,
["rootIconID"] = 2735955,
["configID"] = 51148805,
["state"] = 0,
["treeID"] = 994,
["knowledgeMaxLevel"] = 200,
["name"] = "Engineered Equipment",
},
{
["rootNodeID"] = 100791,
["highlights"] = {
{
["description"] = "Become increasingly confident handling your own devices to reduce their chance of catastrophic outcomes.",
},
{
["description"] = "Improve your ability to efficiently craft tinkers, explosives, and other devices.",
},
{
["description"] = "Master an undisclosed technique to retain explosives despite their obvious explosions.",
},
},
["description"] = "Specialize in the complexities of your own devices to use them with minimal risk to your own wellbeing, and maximum risk to the wellbeing of your foes.",
["knowledgeLevel"] = 17,
["rootIconID"] = 4548852,
["configID"] = 51148805,
["state"] = 1,
["treeID"] = 995,
["knowledgeMaxLevel"] = 100,
["name"] = "Devices",
},
{
["rootNodeID"] = 100843,
["highlights"] = {
{
["description"] = "Gain significant improvements to skill towards all Engineering crafts.",
},
{
["description"] = "Elevate your ability to invent new gadgets and learn from your mistakes.",
},
{
["description"] = "Become scrappy with your scrap for efficiency gains.",
},
},
["description"] = "Specialize in the sciences of destructive construction to improve your ability to invent new gadgets and your technique with Engineering generally.",
["knowledgeLevel"] = 110,
["rootIconID"] = 4777831,
["configID"] = 51148805,
["state"] = 1,
["treeID"] = 996,
["knowledgeMaxLevel"] = 180,
["name"] = "Inventing",
},
},
["skillLineID"] = 202,
["level"] = 72,
["knowledgeUnspent"] = 7,
},
},
["name"] = "Benthos",
["className"] = "Death Knight",
["factionName"] = "Horde",
["level"] = 76,
["lastUpdate"] = 1727563889,
["raceID"] = 31,
},
["Player-75-0F471196"] = {
["enabled"] = true,
["factionEnglish"] = "",
["raceEnglish"] = "",
["lastUpdate"] = 0,
["realmName"] = "",
["classID"] = 0,
["GUID"] = "Player-75-0F471196",
["completed"] = {
},
["factionName"] = "",
["name"] = "",
["className"] = "",
["professions"] = {
},
["level"] = 0,
["raceName"] = "",
["raceID"] = 0,
},
["Player-3693-0E6E2E59"] = {
["enabled"] = true,
["GUID"] = "Player-3693-0E6E2E59",
["factionEnglish"] = "Horde",
["raceName"] = "Vulpera",
["lastUpdate"] = 1727499872,
["realmName"] = "Kel'Thuzad",
["classID"] = 1,
["name"] = "Esker",
["completed"] = {
[83062] = true,
[83909] = true,
[83850] = true,
[83854] = true,
[83106] = true,
[83051] = true,
[82614] = true,
[83059] = true,
[83256] = true,
[29518] = true,
[83906] = true,
[83910] = true,
[83851] = true,
[83855] = true,
[83733] = true,
[83052] = true,
[84127] = true,
[83257] = true,
[82631] = true,
[83907] = true,
[84226] = true,
[83852] = true,
[83049] = true,
[83053] = true,
[83726] = true,
[81391] = true,
[29508] = true,
[83911] = true,
[83912] = true,
[83908] = true,
[84227] = true,
[83853] = true,
[81390] = true,
[83849] = true,
[83913] = true,
[83050] = true,
[83054] = true,
[83848] = true,
},
["professions"] = {
{
["enabled"] = true,
["knowledgeMaxLevel"] = 865,
["maxLevel"] = 100,
["knowledgeLevel"] = 145,
["skillLineID"] = 164,
["level"] = 100,
["specializations"] = {
{
["rootNodeID"] = 99267,
["highlights"] = {
{
["description"] = "Learn to craft Everburning Ignition and set your crafting ability ablaze.",
},
{
["description"] = "Enhance the Everburning Ignition to grant even more Ingenuity, Multicraft, and Resourcefulness.",
},
{
["description"] = "Gain additional charges of Everburning Ignition and reduce its cooldown rate.",
},
},
["description"] = "Unlock the secrets of the Everburning Forge, significantly improving your Blacksmithing capabilities while active.",
["knowledgeLevel"] = 40,
["rootIconID"] = 5931165,
["configID"] = 48694178,
["state"] = 1,
["treeID"] = 966,
["name"] = "Everburning Forge",
["knowledgeMaxLevel"] = 100,
},
{
["rootNodeID"] = 99589,
["highlights"] = {
{
["description"] = "Add Optional and Finishing Reagents when crafting profession equipment to increase their potency.",
},
{
["description"] = "Improve your ability to craft consumable items, such as weapon stones and frameworks.",
},
},
["description"] = "Master the art of smithing profession equipment and consumable items.",
["knowledgeLevel"] = 80,
["rootIconID"] = 4624394,
["configID"] = 48694178,
["state"] = 1,
["treeID"] = 971,
["name"] = "Means of Production",
["knowledgeMaxLevel"] = 240,
},
{
["rootNodeID"] = 99453,
["highlights"] = {
{
["description"] = "Learn recipes to craft Epic weapons.",
},
{
["description"] = "Add Optional and Finishing Reagents when crafting weapons to increase their potency.",
},
{
["description"] = "Improve your ability to repair equipment with the Master's Hammer.",
},
{
["description"] = "Gain additional Skill when crafting weapons.",
},
},
["description"] = "Master the techniques of Khaz Algar to improve your ability to craft weapons of various types.",
["knowledgeLevel"] = 25,
["rootIconID"] = 5547326,
["configID"] = 48694178,
["state"] = 1,
["treeID"] = 969,
["name"] = "Weaponsmithing",
["knowledgeMaxLevel"] = 180,
},
{
["rootNodeID"] = 99239,
["highlights"] = {
{
["description"] = "Learn recipes to craft Epic plate armor and shields.",
},
{
["description"] = "Add Optional and Finishing Reagents when crafting armor and shields to increase their potency.",
},
{
["description"] = "Improve your ability to repair equipment with the Master's Hammer.",
},
{
["description"] = "Gain additional Skill when crafting armor and shields.",
},
},
["description"] = "Leverage the tools and techniques of Khaz Algar to craft plate armor.",
["knowledgeLevel"] = 0,
["rootIconID"] = 5799475,
["configID"] = 48694178,
["state"] = 1,
["treeID"] = 965,
["name"] = "Armorsmithing",
["knowledgeMaxLevel"] = 345,
},
},
["knowledgeUnspent"] = 5,
},
{
["enabled"] = true,
["knowledgeMaxLevel"] = 500,
["maxLevel"] = 100,
["knowledgeLevel"] = 158,
["skillLineID"] = 186,
["level"] = 100,
["specializations"] = {
{
["rootNodeID"] = 100085,
["highlights"] = {
{
["description"] = "Gain increases to skill to acquire higher quality ore when mining the ores you have chosen to specialize in.",
},
{
["description"] = "Learn Refinement recipes which allow you to improve the quality of small quantities of ore.",
},
{
["description"] = "Improve your ability to harvest the elusive Null Stones.",
},
{
["description"] = "Improve the speed at which you mine ore, so you have time to mine even more!",
},
},
["description"] = "Specialize in the acquisition of various ores scattered upon and beneath Khaz Algar.",
["knowledgeLevel"] = 98,
["rootIconID"] = 876371,
["configID"] = 48694746,
["state"] = 1,
["treeID"] = 982,
["name"] = "Plethora of Ore",
["knowledgeMaxLevel"] = 185,
},
{
["rootNodeID"] = 100111,
["highlights"] = {
{
["description"] = "Learn how to mine ore deposits while mounted.",
},
{
["description"] = "Improve your finesse, deftness, and perception when mining in Khaz Algar.",
},
{
["description"] = "Chunks of ore dislodged while mining can be mined for additional yield.",
},
},
["description"] = "Specialize in nuanced mining methodology to improve your techniques. Knowledge in this area will allow you to get the most out of your rich and seam deposits discoveries.",
["knowledgeLevel"] = 60,
["rootIconID"] = 4620679,
["configID"] = 48694746,
["state"] = 1,
["treeID"] = 983,
["name"] = "Mining Fundamentals",
["knowledgeMaxLevel"] = 110,
},
{
["rootNodeID"] = 100162,
["highlights"] = {
{
["description"] = "Gain significant cooldown reduction to Overload while mining.",
},
{
["description"] = "Learn how to protect yourself and improve yield from unusual deposits found across Khaz Algar.",
},
{
["description"] = "Gain an additional charge of Overload.",
},
},
["description"] = "Specialize in mining unusual deposits across Khaz Algar, such as those touched by ominous forces.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554440,
["configID"] = 48694746,
["state"] = 1,
["treeID"] = 984,
["name"] = "Mastering the Mysterious",
["knowledgeMaxLevel"] = 205,
},
},
["knowledgeUnspent"] = 1,
},
},
["classFile"] = "WARRIOR",
["className"] = "Warrior",
["factionName"] = "Horde",
["level"] = 80,
["raceEnglish"] = "Vulpera",
["raceID"] = 35,
},
["Player-75-0F3C82E0"] = {
["enabled"] = true,
["factionEnglish"] = "",
["raceEnglish"] = "",
["lastUpdate"] = 0,
["realmName"] = "",
["classID"] = 0,
["GUID"] = "Player-75-0F3C82E0",
["raceName"] = "",
["factionName"] = "",
["name"] = "",
["className"] = "",
["professions"] = {
},
["level"] = 0,
["completed"] = {
},
["raceID"] = 0,
},
["Player-75-0EEA107B"] = {
["GUID"] = "Player-75-0EEA107B",
["enabled"] = true,
["factionEnglish"] = "Horde",
["raceName"] = "Orc",
["lastUpdate"] = 1727567394,
["realmName"] = "Argent Dawn",
["classID"] = 10,
["name"] = "Sverdrup",
["completed"] = {
[83877] = true,
[83881] = true,
[83885] = true,
[83889] = true,
[83874] = true,
[29514] = true,
[83882] = true,
[83886] = true,
[82630] = true,
[83264] = true,
[83729] = true,
[83875] = true,
[83879] = true,
[83883] = true,
[83887] = true,
[80749] = true,
[82958] = true,
[83730] = true,
[29515] = true,
[81421] = true,
[84129] = true,
[83876] = true,
[81423] = true,
[83884] = true,
[83888] = true,
[83262] = true,
[82636] = true,
[80750] = true,
[81417] = true,
[81419] = true,
[83066] = true,
[83878] = true,
[83880] = true,
[83064] = true,
[81420] = true,
[81418] = true,
[81416] = true,
[81422] = true,
},
["professions"] = {
{
["knowledgeMaxLevel"] = 560,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 173,
["skillLineID"] = 182,
["specializations"] = {
{
["rootNodeID"] = 96358,
["highlights"] = {
{
["description"] = "Increase your skill while gathering herbs.",
},
{
["description"] = "Increase the effect of Finesse while gathering herbs.",
},
{
["description"] = "Learn to refine herbs into higher qualities.",
},
{
["description"] = "Gather the rare and elusive Null Lotus from additional sources.",
},
},
["description"] = "Specialize in gathering the herbs found throughout Khaz Algar.",
["knowledgeLevel"] = 53,
["rootIconID"] = 3615517,
["configID"] = 51061426,
["state"] = 1,
["treeID"] = 905,
["knowledgeMaxLevel"] = 240,
["name"] = "Bountiful Harvests",
},
{
["rootNodeID"] = 96248,
["highlights"] = {
{
["description"] = "Gather herbs while mounted.",
},
{
["description"] = "Learn to plant and cultivate seeds at Beledar's Bounty in Hallowfall.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while gathering herbs.",
},
},
["description"] = "Study the various plantlife found on and around Khaz Algar and how to gather them.",
["knowledgeLevel"] = 120,
["rootIconID"] = 134913,
["configID"] = 51061426,
["state"] = 1,
["treeID"] = 903,
["knowledgeMaxLevel"] = 120,
["name"] = "Botany",
},
{
["rootNodeID"] = 96298,
["highlights"] = {
{
["description"] = "Reduce the cooldown of Overload Empowered Herbs while you gather.",
},
{
["description"] = "Reduce the negative side-effects of gathering empowered herbs and gain additional benefits.",
},
{
["description"] = "Increase your Finesse and Perception while gathering empowered herbs.",
},
},
["description"] = "Specialize in gathering empowered herbs and Overloading them to various effects.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554441,
["configID"] = 51061426,
["state"] = 1,
["treeID"] = 904,
["knowledgeMaxLevel"] = 200,
["name"] = "Overloading the Underground",
},
},
["level"] = 100,
["knowledgeUnspent"] = 0,
},
{
["knowledgeMaxLevel"] = 780,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 143,
["skillLineID"] = 773,
["specializations"] = {
{
["rootNodeID"] = 101595,
["highlights"] = {
{
["description"] = "Become an expert on Algari Treatises used by all professions.",
},
{
["description"] = "Extract more knowledge from treatises each week.",
},
{
["description"] = "Significantly boost your crafting stats including Ingenuity, Resourcefulness, and Multicraft.",
},
},
["description"] = "Master the fundamentals of Inscription, improving your ability to craft in general.",
["knowledgeLevel"] = 60,
["rootIconID"] = 4638491,
["configID"] = 51061363,
["state"] = 1,
["treeID"] = 1004,
["knowledgeMaxLevel"] = 120,
["name"] = "Pursuit of Knowledge",
},
{
["rootNodeID"] = 101627,
["highlights"] = {
{
["description"] = "Learn to rapidly create Inscription reagents when crafting in bulk.",
},
{
["description"] = "Gain additional skill when crafting all Inscription reagents.",
},
},
["description"] = "Master the art of milling and crafting reagents like inks and ciphers.",
["knowledgeLevel"] = 30,
["rootIconID"] = 4638492,
["configID"] = 51061363,
["state"] = 1,
["treeID"] = 1005,
["knowledgeMaxLevel"] = 120,
["name"] = "Pursuit of Perfection",
},
{
["rootNodeID"] = 101563,
["highlights"] = {
{
["description"] = "Master your quill and perfect other Profession Tools.",
},
{
["description"] = "Craft high quality Staves and Off-hands to be used in combat.",
},
{
["description"] = "Polish the production of equipment and save resources.",
},
},
["description"] = "Master your ability to craft new weapons and profession equipment.",
["knowledgeLevel"] = 0,
["rootIconID"] = 1122137,
["configID"] = 51061363,
["state"] = 1,
["treeID"] = 1003,
["knowledgeMaxLevel"] = 240,
["name"] = "Careful Carvings",
},
{
["rootNodeID"] = 101881,
["highlights"] = {
{
["description"] = "Learn how to transcribe and find Darkmoon Cards across Khaz Algar.",
},
{
["description"] = "Improve your ability to craft Contracts, Missives, and Vantus Runes.",
},
{
["description"] = "Embellish your gear with powerful Darkmoon Sigils.",
},
},
["description"] = "Master the creation of various inscription services and the esoteric Darkmoon Cards.",
["knowledgeLevel"] = 53,
["rootIconID"] = 4638485,
["configID"] = 51061363,
["state"] = 1,
["treeID"] = 1008,
["knowledgeMaxLevel"] = 300,
["name"] = "Archival Additions",
},
},
["level"] = 96,
["knowledgeUnspent"] = 0,
},
},
["classFile"] = "MONK",
["className"] = "Monk",
["factionName"] = "Horde",
["level"] = 80,
["raceEnglish"] = "Orc",
["raceID"] = 2,
},
["Player-75-0EE8A760"] = {
["enabled"] = true,
["GUID"] = "Player-75-0EE8A760",
["factionEnglish"] = "Alliance",
["raceName"] = "Worgen",
["lastUpdate"] = 1727645101,
["realmName"] = "Argent Dawn",
["classID"] = 4,
["name"] = "Estuary",
["completed"] = {
[80979] = true,
[83267] = true,
[83901] = true,
[83905] = true,
[83917] = true,
[83921] = true,
[83067] = true,
[29517] = true,
[83898] = true,
[83902] = true,
[83914] = true,
[83918] = true,
[84131] = true,
[83068] = true,
[83899] = true,
[83903] = true,
[83915] = true,
[82596] = true,
[83734] = true,
[29519] = true,
[83098] = true,
[80978] = true,
[81464] = true,
[81462] = true,
[81461] = true,
[81463] = true,
[83916] = true,
[83900] = true,
[83904] = true,
[82626] = true,
[84232] = true,
[81459] = true,
[83920] = true,
[83732] = true,
[81460] = true,
[84233] = true,
[83919] = true,
[83268] = true,
},
["professions"] = {
{
["enabled"] = true,
["knowledgeMaxLevel"] = 800,
["maxLevel"] = 100,
["knowledgeLevel"] = 146,
["skillLineID"] = 165,
["level"] = 79,
["specializations"] = {
{
["rootNodeID"] = 97640,
["highlights"] = {
{
["description"] = "Increase the effectiveness of Concentration and Ingenuity for all patterns.",
},
{
["description"] = "Improve your reagent saving capabilities when your Resourcefulness activates.",
},
{
["description"] = "Improve your ability to craft multiple consumables and reagents at the same time.",
},
},
["description"] = "Master your Leatherworking fundamentals to increase your reagent efficiency, ability to concentrate, general stitchwork, and production process.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4635266,
["configID"] = 51057238,
["state"] = 1,
["treeID"] = 937,
["knowledgeMaxLevel"] = 120,
["name"] = "Learned Leatherworker",
},
{
["rootNodeID"] = 97712,
["highlights"] = {
{
["description"] = "Learn to craft epic Rune-Branded leather armor.",
},
{
["description"] = "Customize leather armor you make with Optional and Finishing Reagents.",
},
{
["description"] = "Increase your Ingenuity, Resourcefulness, and Skill when crafting leather armor.",
},
},
["description"] = "Specialize in crafting leather armor, increasing your ability to craft at a higher quality. In addition, learn new patterns and ways to customize the armor you craft!",
["knowledgeLevel"] = 90,
["rootIconID"] = 4635264,
["configID"] = 51057238,
["state"] = 1,
["treeID"] = 938,
["knowledgeMaxLevel"] = 250,
["name"] = "Luxurious Leathers",
},
{
["rootNodeID"] = 97784,
["highlights"] = {
{
["description"] = "Learn to craft epic Glyph-Etched mail armor.",
},
{
["description"] = "Customize mail armor you make with Optional and Finishing Reagents.",
},
{
["description"] = "Increase your Ingenuity, Resourcefulness, and Skill when crafting mail armor.",
},
},
["description"] = "Specialize in crafting mail armor, increasing your ability to craft at a higher quality. In addition, learn new patterns and ways to customize the armor you craft!",
["knowledgeLevel"] = 26,
["rootIconID"] = 4635255,
["configID"] = 51057238,
["state"] = 1,
["treeID"] = 939,
["knowledgeMaxLevel"] = 250,
["name"] = "Concrete Chitin",
},
{
["rootNodeID"] = 97560,
["highlights"] = {
{
["description"] = "Improve your ability to craft profession equipment.",
},
{
["description"] = "Learn to craft embellishments with various effects.",
},
{
["description"] = "Gain additional skill and resourcefulness when crafting armor kits and other consumables.",
},
},
["description"] = "Master the techniques of Khaz Algar to craft specialty items beyond that of standard armor.",
["knowledgeLevel"] = 30,
["rootIconID"] = 4635270,
["configID"] = 51057238,
["state"] = 1,
["treeID"] = 935,
["knowledgeMaxLevel"] = 180,
["name"] = "Flawless Fortes",
},
},
["knowledgeUnspent"] = 0,
},
{
["enabled"] = true,
["knowledgeMaxLevel"] = 400,
["maxLevel"] = 105,
["knowledgeLevel"] = 127,
["skillLineID"] = 393,
["level"] = 105,
["specializations"] = {
{
["rootNodeID"] = 96830,
["highlights"] = {
{
["description"] = "Learn to Sharpen Your Knife, guaranteeing hides from skinning.",
},
{
["description"] = "Increase your skill while skinning.",
},
{
["description"] = "Refine lower quality reagents into a higher quality.",
},
},
["description"] = "Improve at your general skinning techniques, learning how to gather, prepare, and store the various standard reagents you can gather from the creatures of Khaz Algar.",
["knowledgeLevel"] = 120,
["rootIconID"] = 4046656,
["configID"] = 51057249,
["state"] = 1,
["treeID"] = 921,
["knowledgeMaxLevel"] = 120,
["name"] = "Tanning",
},
{
["rootNodeID"] = 96770,
["highlights"] = {
{
["description"] = "Gather meat for cooking from skinned creatures.",
},
{
["description"] = "Gather additional rare reagents from skinned creatures.",
},
{
["description"] = "Craft Lures used to target specific fish.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while skinning.",
},
},
["description"] = "Specialize in harvesting unique materials that are utilized by many professions.",
["knowledgeLevel"] = 0,
["rootIconID"] = 464119,
["configID"] = 51057249,
["state"] = 1,
["treeID"] = 919,
["knowledgeMaxLevel"] = 160,
["name"] = "Harvesting",
},
{
["rootNodeID"] = 96800,
["highlights"] = {
{
["description"] = "Create bait to lure creatures that yield rare materials when skinned.",
},
{
["description"] = "Infuse bait with empowered energy found throughout Khaz Algar, allowing you to gather additional reagents.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while skinning.",
},
},
["description"] = "Specialize in creating special baits to lure out the elusive creatures of Khaz Algar.",
["knowledgeLevel"] = 7,
["rootIconID"] = 134026,
["configID"] = 51057249,
["state"] = 1,
["treeID"] = 920,
["knowledgeMaxLevel"] = 120,
["name"] = "Luring",
},
},
["knowledgeUnspent"] = 0,
},
},
["classFile"] = "ROGUE",
["className"] = "Rogue",
["factionName"] = "Alliance",
["level"] = 80,
["raceEnglish"] = "Worgen",
["raceID"] = 22,
},
["Player-75-0F3C7B2E"] = {
["enabled"] = true,
["factionEnglish"] = "",
["raceEnglish"] = "",
["lastUpdate"] = 0,
["realmName"] = "",
["classID"] = 0,
["GUID"] = "Player-75-0F3C7B2E",
["completed"] = {
},
["factionName"] = "",
["name"] = "",
["className"] = "",
["professions"] = {
},
["level"] = 0,
["raceName"] = "",
["raceID"] = 0,
},
["Player-75-0EEA1257"] = {
["enabled"] = true,
["factionEnglish"] = "",
["lastUpdate"] = 0,
["raceEnglish"] = "",
["realmName"] = "",
["classID"] = 0,
["completed"] = {
},
["raceName"] = "",
["professions"] = {
},
["name"] = "",
["className"] = "",
["factionName"] = "",
["level"] = 0,
["GUID"] = "Player-75-0EEA1257",
["raceID"] = 0,
},
["Player-75-0EEA10F9"] = {
["GUID"] = "Player-75-0EEA10F9",
["enabled"] = true,
["factionEnglish"] = "Alliance",
["lastUpdate"] = 1727646736,
["raceEnglish"] = "Pandaren",
["realmName"] = "Argent Dawn",
["classID"] = 7,
["classFile"] = "SHAMAN",
["raceName"] = "Pandaren",
["professions"] = {
{
["knowledgeMaxLevel"] = 560,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 165,
["specializations"] = {
{
["rootNodeID"] = 96358,
["highlights"] = {
{
["description"] = "Increase your skill while gathering herbs.",
},
{
["description"] = "Increase the effect of Finesse while gathering herbs.",
},
{
["description"] = "Learn to refine herbs into higher qualities.",
},
{
["description"] = "Gather the rare and elusive Null Lotus from additional sources.",
},
},
["description"] = "Specialize in gathering the herbs found throughout Khaz Algar.",
["knowledgeLevel"] = 120,
["rootIconID"] = 3615517,
["configID"] = 51292163,
["state"] = 1,
["treeID"] = 905,
["knowledgeMaxLevel"] = 240,
["name"] = "Bountiful Harvests",
},
{
["rootNodeID"] = 96248,
["highlights"] = {
{
["description"] = "Gather herbs while mounted.",
},
{
["description"] = "Learn to plant and cultivate seeds at Beledar's Bounty in Hallowfall.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while gathering herbs.",
},
},
["description"] = "Study the various plantlife found on and around Khaz Algar and how to gather them.",
["knowledgeLevel"] = 40,
["rootIconID"] = 134913,
["configID"] = 51292163,
["state"] = 1,
["treeID"] = 903,
["knowledgeMaxLevel"] = 120,
["name"] = "Botany",
},
{
["rootNodeID"] = 96298,
["highlights"] = {
{
["description"] = "Reduce the cooldown of Overload Empowered Herbs while you gather.",
},
{
["description"] = "Reduce the negative side-effects of gathering empowered herbs and gain additional benefits.",
},
{
["description"] = "Increase your Finesse and Perception while gathering empowered herbs.",
},
},
["description"] = "Specialize in gathering empowered herbs and Overloading them to various effects.",
["knowledgeLevel"] = 5,
["rootIconID"] = 4554441,
["configID"] = 51292163,
["state"] = 1,
["treeID"] = 904,
["knowledgeMaxLevel"] = 200,
["name"] = "Overloading the Underground",
},
},
["level"] = 100,
["skillLineID"] = 182,
["knowledgeUnspent"] = 3,
},
{
["knowledgeMaxLevel"] = 400,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 124,
["specializations"] = {
{
["rootNodeID"] = 96830,
["highlights"] = {
{
["description"] = "Learn to Sharpen Your Knife, guaranteeing hides from skinning.",
},
{
["description"] = "Increase your skill while skinning.",
},
{
["description"] = "Refine lower quality reagents into a higher quality.",
},
},
["description"] = "Improve at your general skinning techniques, learning how to gather, prepare, and store the various standard reagents you can gather from the creatures of Khaz Algar.",
["knowledgeLevel"] = 120,
["rootIconID"] = 4046656,
["configID"] = 50055875,
["state"] = 1,
["treeID"] = 921,
["knowledgeMaxLevel"] = 120,
["name"] = "Tanning",
},
{
["rootNodeID"] = 96770,
["highlights"] = {
{
["description"] = "Gather meat for cooking from skinned creatures.",
},
{
["description"] = "Gather additional rare reagents from skinned creatures.",
},
{
["description"] = "Craft Lures used to target specific fish.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while skinning.",
},
},
["description"] = "Specialize in harvesting unique materials that are utilized by many professions.",
["knowledgeLevel"] = 4,
["rootIconID"] = 464119,
["configID"] = 50055875,
["state"] = 1,
["treeID"] = 919,
["knowledgeMaxLevel"] = 160,
["name"] = "Harvesting",
},
{
["rootNodeID"] = 96800,
["highlights"] = {
{
["description"] = "Create bait to lure creatures that yield rare materials when skinned.",
},
{
["description"] = "Infuse bait with empowered energy found throughout Khaz Algar, allowing you to gather additional reagents.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while skinning.",
},
},
["description"] = "Specialize in creating special baits to lure out the elusive creatures of Khaz Algar.",
["knowledgeLevel"] = 0,
["rootIconID"] = 134026,
["configID"] = 50055875,
["state"] = 1,
["treeID"] = 920,
["knowledgeMaxLevel"] = 120,
["name"] = "Luring",
},
},
["level"] = 100,
["skillLineID"] = 393,
["knowledgeUnspent"] = 0,
},
},
["name"] = "Headcut",
["className"] = "Shaman",
["factionName"] = "Alliance",
["level"] = 80,
["completed"] = {
[83877] = true,
[83881] = true,
[83066] = true,
[83917] = true,
[83921] = true,
[83874] = true,
[29514] = true,
[83067] = true,
[82630] = true,
[29519] = true,
[83914] = true,
[83729] = true,
[83875] = true,
[83879] = true,
[82958] = true,
[83915] = true,
[82596] = true,
[83734] = true,
[83098] = true,
[84233] = true,
[83876] = true,
[81423] = true,
[84232] = true,
[83918] = true,
[83880] = true,
[83919] = true,
[83900] = true,
[81417] = true,
[81419] = true,
[83878] = true,
[83916] = true,
[83920] = true,
[81421] = true,
[81420] = true,
[81418] = true,
[81416] = true,
[81422] = true,
},
["raceID"] = 25,
},
["Player-3693-0E792E1F"] = {
["GUID"] = "Player-3693-0E792E1F",
["enabled"] = true,
["factionEnglish"] = "Horde",
["raceEnglish"] = "Goblin",
["lastUpdate"] = 1727567185,
["realmName"] = "Kel'Thuzad",
["classID"] = 5,
["classFile"] = "PRIEST",
["raceName"] = "Goblin",
["professions"] = {
{
["knowledgeMaxLevel"] = 565,
["enabled"] = true,
["maxLevel"] = 105,
["knowledgeLevel"] = 147,
["skillLineID"] = 171,
["level"] = 105,
["specializations"] = {
{
["rootNodeID"] = 99020,
["highlights"] = {
{
["description"] = "Reduce the risks and increase the benefits of experimenting with the herbs of Khaz Algar.",
},
{
["description"] = "Improve the chance to discover new alchemical formulae.",
},
{
["description"] = "Create reagents from combinations of herbs.",
},
{
["description"] = "Increase your Skill, Ingenuity, and reduce Concentration costs when crafting recipes with specific herbs.",
},
},
["description"] = "Master your ability to experiment with the various flora found in Khaz Algar.",
["knowledgeLevel"] = 30,
["rootIconID"] = 4620669,
["configID"] = 49997287,
["state"] = 1,
["treeID"] = 961,
["name"] = "Alchemical Mastery",
["knowledgeMaxLevel"] = 250,
},
{
["rootNodeID"] = 98953,
["highlights"] = {
{
["description"] = "Craft additional soulbound Flasks per day.",
},
{
["description"] = "Learn to craft Flask Cauldrons.",
},
{
["description"] = "Increase your Multicraft, Resourcefulness and Skill when crafting Flasks and Phials.",
},
{
["description"] = "Gain Spillover from crafting Flasks and Phials.",
},
},
["description"] = "Master the arts of flask and phial-crafting using techniques found in Khaz Algar.",
["knowledgeLevel"] = 0,
["rootIconID"] = 967511,
["configID"] = 49997287,
["state"] = 1,
["treeID"] = 960,
["name"] = "Fantastic Flasks",
["knowledgeMaxLevel"] = 80,
},
{
["rootNodeID"] = 99041,
["highlights"] = {
{
["description"] = "Craft additional soulbound conjured potions per day.",
},
{
["description"] = "Learn to craft Potion Cauldrons.",
},
{
["description"] = "Increase your Multicraft, Resourcefulness and Skill when crafting potions.",
},
},
["description"] = "Master the subtle art of potion-making via techniques from Khaz Algar.",
["knowledgeLevel"] = 15,
["rootIconID"] = 967511,
["configID"] = 49997287,
["state"] = 1,
["treeID"] = 962,
["name"] = "Potent Potions",
["knowledgeMaxLevel"] = 55,
},
{
["rootNodeID"] = 99059,
["highlights"] = {
{
["description"] = "Gain bonus transmutagen from performing acts of thaumaturgy and transmutation.",
},
{
["description"] = "Create Coreway Catalysts.",
},
{
["description"] = "Increase your Resourcefulness, Skill, and additional yields from your acts of thaumaturgy and transmutation.",
},
},
["description"] = "Master the art of transmuting materials into other substances.",
["knowledgeLevel"] = 102,
["rootIconID"] = 4554336,
["configID"] = 49997287,
["state"] = 1,
["treeID"] = 963,
["name"] = "Thaumaturgy",
["knowledgeMaxLevel"] = 180,
},
},
["knowledgeUnspent"] = 0,
},
{
["knowledgeMaxLevel"] = 560,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 174,
["skillLineID"] = 182,
["level"] = 100,
["specializations"] = {
{
["rootNodeID"] = 96358,
["highlights"] = {
{
["description"] = "Increase your skill while gathering herbs.",
},
{
["description"] = "Increase the effect of Finesse while gathering herbs.",
},
{
["description"] = "Learn to refine herbs into higher qualities.",
},
{
["description"] = "Gather the rare and elusive Null Lotus from additional sources.",
},
},
["description"] = "Specialize in gathering the herbs found throughout Khaz Algar.",
["knowledgeLevel"] = 134,
["rootIconID"] = 3615517,
["configID"] = 49997386,
["state"] = 1,
["treeID"] = 905,
["name"] = "Bountiful Harvests",
["knowledgeMaxLevel"] = 240,
},
{
["rootNodeID"] = 96248,
["highlights"] = {
{
["description"] = "Gather herbs while mounted.",
},
{
["description"] = "Learn to plant and cultivate seeds at Beledar's Bounty in Hallowfall.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while gathering herbs.",
},
},
["description"] = "Study the various plantlife found on and around Khaz Algar and how to gather them.",
["knowledgeLevel"] = 40,
["rootIconID"] = 134913,
["configID"] = 49997386,
["state"] = 1,
["treeID"] = 903,
["name"] = "Botany",
["knowledgeMaxLevel"] = 120,
},
{
["rootNodeID"] = 96298,
["highlights"] = {
{
["description"] = "Reduce the cooldown of Overload Empowered Herbs while you gather.",
},
{
["description"] = "Reduce the negative side-effects of gathering empowered herbs and gain additional benefits.",
},
{
["description"] = "Increase your Finesse and Perception while gathering empowered herbs.",
},
},
["description"] = "Specialize in gathering empowered herbs and Overloading them to various effects.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554441,
["configID"] = 49997386,
["state"] = 1,
["treeID"] = 904,
["name"] = "Overloading the Underground",
["knowledgeMaxLevel"] = 200,
},
},
["knowledgeUnspent"] = 0,
},
},
["name"] = "Gelae",
["className"] = "Priest",
["factionName"] = "Horde",
["level"] = 80,
["completed"] = {
[83877] = true,
[84133] = true,
[83066] = true,
[82633] = true,
[83842] = true,
[83846] = true,
[83874] = true,
[83878] = true,
[82630] = true,
[83843] = true,
[83847] = true,
[83725] = true,
[83729] = true,
[83875] = true,
[83879] = true,
[83253] = true,
[83840] = true,
[83844] = true,
[81147] = true,
[83881] = true,
[82958] = true,
[83876] = true,
[83880] = true,
[81422] = true,
[81146] = true,
[81417] = true,
[83058] = true,
[81423] = true,
[83841] = true,
[83845] = true,
[29506] = true,
[83255] = true,
[81418] = true,
[81419] = true,
[81420] = true,
[81421] = true,
[81416] = true,
[29514] = true,
},
["raceID"] = 9,
},
["Player-75-0EE5568B"] = {
["GUID"] = "Player-75-0EE5568B",
["enabled"] = true,
["factionEnglish"] = "Alliance",
["lastUpdate"] = 1727386281,
["raceEnglish"] = "Dracthyr",
["realmName"] = "Argent Dawn",
["classID"] = 13,
["classFile"] = "EVOKER",
["raceName"] = "Dracthyr",
["professions"] = {
{
["knowledgeMaxLevel"] = 560,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 171,
["level"] = 100,
["specializations"] = {
{
["rootNodeID"] = 96358,
["highlights"] = {
{
["description"] = "Increase your skill while gathering herbs.",
},
{
["description"] = "Increase the effect of Finesse while gathering herbs.",
},
{
["description"] = "Learn to refine herbs into higher qualities.",
},
{
["description"] = "Gather the rare and elusive Null Lotus from additional sources.",
},
},
["description"] = "Specialize in gathering the herbs found throughout Khaz Algar.",
["knowledgeLevel"] = 131,
["rootIconID"] = 3615517,
["configID"] = 49313670,
["state"] = 1,
["treeID"] = 905,
["name"] = "Bountiful Harvests",
["knowledgeMaxLevel"] = 240,
},
{
["rootNodeID"] = 96248,
["highlights"] = {
{
["description"] = "Gather herbs while mounted.",
},
{
["description"] = "Learn to plant and cultivate seeds at Beledar's Bounty in Hallowfall.",
},
{
["description"] = "Increase your Deftness, Finesse, and Perception while gathering herbs.",
},
},
["description"] = "Study the various plantlife found on and around Khaz Algar and how to gather them.",
["knowledgeLevel"] = 40,
["rootIconID"] = 134913,
["configID"] = 49313670,
["state"] = 1,
["treeID"] = 903,
["name"] = "Botany",
["knowledgeMaxLevel"] = 120,
},
{
["rootNodeID"] = 96298,
["highlights"] = {
{
["description"] = "Reduce the cooldown of Overload Empowered Herbs while you gather.",
},
{
["description"] = "Reduce the negative side-effects of gathering empowered herbs and gain additional benefits.",
},
{
["description"] = "Increase your Finesse and Perception while gathering empowered herbs.",
},
},
["description"] = "Specialize in gathering empowered herbs and Overloading them to various effects.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554441,
["configID"] = 49313670,
["state"] = 1,
["treeID"] = 904,
["name"] = "Overloading the Underground",
["knowledgeMaxLevel"] = 200,
},
},
["skillLineID"] = 182,
["knowledgeUnspent"] = 0,
},
{
["knowledgeMaxLevel"] = 500,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 157,
["level"] = 100,
["specializations"] = {
{
["rootNodeID"] = 100085,
["highlights"] = {
{
["description"] = "Gain increases to skill to acquire higher quality ore when mining the ores you have chosen to specialize in.",
},
{
["description"] = "Learn Refinement recipes which allow you to improve the quality of small quantities of ore.",
},
{
["description"] = "Improve your ability to harvest the elusive Null Stones.",
},
{
["description"] = "Improve the speed at which you mine ore, so you have time to mine even more!",
},
},
["description"] = "Specialize in the acquisition of various ores scattered upon and beneath Khaz Algar.",
["knowledgeLevel"] = 97,
["rootIconID"] = 876371,
["configID"] = 49314067,
["state"] = 1,
["treeID"] = 982,
["name"] = "Plethora of Ore",
["knowledgeMaxLevel"] = 185,
},
{
["rootNodeID"] = 100111,
["highlights"] = {
{
["description"] = "Learn how to mine ore deposits while mounted.",
},
{
["description"] = "Improve your finesse, deftness, and perception when mining in Khaz Algar.",
},
{
["description"] = "Chunks of ore dislodged while mining can be mined for additional yield.",
},
},
["description"] = "Specialize in nuanced mining methodology to improve your techniques. Knowledge in this area will allow you to get the most out of your rich and seam deposits discoveries.",
["knowledgeLevel"] = 60,
["rootIconID"] = 4620679,
["configID"] = 49314067,
["state"] = 1,
["treeID"] = 983,
["name"] = "Mining Fundamentals",
["knowledgeMaxLevel"] = 110,
},
{
["rootNodeID"] = 100162,
["highlights"] = {
{
["description"] = "Gain significant cooldown reduction to Overload while mining.",
},
{
["description"] = "Learn how to protect yourself and improve yield from unusual deposits found across Khaz Algar.",
},
{
["description"] = "Gain an additional charge of Overload.",
},
},
["description"] = "Specialize in mining unusual deposits across Khaz Algar, such as those touched by ominous forces.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554440,
["configID"] = 49314067,
["state"] = 1,
["treeID"] = 984,
["name"] = "Mastering the Mysterious",
["knowledgeMaxLevel"] = 205,
},
},
["skillLineID"] = 186,
["knowledgeUnspent"] = 0,
},
},
["name"] = "Alluvium",
["className"] = "Evoker",
["factionName"] = "Alliance",
["level"] = 80,
["completed"] = {
[83877] = true,
[83881] = true,
[83066] = true,
[83909] = true,
[83913] = true,
[83106] = true,
[83051] = true,
[82614] = true,
[81421] = true,
[82630] = true,
[29518] = true,
[83906] = true,
[81390] = true,
[83729] = true,
[83733] = true,
[83052] = true,
[83875] = true,
[83879] = true,
[82958] = true,
[83907] = true,
[81391] = true,
[81422] = true,
[81416] = true,
[83049] = true,
[83053] = true,
[83876] = true,
[81423] = true,
[83878] = true,
[81420] = true,
[83062] = true,
[29514] = true,
[83880] = true,
[81419] = true,
[83908] = true,
[83912] = true,
[81417] = true,
[83874] = true,
[83910] = true,
[83911] = true,
[83050] = true,
[83054] = true,
[81418] = true,
},
["raceID"] = 52,
},
["Player-75-0F40E777"] = {
["GUID"] = "Player-75-0F40E777",
["enabled"] = true,
["factionEnglish"] = "Horde",
["lastUpdate"] = 1727643894,
["raceEnglish"] = "Nightborne",
["realmName"] = "Argent Dawn",
["classID"] = 8,
["classFile"] = "MAGE",
["raceName"] = "Nightborne",
["professions"] = {
{
["knowledgeMaxLevel"] = 670,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 90,
["specializations"] = {
{
["rootNodeID"] = 101801,
["highlights"] = {
{
["description"] = "Consecrate Weavercloth into powerful Consecreated Equipment.",
},
{
["description"] = "Ascend your Consecrated Equipment to higher item level ",
},
{
["description"] = "Gain additional skill when crafting Consecrated Equipment.",
},
{
["description"] = "Add Optional and Finishing Reagents to further empower Consecrated Equipment.",
},
},
["description"] = "Specialize in crafting a broad range of equipment necessary for your adventures in Khaz Algar.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4624558,
["configID"] = 50533535,
["state"] = 0,
["treeID"] = 1007,
["knowledgeMaxLevel"] = 300,
["name"] = "Threads of Devotion",
},
{
["rootNodeID"] = 100306,
["highlights"] = {
{
["description"] = "Learn recipes centered on the magical consistency of Dawn's light and Dusk's shadow.",
},
{
["description"] = "Craft unique Optional Reagents used by all sorts of adventurers.",
},
{
["description"] = "Craft Duskweave and Dawnweave Bolts more frequently each day.",
},
{
["description"] = "Imbue Dawnweave and Duskweave threads into powerful set bonus equipment.",
},
},
["description"] = "Specialize in the energy imbued in threads around Khaz Algar to make powerful cloth gear and reagent items.",
["knowledgeLevel"] = 30,
["rootIconID"] = 4914680,
["configID"] = 50533535,
["state"] = 1,
["treeID"] = 987,
["knowledgeMaxLevel"] = 130,
["name"] = "From Dawn Until Dusk",
},
{
["rootNodeID"] = 100907,
["highlights"] = {
{
["description"] = "Craft powerful Spellthreads used by all kinds of adventurers.",
},
{
["description"] = "Perfect your ability to unravel and weave the highest quality cloth.",
},
{
["description"] = "Become an expert in embroidering quality Finishing Reagents used in various crafts.",
},
{
["description"] = "Improve the quality of the materials you use and perfect your tailoring empire.",
},
},
["description"] = "Specialize in the techniques necessary to become an expert at unraveling various pieces of cloth, weaving that cloth into bolts, and embroidering various items. ",
["knowledgeLevel"] = 30,
["rootIconID"] = 4624569,
["configID"] = 50533535,
["state"] = 1,
["treeID"] = 998,
["knowledgeMaxLevel"] = 120,
["name"] = "Quality Fabric",
},
{
["rootNodeID"] = 100939,
["highlights"] = {
{
["description"] = "Increase the amount of cloth you find across Khaz Algar.",
},
{
["description"] = "Increase the effectiveness of Ingenuity for all recipes.",
},
{
["description"] = "Increase the effectiveness of Resourcefulness for all recipes.",
},
{
["description"] = "Increase the effectiveness of Multicraft for all recipes.",
},
},
["description"] = "Improve the fundamentals of Tailoring and become more efficient at crafting all kinds of Tailoring goods.",
["knowledgeLevel"] = 30,
["rootIconID"] = 2023245,
["configID"] = 50533535,
["state"] = 1,
["treeID"] = 999,
["knowledgeMaxLevel"] = 120,
["name"] = "Textile Treasures",
},
},
["level"] = 68,
["skillLineID"] = 197,
["knowledgeUnspent"] = 45,
},
{
["knowledgeMaxLevel"] = 640,
["enabled"] = true,
["maxLevel"] = 100,
["knowledgeLevel"] = 153,
["specializations"] = {
{
["rootNodeID"] = 100040,
["highlights"] = {
{
["description"] = "Learn to shatter magical essences, gaining temporary bonuses that improve the more you specialize.",
},
{
["description"] = "Improve the efficiency of your Concentration and Ingenuity.",
},
{
["description"] = "Improve your Multicraft yield for consumable products.",
},
},
["description"] = "Specialize in shattering the magical essences of Khaz Algar, gleaning fleeting but increasingly potent crafting bonuses from the magic within. Your studies will also benefit your Concentration!",
["knowledgeLevel"] = 0,
["rootIconID"] = 4777834,
["configID"] = 50533544,
["state"] = 1,
["treeID"] = 981,
["knowledgeMaxLevel"] = 120,
["name"] = "Supplementary Shattering",
},
{
["rootNodeID"] = 99890,
["highlights"] = {
{
["description"] = "Increase the quality of enchanting reagents created through disenchanting.",
},
{
["description"] = "Increase the quantity of Storm Dust and Gleaming Shards you can receive when disenchanting.",
},
{
["description"] = "Unlock the ability to sometimes extract magical essences when disenchanting Epic items.",
},
},
["description"] = "Master your disenchanting capabilities, maximizing the quality of reagents you receive when destroying items.",
["knowledgeLevel"] = 120,
["rootIconID"] = 132853,
["configID"] = 50533544,
["state"] = 1,
["treeID"] = 978,
["knowledgeMaxLevel"] = 120,
["name"] = "Designated Disenchanter",
},
{
["rootNodeID"] = 100008,
["highlights"] = {
{
["description"] = "Improve the quality of your permanent enchantments.",
},
{
["description"] = "Learn a variety of new formulas to improve gear.",
},
{
["description"] = "Reduce the amount of Concentration needed to Concentrate on a permanent enchant when fully specialized into it.",
},
},
["description"] = "Master the art of magical matrices and formulas that permanently improve equipment.",
["knowledgeLevel"] = 33,
["rootIconID"] = 132148,
["configID"] = 50533544,
["state"] = 1,
["treeID"] = 980,
["knowledgeMaxLevel"] = 230,
["name"] = "Everlasting Enchantments",
},
{
["rootNodeID"] = 99940,
["highlights"] = {
{
["description"] = "Improve the quality of your illusions, increasing their duration.",
},
{
["description"] = "Learn to create powerful magical wands and enchanting rods.",
},
{
["description"] = "Master formulas for consumable items, increasing their effectiveness.",
},
},
["description"] = "Perfect the art of temporary illusions, equipment, reagents, and mana oils.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4224731,
["configID"] = 50533544,
["state"] = 0,
["treeID"] = 979,
["knowledgeMaxLevel"] = 170,
["name"] = "Ephemerals, Enrichments, and Equipment",
},
},
["level"] = 61,
["skillLineID"] = 333,
["knowledgeUnspent"] = 9,
},
},
["name"] = "Emptyrivers",
["className"] = "Mage",
["factionName"] = "Horde",
["level"] = 80,
["completed"] = {
[83259] = true,
[84086] = true,
[84291] = true,
[84295] = true,
[29510] = true,
[83929] = true,
[82634] = true,
[29520] = true,
[84292] = true,
[83859] = true,
[83863] = true,
[83060] = true,
[82635] = true,
[83269] = true,
[83926] = true,
[83864] = true,
[81076] = true,
[84293] = true,
[83856] = true,
[83923] = true,
[83927] = true,
[84132] = true,
[83928] = true,
[83735] = true,
[83061] = true,
[83860] = true,
[83258] = true,
[84294] = true,
[80872] = true,
[83270] = true,
[84290] = true,
[83924] = true,
[81077] = true,
[83727] = true,
[83925] = true,
[83861] = true,
[83865] = true,
[83862] = true,
[83922] = true,
[80871] = true,
},
["raceID"] = 27,
},
["Player-75-0EEA1695"] = {
["enabled"] = true,
["GUID"] = "Player-75-0EEA1695",
["factionEnglish"] = "Alliance",
["lastUpdate"] = 1727645484,
["raceEnglish"] = "VoidElf",
["realmName"] = "Argent Dawn",
["classID"] = 9,
["classFile"] = "WARLOCK",
["completed"] = {
[83062] = true,
[83893] = true,
[82637] = true,
[81259] = true,
[83909] = true,
[83913] = true,
[83106] = true,
[29511] = true,
[83051] = true,
[82614] = true,
[84130] = true,
[29516] = true,
[83890] = true,
[83894] = true,
[83906] = true,
[83910] = true,
[83733] = true,
[83871] = true,
[83891] = true,
[83265] = true,
[83907] = true,
[81391] = true,
[83911] = true,
[83868] = true,
[83053] = true,
[83873] = true,
[83049] = true,
[83065] = true,
[81390] = true,
[83892] = true,
[83896] = true,
[83897] = true,
[83895] = true,
[83908] = true,
[83912] = true,
[81260] = true,
[83731] = true,
[83266] = true,
[83052] = true,
[83050] = true,
[83054] = true,
[29518] = true,
},
["factionName"] = "Alliance",
["name"] = "Riparium",
["className"] = "Warlock",
["professions"] = {
{
["enabled"] = true,
["knowledgeMaxLevel"] = 500,
["maxLevel"] = 100,
["knowledgeLevel"] = 156,
["specializations"] = {
{
["rootNodeID"] = 100085,
["highlights"] = {
{
["description"] = "Gain increases to skill to acquire higher quality ore when mining the ores you have chosen to specialize in.",
},
{
["description"] = "Learn Refinement recipes which allow you to improve the quality of small quantities of ore.",
},
{
["description"] = "Improve your ability to harvest the elusive Null Stones.",
},
{
["description"] = "Improve the speed at which you mine ore, so you have time to mine even more!",
},
},
["description"] = "Specialize in the acquisition of various ores scattered upon and beneath Khaz Algar.",
["knowledgeLevel"] = 96,
["rootIconID"] = 876371,
["configID"] = 50972707,
["state"] = 1,
["treeID"] = 982,
["name"] = "Plethora of Ore",
["knowledgeMaxLevel"] = 185,
},
{
["rootNodeID"] = 100111,
["highlights"] = {
{
["description"] = "Learn how to mine ore deposits while mounted.",
},
{
["description"] = "Improve your finesse, deftness, and perception when mining in Khaz Algar.",
},
{
["description"] = "Chunks of ore dislodged while mining can be mined for additional yield.",
},
},
["description"] = "Specialize in nuanced mining methodology to improve your techniques. Knowledge in this area will allow you to get the most out of your rich and seam deposits discoveries.",
["knowledgeLevel"] = 60,
["rootIconID"] = 4620679,
["configID"] = 50972707,
["state"] = 1,
["treeID"] = 983,
["name"] = "Mining Fundamentals",
["knowledgeMaxLevel"] = 110,
},
{
["rootNodeID"] = 100162,
["highlights"] = {
{
["description"] = "Gain significant cooldown reduction to Overload while mining.",
},
{
["description"] = "Learn how to protect yourself and improve yield from unusual deposits found across Khaz Algar.",
},
{
["description"] = "Gain an additional charge of Overload.",
},
},
["description"] = "Specialize in mining unusual deposits across Khaz Algar, such as those touched by ominous forces.",
["knowledgeLevel"] = 0,
["rootIconID"] = 4554440,
["configID"] = 50972707,
["state"] = 1,
["treeID"] = 984,
["name"] = "Mastering the Mysterious",
["knowledgeMaxLevel"] = 205,
},
},
["skillLineID"] = 186,
["level"] = 100,
["knowledgeUnspent"] = 0,
},
{
["enabled"] = true,
["knowledgeMaxLevel"] = 720,
["maxLevel"] = 100,
["knowledgeLevel"] = 137,
["specializations"] = {
{
["rootNodeID"] = 98614,
["highlights"] = {
{
["description"] = "Learn how to use Finishing Reagents to improve your gem cuts.",
},
{
["description"] = "Retain Finishing Reagent shards when cutting gems to increase your Skill on future gem cuts.",
},
{
["description"] = "Gain additional skill when cutting gems.",
},
{
["description"] = "Create Prisms which contain uncut gems.",
},
},
["description"] = "Specialize in the cutting and polishing of specific Khaz Algar gemstones.",
["knowledgeLevel"] = 0,
["rootIconID"] = 132595,
["configID"] = 49856841,
["state"] = 0,
["treeID"] = 950,
["name"] = "Gemcutting",
["knowledgeMaxLevel"] = 410,
},
{
["rootNodeID"] = 98245,
["highlights"] = {
{
["description"] = "Learn how to craft powerful Neck and Ring designs.",
},
{
["description"] = "Customize jewelry with Optional Reagents.",
},
{
["description"] = "Improve your ability to craft profession accessories.",
},
{
["description"] = "Gain Skill, Resourcefulness, and Concentration cost reduction when crafting jewelry.",
},
},
["description"] = "Specialize in the art of crafting amulets and rings using various techniques found in Khaz Algar.",
["knowledgeLevel"] = 0,
["rootIconID"] = 132595,
["configID"] = 49856841,
["state"] = 0,
["treeID"] = 946,
["name"] = "Jewelrycrafting",
["knowledgeMaxLevel"] = 130,
},
{
["rootNodeID"] = 98666,
["highlights"] = {
{
["description"] = "Learn to craft various Optional Reagents such as the Elemental Focusing Lens.",
},
{
["description"] = "Improve your ability to find gems and reagents when Prospecting.",
},
{
["description"] = "Gain additional skill and resourcefulness when creating reagents.",
},
},
["description"] = " Improve in the practice of extracting jewelcrafting reagents in a usable state and utilizing them in specialized crafts.",
["knowledgeLevel"] = 137,
["rootIconID"] = 4631356,
["configID"] = 49856841,
["state"] = 1,
["treeID"] = 951,
["name"] = "Shaping",
["knowledgeMaxLevel"] = 180,
},
},
["skillLineID"] = 755,
["level"] = 46,
["knowledgeUnspent"] = 0,
},
},
["level"] = 80,
["raceName"] = "Void Elf",
["raceID"] = 29,
},
},
["checklist"] = {
["hideCompletedObjectives"] = true,
["open"] = true,
["windowScale"] = 80,
["hiddenColumns"] = {
["Progress"] = false,
["Points"] = true,
["Profession"] = true,
},
},
["weeklyReset"] = 1727794798,
["minimap"] = {
["showInCompartment"] = true,
},
},
}
