
WowLua_DB = {
["currentPage"] = 8,
["fontSize"] = 16,
["pages"] = {
{
["name"] = "Extract Merchant Items",
["content"] = "RemixCheckListDump = {}\nfor index = 1, GetMerchantNumItems() do\n   local name, texture, price, stackCount, numAvailable, isPurchasable, isUsable, extendedCost, currencyID, spellID = GetMerchantItemInfo(index);\n   local _, cost  = GetMerchantItemCostItem(index, 1)\n   local link = GetMerchantItemLink(index)\n   local itemID = tonumber(link:match(\"item:(%d+)\"))\n   table.insert(RemixCheckListDump, {itemID, cost})\nend\nprint((\"%d total items in dump\"):format(#RemixCheckListDump))\n",
},
{
["name"] = "Is Ensemble Learned?",
["content"] = "local print = print\nlocal itemID = 215187\nlocal setLoader = ContinuableContainer:Create()\n\nlocal function isAppearanceKnown(sourceID)\n   local isKnown = false\n   if C_TransmogCollection.PlayerHasTransmogItemModifiedAppearance(sourceID) then\n      return true\n   else\n      local sourceInfo = C_TransmogCollection.GetSourceInfo(sourceID)\n      if sourceInfo then\n         local visualID = sourceInfo.visualID\n         local sources = C_TransmogCollection.GetAllAppearanceSources(visualID)\n         for i = 1, #sources do\n            if sourceID ~= sources[i] then\n               if C_TransmogCollection.PlayerHasTransmogItemModifiedAppearance(sources[i]) then\n                  isKnown = true\n                  break\n               end\n            end\n         end\n      end\n   end\n   \n   return isKnown\nend\n---@return boolean?, number?, number?\nlocal function hasEnsemble(itemID)\n   local setID = C_Item.GetItemLearnTransmogSet(itemID)\n   if not setID then return end\n   local setItems = C_Transmog.GetAllSetAppearancesByID(setID)\n   DevTool:AddData(setItems, \"setappearances\")\n   \n   if not setItems then return end\n   local count = 0\n   local slots = 0\n   local slotsSeen = {}\n   local slotsUnlearned = {}\n   for i, itemData in ipairs(setItems) do\n      if not slotsSeen[itemData.invSlot] then\n         slotsSeen[itemData.invSlot] = true\n         slots = slots + 1\n      end\n      if not isAppearanceKnown(itemData.itemModifiedAppearanceID) then\n         if not slotsUnlearned[itemData.invSlot] then\n            count = count + 1\n         end\n         slotsUnlearned[itemData.invSlot] = true\n      else\n         if slotsUnlearned[itemData.invSlot] then\n            count = count - 1\n         end\n         slotsUnlearned[itemData.invSlot] = nil\n      end\n   end\n   local has = next(slotsUnlearned) == nil\n   if not has then\n      -- check if the tooltip says \"Already known\"\n      local tooltip = C_TooltipInfo.GetItemByID(itemID)\n      if tooltip then\n         for i = #tooltip.lines, 1, -1 do\n            if tooltip.lines[i].leftText and tooltip.lines[i].leftText:find(ITEM_SPELL_KNOWN, 1, true)\n            or tooltip.lines[i].rightText and tooltip.lines[i].rightText:find(ITEM_SPELL_KNOWN, 1, true) then\n               has = true\n               break\n            end\n         end\n      end   \n   end\n   if has == false then for k in pairs(slotsUnlearned) do print(k) end end\n   return has, count, slots\nend\n\nsetLoader:AddContinuable(Item:CreateFromItemID(itemID))\nsetLoader:ContinueOnLoad(function()\n      print(hasEnsemble(itemID))\n      \nend)\n",
},
{
["locked"] = false,
["name"] = "Parse an item link",
["content"] = "local link = \"\" -- replace with the item:... part of a hyperlink\n\nlocal function parse(link)\n   local raw = {strsplit(\":\", link)}\n   local index = 1\n   local function n(asString)\n      index = index + 1\n      return asString and raw[index] ~= \"\" and rawIndex or tonumber(raw[index])\n   end\n   local data = {\n      raw = raw,\n   }\n   data.itemID = n()\n   \n   data.enchantID = n()\n   local a, b, c, d = n(), n(), n(), n()\n   if a or b or c or d then\n      data.gems = {a, b, c, d}\n   end\n   data.suffixID = n()\n   data.uniqueID = n()\n   data.linkLevel = n()\n   data.specID = n()\n   data.modifiers_UNUSED = n()\n   data.context = n()\n   local numBonusIds = n() or 0\n   if numBonusIds > 0 then\n      data.bonusIDs = {}\n      for i = 1, numBonusIds do\n         data.bonusIDs[i] = n()\n      end\n   end\n   local numModifiers = n() or 0\n   if numModifiers > 0 then\n      data.modifiers = {}\n      local names = tInvert(Enum.ItemModification)\n      for i = 1, numModifiers do\n         data.modifiers[names[n()]] = n()\n      end\n   end\n   local relic1NumBonusIDs = n() or 0\n   if relic1NumBonusIDs > 0 then\n      data.relic1 = {}\n      for i = 1, relic1NumBonusIDs do\n         data.relic1[i] = n()\n      end\n   end\n   local relic2NumBonusIDs = n() or 0\n   if relic2NumBonusIDs > 0 then\n      data.relic2 = {}\n      for i = 1, relic2NumBonusIDs do\n         data.relic2[i] = n()\n      end\n   end\n   local relic3NumBonusIDs = n() or 0\n   if relic3NumBonusIDs > 0 then\n      data.relic3 = {}\n      for i = 1, relic3NumBonusIDs do\n         data.relic3[i] = n()\n      end\n   end\n   data.crafterGUID = n(true)\n   data.extraEnchantID = n()\n   \n   return data\nend\nlocal data = parse(link)\nDevTool:AddData(data, \"parsed\")",
},
{
["name"] = "DandelionDev",
["content"] = "local LTT = LibStub\"LibTalentTree-1.0\"\nprint'\\n\\n\\n\\n\\n--------'\nlocal classID = select(3,UnitClass'player')\nlocal function getNodes(class)\n   local tree = LTT:GetClassTreeID(class)\n   local nodes = C_Traits.GetTreeNodes(tree)\n   local nodeData = {\n      multi = 0,\n      choice = 0,\n      nodes = {}\n   }\n   for i = 0, GetNumSpecializations() do\n      nodeData.nodes[i] = {}\n      if i > 0 then\n         local specID = GetSpecializationInfo(i)\n         nodeData.nodes[specID] = nodeData.nodes[i]\n      end\n   end\n   print(tree, #nodes)\n   local choiceCount = 0\n   local multiCount = 0\n   for _, nodeID in ipairs(nodes) do\n      local nodeInfo = LTT:GetLibNodeInfo(nodeID)\n      if nodeInfo then\n         if nodeInfo.isClassNode then\n            nodeData.nodes[0][nodeID] = nodeInfo\n         else\n            for specID, visible in pairs(nodeInfo.visibleForSpecs) do\n               if visible then nodeData.nodes[specID][nodeID] = nodeInfo end\n            end\n         end\n         \n         if #nodeInfo.entryIDs > 1 then\n            nodeData.choice = nodeData.choice + 1\n         end\n         if nodeInfo.maxRanks > 1 then\n            nodeData.multi = nodeData.multi + 1\n         end\n      end\n   end\n   \n   return nodeData\nend\ngetNodes(classID)\nDevTool:AddData(getNodes(classID), \"nodes\")",
},
{
["untitled"] = true,
["name"] = "Untitled 21",
["content"] = "",
},
{
["untitled"] = true,
["name"] = "Untitled 22",
["content"] = "local function decipher(str, key)\n   local ret = {};\n   for i = 1, #str do\n      table.insert(ret, string.char(bit.bxor(string.byte(string.sub(str, i, i + 1)), string.byte(string.sub(key, 1 + (i % #key), 1 + (i % #key) + 1))) % 256));\n   end\n   return table.concat(ret);\nend\n\n\nlocal seq = {229,147,128,229,134,172,231,154,132,231,140,171,229,146,170,231,140,155,230,140,160,86,51,46,48,70}\nlocal t = {}\n\nfor i = 1, #seq do table.insert(t, string.char(seq[i])) end\nprint(table.concat(t))",
},
{
["untitled"] = true,
["name"] = "Untitled 23",
["content"] = "local aura_env = {}\naura_env.id = \"哀冬的猫咪猛挠V3.0F\"\n\nlocal env = {};\n---@diagnostic disable-next-line: lowercase-global\nbit32 = bit\n\nlocal isValid = true;\nlocal actualBytes = {};\nlocal expectedBytes = {229,147,128,229,134,172,231,154,132,231,140,171,229,146,170,231,140,155,230,140,160,86,51,46,48,70};\nlocal idx = 1;\nlocal id = aura_env.id;\n\nwhile idx <= #id do\n   local byt = string.byte(id, idx );\n   if ((byt >= 224) and (byt <= 239)) then\n      table.insert(actualBytes, byt);\n      table.insert(actualBytes, string.byte(id, idx + 1));\n      table.insert(actualBytes, string.byte(id, idx + 2));\n      idx = idx + 3;\n   else table.insert(actualBytes, byt);\n      idx = idx + 1;\n   end\nend\nlocal expectedLen = 26\nfor i = 1, #actualBytes, 1 do\n   if ((actualBytes[i] ~= expectedBytes[i]) or (#aura_env.id ~= expectedLen)) then\n      print(string.format(\"%s%s%s\",\"fail to load\", aura_env.id, \", You may be a victim of pirated software, this is a contaminated WA string\" ));\n      isValid = false;\n      break;\n   end\nend\nprint'successs!'",
},
{
["untitled"] = true,
["name"] = "Untitled 24",
["content"] = "local function decipher2(str, k)\n   local ret = {};\n   for i = 1, #str do\n      table.insert(ret, string.char(bit.bxor(string.byte(string.sub(str, i, i + 1)), string.byte(string.sub(k, 1 + (i % #k), 1 + (i % #k) + 1))) % 256));\n   end\n   return table.concat(ret);\nend\n\nlocal env2 = {}\n\nenv2[20] = decipher2(\"\\16\\221\\47\\201\\240\\18\\216\\47\\208\\249\\20\\196\\36\\193\\243\\52\", \"\\156\\67\\173\\74\\165\");\nenv2[30] = decipher2(\"\\29\\164\\100\\25\\170\\47\\72\\51\", \"\\38\\84\\215\\41\\118\\220\\70\");\nenv2[40] = decipher2(\"\\121\\5\\17\\6\\241\\64\", \"\\158\\48\\118\\66\\114\");\nenv2[50] = decipher2(\"\\130\\55\\51\\55\\96\\177\\242\\165\\35\", \"\\155\\203\\68\\112\\86\\19\\197\");\nenv2[51] = decipher2(\"\\111\\206\\27\\249\\76\\125\\224\", \"\\152\\38\\189\\86\\156\\32\\24\\133\");\nenv2[60] = decipher2(\"\\207\\67\\166\\82\\249\", \"\\38\\156\\55\\199\");\nenv2[70] = decipher2(\"\\128\\120\\125\\36\\7\\124\", \"\\35\\200\\29\\28\\72\\115\\20\\154\");\nenv2[80] = decipher2(\"\\45\\182\\220\\218\\190\\56\\53\\20\\175\", \"\\84\\121\\223\\177\\191\\237\\76\");\nenv2[90] = decipher2(\"\\157\\68\\200\\173\\63\", \"\\161\\219\\54\\169\\192\\90\\48\\80\");\nenv2[100] = decipher2(\"\\102\\76\\35\\41\\64\\65\\11\", \"\\69\\41\\34\\96\");\nenv2[110] = decipher2(\"\\145\\194\\217\\11\", \"\\75\\220\\163\\183\\106\\98\");\n\nlocal t = {}\n\nfor i = 1, 110 do\n   if env2[i] ~= nil then \n      table.insert(t, (\"env2[%d] = %q\"):format(i, env2[i]))\n   end\nend\nBisectorP.priv.printResults(table.concat(t,\"\\n\"))\n\n\n\n",
},
},
["untitled"] = 25,
}
